package banking

// service.go
// =============================================================================
// Service — the business-logic layer for an organisation's own bank
// accounts. It is the banking equivalent of ContactService: it owns
// authorisation, validation, the mapping between the API shape (pound strings,
// optional strings) and the database shape (pence int64, pgx types), and the
// calls into the sqlc-generated `banking` package.
//
//   HTTP handler (handler.go)
//     ↓
//   Service (this file)
//     ↓
//   *banking.Queries (db/banking — generated by sqlc)
//     ↓
//   PostgreSQL
//
// Unlike contacts, this domain lives in internal/<domain> (the modular-monolith
// target), so it calls the shared kernel helpers as kernel.X directly rather than
// the root package's aliases.
//
// MONEY: opening/current balances cross the API as decimal POUND strings and are
// stored as BIGINT pence (int64). Conversion is money.PoundsToMinor (in) /
// money.MinorToPounds (out) — never float.
//
// AUTHZ: any active member may read/list; only an owner/admin may create, update
// or delete (bank accounts are company financial config, like Company Details).
// =============================================================================

import (
	"context"
	"errors"
	"strings"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/jackc/pgx/v5/pgxpool"

	auth "github.com/operationfb/accounting-saas/db/auth"
	banking "github.com/operationfb/accounting-saas/db/banking"
	"github.com/operationfb/accounting-saas/internal/kernel"
	"github.com/operationfb/accounting-saas/money"
)

// Service holds the pool (for the multi-statement primary-flip
// transaction), the banking query set, and the auth queries used to resolve the
// caller's membership/role.
type Service struct {
	pool        *pgxpool.Pool
	queries     *banking.Queries
	authQueries auth.Querier
}

// NewService is the constructor, called once in main.go (and the test harness).
func NewService(pool *pgxpool.Pool, queries *banking.Queries, authQueries auth.Querier) *Service {
	return &Service{pool: pool, queries: queries, authQueries: authQueries}
}

// =============================================================================
// DTOs
// =============================================================================

// CreateBankAccountRequest is the POST/PUT body. organisation_id and
// created_by_user_id are taken from the token, never the body. Optional/nullable
// columns are pointers so "omitted" (nil → NULL) differs from an explicit value.
// The two form checkboxes that default ON (show_on_invoices, guess_explanations)
// are *bool so a missing field means "checked".
type CreateBankAccountRequest struct {
	Name               string  `json:"name" binding:"required,max=200"`
	Currency           string  `json:"currency" binding:"omitempty,len=3"`           // default GBP
	Status             string  `json:"status" binding:"omitempty,oneof=active closed"` // default active
	IsPersonal         bool    `json:"is_personal"`
	IsPrimary          bool    `json:"is_primary"`
	BankName           *string `json:"bank_name"`
	AccountNumber      *string `json:"account_number"`
	SortCode           *string `json:"sort_code"`        // UK
	RoutingNumber      *string `json:"routing_number"`   // US ABA
	BankAccountType    *string `json:"bank_account_type" binding:"omitempty,oneof=checking savings"` // US
	IBAN               *string `json:"iban"`
	BIC                *string `json:"bic"`
	ShowOnInvoices     *bool   `json:"show_on_invoices"`     // nil → true (form default)
	OpeningBalance     string  `json:"opening_balance"`      // pound string, default "0.00"
	OpeningBalanceDate *string `json:"opening_balance_date"` // YYYY-MM-DD, optional
	GuessExplanations  *bool   `json:"guess_explanations"`   // nil → true (form default)
}

// BankAccountResponse is the JSON shape returned to clients. Money is exposed as
// pound strings; nullable columns as *string (omitted when null in the DB).
type BankAccountResponse struct {
	ID                 string  `json:"id"`
	OrganisationID     string  `json:"organisation_id"`
	CreatedByUserID    string  `json:"created_by_user_id"`
	Name               string  `json:"name"`
	Currency           string  `json:"currency"`
	Status             string  `json:"status"`
	IsPersonal         bool    `json:"is_personal"`
	IsPrimary          bool    `json:"is_primary"`
	BankName           *string `json:"bank_name,omitempty"`
	AccountNumber      *string `json:"account_number,omitempty"`
	SortCode           *string `json:"sort_code,omitempty"`
	RoutingNumber      *string `json:"routing_number,omitempty"`
	BankAccountType    *string `json:"bank_account_type,omitempty"`
	IBAN               *string `json:"iban,omitempty"`
	BIC                *string `json:"bic,omitempty"`
	ShowOnInvoices     bool    `json:"show_on_invoices"`
	OpeningBalance     string  `json:"opening_balance"` // pounds, e.g. "4109.42"
	CurrentBalance     string  `json:"current_balance"` // pounds, derived (opening + Σ txns)
	OpeningBalanceDate *string `json:"opening_balance_date,omitempty"`
	GuessExplanations  bool    `json:"guess_explanations"`
	CreatedAt          string  `json:"created_at"`
	UpdatedAt          string  `json:"updated_at"`
}

// =============================================================================
// AUTHORIZATION
// =============================================================================

// authorize confirms the caller is an ACTIVE member and returns their role.
func (s *Service) authorize(ctx context.Context, userID, orgID uuid.UUID) (auth.OrganisationRole, error) {
	return kernel.AuthorizeMember(ctx, s.authQueries, userID, orgID)
}

// requireAdmin authorises the caller AND requires owner/admin — the gate on every
// mutation (create/update/delete). Reading does not call this.
func (s *Service) requireAdmin(ctx context.Context, userID, orgID uuid.UUID) error {
	role, err := s.authorize(ctx, userID, orgID)
	if err != nil {
		return err
	}
	if !kernel.IsOrgAdmin(role) {
		return kernel.ErrForbidden("only an owner or admin can manage bank accounts")
	}
	return nil
}

// =============================================================================
// CREATE
// =============================================================================

// CreateBankAccount validates + normalises the request and inserts one account.
// When is_primary is requested, the existing primary is cleared first, inside one
// transaction, to satisfy the "≤1 primary per org" partial unique index.
func (s *Service) CreateBankAccount(ctx context.Context, authUserID, authOrgID uuid.UUID, req CreateBankAccountRequest) (*BankAccountResponse, error) {
	if err := s.requireAdmin(ctx, authUserID, authOrgID); err != nil {
		return nil, err
	}

	params, err := s.buildAccountFields(req)
	if err != nil {
		return nil, err
	}
	createParams := banking.CreateBankAccountParams{
		OrganisationID:      authOrgID,
		CreatedByUserID:     authUserID,
		Name:                params.Name,
		Currency:            params.Currency,
		Status:              params.Status,
		IsPersonal:          req.IsPersonal,
		IsPrimary:           req.IsPrimary,
		BankName:            params.BankName,
		AccountNumber:       params.AccountNumber,
		SortCode:            params.SortCode,
		RoutingNumber:       params.RoutingNumber,
		BankAccountType:     params.BankAccountType,
		Iban:                params.IBAN,
		Bic:                 params.BIC,
		ShowOnInvoices:      params.ShowOnInvoices,
		OpeningBalanceMinor: params.OpeningBalanceMinor,
		OpeningBalanceDate:  params.OpeningBalanceDate,
		GuessExplanations:   params.GuessExplanations,
	}

	var created banking.BankAccount
	if req.IsPrimary {
		err = kernel.WithTx(ctx, s.pool, func(tx pgx.Tx) error {
			qtx := s.queries.WithTx(tx)
			if err := qtx.UnsetPrimaryBankAccounts(ctx, authOrgID); err != nil {
				return err
			}
			var e error
			created, e = qtx.CreateBankAccount(ctx, createParams)
			return e
		})
	} else {
		created, err = s.queries.CreateBankAccount(ctx, createParams)
	}
	if err != nil {
		return nil, kernel.ErrInternal(err)
	}
	// A fresh account has no transactions, so its current balance IS its opening.
	return bankAccountToResponse(created, created.OpeningBalanceMinor), nil
}

// =============================================================================
// GET / LIST
// =============================================================================

// GetBankAccount fetches one account (with its derived current balance),
// org-scoped. Any active member may read.
func (s *Service) GetBankAccount(ctx context.Context, authUserID, authOrgID uuid.UUID, id string) (*BankAccountResponse, error) {
	accountUUID, err := uuid.Parse(id)
	if err != nil {
		return nil, kernel.ErrValidation("id is not a valid UUID", err)
	}
	if _, err := s.authorize(ctx, authUserID, authOrgID); err != nil {
		return nil, err
	}
	row, err := s.queries.GetBankAccount(ctx, banking.GetBankAccountParams{ID: accountUUID, OrganisationID: authOrgID})
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, kernel.ErrNotFound("bank account", id)
		}
		return nil, kernel.ErrInternal(err)
	}
	return bankAccountToResponse(accountFromGetRow(row), row.CurrentBalanceMinor), nil
}

// ListBankAccounts returns every live account for the caller's org, each with its
// derived current balance (primary first, then by name). Any active member.
func (s *Service) ListBankAccounts(ctx context.Context, authUserID, authOrgID uuid.UUID) ([]*BankAccountResponse, error) {
	if _, err := s.authorize(ctx, authUserID, authOrgID); err != nil {
		return nil, err
	}
	rows, err := s.queries.ListBankAccounts(ctx, authOrgID)
	if err != nil {
		return nil, kernel.ErrInternal(err)
	}
	out := make([]*BankAccountResponse, 0, len(rows))
	for _, r := range rows {
		out = append(out, bankAccountToResponse(accountFromListRow(r), r.CurrentBalanceMinor))
	}
	return out, nil
}

// =============================================================================
// UPDATE / DELETE
// =============================================================================

// UpdateBankAccount performs a full update of an account's editable fields (PUT
// semantics). Owner/admin only. The primary flip (if requested) and the update
// run in one transaction; the response is re-read so its current_balance reflects
// the derived sum.
func (s *Service) UpdateBankAccount(ctx context.Context, authUserID, authOrgID uuid.UUID, id string, req CreateBankAccountRequest) (*BankAccountResponse, error) {
	accountUUID, err := uuid.Parse(id)
	if err != nil {
		return nil, kernel.ErrValidation("id is not a valid UUID", err)
	}
	if err := s.requireAdmin(ctx, authUserID, authOrgID); err != nil {
		return nil, err
	}

	// 404 if it doesn't exist in this org (or was already deleted).
	if _, err := s.queries.GetBankAccount(ctx, banking.GetBankAccountParams{ID: accountUUID, OrganisationID: authOrgID}); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, kernel.ErrNotFound("bank account", id)
		}
		return nil, kernel.ErrInternal(err)
	}

	fields, err := s.buildAccountFields(req)
	if err != nil {
		return nil, err
	}
	updateParams := banking.UpdateBankAccountParams{
		ID:                  accountUUID,
		OrganisationID:      authOrgID,
		Name:                fields.Name,
		Currency:            fields.Currency,
		Status:              fields.Status,
		IsPersonal:          req.IsPersonal,
		IsPrimary:           req.IsPrimary,
		BankName:            fields.BankName,
		AccountNumber:       fields.AccountNumber,
		SortCode:            fields.SortCode,
		RoutingNumber:       fields.RoutingNumber,
		BankAccountType:     fields.BankAccountType,
		Iban:                fields.IBAN,
		Bic:                 fields.BIC,
		ShowOnInvoices:      fields.ShowOnInvoices,
		OpeningBalanceMinor: fields.OpeningBalanceMinor,
		OpeningBalanceDate:  fields.OpeningBalanceDate,
		GuessExplanations:   fields.GuessExplanations,
	}

	err = kernel.WithTx(ctx, s.pool, func(tx pgx.Tx) error {
		qtx := s.queries.WithTx(tx)
		if req.IsPrimary {
			if err := qtx.UnsetPrimaryBankAccounts(ctx, authOrgID); err != nil {
				return err
			}
		}
		_, e := qtx.UpdateBankAccount(ctx, updateParams)
		return e
	})
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, kernel.ErrNotFound("bank account", id)
		}
		return nil, kernel.ErrInternal(err)
	}

	// Re-read so current_balance is the derived value (the update returns the base row).
	row, err := s.queries.GetBankAccount(ctx, banking.GetBankAccountParams{ID: accountUUID, OrganisationID: authOrgID})
	if err != nil {
		return nil, kernel.ErrInternal(err)
	}
	return bankAccountToResponse(accountFromGetRow(row), row.CurrentBalanceMinor), nil
}

// DeleteBankAccount soft-deletes an account (sets deleted_at). Owner/admin only.
func (s *Service) DeleteBankAccount(ctx context.Context, authUserID, authOrgID uuid.UUID, id string) error {
	accountUUID, err := uuid.Parse(id)
	if err != nil {
		return kernel.ErrValidation("id is not a valid UUID", err)
	}
	if err := s.requireAdmin(ctx, authUserID, authOrgID); err != nil {
		return err
	}
	// Load for a clean 404 (GetBankAccount filters deleted_at IS NULL).
	if _, err := s.queries.GetBankAccount(ctx, banking.GetBankAccountParams{ID: accountUUID, OrganisationID: authOrgID}); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return kernel.ErrNotFound("bank account", id)
		}
		return kernel.ErrInternal(err)
	}
	if err := s.queries.SoftDeleteBankAccount(ctx, banking.SoftDeleteBankAccountParams{ID: accountUUID, OrganisationID: authOrgID}); err != nil {
		return kernel.ErrInternal(err)
	}
	return nil
}

// =============================================================================
// VALIDATION / NORMALISATION
// =============================================================================

// accountFields holds the normalised, DB-ready column values shared by create and
// update (everything except the id/org/creator/flags taken verbatim from the req).
type accountFields struct {
	Name                string
	Currency            string
	Status              string
	BankName            pgtype.Text
	AccountNumber       pgtype.Text
	SortCode            pgtype.Text
	RoutingNumber       pgtype.Text
	BankAccountType     pgtype.Text
	IBAN                pgtype.Text
	BIC                 pgtype.Text
	ShowOnInvoices      bool
	OpeningBalanceMinor int64
	OpeningBalanceDate  pgtype.Date
	GuessExplanations   bool
}

// buildAccountFields normalises currency/status, parses the opening balance
// (pounds → pence) and the optional opening-balance date, and applies the
// default-ON semantics for the two checkbox flags. Validation errors map to 422.
func (s *Service) buildAccountFields(req CreateBankAccountRequest) (accountFields, error) {
	currency, err := normaliseCurrency(req.Currency)
	if err != nil {
		return accountFields{}, err
	}
	status, err := normaliseStatus(req.Status)
	if err != nil {
		return accountFields{}, err
	}

	openingStr := strings.TrimSpace(req.OpeningBalance)
	if openingStr == "" {
		openingStr = "0"
	}
	openingMinor, err := money.PoundsToMinor(openingStr)
	if err != nil {
		return accountFields{}, kernel.ErrValidation("opening_balance must be a valid amount", err)
	}

	openingDate, err := parseOptionalDate(req.OpeningBalanceDate)
	if err != nil {
		return accountFields{}, err
	}

	return accountFields{
		Name:                strings.TrimSpace(req.Name),
		Currency:            currency,
		Status:              status,
		BankName:            kernel.NullText(req.BankName),
		AccountNumber:       kernel.NullText(req.AccountNumber),
		SortCode:            kernel.NullText(req.SortCode),
		RoutingNumber:       kernel.NullText(req.RoutingNumber),
		BankAccountType:     kernel.NullText(req.BankAccountType),
		IBAN:                kernel.NullText(req.IBAN),
		BIC:                 kernel.NullText(req.BIC),
		ShowOnInvoices:      boolOrDefault(req.ShowOnInvoices, true),
		OpeningBalanceMinor: openingMinor,
		OpeningBalanceDate:  openingDate,
		GuessExplanations:   boolOrDefault(req.GuessExplanations, true),
	}, nil
}

// normaliseCurrency upper-cases + trims; defaults blank → GBP; must be 3 letters.
func normaliseCurrency(raw string) (string, error) {
	code := strings.ToUpper(strings.TrimSpace(raw))
	if code == "" {
		return "GBP", nil
	}
	if len(code) != 3 {
		return "", kernel.ErrValidation("currency must be a 3-letter ISO 4217 code", nil)
	}
	return code, nil
}

// normaliseStatus lower-cases + trims; defaults blank → active; active|closed only.
func normaliseStatus(raw string) (string, error) {
	v := strings.ToLower(strings.TrimSpace(raw))
	if v == "" {
		return "active", nil
	}
	if v != "active" && v != "closed" {
		return "", kernel.ErrValidation("status must be 'active' or 'closed'", nil)
	}
	return v, nil
}

// boolOrDefault returns *p when set, else def — for the default-ON checkboxes.
func boolOrDefault(p *bool, def bool) bool {
	if p != nil {
		return *p
	}
	return def
}

// parseOptionalDate parses an optional "YYYY-MM-DD" into a pgtype.Date; nil/blank
// → an invalid (NULL) date; a malformed value → 422.
func parseOptionalDate(s *string) (pgtype.Date, error) {
	if s == nil || strings.TrimSpace(*s) == "" {
		return pgtype.Date{}, nil
	}
	t, err := time.Parse("2006-01-02", strings.TrimSpace(*s))
	if err != nil {
		return pgtype.Date{}, kernel.ErrValidation("opening_balance_date must be in YYYY-MM-DD format", err)
	}
	return pgtype.Date{Time: t, Valid: true}, nil
}

// =============================================================================
// RESPONSE FORMATTER
// =============================================================================

// bankAccountToResponse maps a stored account plus its (possibly derived) current
// balance into the API shape. Balances become pound strings (money.MinorToPounds);
// nullable columns become *string (kernel.NullTextToPtr).
func bankAccountToResponse(a banking.BankAccount, currentBalanceMinor int64) *BankAccountResponse {
	return &BankAccountResponse{
		ID:                 a.ID.String(),
		OrganisationID:     a.OrganisationID.String(),
		CreatedByUserID:    a.CreatedByUserID.String(),
		Name:               a.Name,
		Currency:           a.Currency,
		Status:             a.Status,
		IsPersonal:         a.IsPersonal,
		IsPrimary:          a.IsPrimary,
		BankName:           kernel.NullTextToPtr(a.BankName),
		AccountNumber:      kernel.NullTextToPtr(a.AccountNumber),
		SortCode:           kernel.NullTextToPtr(a.SortCode),
		RoutingNumber:      kernel.NullTextToPtr(a.RoutingNumber),
		BankAccountType:    kernel.NullTextToPtr(a.BankAccountType),
		IBAN:               kernel.NullTextToPtr(a.Iban),
		BIC:                kernel.NullTextToPtr(a.Bic),
		ShowOnInvoices:     a.ShowOnInvoices,
		OpeningBalance:     money.MinorToPounds(a.OpeningBalanceMinor),
		CurrentBalance:     money.MinorToPounds(currentBalanceMinor),
		OpeningBalanceDate: dateToPtr(a.OpeningBalanceDate),
		GuessExplanations:  a.GuessExplanations,
		CreatedAt:          a.CreatedAt.Time.Format(time.RFC3339),
		UpdatedAt:          a.UpdatedAt.Time.Format(time.RFC3339),
	}
}

// dateToPtr renders a nullable DATE as an optional "YYYY-MM-DD" string.
func dateToPtr(d pgtype.Date) *string {
	if !d.Valid {
		return nil
	}
	s := d.Time.Format("2006-01-02")
	return &s
}

// accountFromGetRow / accountFromListRow adapt the derived-balance row types
// (which carry every BankAccount column plus current_balance_minor) back to a
// BankAccount, so the single projector above renders all four read shapes. sqlc
// emits Get and List as distinct-but-identical row structs, hence two adapters.
func accountFromGetRow(r banking.GetBankAccountRow) banking.BankAccount {
	return banking.BankAccount{
		ID: r.ID, OrganisationID: r.OrganisationID, CreatedByUserID: r.CreatedByUserID,
		Name: r.Name, Currency: r.Currency, Status: r.Status,
		IsPersonal: r.IsPersonal, IsPrimary: r.IsPrimary,
		BankName: r.BankName, AccountNumber: r.AccountNumber, SortCode: r.SortCode,
		RoutingNumber: r.RoutingNumber, BankAccountType: r.BankAccountType,
		Iban: r.Iban, Bic: r.Bic, ShowOnInvoices: r.ShowOnInvoices,
		OpeningBalanceMinor: r.OpeningBalanceMinor, OpeningBalanceDate: r.OpeningBalanceDate,
		GuessExplanations: r.GuessExplanations, DeletedAt: r.DeletedAt,
		CreatedAt: r.CreatedAt, UpdatedAt: r.UpdatedAt,
	}
}

func accountFromListRow(r banking.ListBankAccountsRow) banking.BankAccount {
	return banking.BankAccount{
		ID: r.ID, OrganisationID: r.OrganisationID, CreatedByUserID: r.CreatedByUserID,
		Name: r.Name, Currency: r.Currency, Status: r.Status,
		IsPersonal: r.IsPersonal, IsPrimary: r.IsPrimary,
		BankName: r.BankName, AccountNumber: r.AccountNumber, SortCode: r.SortCode,
		RoutingNumber: r.RoutingNumber, BankAccountType: r.BankAccountType,
		Iban: r.Iban, Bic: r.Bic, ShowOnInvoices: r.ShowOnInvoices,
		OpeningBalanceMinor: r.OpeningBalanceMinor, OpeningBalanceDate: r.OpeningBalanceDate,
		GuessExplanations: r.GuessExplanations, DeletedAt: r.DeletedAt,
		CreatedAt: r.CreatedAt, UpdatedAt: r.UpdatedAt,
	}
}
