package platformadmin

// service.go
// =============================================================================
// Service — the business logic for the platform-admin ("god view").
//
// A superuser (users.is_superuser = TRUE, set manually in the DB) gets a
// READ-ONLY, cross-tenant view of the whole platform: every organisation and
// every user. This is the ONE place in the codebase that deliberately steps
// outside org-scoping, so EVERY method starts with requireSuperuser — a normal
// caller (no flag) is refused with 403 before any cross-tenant query runs.
//
//   HTTP handler (handler.go)
//     ↓
//   Service (this file) — requireSuperuser gate, then a cross-tenant read
//     ↓
//   auth.Querier (db/auth — generated by sqlc)
//     ↓
//   PostgreSQL
//
// It is thin and read-only (no pool/transaction, no money): it reuses the
// generated auth queries (ListAllOrganisations / ListAllUsers /
// ListMembershipsForUser / GetOrganisation / GetUser / ListMembersByOrganisation)
// and the kernel.Err* + kernel.Timestamp helpers.
// =============================================================================

import (
	"context"
	"errors"
	"strings"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/jackc/pgx/v5/pgxpool"
	"golang.org/x/crypto/bcrypt"

	auth "github.com/operationfb/accounting-saas/db/auth"
	categoriesdb "github.com/operationfb/accounting-saas/db/categories"
	"github.com/operationfb/accounting-saas/internal/categories"
	"github.com/operationfb/accounting-saas/internal/kernel"
	"github.com/operationfb/accounting-saas/internal/organisation"
)

// Service holds the auth query set plus the organisation service. The god-view
// reads are single read-only queries (authQueries directly); the one WRITE
// surface — editing a chosen org's company details — reuses the organisation
// service's read-modify-write, so the validation/preservation logic isn't
// duplicated (this package supplies the superuser gate instead of membership).
type Service struct {
	pool        *pgxpool.Pool
	authQueries auth.Querier
	orgSvc      *organisation.Service
}

// NewService is the constructor, called once in main.go with the same shared
// auth.Querier the other services use, plus the organisation service it delegates
// company-details edits to. The pool backs the one multi-table write —
// CreateOrganisation, which creates the org and provisions its chart of accounts
// in a single transaction.
func NewService(pool *pgxpool.Pool, authQueries auth.Querier, orgSvc *organisation.Service) *Service {
	return &Service{pool: pool, authQueries: authQueries, orgSvc: orgSvc}
}

// =============================================================================
// AUTHORIZATION
// =============================================================================

// requireSuperuser is the gate on every god-view read. It loads the caller by id
// (from the token) and refuses anyone who is not a platform superuser with 403.
// This is intentionally NOT the org-membership check (kernel.AuthorizeMember) —
// the god view is platform-wide, not scoped to any org the caller belongs to.
func (s *Service) requireSuperuser(ctx context.Context, authUserID uuid.UUID) error {
	u, err := s.authQueries.GetUser(ctx, authUserID)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			// Soft-deleted / unknown caller — treat as forbidden (no enumeration).
			return kernel.ErrForbidden("platform admin access required")
		}
		return kernel.ErrInternal(err)
	}
	if !u.IsSuperuser {
		return kernel.ErrForbidden("platform admin access required")
	}
	return nil
}

// =============================================================================
// ORGANISATIONS
// =============================================================================

// ListOrganisations returns every live organisation on the platform (with a
// member count). Superuser only.
func (s *Service) ListOrganisations(ctx context.Context, authUserID uuid.UUID) ([]AdminOrganisationResponse, error) {
	if err := s.requireSuperuser(ctx, authUserID); err != nil {
		return nil, err
	}
	rows, err := s.authQueries.ListAllOrganisations(ctx)
	if err != nil {
		return nil, kernel.ErrInternal(err)
	}
	out := make([]AdminOrganisationResponse, 0, len(rows))
	for _, r := range rows {
		out = append(out, AdminOrganisationResponse{
			ID:          r.ID.String(),
			Name:        r.Name,
			CountryCode: r.CountryCode,
			Plan:        r.Plan,
			MemberCount: r.MemberCount,
			CreatedAt:   r.CreatedAt.Time.Format(time.RFC3339),
		})
	}
	return out, nil
}

// CreateOrganisation creates a brand-new organisation AND provisions its chart of
// accounts, in a single transaction. Superuser only. The org is created with no
// members (assigning an owner is a separate step); country_code + native_currency
// are fixed here and immutable afterward. Without the CoA an org can't post to the
// GL, so ProvisionChart runs in the same tx (GL posting rules are global, so
// nothing else needs seeding).
func (s *Service) CreateOrganisation(ctx context.Context, authUserID uuid.UUID, req CreateOrganisationRequest) (*AdminOrganisationResponse, error) {
	if err := s.requireSuperuser(ctx, authUserID); err != nil {
		return nil, err
	}

	// Validate / normalise. name is NOT NULL; country_code is normalised + checked
	// like the Company Details path; native_currency is upper-cased (its existence
	// is enforced by the FK, mapped to a 422 below).
	name := strings.TrimSpace(req.Name)
	if name == "" {
		return nil, kernel.ErrValidation("name is required", nil)
	}
	countryCode, err := kernel.NormaliseCountryCode(req.CountryCode)
	if err != nil {
		return nil, err
	}
	currency := strings.ToUpper(strings.TrimSpace(req.NativeCurrency))
	if len(currency) != 3 {
		return nil, kernel.ErrValidation("native_currency must be a 3-letter ISO 4217 code", nil)
	}

	// A URL-safe slug derived from the name (nullable, UNIQUE). Empty → NULL.
	slug := slugify(name)

	var created auth.Organisation
	err = kernel.WithTx(ctx, s.pool, func(tx pgx.Tx) error {
		org, txErr := auth.New(tx).CreateOrganisation(ctx, auth.CreateOrganisationParams{
			Name:           name,
			Slug:           pgtype.Text{String: slug, Valid: slug != ""},
			NativeCurrency: currency,
			Timezone:       "Europe/London", // schema default; not a form field yet
			CountryCode:    countryCode,
		})
		if txErr != nil {
			return txErr
		}
		created = org
		// Seed the chart of accounts from the country/global template, in the same
		// tx so it commits atomically with the org.
		return categories.ProvisionChart(ctx, categoriesdb.New(tx), org.ID, org.CountryCode)
	})
	if err != nil {
		// A name/slug clash trips the UNIQUE slug index.
		if kernel.IsUniqueViolation(err) {
			return nil, kernel.ErrConflict("an organisation with this name already exists")
		}
		// An unknown currency trips the native_currency → currencies FK (23503).
		var pgErr *pgconn.PgError
		if errors.As(err, &pgErr) && pgErr.Code == "23503" {
			return nil, kernel.ErrValidation("unknown currency code", err)
		}
		return nil, kernel.ErrInternal(err)
	}

	return &AdminOrganisationResponse{
		ID:          created.ID.String(),
		Name:        created.Name,
		CountryCode: created.CountryCode,
		Plan:        created.Plan,
		MemberCount: 0, // brand-new org has no members yet
		CreatedAt:   created.CreatedAt.Time.Format(time.RFC3339),
	}, nil
}

// slugify turns an organisation name into a URL-safe slug: lowercase, non-alnum
// runs collapsed to single hyphens, trimmed, capped at the slug column's 100
// chars. Returns "" when nothing usable remains (→ a NULL slug).
func slugify(name string) string {
	var b strings.Builder
	prevHyphen := false
	for _, r := range strings.ToLower(name) {
		switch {
		case (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9'):
			b.WriteRune(r)
			prevHyphen = false
		default:
			if !prevHyphen && b.Len() > 0 {
				b.WriteByte('-')
				prevHyphen = true
			}
		}
	}
	slug := strings.Trim(b.String(), "-")
	if len(slug) > 100 {
		slug = strings.Trim(slug[:100], "-")
	}
	return slug
}

// GetOrganisation returns one organisation plus its members (the org drill-in).
// Superuser only; cross-tenant (any org id is allowed — that's the point).
func (s *Service) GetOrganisation(ctx context.Context, authUserID, orgID uuid.UUID) (*AdminOrganisationDetailResponse, error) {
	if err := s.requireSuperuser(ctx, authUserID); err != nil {
		return nil, err
	}
	return s.buildOrgDetail(ctx, orgID)
}

// buildOrgDetail assembles the org-summary + members response for an org, with NO
// authorisation — the CALLER gates it. Shared by GetOrganisation and the two
// member-mutation methods (so they return the refreshed list in one round-trip).
func (s *Service) buildOrgDetail(ctx context.Context, orgID uuid.UUID) (*AdminOrganisationDetailResponse, error) {
	org, err := s.authQueries.GetOrganisation(ctx, orgID)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, kernel.ErrNotFound("organisation", orgID.String())
		}
		return nil, kernel.ErrInternal(err)
	}
	members, err := s.authQueries.ListMembersByOrganisation(ctx, orgID)
	if err != nil {
		return nil, kernel.ErrInternal(err)
	}
	memberDTOs := make([]AdminOrganisationMemberResponse, 0, len(members))
	for _, m := range members {
		memberDTOs = append(memberDTOs, AdminOrganisationMemberResponse{
			UserID:      m.UserID.String(),
			Email:       m.Email,
			FirstName:   m.FirstName,
			LastName:    m.LastName,
			Role:        string(m.Role),
			Status:      m.Status,
			LastLoginAt: kernel.TimestampToStringPtr(m.LastLoginAt),
			MemberSince: m.MemberSince.Time.Format(time.RFC3339),
		})
	}
	return &AdminOrganisationDetailResponse{
		Organisation: AdminOrganisationResponse{
			ID:          org.ID.String(),
			Name:        org.Name,
			CountryCode: org.CountryCode,
			Plan:        org.Plan,
			MemberCount: int64(len(members)),
			CreatedAt:   org.CreatedAt.Time.Format(time.RFC3339),
		},
		Members: memberDTOs,
	}, nil
}

// =============================================================================
// ORG MEMBERS (add existing / create new) — the god-view's cross-tenant member
// management. Both gate on requireSuperuser, target the org from the path, and
// allow ANY role (owner included). They mirror internal/members.CreateMember but
// without the membership check. Return the refreshed org detail.
// =============================================================================

// AddOrganisationMember attaches an EXISTING platform user to the org as an active
// member. Superuser only. 404 if the org or user is gone; 409 if they're already
// a member.
func (s *Service) AddOrganisationMember(ctx context.Context, authUserID, orgID uuid.UUID, req AddOrganisationMemberRequest) (*AdminOrganisationDetailResponse, error) {
	if err := s.requireSuperuser(ctx, authUserID); err != nil {
		return nil, err
	}
	targetID, err := uuid.Parse(req.UserID)
	if err != nil {
		return nil, kernel.ErrBadRequest("user_id must be a valid UUID", err)
	}

	// The org must exist (else 404).
	if _, err := s.authQueries.GetOrganisation(ctx, orgID); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, kernel.ErrNotFound("organisation", orgID.String())
		}
		return nil, kernel.ErrInternal(err)
	}
	// The user must exist (GetUser filters soft-deleted → 404).
	if _, err := s.authQueries.GetUser(ctx, targetID); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, kernel.ErrNotFound("user", targetID.String())
		}
		return nil, kernel.ErrInternal(err)
	}
	// Reject a duplicate membership up front (the unique (org,user) index would too).
	if _, err := s.authQueries.GetMembership(ctx, auth.GetMembershipParams{OrganisationID: orgID, UserID: targetID}); err == nil {
		return nil, kernel.ErrConflict("user is already a member of this organisation")
	} else if !errors.Is(err, pgx.ErrNoRows) {
		return nil, kernel.ErrInternal(err)
	}

	if _, err := s.authQueries.CreateMembership(ctx, auth.CreateMembershipParams{
		OrganisationID: orgID,
		UserID:         targetID,
		Role:           auth.OrganisationRole(req.Role),
		Status:         "active",
	}); err != nil {
		if kernel.IsUniqueViolation(err) { // a race past the pre-check
			return nil, kernel.ErrConflict("user is already a member of this organisation")
		}
		return nil, kernel.ErrInternal(err)
	}
	return s.buildOrgDetail(ctx, orgID)
}

// CreateOrganisationUser creates a NEW user and attaches them to the org as an
// active member, in one transaction (mirrors internal/members.CreateMember).
// Superuser only. 404 if the org is gone; 409 on a duplicate email.
func (s *Service) CreateOrganisationUser(ctx context.Context, authUserID, orgID uuid.UUID, req CreateOrganisationUserRequest) (*AdminOrganisationDetailResponse, error) {
	if err := s.requireSuperuser(ctx, authUserID); err != nil {
		return nil, err
	}

	// The org must exist (else 404) before we create a user for it.
	if _, err := s.authQueries.GetOrganisation(ctx, orgID); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, kernel.ErrNotFound("organisation", orgID.String())
		}
		return nil, kernel.ErrInternal(err)
	}

	firstName := strings.TrimSpace(req.FirstName)
	lastName := strings.TrimSpace(req.LastName)
	if firstName == "" {
		return nil, kernel.ErrValidation("first_name is required", nil)
	}
	if lastName == "" {
		return nil, kernel.ErrValidation("last_name is required", nil)
	}
	email := strings.ToLower(strings.TrimSpace(req.Email))

	// Clean 409 for an existing email (the global unique index would reject it too).
	if _, err := s.authQueries.GetUserByEmail(ctx, email); err == nil {
		return nil, kernel.ErrConflict("a user with this email already exists")
	} else if !errors.Is(err, pgx.ErrNoRows) {
		return nil, kernel.ErrInternal(err)
	}

	hash, err := bcrypt.GenerateFromPassword([]byte(req.Password), 12)
	if err != nil {
		return nil, kernel.ErrInternal(err)
	}

	// One transaction: create the user, then the active membership.
	err = kernel.WithTx(ctx, s.pool, func(tx pgx.Tx) error {
		qtx := auth.New(tx)
		user, err := qtx.CreateUser(ctx, auth.CreateUserParams{
			Email:        email,
			PasswordHash: pgtype.Text{String: string(hash), Valid: true},
			FirstName:    firstName,
			LastName:     lastName,
			Phone:        pgtype.Text{}, // not collected on this form
		})
		if err != nil {
			if kernel.IsUniqueViolation(err) {
				return kernel.ErrConflict("a user with this email already exists")
			}
			return kernel.ErrInternal(err)
		}
		if _, err := qtx.CreateMembership(ctx, auth.CreateMembershipParams{
			OrganisationID: orgID,
			UserID:         user.ID,
			Role:           auth.OrganisationRole(req.Role),
			Status:         "active",
		}); err != nil {
			return kernel.ErrInternal(err)
		}
		return nil
	})
	if err != nil {
		return nil, err
	}
	return s.buildOrgDetail(ctx, orgID)
}

// =============================================================================
// COMPANY DETAILS (the god-view's one WRITE surface)
// A superuser may view AND edit any org's Company Details. Both methods gate on
// requireSuperuser, then delegate cross-tenant to the organisation service's
// no-auth GetByID/UpdateByID — so the form fields, validation, and the
// country_code/native_currency immutability are identical to the self path.
// =============================================================================

// GetOrganisationDetails returns a chosen org's full company details. Superuser only.
func (s *Service) GetOrganisationDetails(ctx context.Context, authUserID, orgID uuid.UUID) (*organisation.OrganisationDetailsResponse, error) {
	if err := s.requireSuperuser(ctx, authUserID); err != nil {
		return nil, err
	}
	return s.orgSvc.GetByID(ctx, orgID)
}

// UpdateOrganisationDetails edits a chosen org's company details. Superuser only.
func (s *Service) UpdateOrganisationDetails(ctx context.Context, authUserID, orgID uuid.UUID, req organisation.UpdateOrganisationRequest) (*organisation.OrganisationDetailsResponse, error) {
	if err := s.requireSuperuser(ctx, authUserID); err != nil {
		return nil, err
	}
	return s.orgSvc.UpdateByID(ctx, orgID, req)
}

// =============================================================================
// USERS
// =============================================================================

// ListUsers returns every live user on the platform. Superuser only.
func (s *Service) ListUsers(ctx context.Context, authUserID uuid.UUID) ([]AdminUserResponse, error) {
	if err := s.requireSuperuser(ctx, authUserID); err != nil {
		return nil, err
	}
	rows, err := s.authQueries.ListAllUsers(ctx)
	if err != nil {
		return nil, kernel.ErrInternal(err)
	}
	out := make([]AdminUserResponse, 0, len(rows))
	for _, r := range rows {
		out = append(out, AdminUserResponse{
			ID:          r.ID.String(),
			Email:       r.Email,
			FirstName:   r.FirstName,
			LastName:    r.LastName,
			IsActive:    r.IsActive,
			IsSuperuser: r.IsSuperuser,
			LastLoginAt: kernel.TimestampToStringPtr(r.LastLoginAt),
			CreatedAt:   r.CreatedAt.Time.Format(time.RFC3339),
		})
	}
	return out, nil
}

// GetUser returns one user plus every organisation they belong to (the user
// drill-in). Superuser only.
func (s *Service) GetUser(ctx context.Context, authUserID, targetID uuid.UUID) (*AdminUserDetailResponse, error) {
	if err := s.requireSuperuser(ctx, authUserID); err != nil {
		return nil, err
	}
	u, err := s.authQueries.GetUser(ctx, targetID)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, kernel.ErrNotFound("user", targetID.String())
		}
		return nil, kernel.ErrInternal(err)
	}
	memberships, err := s.authQueries.ListMembershipsForUser(ctx, targetID)
	if err != nil {
		return nil, kernel.ErrInternal(err)
	}
	membershipDTOs := make([]AdminMembershipResponse, 0, len(memberships))
	for _, m := range memberships {
		membershipDTOs = append(membershipDTOs, AdminMembershipResponse{
			OrganisationID:   m.OrganisationID.String(),
			OrganisationName: m.OrganisationName,
			Role:             string(m.Role),
			Status:           m.Status,
			MemberSince:      m.MemberSince.Time.Format(time.RFC3339),
		})
	}
	return &AdminUserDetailResponse{
		User: AdminUserResponse{
			ID:          u.ID.String(),
			Email:       u.Email,
			FirstName:   u.FirstName,
			LastName:    u.LastName,
			IsActive:    u.IsActive,
			IsSuperuser: u.IsSuperuser,
			LastLoginAt: kernel.TimestampToStringPtr(u.LastLoginAt),
			CreatedAt:   u.CreatedAt.Time.Format(time.RFC3339),
		},
		Memberships: membershipDTOs,
	}, nil
}
