-- ==============================================================================
-- SEED: chart_template  (the DEFAULT chart of accounts for a new organisation)
-- GLOBAL reference data (country_code NULL = the global fallback template). The
-- single, consolidated source for the standard chart — provisioned into an org's
-- categories by ProvisionCategoriesForOrg. Generated from the FreeAgent chart.
-- Per-country override templates can be added later with a non-NULL country_code.
--
-- Idempotent. Apply with:  psql "$DATABASE_URL" -f db/seeds/chart_template.sql
-- ==============================================================================

INSERT INTO chart_template (country_code, nominal_code, name, account_type, api_group,
    tax_reporting_name, allowable_for_tax, default_vat, is_capital_asset, is_system_managed, is_user_subdivided) VALUES
  (NULL, '001', 'Sales', 'INCOME', 'income_categories', NULL, NULL, 'STANDARD', 'f', 'f', 'f'),
  (NULL, '051', 'Interest Received', 'OTHER_INCOME', 'general_categories', NULL, NULL, 'EXEMPT', 'f', 'f', 'f'),
  (NULL, '056', 'Refund of Other Tax Received', 'OTHER_INCOME', 'general_categories', NULL, NULL, 'OUTSIDE_SCOPE', 'f', 'f', 'f'),
  (NULL, '100', 'Purchases', 'COST_OF_SALES', 'cost_of_sales_categories', NULL, 't', 'STANDARD', 'f', 'f', 'f'),
  (NULL, '101', 'Materials', 'COST_OF_SALES', 'cost_of_sales_categories', NULL, 't', 'STANDARD', 'f', 'f', 'f'),
  (NULL, '102', 'Commission Paid', 'COST_OF_SALES', 'cost_of_sales_categories', NULL, 't', 'STANDARD', 'f', 'f', 'f'),
  (NULL, '103', 'Subcontractor Costs', 'COST_OF_SALES', 'cost_of_sales_categories', NULL, 't', 'STANDARD', 'f', 'f', 'f'),
  (NULL, '200', 'Accountancy Fees', 'ADMIN_EXPENSE', 'admin_expenses_categories', NULL, 't', 'STANDARD', 'f', 'f', 'f'),
  (NULL, '201', 'Advertising', 'ADMIN_EXPENSE', 'admin_expenses_categories', NULL, 't', 'STANDARD', 'f', 'f', 'f'),
  (NULL, '202', 'Bad Debts Written Off', 'ADMIN_EXPENSE', 'admin_expenses_categories', NULL, 't', 'OUTSIDE_SCOPE', 'f', 'f', 'f'),
  (NULL, '203', 'Bank Charges', 'ADMIN_EXPENSE', 'admin_expenses_categories', NULL, 't', 'EXEMPT', 'f', 'f', 'f'),
  (NULL, '204', 'Business Entertaining', 'ADMIN_EXPENSE', 'admin_expenses_categories', NULL, 'f', 'STANDARD', 'f', 'f', 'f'),
  (NULL, '205', 'Canteen', 'ADMIN_EXPENSE', 'admin_expenses_categories', NULL, 't', 'STANDARD', 'f', 'f', 'f'),
  (NULL, '206', 'Charitable Donations', 'ADMIN_EXPENSE', 'admin_expenses_categories', NULL, 'f', 'OUTSIDE_SCOPE', 'f', 'f', 'f'),
  (NULL, '207', 'Computer Software Costs', 'ADMIN_EXPENSE', 'admin_expenses_categories', NULL, 't', 'STANDARD', 'f', 'f', 'f'),
  (NULL, '208', 'Consumable Items', 'ADMIN_EXPENSE', 'admin_expenses_categories', NULL, 't', 'STANDARD', 'f', 'f', 'f'),
  (NULL, '209', 'Credit Card Charges', 'ADMIN_EXPENSE', 'admin_expenses_categories', NULL, 't', 'EXEMPT', 'f', 'f', 'f'),
  (NULL, '210', 'Depreciation of Fixed Assets', 'ADMIN_EXPENSE', 'admin_expenses_categories', NULL, 'f', 'OUTSIDE_SCOPE', 'f', 'f', 'f'),
  (NULL, '211', 'Directors'' Pensions', 'ADMIN_EXPENSE', 'admin_expenses_categories', NULL, 't', 'OUTSIDE_SCOPE', 'f', 'f', 'f'),
  (NULL, '212', 'Directors'' Remuneration', 'ADMIN_EXPENSE', 'admin_expenses_categories', NULL, 't', 'OUTSIDE_SCOPE', 'f', 'f', 'f'),
  (NULL, '213', 'Employers NI (Directors)', 'ADMIN_EXPENSE', 'admin_expenses_categories', NULL, 't', 'OUTSIDE_SCOPE', 'f', 'f', 'f'),
  (NULL, '214', 'Employers NI (Staff)', 'ADMIN_EXPENSE', 'admin_expenses_categories', NULL, 't', 'OUTSIDE_SCOPE', 'f', 'f', 'f'),
  (NULL, '215', 'Finance Charges', 'ADMIN_EXPENSE', 'admin_expenses_categories', NULL, 't', 'EXEMPT', 'f', 'f', 'f'),
  (NULL, '216', 'FX Transaction Charges', 'ADMIN_EXPENSE', 'admin_expenses_categories', NULL, 't', 'OUTSIDE_SCOPE', 'f', 'f', 'f'),
  (NULL, '217', 'Gain on Disposal of Assets', 'ADMIN_EXPENSE', 'admin_expenses_categories', NULL, 'f', 'OUTSIDE_SCOPE', 'f', 'f', 'f'),
  (NULL, '218', 'Gain on FX Transactions', 'ADMIN_EXPENSE', 'admin_expenses_categories', NULL, 'f', 'OUTSIDE_SCOPE', 'f', 'f', 'f'),
  (NULL, '219', 'General Consultancy Fees', 'ADMIN_EXPENSE', 'admin_expenses_categories', NULL, 't', 'STANDARD', 'f', 'f', 'f'),
  (NULL, '220', 'General Maintenance', 'ADMIN_EXPENSE', 'admin_expenses_categories', NULL, 't', 'STANDARD', 'f', 'f', 'f'),
  (NULL, '221', 'Hire/Lease - Computer Equipment', 'ADMIN_EXPENSE', 'admin_expenses_categories', NULL, 't', 'STANDARD', 'f', 'f', 'f'),
  (NULL, '222', 'Hire/Lease - Motor Vehicles', 'ADMIN_EXPENSE', 'admin_expenses_categories', NULL, 't', 'STANDARD', 'f', 'f', 'f'),
  (NULL, '223', 'Hire/Lease - Other Assets', 'ADMIN_EXPENSE', 'admin_expenses_categories', NULL, 't', 'STANDARD', 'f', 'f', 'f'),
  (NULL, '224', 'IT and Computer Consumables', 'ADMIN_EXPENSE', 'admin_expenses_categories', NULL, 't', 'STANDARD', 'f', 'f', 'f'),
  (NULL, '225', 'Insurance', 'ADMIN_EXPENSE', 'admin_expenses_categories', NULL, 't', 'EXEMPT', 'f', 'f', 'f'),
  (NULL, '226', 'Insurance on Premises', 'ADMIN_EXPENSE', 'admin_expenses_categories', NULL, 't', 'EXEMPT', 'f', 'f', 'f'),
  (NULL, '227', 'Interest Payable', 'ADMIN_EXPENSE', 'admin_expenses_categories', NULL, 't', 'EXEMPT', 'f', 'f', 'f'),
  (NULL, '228', 'Irrecoverable VAT', 'ADMIN_EXPENSE', 'admin_expenses_categories', NULL, 't', 'OUTSIDE_SCOPE', 'f', 'f', 'f'),
  (NULL, '229', 'Late Payment of Tax', 'ADMIN_EXPENSE', 'admin_expenses_categories', NULL, 'f', 'OUTSIDE_SCOPE', 'f', 'f', 'f'),
  (NULL, '230', 'Leases and Hire Purchase', 'ADMIN_EXPENSE', 'admin_expenses_categories', NULL, 't', 'STANDARD', 'f', 'f', 'f'),
  (NULL, '231', 'Legal Fees', 'ADMIN_EXPENSE', 'admin_expenses_categories', NULL, 't', 'STANDARD', 'f', 'f', 'f'),
  (NULL, '232', 'Management Fees', 'ADMIN_EXPENSE', 'admin_expenses_categories', NULL, 't', 'STANDARD', 'f', 'f', 'f'),
  (NULL, '233', 'Other Legal & Professional Fees', 'ADMIN_EXPENSE', 'admin_expenses_categories', NULL, 't', 'STANDARD', 'f', 'f', 'f'),
  (NULL, '234', 'Political Donations', 'ADMIN_EXPENSE', 'admin_expenses_categories', NULL, 'f', 'OUTSIDE_SCOPE', 'f', 'f', 'f'),
  (NULL, '235', 'Postage Costs', 'ADMIN_EXPENSE', 'admin_expenses_categories', NULL, 't', 'ZERO', 'f', 'f', 'f'),
  (NULL, '236', 'Premises Cleaning', 'ADMIN_EXPENSE', 'admin_expenses_categories', NULL, 't', 'STANDARD', 'f', 'f', 'f'),
  (NULL, '237', 'Premises Repairs & Maintenance', 'ADMIN_EXPENSE', 'admin_expenses_categories', NULL, 't', 'STANDARD', 'f', 'f', 'f'),
  (NULL, '238', 'Premises Repairs & Renewals', 'ADMIN_EXPENSE', 'admin_expenses_categories', NULL, 't', 'STANDARD', 'f', 'f', 'f'),
  (NULL, '239', 'Printing Costs', 'ADMIN_EXPENSE', 'admin_expenses_categories', NULL, 't', 'STANDARD', 'f', 'f', 'f'),
  (NULL, '240', 'Publications & Subscriptions', 'ADMIN_EXPENSE', 'admin_expenses_categories', NULL, 't', 'STANDARD', 'f', 'f', 'f'),
  (NULL, '241', 'Rates on Premises', 'ADMIN_EXPENSE', 'admin_expenses_categories', NULL, 't', 'OUTSIDE_SCOPE', 'f', 'f', 'f'),
  (NULL, '242', 'Rent of Premises', 'ADMIN_EXPENSE', 'admin_expenses_categories', NULL, 't', 'STANDARD', 'f', 'f', 'f'),
  (NULL, '243', 'Research & Development', 'ADMIN_EXPENSE', 'admin_expenses_categories', NULL, 't', 'STANDARD', 'f', 'f', 'f'),
  (NULL, '244', 'Staff Benefits in Kind', 'ADMIN_EXPENSE', 'admin_expenses_categories', NULL, 'f', 'OUTSIDE_SCOPE', 'f', 'f', 'f'),
  (NULL, '245', 'Staff Entertaining', 'ADMIN_EXPENSE', 'admin_expenses_categories', NULL, 't', 'STANDARD', 'f', 'f', 'f'),
  (NULL, '246', 'Staff Pensions', 'ADMIN_EXPENSE', 'admin_expenses_categories', NULL, 't', 'OUTSIDE_SCOPE', 'f', 'f', 'f'),
  (NULL, '247', 'Staff Training', 'ADMIN_EXPENSE', 'admin_expenses_categories', NULL, 't', 'STANDARD', 'f', 'f', 'f'),
  (NULL, '248', 'Staff Welfare', 'ADMIN_EXPENSE', 'admin_expenses_categories', NULL, 't', 'STANDARD', 'f', 'f', 'f'),
  (NULL, '249', 'Stationery', 'ADMIN_EXPENSE', 'admin_expenses_categories', NULL, 't', 'STANDARD', 'f', 'f', 'f'),
  (NULL, '250', 'Professional Body Subscriptions', 'ADMIN_EXPENSE', 'admin_expenses_categories', NULL, 't', 'STANDARD', 'f', 'f', 'f'),
  (NULL, '251', 'Sundry Expenses', 'ADMIN_EXPENSE', 'admin_expenses_categories', NULL, 't', 'STANDARD', 'f', 'f', 'f'),
  (NULL, '252', 'Telecommunication Costs', 'ADMIN_EXPENSE', 'admin_expenses_categories', NULL, 't', 'STANDARD', 'f', 'f', 'f'),
  (NULL, '253', 'Accommodation and Meals', 'ADMIN_EXPENSE', 'admin_expenses_categories', NULL, 't', 'STANDARD', 'f', 'f', 'f'),
  (NULL, '254', 'Travel and Subsistence', 'ADMIN_EXPENSE', 'admin_expenses_categories', NULL, 't', 'STANDARD', 'f', 'f', 'f'),
  (NULL, '255', 'Use of Residence', 'ADMIN_EXPENSE', 'admin_expenses_categories', NULL, 't', 'OUTSIDE_SCOPE', 'f', 'f', 'f'),
  (NULL, '256', 'Vehicle Running Costs', 'ADMIN_EXPENSE', 'admin_expenses_categories', NULL, 't', 'STANDARD', 'f', 'f', 'f'),
  (NULL, '257', 'Wages and Salaries', 'ADMIN_EXPENSE', 'admin_expenses_categories', NULL, 't', 'OUTSIDE_SCOPE', 'f', 'f', 'f'),
  (NULL, '258', 'Amortisation of Intangibles', 'ADMIN_EXPENSE', 'admin_expenses_categories', NULL, 'f', 'OUTSIDE_SCOPE', 'f', 'f', 'f'),
  (NULL, '390', 'Realized Currency Exchange Gain/Loss', 'ADMIN_EXPENSE', 'admin_expenses_categories', NULL, 'f', 'OUTSIDE_SCOPE', 'f', 'f', 'f'),
  (NULL, '391', 'Unrealized Currency Exchange Gain/Loss', 'ADMIN_EXPENSE', 'admin_expenses_categories', NULL, 'f', 'OUTSIDE_SCOPE', 'f', 'f', 'f'),
  (NULL, '401', 'Salaries', 'PAYROLL_EXPENSE', NULL, NULL, NULL, NULL, 'f', 'f', 'f'),
  (NULL, '402', 'Employer NICs', 'PAYROLL_EXPENSE', NULL, NULL, NULL, NULL, 'f', 'f', 'f'),
  (NULL, '403', 'Staff Pensions', 'PAYROLL_EXPENSE', NULL, NULL, NULL, NULL, 'f', 'f', 'f'),
  (NULL, '407', 'Directors'' Salaries', 'PAYROLL_EXPENSE', NULL, NULL, NULL, NULL, 'f', 'f', 'f'),
  (NULL, '408', 'Directors'' Employer NICs', 'PAYROLL_EXPENSE', NULL, NULL, NULL, NULL, 'f', 'f', 'f'),
  (NULL, '409', 'Directors'' Staff Pensions', 'PAYROLL_EXPENSE', NULL, NULL, NULL, NULL, 'f', 'f', 'f'),
  (NULL, '602', 'Capital Asset Additions', 'CAPITAL_ASSET', 'general_categories', NULL, NULL, 'STANDARD', 't', 'f', 'f'),
  (NULL, '604', 'Capital Asset Disposal', 'CAPITAL_ASSET', 'general_categories', NULL, NULL, 'STANDARD', 't', 'f', 'f'),
  (NULL, '670', 'Share Premium', 'EQUITY', 'general_categories', NULL, NULL, NULL, 'f', 'f', 'f'),
  (NULL, '681', 'Trade Debtors', 'CURRENT_ASSET', 'general_categories', NULL, NULL, NULL, 'f', 't', 'f'),
  (NULL, '682', 'Other Debtors', 'CURRENT_ASSET', 'general_categories', NULL, NULL, NULL, 'f', 't', 'f'),
  (NULL, '684', 'Prepayments and Accrued Income', 'CURRENT_ASSET', 'general_categories', NULL, NULL, NULL, 'f', 't', 'f'),
  (NULL, '688', 'Stock / Work in Progress', 'CURRENT_ASSET', 'general_categories', NULL, NULL, NULL, 'f', 't', 'f'),
  (NULL, '750', 'Bank Account', 'BANK', 'general_categories', NULL, NULL, NULL, 'f', 't', 'f'),
  (NULL, '796', 'Trade Creditors', 'LIABILITY', 'general_categories', NULL, NULL, NULL, 'f', 't', 'f'),
  (NULL, '797', 'Other Creditors', 'LIABILITY', 'general_categories', NULL, NULL, NULL, 'f', 'f', 'f'),
  (NULL, '813', 'Pension Creditor', 'LIABILITY', 'general_categories', NULL, NULL, NULL, 'f', 't', 'f'),
  (NULL, '814', 'PAYE / NI', 'TAX_LIABILITY', 'general_categories', NULL, NULL, NULL, 'f', 't', 'f'),
  (NULL, '815', 'Other Payroll Deductions', 'TAX_LIABILITY', 'general_categories', NULL, NULL, NULL, 'f', 't', 'f'),
  (NULL, '817', 'VAT', 'TAX_LIABILITY', 'general_categories', NULL, NULL, NULL, 'f', 't', 'f'),
  (NULL, '820', 'Corporation Tax', 'TAX_LIABILITY', 'general_categories', NULL, NULL, NULL, 'f', 't', 'f'),
  (NULL, '823', 'Deferred VAT', 'TAX_LIABILITY', 'general_categories', NULL, NULL, NULL, 'f', 't', 'f'),
  (NULL, '824', 'VAT OSS', 'TAX_LIABILITY', 'general_categories', NULL, NULL, NULL, 'f', 't', 'f'),
  (NULL, '900', 'Capital Account', 'USER_ACCOUNT', 'general_categories', NULL, NULL, NULL, 'f', 't', 't'),
  (NULL, '902', 'Net Salary and Bonuses', 'USER_ACCOUNT', 'general_categories', NULL, NULL, NULL, 'f', 't', 't'),
  (NULL, '904', 'Employer NI', 'USER_ACCOUNT', 'general_categories', NULL, NULL, NULL, 'f', 't', 't'),
  (NULL, '905', 'Expense Payment', 'USER_ACCOUNT', 'general_categories', NULL, NULL, NULL, 'f', 't', 't'),
  (NULL, '907', 'Director Loan Account', 'USER_ACCOUNT', 'general_categories', NULL, NULL, NULL, 'f', 't', 't'),
  (NULL, '908', 'Dividend', 'USER_ACCOUNT', 'general_categories', NULL, NULL, NULL, 'f', 't', 't'),
  (NULL, '910', 'Capital Introduced', 'USER_ACCOUNT', 'general_categories', NULL, NULL, NULL, 'f', 't', 't'),
  (NULL, '921', 'Share Capital', 'EQUITY', 'general_categories', NULL, NULL, NULL, 'f', 't', 'f'),
  (NULL, '968', 'Profit and Loss', 'EQUITY', 'general_categories', NULL, NULL, NULL, 'f', 't', 'f'),
  (NULL, '998', 'Money in Transit / Contra', 'SYSTEM', 'general_categories', NULL, NULL, NULL, 'f', 't', 'f'),
  (NULL, '999', 'Suspense Account', 'SYSTEM', 'general_categories', NULL, NULL, NULL, 'f', 't', 'f')
ON CONFLICT (country_code, nominal_code) DO NOTHING;
