package organisation

// service.go
// =============================================================================
// Service — the business logic layer for an organisation's own
// "Company Details" (the settings screen modelled on FreeAgent's Company
// Details: company type, name, registered address, UK tax references, invoice
// contact details, and a short business profile).
//
// All of this data lives on the organisations table (db/schema/auth_schema.sql),
// so this service is a thin layer over the existing auth queries — exactly like
// MemberService:
//
//   HTTP handler (server.go)
//     ↓
//   Service (this file)
//     ↓
//   auth.Querier (db/auth — generated by sqlc)
//     ↓
//   PostgreSQL
//
// There is always exactly ONE organisation in scope — the caller's, taken from
// the bearer token (authOrgID), never a path/body param — so there is no list
// and no id to pass. A caller can therefore only ever read or edit their OWN
// organisation; multi-tenant isolation is inherent.
//
// Access rules:
//   - GET  : any ACTIVE member may view the company details.
//   - PUT  : only an OWNER or ADMIN may edit them (kernel.IsOrgAdmin).
//
// It reuses the shared kernel: kernel.AuthorizeMember / kernel.IsOrgAdmin for the
// membership+role check, kernel.NullText / kernel.NullTextToPtr for nullable text,
// kernel.NormaliseCountryCode for the country-code field, and the kernel.Err*
// constructors. There is no money here, so no pence/decimal conversion.
// =============================================================================

import (
	"context"
	"errors"
	"strings"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"

	auth "github.com/operationfb/accounting-saas/db/auth"
	"github.com/operationfb/accounting-saas/internal/kernel"
)

// validCompanyType is the set company_type is restricted to. It mirrors the CHECK
// constraint in auth_schema.sql and the form's "Company type" dropdown. Codes are
// snake_case; the frontend maps them to labels ("Limited Company", etc.).
var validCompanyType = map[string]bool{
	"limited":     true, // limited company
	"sole_trader": true,
	"partnership": true,
	"landlord":    true, // unincorporated landlord
	"corporation": true,
}

// Service holds only the auth query set: reading and updating the
// organisation are single-table, single-statement operations, so there is no
// pool/transaction to keep (same shape as MemberService).
type Service struct {
	authQueries auth.Querier
}

// NewService is the constructor, called once in main.go. authQueries
// is the same auth.Querier already shared with the other services.
func NewService(authQueries auth.Querier) *Service {
	return &Service{authQueries: authQueries}
}

// =============================================================================
// AUTHORIZATION
// =============================================================================

// authorize confirms the caller is an ACTIVE member of the organisation and
// returns their role. Mirrors MemberService.authorize / ContactService.authorize
// (kept per-service for consistency). Non-members and deactivated members are
// refused (403); the returned role lets UpdateOrganisation gate editing to
// owners/admins.
func (s *Service) authorize(ctx context.Context, userID, orgID uuid.UUID) (auth.OrganisationRole, error) {
	return kernel.AuthorizeMember(ctx, s.authQueries, userID, orgID)
}

// =============================================================================
// GET
// =============================================================================

// GetOrganisation returns the caller's organisation company details. Any active
// member may read them. The organisation is taken from the authenticated token,
// so a caller can only ever read their own org.
func (s *Service) GetOrganisation(
	ctx context.Context,
	authUserID uuid.UUID,
	authOrgID uuid.UUID,
) (*OrganisationDetailsResponse, error) {
	if _, err := s.authorize(ctx, authUserID, authOrgID); err != nil {
		return nil, err
	}
	return s.GetByID(ctx, authOrgID)
}

// GetByID fetches an organisation's company details by id, with NO authorisation
// — the CALLER is responsible for it. The self handler (GetOrganisation) checks
// membership first; the platform-admin handler checks superuser first and then
// calls this cross-tenant. Kept separate so the read logic isn't duplicated.
func (s *Service) GetByID(ctx context.Context, orgID uuid.UUID) (*OrganisationDetailsResponse, error) {
	org, err := s.authQueries.GetOrganisation(ctx, orgID)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, kernel.ErrNotFound("organisation", orgID.String())
		}
		return nil, kernel.ErrInternal(err)
	}
	return organisationToResponse(org), nil
}

// =============================================================================
// UPDATE
// =============================================================================

// UpdateOrganisation updates the company-details fields (PUT semantics). Only an
// owner or admin may edit. The organisation is taken from the token, so it always
// targets the caller's own org.
//
// This is a read-modify-write: a few organisation columns are NOT part of the
// Company Details form (slug, native_currency, timezone, and — until VAT is added
// to the form — vrn). We fetch the existing row first and pass those through
// unchanged so a PUT from this form can't wipe them. A future "general settings"
// or "VAT" screen will set them via their own request fields.
func (s *Service) UpdateOrganisation(
	ctx context.Context,
	authUserID uuid.UUID,
	authOrgID uuid.UUID,
	req UpdateOrganisationRequest,
) (*OrganisationDetailsResponse, error) {
	role, err := s.authorize(ctx, authUserID, authOrgID)
	if err != nil {
		return nil, err
	}
	if !kernel.IsOrgAdmin(role) {
		return nil, kernel.ErrForbidden("only owners and admins can edit company details")
	}
	return s.UpdateByID(ctx, authOrgID, req)
}

// UpdateByID applies the company-details read-modify-write to an organisation by
// id, with NO authorisation — the CALLER is responsible for it (the self handler
// checks owner/admin membership; the platform-admin handler checks superuser and
// calls this cross-tenant). country_code + native_currency (and slug/vrn/timezone)
// are preserved from the stored row, so they stay immutable on either path.
func (s *Service) UpdateByID(
	ctx context.Context,
	orgID uuid.UUID,
	req UpdateOrganisationRequest,
) (*OrganisationDetailsResponse, error) {
	// Validate / normalise. name is the org's NOT NULL primary name, so it is
	// required (the form's "Company name"). The binding `required` tag catches a
	// missing value at the HTTP edge; this re-check covers direct/test callers.
	name := strings.TrimSpace(req.Name)
	if name == "" {
		return nil, kernel.ErrValidation("name is required", nil)
	}
	companyType, err := normaliseCompanyType(req.CompanyType)
	if err != nil {
		return nil, err
	}

	// Read first so we can preserve the fields this form does not edit (and to
	// 404 if the org was soft-deleted).
	existing, err := s.authQueries.GetOrganisation(ctx, orgID)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, kernel.ErrNotFound("organisation", orgID.String())
		}
		return nil, kernel.ErrInternal(err)
	}

	updated, err := s.authQueries.UpdateOrganisation(ctx, auth.UpdateOrganisationParams{
		ID:   orgID,
		Name: name,

		// Preserved — not on the Company Details form, or fixed at creation and
		// immutable here (country_code + native_currency).
		Slug:           existing.Slug,
		Vrn:            existing.Vrn,
		NativeCurrency: existing.NativeCurrency,
		Timezone:       existing.Timezone,
		CountryCode:    existing.CountryCode,

		// Identity & UK company/tax references.
		LegalName:               kernel.NullText(req.LegalName),
		CompanyType:             kernel.NullText(companyType),
		CompaniesHouseNumber:    kernel.NullText(req.CompaniesHouseNumber),
		Utr:                     kernel.NullText(req.Utr), // "Corporation Tax Reference"
		PayeReference:           kernel.NullText(req.PayeReference),
		AccountsOfficeReference: kernel.NullText(req.AccountsOfficeReference),
		// Employment Allowance claim flag: nil (field omitted) preserves the stored
		// value, so an older client that doesn't send it can't accidentally clear it.
		ClaimsEmploymentAllowance: boolOr(req.ClaimsEmploymentAllowance, existing.ClaimsEmploymentAllowance),

		// Structured address.
		AddressLine1: kernel.NullText(req.AddressLine1),
		AddressLine2: kernel.NullText(req.AddressLine2),
		AddressLine3: kernel.NullText(req.AddressLine3),
		Town:         kernel.NullText(req.Town),
		Region:       kernel.NullText(req.Region),
		Postcode:     kernel.NullText(req.Postcode),

		// Invoice contact details + business profile.
		BusinessPhone:       kernel.NullText(req.BusinessPhone),
		ContactEmail:        kernel.NullText(req.ContactEmail),
		ContactPhone:        kernel.NullText(req.ContactPhone),
		Website:             kernel.NullText(req.Website),
		BusinessCategory:    kernel.NullText(req.BusinessCategory),
		BusinessDescription: kernel.NullText(req.BusinessDescription),
	})
	if err != nil {
		// The row was live a moment ago; ErrNoRows means it was soft-deleted in between.
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, kernel.ErrNotFound("organisation", orgID.String())
		}
		return nil, kernel.ErrInternal(err)
	}
	return organisationToResponse(updated), nil
}

// =============================================================================
// VALIDATION / NORMALISATION HELPERS
// =============================================================================

// normaliseCompanyType trims + lower-cases the company type and treats a nil or
// blank value as NULL (no type set). Anything else must be in the allowed set.
// Defence-in-depth behind the handler's `oneof` binding and the DB CHECK, so the
// service is correct even when called directly (e.g. from a test).
func normaliseCompanyType(raw *string) (*string, error) {
	if raw == nil {
		return nil, nil
	}
	v := strings.ToLower(strings.TrimSpace(*raw))
	if v == "" {
		return nil, nil
	}
	if !validCompanyType[v] {
		return nil, kernel.ErrValidation("company_type must be one of limited, sole_trader, partnership, landlord, corporation", nil)
	}
	return &v, nil
}

// boolOr returns *v when the pointer is set, else the fallback (used to preserve a
// stored bool when the request omits the field).
func boolOr(v *bool, fallback bool) bool {
	if v != nil {
		return *v
	}
	return fallback
}

// =============================================================================
// RESPONSE FORMATTER
// =============================================================================

// organisationToResponse converts a database Organisation row (pgx types, UUIDs)
// into the API response shape (plain/optional strings). Nullable columns use the
// shared kernel.NullTextToPtr helper from expense_service.go. The legacy free-text
// registered_address column is intentionally NOT exposed (superseded by the
// structured address). native_currency / timezone / plan are returned read-only
// for the frontend's convenience even though this screen doesn't edit them.
func organisationToResponse(o auth.Organisation) *OrganisationDetailsResponse {
	return &OrganisationDetailsResponse{
		ID:          o.ID.String(),
		Name:        o.Name,
		Slug:        kernel.NullTextToPtr(o.Slug),
		LegalName:   kernel.NullTextToPtr(o.LegalName),
		CompanyType: kernel.NullTextToPtr(o.CompanyType),

		CompaniesHouseNumber:      kernel.NullTextToPtr(o.CompaniesHouseNumber),
		Utr:                       kernel.NullTextToPtr(o.Utr),
		Vrn:                       kernel.NullTextToPtr(o.Vrn),
		PayeReference:             kernel.NullTextToPtr(o.PayeReference),
		AccountsOfficeReference:   kernel.NullTextToPtr(o.AccountsOfficeReference),
		ClaimsEmploymentAllowance: o.ClaimsEmploymentAllowance,

		AddressLine1: kernel.NullTextToPtr(o.AddressLine1),
		AddressLine2: kernel.NullTextToPtr(o.AddressLine2),
		AddressLine3: kernel.NullTextToPtr(o.AddressLine3),
		Town:         kernel.NullTextToPtr(o.Town),
		Region:       kernel.NullTextToPtr(o.Region),
		Postcode:     kernel.NullTextToPtr(o.Postcode),
		CountryCode:  o.CountryCode,

		BusinessPhone:       kernel.NullTextToPtr(o.BusinessPhone),
		ContactEmail:        kernel.NullTextToPtr(o.ContactEmail),
		ContactPhone:        kernel.NullTextToPtr(o.ContactPhone),
		Website:             kernel.NullTextToPtr(o.Website),
		BusinessCategory:    kernel.NullTextToPtr(o.BusinessCategory),
		BusinessDescription: kernel.NullTextToPtr(o.BusinessDescription),

		NativeCurrency: o.NativeCurrency,
		Timezone:       o.Timezone,
		Plan:           o.Plan,
		IsActive:       o.IsActive,
		CreatedAt:      o.CreatedAt.Time.Format(time.RFC3339),
		UpdatedAt:      o.UpdatedAt.Time.Format(time.RFC3339),
	}
}
