package invoices

// service.go
// =============================================================================
// Service — the business logic layer for the invoices domain.
//
// An invoice is a sales document an organisation issues to one of its contacts.
// This service owns authorisation, validation, the money roll-up (lines → header
// totals), the status state machine (status.go), and the mapping between the API
// shape (decimal pound strings + percentage strings) and the database shape (pence
// integers + basis points + pgx types).
//
//   HTTP handler (handler.go)
//     ↓
//   Service (this file)
//     ↓
//   *invoicesdb.Queries (db/invoices — generated by sqlc)
//     ↓
//   PostgreSQL
//
// Money rules (see money/money.go):
//   - Amounts are stored as integer minor units (pence), BIGINT (int64), because
//     invoice totals can exceed the int32 ceiling.
//   - Line price is VAT-EXCLUSIVE; line VAT is ADDED ON TOP via money.AddOnVAT
//     (NOT money.ComputeFixedVAT, which extracts VAT from a gross — the expenses
//     direction). Line net = round(quantity × unit price) to whole pence.
//   - The header net/sales_tax/total are the sums of the lines, recomputed on every
//     save; due_value is a generated column (total − paid).
//
// Authorisation mirrors contacts: any active member may create/read/list; update /
// delete / status change require the invoice's creator OR an owner/admin.
// =============================================================================

import (
	"context"
	"errors"
	"fmt"
	"strconv"
	"strings"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/shopspring/decimal"

	auth "github.com/operationfb/accounting-saas/db/auth"
	contactsdb "github.com/operationfb/accounting-saas/db/contacts"
	invoicesdb "github.com/operationfb/accounting-saas/db/invoices"
	vatdb "github.com/operationfb/accounting-saas/db/vat"
	"github.com/operationfb/accounting-saas/internal/kernel"
	"github.com/operationfb/accounting-saas/internal/ledger"
	"github.com/operationfb/accounting-saas/money"
)

// Service holds the connection pool, the invoices query set, the auth query set
// used to resolve the caller's membership/role, and the contacts query set used to
// validate an invoice's contact belongs to the same organisation.
type Service struct {
	pool           *pgxpool.Pool
	queries        *invoicesdb.Queries
	authQueries    auth.Querier
	contactQueries contactsdb.Querier
	// vatQueries is the read-only VAT lookup behind the filed-period lock: issuing or
	// reopening an invoice changes whether it counts in its VAT period, so an invoice
	// dated in an already-filed period can't cross the SENT boundary (assertNotFiled).
	vatQueries *vatdb.Queries
	// poster writes the GL journal entry when an invoice is issued (→SENT) and removes
	// it when reopened. Nil-guarded: with no poster wired, the GL is simply not posted.
	poster ledger.Poster
	// rates is the cross-domain FX-rate read seam (internal/fxrates): when a foreign
	// invoice arrives WITHOUT an explicit exchange_rate, nativeAmounts auto-fills it
	// from the stored daily rate for the invoice date. Nil-guarded — with no rates
	// wired, a missing rate on a foreign invoice stays a 422 (the old behaviour).
	rates RateLookup
}

// RateLookup is the read seam over the exchange-rate service. Given a currency and a
// date it returns the rate (HOME units per 1 unit of currency) effective on or before
// that date; the bool is false when no rate is stored. fxrates.Service satisfies this.
type RateLookup interface {
	RateOnOrBefore(ctx context.Context, currency string, on time.Time) (decimal.Decimal, bool, error)
}

// SetPoster wires the general-ledger poster after construction (mirrors the
// expenses.SetPublisher seam). Nil leaves GL posting off.
func (s *Service) SetPoster(p ledger.Poster) { s.poster = p }

// NewService is the constructor, called once in main.go. contactQueries is a
// cross-domain dependency (like authQueries), used to validate contact_id — the
// same pattern projects uses. vatQueries powers the filed-period lock; pass nil to
// disable it (the lock is then off). rates auto-fills a foreign invoice's exchange
// rate; pass nil to disable auto-fill.
func NewService(
	pool *pgxpool.Pool,
	queries *invoicesdb.Queries,
	authQueries auth.Querier,
	contactQueries contactsdb.Querier,
	vatQueries *vatdb.Queries,
	rates RateLookup,
) *Service {
	return &Service{
		pool:           pool,
		queries:        queries,
		authQueries:    authQueries,
		contactQueries: contactQueries,
		vatQueries:     vatQueries,
		rates:          rates,
	}
}

// assertNotFiled refuses the operation (409 conflict) when the given date falls
// inside a FILED VAT period — moving an invoice across the SENT boundary (issue / send
// / reopen / write_off / refund) changes a submitted return's output VAT. Nil-safe:
// with no vat querier wired (or an invalid date), the lock is inactive. Mirrors the
// bills/banking/expenses guard.
func (s *Service) assertNotFiled(ctx context.Context, orgID uuid.UUID, dated pgtype.Date) error {
	if s.vatQueries == nil || !dated.Valid {
		return nil
	}
	locked, err := s.vatQueries.IsDateInFiledPeriod(ctx, vatdb.IsDateInFiledPeriodParams{OrganisationID: orgID, DatedOn: dated})
	if err != nil {
		return kernel.ErrInternal(err)
	}
	if locked {
		return kernel.ErrConflict("this invoice is dated in a VAT period that has been filed, so its status can no longer be changed")
	}
	return nil
}

// =============================================================================
// AUTHORIZATION / VALIDATION
// =============================================================================

// authorize confirms the caller is an ACTIVE member of the organisation and
// returns their role (used to gate who may modify an invoice).
func (s *Service) authorize(ctx context.Context, userID, orgID uuid.UUID) (auth.OrganisationRole, error) {
	return kernel.AuthorizeMember(ctx, s.authQueries, userID, orgID)
}

// validateContact confirms contactID exists in the organisation and isn't
// soft-deleted. GetContact already filters by org + deleted_at IS NULL, so one
// query does both checks. Mirrors projects.validateContact.
func (s *Service) validateContact(ctx context.Context, contactID, orgID uuid.UUID) error {
	_, err := s.contactQueries.GetContact(ctx, contactsdb.GetContactParams{
		ID:             contactID,
		OrganisationID: orgID,
	})
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return kernel.ErrValidation("contact_id does not exist or does not belong to this organisation", nil)
		}
		return kernel.ErrInternal(err)
	}
	return nil
}

// =============================================================================
// CREATE
// =============================================================================

// CreateInvoice validates the request, computes the money roll-up, and writes the
// header + lines + totals in one transaction. The owning org and creator come from
// the token. Any active member may create an invoice; it starts as DRAFT.
func (s *Service) CreateInvoice(
	ctx context.Context,
	authUserID uuid.UUID,
	authOrgID uuid.UUID,
	req CreateInvoiceRequest,
) (*InvoiceResponse, error) {
	if _, err := s.authorize(ctx, authUserID, authOrgID); err != nil {
		return nil, err
	}

	ref, err := validateReference(req.Reference)
	if err != nil {
		return nil, err
	}

	contactID, err := uuid.Parse(req.ContactID)
	if err != nil {
		return nil, kernel.ErrValidation("contact_id is not a valid UUID", err)
	}
	if err := s.validateContact(ctx, contactID, authOrgID); err != nil {
		return nil, err
	}

	datedOn, err := parseDate("dated_on", req.DatedOn)
	if err != nil {
		return nil, err
	}
	dueOn, err := parseOptionalDate("due_on", req.DueOn)
	if err != nil {
		return nil, err
	}

	lines, net, tax, total, err := buildLines(req.Items)
	if err != nil {
		return nil, err
	}

	var detail *InvoiceResponse
	err = kernel.WithTx(ctx, s.pool, func(tx pgx.Tx) error {
		qtx := s.queries.WithTx(tx)

		inv, err := qtx.CreateInvoice(ctx, invoicesdb.CreateInvoiceParams{
			OrganisationID:  authOrgID,
			CreatedByUserID: authUserID,
			ContactID:       contactID,
			DatedOn:         datedOn,
			DueOn:           dueOn,
			Reference:       pgtype.Text{String: ref, Valid: true},
			Currency:        normaliseCurrency(req.Currency),
		})
		if err != nil {
			if kernel.IsUniqueViolation(err) {
				return kernel.ErrConflict("an invoice with reference " + ref + " already exists")
			}
			return kernel.ErrInternal(err)
		}

		// Raise the org's invoice-counter floor past this number (when the reference
		// is numeric) so the next suggestion always advances and never reuses it.
		if err := raiseInvoiceCounter(ctx, tx, authOrgID, ref); err != nil {
			return err
		}

		if err := insertLines(ctx, qtx, inv.ID, authOrgID, lines); err != nil {
			return err
		}

		rate, nNet, nTax, nTotal, err := s.nativeAmounts(ctx, qtx, authOrgID, normaliseCurrency(req.Currency), req.ExchangeRate, datedOn, net, tax, total)
		if err != nil {
			return err
		}
		updated, err := qtx.UpdateInvoiceTotals(ctx, invoicesdb.UpdateInvoiceTotalsParams{
			ID:                       inv.ID,
			OrganisationID:           authOrgID,
			NetValueMinor:            net,
			SalesTaxValueMinor:       tax,
			TotalValueMinor:          total,
			ExchangeRate:             rate,
			NativeNetValueMinor:      nNet,
			NativeSalesTaxValueMinor: nTax,
			NativeTotalValueMinor:    nTotal,
		})
		if err != nil {
			return kernel.ErrInternal(err)
		}

		detail, err = s.buildDetail(ctx, qtx, updated)
		return err
	})
	if err != nil {
		return nil, err
	}
	return detail, nil
}

// =============================================================================
// GET / LIST
// =============================================================================

// GetInvoice fetches one invoice (header + line items), org-scoped. Any active
// member may read.
func (s *Service) GetInvoice(
	ctx context.Context,
	authUserID uuid.UUID,
	authOrgID uuid.UUID,
	id string,
) (*InvoiceResponse, error) {
	invID, err := uuid.Parse(id)
	if err != nil {
		return nil, kernel.ErrValidation("id is not a valid UUID", err)
	}
	if _, err := s.authorize(ctx, authUserID, authOrgID); err != nil {
		return nil, err
	}

	inv, err := s.queries.GetInvoice(ctx, invoicesdb.GetInvoiceParams{ID: invID, OrganisationID: authOrgID})
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, kernel.ErrNotFound("invoice", id)
		}
		return nil, kernel.ErrInternal(err)
	}
	resp, err := s.buildDetail(ctx, s.queries, inv)
	if err != nil {
		return nil, err
	}
	// Attach the read-only FX gain/loss panel for a SENT, foreign-currency invoice. A
	// native invoice stores a NULL exchange_rate, so .Valid already screens those out
	// (no extra org lookup for the common case). Soft errors (no today rate) omit the
	// panel rather than fail the read.
	if inv.ExchangeRate.Valid && inv.Status == StatusSent {
		summary, ferr := s.buildFXSummary(ctx, s.queries, inv)
		if ferr != nil {
			return nil, ferr
		}
		resp.FXSummary = summary
	}
	return resp, nil
}

// ListInvoices returns the org's invoices, newest first, WITHOUT line items (the
// list is a lighter summary; fetch one for its lines). Any active member may list.
func (s *Service) ListInvoices(
	ctx context.Context,
	authUserID uuid.UUID,
	authOrgID uuid.UUID,
) ([]*InvoiceResponse, error) {
	if _, err := s.authorize(ctx, authUserID, authOrgID); err != nil {
		return nil, err
	}

	rows, err := s.queries.ListInvoices(ctx, authOrgID)
	if err != nil {
		return nil, kernel.ErrInternal(err)
	}
	out := make([]*InvoiceResponse, 0, len(rows))
	for _, inv := range rows {
		out = append(out, invoiceToResponse(inv))
	}
	return out, nil
}

// ListOutstandingInvoices returns the org's SENT-but-not-fully-paid invoices (those
// still owing money — covers both unpaid and partially-paid). It backs the banking
// "Invoice Receipt" explanation picker: only a sent invoice can be settled, and a
// fully-paid one drops off. Any active member may list (the picker needs it). Reuses
// the same InvoiceResponse shape as ListInvoices (no line items); the dropdown label
// is composed client-side from reference + due_value.
func (s *Service) ListOutstandingInvoices(
	ctx context.Context,
	authUserID uuid.UUID,
	authOrgID uuid.UUID,
) ([]*InvoiceResponse, error) {
	if _, err := s.authorize(ctx, authUserID, authOrgID); err != nil {
		return nil, err
	}

	rows, err := s.queries.ListOutstandingInvoices(ctx, authOrgID)
	if err != nil {
		return nil, kernel.ErrInternal(err)
	}
	out := make([]*InvoiceResponse, 0, len(rows))
	for _, inv := range rows {
		out = append(out, invoiceToResponse(inv))
	}
	return out, nil
}

// =============================================================================
// NEXT REFERENCE (invoice auto-numbering)
// =============================================================================

// NextInvoiceReference returns the suggested reference for a NEW invoice — the
// org's next sequential invoice number, zero-padded (1 → "001"). The create form
// pre-fills it; the user may overwrite it. Any active member may read it.
func (s *Service) NextInvoiceReference(ctx context.Context, authUserID, authOrgID uuid.UUID) (string, error) {
	if _, err := s.authorize(ctx, authUserID, authOrgID); err != nil {
		return "", err
	}
	// The suggestion is the greater of (a) the stored counter floor and (b) one more
	// than the highest numeric reference already in use — so it always advances and
	// never re-suggests a taken number, even if the stored counter has drifted below
	// the references actually in use.
	floor, err := s.authQueries.GetNextInvoiceNumber(ctx, authOrgID)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return "", kernel.ErrNotFound("organisation", authOrgID.String())
		}
		return "", kernel.ErrInternal(err)
	}
	maxRef, err := s.queries.MaxNumericInvoiceReference(ctx, authOrgID)
	if err != nil {
		return "", kernel.ErrInternal(err)
	}
	next := floor
	if maxRef+1 > next {
		next = maxRef + 1
	}
	return formatInvoiceNumber(next), nil
}

// =============================================================================
// UPDATE
// =============================================================================

// UpdateInvoice fully replaces an invoice's editable fields and REBUILDS its lines
// (delete-all + re-insert) inside one transaction, then recomputes the totals. The
// load + ownership + DRAFT-only guards run inside the same transaction to close the
// check-then-write race. Allowed to the creator or an owner/admin; only a DRAFT may
// be edited (else 409).
func (s *Service) UpdateInvoice(
	ctx context.Context,
	authUserID uuid.UUID,
	authOrgID uuid.UUID,
	id string,
	req UpdateInvoiceRequest,
) (*InvoiceResponse, error) {
	invID, err := uuid.Parse(id)
	if err != nil {
		return nil, kernel.ErrValidation("id is not a valid UUID", err)
	}
	role, err := s.authorize(ctx, authUserID, authOrgID)
	if err != nil {
		return nil, err
	}

	// Validate the request up-front (these are 400/422s independent of DB state).
	ref, err := validateReference(req.Reference)
	if err != nil {
		return nil, err
	}
	contactID, err := uuid.Parse(req.ContactID)
	if err != nil {
		return nil, kernel.ErrValidation("contact_id is not a valid UUID", err)
	}
	if err := s.validateContact(ctx, contactID, authOrgID); err != nil {
		return nil, err
	}
	datedOn, err := parseDate("dated_on", req.DatedOn)
	if err != nil {
		return nil, err
	}
	dueOn, err := parseOptionalDate("due_on", req.DueOn)
	if err != nil {
		return nil, err
	}
	lines, net, tax, total, err := buildLines(req.Items)
	if err != nil {
		return nil, err
	}

	var detail *InvoiceResponse
	err = kernel.WithTx(ctx, s.pool, func(tx pgx.Tx) error {
		qtx := s.queries.WithTx(tx)

		existing, err := qtx.GetInvoice(ctx, invoicesdb.GetInvoiceParams{ID: invID, OrganisationID: authOrgID})
		if err != nil {
			if errors.Is(err, pgx.ErrNoRows) {
				return kernel.ErrNotFound("invoice", id)
			}
			return kernel.ErrInternal(err)
		}
		if existing.CreatedByUserID != authUserID && !kernel.IsOrgAdmin(role) {
			return kernel.ErrForbidden("you do not have access to this invoice")
		}
		if existing.Status != StatusDraft {
			return kernel.ErrConflict("only draft invoices can be edited")
		}

		if _, err := qtx.UpdateInvoice(ctx, invoicesdb.UpdateInvoiceParams{
			ID:             invID,
			OrganisationID: authOrgID,
			ContactID:      contactID,
			DatedOn:        datedOn,
			DueOn:          dueOn,
			Reference:      pgtype.Text{String: ref, Valid: true},
			Currency:       normaliseCurrency(req.Currency),
		}); err != nil {
			if kernel.IsUniqueViolation(err) {
				return kernel.ErrConflict("an invoice with reference " + ref + " already exists")
			}
			return kernel.ErrInternal(err)
		}

		// Replace the lines: delete all, re-insert the submitted set.
		if err := qtx.DeleteInvoiceItemsForInvoice(ctx, invoicesdb.DeleteInvoiceItemsForInvoiceParams{
			InvoiceID:      invID,
			OrganisationID: authOrgID,
		}); err != nil {
			return kernel.ErrInternal(err)
		}
		if err := insertLines(ctx, qtx, invID, authOrgID, lines); err != nil {
			return err
		}

		rate, nNet, nTax, nTotal, err := s.nativeAmounts(ctx, qtx, authOrgID, normaliseCurrency(req.Currency), req.ExchangeRate, datedOn, net, tax, total)
		if err != nil {
			return err
		}
		updated, err := qtx.UpdateInvoiceTotals(ctx, invoicesdb.UpdateInvoiceTotalsParams{
			ID:                       invID,
			OrganisationID:           authOrgID,
			NetValueMinor:            net,
			SalesTaxValueMinor:       tax,
			TotalValueMinor:          total,
			ExchangeRate:             rate,
			NativeNetValueMinor:      nNet,
			NativeSalesTaxValueMinor: nTax,
			NativeTotalValueMinor:    nTotal,
		})
		if err != nil {
			return kernel.ErrInternal(err)
		}

		detail, err = s.buildDetail(ctx, qtx, updated)
		return err
	})
	if err != nil {
		return nil, err
	}
	return detail, nil
}

// =============================================================================
// DELETE
// =============================================================================

// DeleteInvoice soft-deletes an invoice (sets deleted_at). Allowed to the creator
// or an owner/admin; only a DRAFT may be deleted (else 409). Load + guards + write
// run in one transaction.
func (s *Service) DeleteInvoice(
	ctx context.Context,
	authUserID uuid.UUID,
	authOrgID uuid.UUID,
	id string,
) error {
	invID, err := uuid.Parse(id)
	if err != nil {
		return kernel.ErrValidation("id is not a valid UUID", err)
	}
	role, err := s.authorize(ctx, authUserID, authOrgID)
	if err != nil {
		return err
	}

	return kernel.WithTx(ctx, s.pool, func(tx pgx.Tx) error {
		qtx := s.queries.WithTx(tx)

		existing, err := qtx.GetInvoice(ctx, invoicesdb.GetInvoiceParams{ID: invID, OrganisationID: authOrgID})
		if err != nil {
			if errors.Is(err, pgx.ErrNoRows) {
				return kernel.ErrNotFound("invoice", id)
			}
			return kernel.ErrInternal(err)
		}
		if existing.CreatedByUserID != authUserID && !kernel.IsOrgAdmin(role) {
			return kernel.ErrForbidden("you do not have access to this invoice")
		}
		if existing.Status != StatusDraft {
			return kernel.ErrConflict("only draft invoices can be deleted")
		}

		if err := qtx.SoftDeleteInvoice(ctx, invoicesdb.SoftDeleteInvoiceParams{ID: invID, OrganisationID: authOrgID}); err != nil {
			return kernel.ErrInternal(err)
		}
		return nil
	})
}

// =============================================================================
// STATUS
// =============================================================================

// ChangeStatus drives the stored lifecycle via an action discriminator (see
// status.go). Allowed to the creator or an owner/admin. An action that is illegal
// from the current status is a 409. Load + guard + write run in one transaction.
func (s *Service) ChangeStatus(
	ctx context.Context,
	authUserID uuid.UUID,
	authOrgID uuid.UUID,
	id string,
	action string,
) (*InvoiceResponse, error) {
	invID, err := uuid.Parse(id)
	if err != nil {
		return nil, kernel.ErrValidation("id is not a valid UUID", err)
	}
	role, err := s.authorize(ctx, authUserID, authOrgID)
	if err != nil {
		return nil, err
	}

	var detail *InvoiceResponse
	err = kernel.WithTx(ctx, s.pool, func(tx pgx.Tx) error {
		qtx := s.queries.WithTx(tx)

		existing, err := qtx.GetInvoice(ctx, invoicesdb.GetInvoiceParams{ID: invID, OrganisationID: authOrgID})
		if err != nil {
			if errors.Is(err, pgx.ErrNoRows) {
				return kernel.ErrNotFound("invoice", id)
			}
			return kernel.ErrInternal(err)
		}
		if existing.CreatedByUserID != authUserID && !kernel.IsOrgAdmin(role) {
			return kernel.ErrForbidden("you do not have access to this invoice")
		}

		target, ok := resolveTransition(action, existing.Status)
		if !ok {
			return kernel.ErrConflict(fmt.Sprintf("cannot %q an invoice in status %s", action, existing.Status))
		}

		// Filed-period lock: the VAT return counts status='SENT' invoices, so any
		// transition INTO or OUT OF SENT changes whether this invoice is in its period
		// (issue/send add it; reopen/write_off/refund remove it). If the invoice is
		// dated in an already-filed period, that would change a submitted return —
		// refuse it. A transition that doesn't touch SENT (e.g. DRAFT→SCHEDULED) is exempt.
		if target == StatusSent || existing.Status == StatusSent {
			if err := s.assertNotFiled(ctx, authOrgID, existing.DatedOn); err != nil {
				return err
			}
		}

		// A SENT invoice with money recorded against it (a bank Invoice Receipt) is a
		// live/part-paid receivable. Reopening to DRAFT is the ONLY route back to editing
		// — and an edit could then drop the total below the amount already paid. So once
		// any payment has landed, block the reopen: the bank receipt(s) must be removed
		// first (via the banking explain panel), which returns paid_value_minor to 0.
		// Other transitions (write_off / refund) are unaffected.
		if target == StatusDraft && existing.PaidValueMinor > 0 {
			return kernel.ErrConflict("cannot reopen an invoice that has payments recorded against it — remove the bank receipt(s) first")
		}

		updated, err := qtx.UpdateInvoiceStatus(ctx, invoicesdb.UpdateInvoiceStatusParams{
			ID:             invID,
			OrganisationID: authOrgID,
			Status:         target,
		})
		if err != nil {
			return kernel.ErrInternal(err)
		}

		// GL: post the receivable when the invoice is issued (→SENT); remove it when it
		// leaves SENT (reopen / write_off / refund). Atomic with the status change.
		if s.poster != nil {
			switch {
			case target == StatusSent:
				if err := s.postInvoiceSent(ctx, tx, authUserID, authOrgID, updated); err != nil {
					return err
				}
			case existing.Status == StatusSent:
				if err := s.poster.RemoveEntry(ctx, tx, authOrgID, ledgerSourceInvoice, updated.ID); err != nil {
					return err
				}
				// Reopen / write-off / refund is an UNDO, not a settlement: drop any unrealised
				// FX revaluation entry too, so a no-longer-SENT invoice carries no FX history.
				if err := s.poster.RemoveEntry(ctx, tx, authOrgID, ledgerSourceInvoiceRevaluation, updated.ID); err != nil {
					return err
				}
			}
		}

		detail, err = s.buildDetail(ctx, qtx, updated)
		return err
	})
	if err != nil {
		return nil, err
	}
	return detail, nil
}

// =============================================================================
// NATIVE-CURRENCY CONVERSION (for the general ledger)
// =============================================================================

// nativeAmounts converts an invoice's net / sales-tax / total into the organisation's
// native (home) currency, so the GL can post the invoice in the base currency (mirrors
// the expenses dual-currency pattern). For a native-currency invoice the amounts pass
// through unchanged and the rate is NULL; for a foreign invoice the request must supply
// an exchange_rate (native per 1 unit of the invoice currency) and the amounts are
// converted via money.ConvertMinor using each currency's minor_unit. `cur` must already
// be normalised (upper-cased / defaulted).
func (s *Service) nativeAmounts(
	ctx context.Context, q *invoicesdb.Queries, orgID uuid.UUID,
	cur, rateInput string, dated pgtype.Date, net, tax, total int64,
) (rate pgtype.Numeric, nativeNet, nativeTax, nativeTotal int64, err error) {
	org, gerr := s.authQueries.GetOrganisation(ctx, orgID)
	if gerr != nil {
		return rate, 0, 0, 0, kernel.ErrInternal(gerr)
	}

	// Same currency as the org's home currency: native == transaction, no rate.
	if strings.EqualFold(cur, org.NativeCurrency) {
		return pgtype.Numeric{}, net, tax, total, nil
	}

	// A foreign invoice needs a rate. The caller may supply one explicitly; otherwise
	// we AUTO-FILL it from the stored daily rate for the invoice date (so the user
	// doesn't hand-type it). Only when neither is available is it a 422.
	rateStr := strings.TrimSpace(rateInput)
	if rateStr == "" {
		filled, ferr := s.autoFillRate(ctx, cur, dated)
		if ferr != nil {
			return rate, 0, 0, 0, ferr
		}
		rateStr = filled
	}
	rateDec, derr := decimal.NewFromString(rateStr)
	if derr != nil || !rateDec.IsPositive() {
		return rate, 0, 0, 0, kernel.ErrValidation("exchange_rate must be a positive number", derr)
	}

	fromExp, err := s.currencyExp(ctx, q, cur)
	if err != nil {
		return rate, 0, 0, 0, err
	}
	toExp, err := s.currencyExp(ctx, q, org.NativeCurrency)
	if err != nil {
		return rate, 0, 0, 0, err
	}

	nativeNet = money.ConvertMinor(net, fromExp, toExp, rateDec)
	nativeTax = money.ConvertMinor(tax, fromExp, toExp, rateDec)
	nativeTotal = money.ConvertMinor(total, fromExp, toExp, rateDec)
	if serr := rate.Scan(rateStr); serr != nil {
		return rate, 0, 0, 0, kernel.ErrInternal(serr)
	}
	return rate, nativeNet, nativeTax, nativeTotal, nil
}

// autoFillRate looks up the stored daily rate for a foreign invoice when the request
// omitted an explicit exchange_rate. Returns the rate as a decimal string (for the
// NUMERIC scan path) or a 422 when no rate source is wired or no rate is stored for
// the currency on/before the invoice date.
func (s *Service) autoFillRate(ctx context.Context, cur string, dated pgtype.Date) (string, error) {
	if s.rates == nil || !dated.Valid {
		return "", kernel.ErrValidation("exchange_rate is required for an invoice not in the organisation's native currency", nil)
	}
	rateDec, ok, err := s.rates.RateOnOrBefore(ctx, cur, dated.Time)
	if err != nil {
		return "", err
	}
	if !ok {
		return "", kernel.ErrValidation("no exchange rate is available for "+cur+" on the invoice date — please enter one", nil)
	}
	return rateDec.String(), nil
}

// currencyExp returns a currency's minor_unit (decimal places) for money.ConvertMinor.
func (s *Service) currencyExp(ctx context.Context, q *invoicesdb.Queries, code string) (int, error) {
	c, err := q.GetCurrency(ctx, code)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return 0, kernel.ErrValidation("unknown currency "+code, nil)
		}
		return 0, kernel.ErrInternal(err)
	}
	return int(c.MinorUnit), nil
}

// GL event/source codes for the invoice receivable.
const (
	ledgerEventInvoiceSent         = "INVOICE_SENT"        // gl_posting_rules.event_code
	ledgerSourceInvoice            = "INVOICE"             // gl_journal_entries.source_type
	ledgerSourceInvoiceRevaluation = "INVOICE_REVALUATION" // the unrealised-FX revaluation entry (Phase 3)
)

// postInvoiceSent posts the issued invoice to the general ledger (Dr Debtors / Cr Sales
// + VAT control) in the org's base currency. The transaction-currency amounts come off
// the invoice; the base amounts are the native_* totals computed on save. Runs on the
// caller's tx, so the entry commits with the status change.
func (s *Service) postInvoiceSent(ctx context.Context, tx pgx.Tx, authUserID, orgID uuid.UUID, inv invoicesdb.Invoice) error {
	org, err := s.authQueries.GetOrganisation(ctx, orgID)
	if err != nil {
		return kernel.ErrInternal(err)
	}
	if err := s.poster.PostEntry(ctx, tx, ledger.EntryContext{
		OrganisationID: orgID,
		CompanyType:    org.CompanyType.String,
		CountryCode:    org.CountryCode,
		BaseCurrency:   org.NativeCurrency,
		TxnCurrency:    inv.Currency,
		ExchangeRate:   inv.ExchangeRate,
		EventCode:      ledgerEventInvoiceSent,
		SourceType:     ledgerSourceInvoice,
		SourceID:       inv.ID,
		EntryDate:      inv.DatedOn,
		Narrative:      "Invoice " + inv.Reference.String,
		CreatedBy:      authUserID,
		Amounts: map[string]ledger.Amount{
			"GROSS": {Txn: inv.TotalValueMinor, Base: inv.NativeTotalValueMinor},
			"NET":   {Txn: inv.NetValueMinor, Base: inv.NativeNetValueMinor},
			"VAT":   {Txn: inv.SalesTaxValueMinor, Base: inv.NativeSalesTaxValueMinor},
		},
	}); err != nil {
		if errors.Is(err, ledger.ErrChartNotProvisioned) {
			return nil // org has no chart of accounts — skip GL
		}
		return err
	}
	return nil
}

// =============================================================================
// MONEY ROLL-UP (lines → totals)
// =============================================================================

// lineCalc is a validated, ready-to-store line plus the computed amounts that feed
// the header totals. quantity is kept as a normalised decimal string for the NUMERIC
// column; priceMinor / rateBps are the stored integer forms.
type lineCalc struct {
	description string
	quantity    string
	priceMinor  int64
	rateBps     int32
}

// buildLines validates each request line, converts pounds→pence and percent→bps,
// computes the line net (quantity × unit price, rounded to whole pence) and line VAT
// (added on top), and returns the lines plus the header net / tax / total. An empty
// item list is allowed (a zero-value draft) and yields zero totals.
func buildLines(items []InvoiceItemRequest) (lines []lineCalc, net, tax, total int64, err error) {
	lines = make([]lineCalc, 0, len(items))
	for i, it := range items {
		n := i + 1 // 1-based for human-friendly error messages

		desc := strings.TrimSpace(it.Description)
		if desc == "" {
			return nil, 0, 0, 0, kernel.ErrValidation(fmt.Sprintf("item %d: description is required", n), nil)
		}
		priceMinor, err := money.PoundsToMinor(strings.TrimSpace(it.Price))
		if err != nil {
			return nil, 0, 0, 0, kernel.ErrValidation(fmt.Sprintf("item %d: price is not a valid amount", n), err)
		}
		rateBps, err := money.PercentToBps(it.SalesTaxRate)
		if err != nil {
			return nil, 0, 0, 0, kernel.ErrValidation(fmt.Sprintf("item %d: sales_tax_rate is not a valid percentage", n), err)
		}
		lineNet, lineTax, err := computeLineMinor(it.Quantity, priceMinor, rateBps)
		if err != nil {
			return nil, 0, 0, 0, kernel.ErrValidation(fmt.Sprintf("item %d: quantity is not a valid number", n), err)
		}

		net += lineNet
		tax += lineTax
		lines = append(lines, lineCalc{
			description: desc,
			quantity:    normaliseDecimalString(it.Quantity),
			priceMinor:  priceMinor,
			rateBps:     rateBps,
		})
	}
	return lines, net, tax, net + tax, nil
}

// computeLineMinor derives a line's net and VAT (in pence) from its stored inputs.
// SINGLE source of truth, used both when writing (buildLines) and when reading
// (itemToResponse), so a line's amounts are computed identically everywhere.
// net = round(quantity × unit price) to whole pence; VAT is added on top.
func computeLineMinor(quantity string, priceMinor int64, rateBps int32) (netMinor, vatMinor int64, err error) {
	qty, err := decimal.NewFromString(strings.TrimSpace(quantity))
	if err != nil {
		return 0, 0, err
	}
	netMinor = qty.Mul(decimal.NewFromInt(priceMinor)).Round(0).IntPart()
	vatMinor = money.AddOnVAT(netMinor, rateBps)
	return netMinor, vatMinor, nil
}

// insertLines writes the validated lines for an invoice, numbering position from 1.
func insertLines(ctx context.Context, q *invoicesdb.Queries, invoiceID, orgID uuid.UUID, lines []lineCalc) error {
	for i, ln := range lines {
		if _, err := q.CreateInvoiceItem(ctx, invoicesdb.CreateInvoiceItemParams{
			InvoiceID:       invoiceID,
			OrganisationID:  orgID,
			Position:        int32(i + 1),
			Description:     ln.description,
			Quantity:        ln.quantity,
			PriceMinor:      ln.priceMinor,
			SalesTaxRateBps: ln.rateBps,
		}); err != nil {
			return kernel.ErrInternal(err)
		}
	}
	return nil
}

// =============================================================================
// RESPONSE BUILDERS
// =============================================================================

// buildDetail fetches an invoice's line items and assembles the full detail
// response. q is either the pooled query set or the tx-scoped one (both *Queries).
func (s *Service) buildDetail(ctx context.Context, q *invoicesdb.Queries, inv invoicesdb.Invoice) (*InvoiceResponse, error) {
	items, err := q.ListInvoiceItems(ctx, invoicesdb.ListInvoiceItemsParams{
		InvoiceID:      inv.ID,
		OrganisationID: inv.OrganisationID,
	})
	if err != nil {
		return nil, kernel.ErrInternal(err)
	}
	resp := invoiceToResponse(inv)
	resp.Items = make([]InvoiceItemResponse, 0, len(items))
	for _, it := range items {
		ir, err := itemToResponse(it)
		if err != nil {
			return nil, kernel.ErrInternal(err)
		}
		resp.Items = append(resp.Items, ir)
	}
	return resp, nil
}

// buildFXSummary computes the read-only "Currency Gains/Losses" panel for a foreign
// invoice (modelled on FreeAgent's). It revalues the OUTSTANDING (due) foreign amount
// at the invoice's booking rate vs today's stored rate; the difference is the UNREALISED
// gain/loss. Realised gain on payment is deferred, so realized is "0.00" and net ==
// unrealized. Returns (nil, nil) — panel omitted — when there is no usable today rate or
// nothing to revalue (zero total), so a fresh DB without rates doesn't break the read.
// Caller guarantees the invoice is foreign (exchange_rate set) and SENT.
func (s *Service) buildFXSummary(ctx context.Context, q *invoicesdb.Queries, inv invoicesdb.Invoice) (*InvoiceFXSummary, error) {
	totalMinor := inv.TotalValueMinor
	if totalMinor == 0 {
		return nil, nil // nothing to revalue
	}

	org, err := s.authQueries.GetOrganisation(ctx, inv.OrganisationID)
	if err != nil {
		return nil, kernel.ErrInternal(err)
	}

	// Today's rate (home per 1 unit of the invoice currency), nearest-prior fallback. No
	// stored rate ⇒ omit the panel (s.rates may be nil if the fxrates module is unwired).
	if s.rates == nil {
		return nil, nil
	}
	todayRate, ok, err := s.rates.RateOnOrBefore(ctx, inv.Currency, time.Now())
	if err != nil {
		return nil, err
	}
	if !ok {
		return nil, nil
	}

	foreignExp, err := s.currencyExp(ctx, q, inv.Currency)
	if err != nil {
		return nil, err
	}
	homeExp, err := s.currencyExp(ctx, q, org.NativeCurrency)
	if err != nil {
		return nil, err
	}

	// We revalue the OUTSTANDING portion only — the paid portion's FX is realised (and
	// deferred). invoiceValue is its home value at the ORIGINAL booking rate, taken as the
	// same proportion of the stored native total (so it matches what was posted); todayValue
	// reconverts the same foreign amount at today's rate. The signed difference is unrealised.
	dueMinor := dueValueMinor(inv)
	invoiceValueMinor := money.Apportion(inv.NativeTotalValueMinor, dueMinor, totalMinor)
	todayValueMinor := money.ConvertMinor(dueMinor, foreignExp, homeExp, todayRate)
	unrealizedMinor := todayValueMinor - invoiceValueMinor

	return &InvoiceFXSummary{
		BaseCurrency: org.NativeCurrency,
		Currency:     inv.Currency,
		InvoiceDate:  inv.DatedOn.Time.Format("2006-01-02"),
		InvoiceRate:  numericToString(inv.ExchangeRate),
		InvoiceValue: money.MinorToPounds(invoiceValueMinor),
		TodayDate:    time.Now().Format("2006-01-02"),
		TodayRate:    todayRate.String(),
		TodayValue:   money.MinorToPounds(todayValueMinor),
		Unrealized:   money.MinorToPounds(unrealizedMinor),
		Realized:     "0.00", // per-payment realised gain is deferred (see BACKLOG)
		Net:          money.MinorToPounds(unrealizedMinor),
	}, nil
}

// invoiceToResponse maps a header row to the API shape (pence→pounds strings,
// stored status + derived display status). It does NOT include line items — callers
// that need the detail use buildDetail.
func invoiceToResponse(inv invoicesdb.Invoice) *InvoiceResponse {
	return &InvoiceResponse{
		ID:              inv.ID.String(),
		OrganisationID:  inv.OrganisationID.String(),
		CreatedByUserID: inv.CreatedByUserID.String(),
		ContactID:       inv.ContactID.String(),
		DatedOn:         inv.DatedOn.Time.Format("2006-01-02"),
		DueOn:           dateToStringPtr(inv.DueOn),
		Reference:       kernel.NullTextToPtr(inv.Reference),
		Currency:        inv.Currency,
		Status:          inv.Status,
		DisplayStatus:   deriveDisplayStatus(inv),
		NetValue:        money.MinorToPounds(inv.NetValueMinor),
		SalesTaxValue:   money.MinorToPounds(inv.SalesTaxValueMinor),
		TotalValue:      money.MinorToPounds(inv.TotalValueMinor),
		PaidValue:       money.MinorToPounds(inv.PaidValueMinor),
		DueValue:        money.MinorToPounds(dueValueMinor(inv)),
		CreatedAt:       inv.CreatedAt.Time.Format(time.RFC3339),
		UpdatedAt:       inv.UpdatedAt.Time.Format(time.RFC3339),
	}
}

// itemToResponse maps a stored line to the API shape, recomputing its net/VAT/total
// from the inputs (the same computeLineMinor used when writing).
func itemToResponse(it invoicesdb.InvoiceItem) (InvoiceItemResponse, error) {
	netMinor, vatMinor, err := computeLineMinor(it.Quantity, it.PriceMinor, it.SalesTaxRateBps)
	if err != nil {
		return InvoiceItemResponse{}, err
	}
	return InvoiceItemResponse{
		ID:            it.ID.String(),
		Position:      it.Position,
		Description:   it.Description,
		Quantity:      normaliseDecimalString(it.Quantity),
		Price:         money.MinorToPounds(it.PriceMinor),
		SalesTaxRate:  money.BpsToPercentString(it.SalesTaxRateBps),
		NetValue:      money.MinorToPounds(netMinor),
		SalesTaxValue: money.MinorToPounds(vatMinor),
		TotalValue:    money.MinorToPounds(netMinor + vatMinor),
	}, nil
}

// deriveDisplayStatus computes the user-facing status from the stored lifecycle +
// money + due date. The stored states pass through; once SENT the presentation
// depends on payment and the due date (see invoices_schema.sql).
func deriveDisplayStatus(inv invoicesdb.Invoice) string {
	switch inv.Status {
	case StatusDraft:
		return "Draft"
	case StatusScheduled:
		return "Scheduled"
	case StatusWrittenOff:
		return "Written off"
	case StatusRefunded:
		return "Refunded"
	case StatusSent:
		switch {
		case inv.TotalValueMinor == 0:
			return "Zero Value"
		case inv.PaidValueMinor > inv.TotalValueMinor:
			return "Overpaid"
		case inv.PaidValueMinor == inv.TotalValueMinor:
			return "Paid"
		case inv.DueOn.Valid && inv.DueOn.Time.Before(todayUTC()):
			return "Overdue"
		default:
			return "Open"
		}
	default:
		return inv.Status
	}
}

// =============================================================================
// SMALL HELPERS
// =============================================================================

// parseDate parses a required YYYY-MM-DD string into a pgtype.Date. field names the
// JSON field for the error message.
func parseDate(field, s string) (pgtype.Date, error) {
	t, err := time.Parse("2006-01-02", strings.TrimSpace(s))
	if err != nil {
		return pgtype.Date{}, kernel.ErrValidation(field+" must be a valid date in YYYY-MM-DD format", err)
	}
	return pgtype.Date{Time: t, Valid: true}, nil
}

// parseOptionalDate parses an optional YYYY-MM-DD pointer; nil/blank → SQL NULL.
func parseOptionalDate(field string, s *string) (pgtype.Date, error) {
	if s == nil || strings.TrimSpace(*s) == "" {
		return pgtype.Date{}, nil
	}
	return parseDate(field, *s)
}

// normaliseCurrency upper-cases the currency and defaults a blank to GBP.
func normaliseCurrency(c string) string {
	c = strings.ToUpper(strings.TrimSpace(c))
	if c == "" {
		return "GBP"
	}
	return c
}

// validateReference trims the (now required) invoice reference and rejects an empty
// / whitespace-only value (422). The handler's `required` binding already rejects a
// missing/empty field as a 400; this guards a whitespace-only one and the
// service-direct callers.
func validateReference(raw string) (string, error) {
	ref := strings.TrimSpace(raw)
	if ref == "" {
		return "", kernel.ErrValidation("reference is required", nil)
	}
	return ref, nil
}

// formatInvoiceNumber renders the org's invoice counter as a zero-padded reference:
// 1 → "001", 42 → "042", 1000 → "1000" (minimum width 3).
func formatInvoiceNumber(n int32) string {
	if n < 1 {
		n = 1
	}
	return fmt.Sprintf("%03d", n)
}

// raiseInvoiceCounter advances the org's invoice-counter floor to one PAST the
// just-used numeric reference, so the next suggestion stays monotonic — a number is
// never re-suggested once used, even after the invoice is deleted. It parses the
// reference as an integer ("001" → 1); a non-numeric / custom reference leaves the
// counter alone. GREATEST (in RaiseInvoiceNumber) only ever moves the floor UP, so
// this is safe to call unconditionally and under concurrency.
func raiseInvoiceCounter(ctx context.Context, tx pgx.Tx, orgID uuid.UUID, reference string) error {
	n, err := strconv.Atoi(strings.TrimSpace(reference))
	if err != nil || n < 1 {
		return nil // custom / out-of-sequence reference — don't move the counter
	}
	if err := auth.New(tx).RaiseInvoiceNumber(ctx, auth.RaiseInvoiceNumberParams{
		ID:      orgID,
		AtLeast: int32(n) + 1,
	}); err != nil {
		return kernel.ErrInternal(err)
	}
	return nil
}

// normaliseDecimalString trims trailing zeros from a numeric string for display
// ("10.0000" → "10", "2.5000" → "2.5"). Falls back to the input if it can't parse.
func normaliseDecimalString(s string) string {
	d, err := decimal.NewFromString(strings.TrimSpace(s))
	if err != nil {
		return s
	}
	return d.String()
}

// numericToString renders a stored pgtype.Numeric (e.g. the invoice's exchange_rate) as
// a clean decimal string with trailing zeros trimmed ("0.867880" → "0.86788"). An invalid
// numeric yields "" (the panel's caller only passes a .Valid rate). Goes via the driver
// Value() (a string) then shopspring/decimal so the format matches the rest of the module.
func numericToString(n pgtype.Numeric) string {
	if !n.Valid {
		return ""
	}
	v, err := n.Value()
	if err != nil {
		return ""
	}
	s, ok := v.(string)
	if !ok {
		return ""
	}
	d, err := decimal.NewFromString(s)
	if err != nil {
		return s
	}
	return d.String()
}

// dateToStringPtr renders a nullable date as a YYYY-MM-DD *string; nil when NULL.
func dateToStringPtr(d pgtype.Date) *string {
	if !d.Valid {
		return nil
	}
	s := d.Time.Format("2006-01-02")
	return &s
}

// dueValueMinor returns the outstanding amount. due_value_minor is a generated
// column (read-only, nullable in Go as pgtype.Int8); fall back to total − paid if
// the driver didn't populate it.
func dueValueMinor(inv invoicesdb.Invoice) int64 {
	if inv.DueValueMinor.Valid {
		return inv.DueValueMinor.Int64
	}
	return inv.TotalValueMinor - inv.PaidValueMinor
}

// todayUTC is midnight today in UTC — the cutoff for "overdue" (an invoice due
// strictly before today is overdue; due today is not).
func todayUTC() time.Time {
	now := time.Now().UTC()
	return time.Date(now.Year(), now.Month(), now.Day(), 0, 0, 0, 0, time.UTC)
}
