package invoices

// service.go
// =============================================================================
// Service — the business logic layer for the invoices domain.
//
// An invoice is a sales document an organisation issues to one of its contacts.
// This service owns authorisation, validation, the money roll-up (lines → header
// totals), the status state machine (status.go), and the mapping between the API
// shape (decimal pound strings + percentage strings) and the database shape (pence
// integers + basis points + pgx types).
//
//   HTTP handler (handler.go)
//     ↓
//   Service (this file)
//     ↓
//   *invoicesdb.Queries (db/invoices — generated by sqlc)
//     ↓
//   PostgreSQL
//
// Money rules (see money/money.go):
//   - Amounts are stored as integer minor units (pence), BIGINT (int64), because
//     invoice totals can exceed the int32 ceiling.
//   - Line price is VAT-EXCLUSIVE; line VAT is ADDED ON TOP via money.AddOnVAT
//     (NOT money.ComputeFixedVAT, which extracts VAT from a gross — the expenses
//     direction). Line net = round(quantity × unit price) to whole pence.
//   - The header net/sales_tax/total are the sums of the lines, recomputed on every
//     save; due_value is a generated column (total − paid).
//
// Authorisation mirrors contacts: any active member may create/read/list; update /
// delete / status change require the invoice's creator OR an owner/admin.
// =============================================================================

import (
	"context"
	"errors"
	"fmt"
	"strconv"
	"strings"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/shopspring/decimal"

	auth "github.com/operationfb/accounting-saas/db/auth"
	contactsdb "github.com/operationfb/accounting-saas/db/contacts"
	invoicesdb "github.com/operationfb/accounting-saas/db/invoices"
	"github.com/operationfb/accounting-saas/internal/kernel"
	"github.com/operationfb/accounting-saas/money"
)

// Service holds the connection pool, the invoices query set, the auth query set
// used to resolve the caller's membership/role, and the contacts query set used to
// validate an invoice's contact belongs to the same organisation.
type Service struct {
	pool           *pgxpool.Pool
	queries        *invoicesdb.Queries
	authQueries    auth.Querier
	contactQueries contactsdb.Querier
}

// NewService is the constructor, called once in main.go. contactQueries is a
// cross-domain dependency (like authQueries), used to validate contact_id — the
// same pattern projects uses.
func NewService(
	pool *pgxpool.Pool,
	queries *invoicesdb.Queries,
	authQueries auth.Querier,
	contactQueries contactsdb.Querier,
) *Service {
	return &Service{
		pool:           pool,
		queries:        queries,
		authQueries:    authQueries,
		contactQueries: contactQueries,
	}
}

// =============================================================================
// AUTHORIZATION / VALIDATION
// =============================================================================

// authorize confirms the caller is an ACTIVE member of the organisation and
// returns their role (used to gate who may modify an invoice).
func (s *Service) authorize(ctx context.Context, userID, orgID uuid.UUID) (auth.OrganisationRole, error) {
	return kernel.AuthorizeMember(ctx, s.authQueries, userID, orgID)
}

// validateContact confirms contactID exists in the organisation and isn't
// soft-deleted. GetContact already filters by org + deleted_at IS NULL, so one
// query does both checks. Mirrors projects.validateContact.
func (s *Service) validateContact(ctx context.Context, contactID, orgID uuid.UUID) error {
	_, err := s.contactQueries.GetContact(ctx, contactsdb.GetContactParams{
		ID:             contactID,
		OrganisationID: orgID,
	})
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return kernel.ErrValidation("contact_id does not exist or does not belong to this organisation", nil)
		}
		return kernel.ErrInternal(err)
	}
	return nil
}

// =============================================================================
// CREATE
// =============================================================================

// CreateInvoice validates the request, computes the money roll-up, and writes the
// header + lines + totals in one transaction. The owning org and creator come from
// the token. Any active member may create an invoice; it starts as DRAFT.
func (s *Service) CreateInvoice(
	ctx context.Context,
	authUserID uuid.UUID,
	authOrgID uuid.UUID,
	req CreateInvoiceRequest,
) (*InvoiceResponse, error) {
	if _, err := s.authorize(ctx, authUserID, authOrgID); err != nil {
		return nil, err
	}

	ref, err := validateReference(req.Reference)
	if err != nil {
		return nil, err
	}

	contactID, err := uuid.Parse(req.ContactID)
	if err != nil {
		return nil, kernel.ErrValidation("contact_id is not a valid UUID", err)
	}
	if err := s.validateContact(ctx, contactID, authOrgID); err != nil {
		return nil, err
	}

	datedOn, err := parseDate("dated_on", req.DatedOn)
	if err != nil {
		return nil, err
	}
	dueOn, err := parseOptionalDate("due_on", req.DueOn)
	if err != nil {
		return nil, err
	}

	lines, net, tax, total, err := buildLines(req.Items)
	if err != nil {
		return nil, err
	}

	var detail *InvoiceResponse
	err = kernel.WithTx(ctx, s.pool, func(tx pgx.Tx) error {
		qtx := s.queries.WithTx(tx)

		inv, err := qtx.CreateInvoice(ctx, invoicesdb.CreateInvoiceParams{
			OrganisationID:  authOrgID,
			CreatedByUserID: authUserID,
			ContactID:       contactID,
			DatedOn:         datedOn,
			DueOn:           dueOn,
			Reference:       pgtype.Text{String: ref, Valid: true},
			Currency:        normaliseCurrency(req.Currency),
		})
		if err != nil {
			if kernel.IsUniqueViolation(err) {
				return kernel.ErrConflict("an invoice with reference " + ref + " already exists")
			}
			return kernel.ErrInternal(err)
		}

		// Raise the org's invoice-counter floor past this number (when the reference
		// is numeric) so the next suggestion always advances and never reuses it.
		if err := raiseInvoiceCounter(ctx, tx, authOrgID, ref); err != nil {
			return err
		}

		if err := insertLines(ctx, qtx, inv.ID, authOrgID, lines); err != nil {
			return err
		}

		updated, err := qtx.UpdateInvoiceTotals(ctx, invoicesdb.UpdateInvoiceTotalsParams{
			ID:                 inv.ID,
			OrganisationID:     authOrgID,
			NetValueMinor:      net,
			SalesTaxValueMinor: tax,
			TotalValueMinor:    total,
		})
		if err != nil {
			return kernel.ErrInternal(err)
		}

		detail, err = s.buildDetail(ctx, qtx, updated)
		return err
	})
	if err != nil {
		return nil, err
	}
	return detail, nil
}

// =============================================================================
// GET / LIST
// =============================================================================

// GetInvoice fetches one invoice (header + line items), org-scoped. Any active
// member may read.
func (s *Service) GetInvoice(
	ctx context.Context,
	authUserID uuid.UUID,
	authOrgID uuid.UUID,
	id string,
) (*InvoiceResponse, error) {
	invID, err := uuid.Parse(id)
	if err != nil {
		return nil, kernel.ErrValidation("id is not a valid UUID", err)
	}
	if _, err := s.authorize(ctx, authUserID, authOrgID); err != nil {
		return nil, err
	}

	inv, err := s.queries.GetInvoice(ctx, invoicesdb.GetInvoiceParams{ID: invID, OrganisationID: authOrgID})
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, kernel.ErrNotFound("invoice", id)
		}
		return nil, kernel.ErrInternal(err)
	}
	return s.buildDetail(ctx, s.queries, inv)
}

// ListInvoices returns the org's invoices, newest first, WITHOUT line items (the
// list is a lighter summary; fetch one for its lines). Any active member may list.
func (s *Service) ListInvoices(
	ctx context.Context,
	authUserID uuid.UUID,
	authOrgID uuid.UUID,
) ([]*InvoiceResponse, error) {
	if _, err := s.authorize(ctx, authUserID, authOrgID); err != nil {
		return nil, err
	}

	rows, err := s.queries.ListInvoices(ctx, authOrgID)
	if err != nil {
		return nil, kernel.ErrInternal(err)
	}
	out := make([]*InvoiceResponse, 0, len(rows))
	for _, inv := range rows {
		out = append(out, invoiceToResponse(inv))
	}
	return out, nil
}

// =============================================================================
// NEXT REFERENCE (invoice auto-numbering)
// =============================================================================

// NextInvoiceReference returns the suggested reference for a NEW invoice — the
// org's next sequential invoice number, zero-padded (1 → "001"). The create form
// pre-fills it; the user may overwrite it. Any active member may read it.
func (s *Service) NextInvoiceReference(ctx context.Context, authUserID, authOrgID uuid.UUID) (string, error) {
	if _, err := s.authorize(ctx, authUserID, authOrgID); err != nil {
		return "", err
	}
	// The suggestion is the greater of (a) the stored counter floor and (b) one more
	// than the highest numeric reference already in use — so it always advances and
	// never re-suggests a taken number, even if the stored counter has drifted below
	// the references actually in use.
	floor, err := s.authQueries.GetNextInvoiceNumber(ctx, authOrgID)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return "", kernel.ErrNotFound("organisation", authOrgID.String())
		}
		return "", kernel.ErrInternal(err)
	}
	maxRef, err := s.queries.MaxNumericInvoiceReference(ctx, authOrgID)
	if err != nil {
		return "", kernel.ErrInternal(err)
	}
	next := floor
	if maxRef+1 > next {
		next = maxRef + 1
	}
	return formatInvoiceNumber(next), nil
}

// =============================================================================
// UPDATE
// =============================================================================

// UpdateInvoice fully replaces an invoice's editable fields and REBUILDS its lines
// (delete-all + re-insert) inside one transaction, then recomputes the totals. The
// load + ownership + DRAFT-only guards run inside the same transaction to close the
// check-then-write race. Allowed to the creator or an owner/admin; only a DRAFT may
// be edited (else 409).
func (s *Service) UpdateInvoice(
	ctx context.Context,
	authUserID uuid.UUID,
	authOrgID uuid.UUID,
	id string,
	req UpdateInvoiceRequest,
) (*InvoiceResponse, error) {
	invID, err := uuid.Parse(id)
	if err != nil {
		return nil, kernel.ErrValidation("id is not a valid UUID", err)
	}
	role, err := s.authorize(ctx, authUserID, authOrgID)
	if err != nil {
		return nil, err
	}

	// Validate the request up-front (these are 400/422s independent of DB state).
	ref, err := validateReference(req.Reference)
	if err != nil {
		return nil, err
	}
	contactID, err := uuid.Parse(req.ContactID)
	if err != nil {
		return nil, kernel.ErrValidation("contact_id is not a valid UUID", err)
	}
	if err := s.validateContact(ctx, contactID, authOrgID); err != nil {
		return nil, err
	}
	datedOn, err := parseDate("dated_on", req.DatedOn)
	if err != nil {
		return nil, err
	}
	dueOn, err := parseOptionalDate("due_on", req.DueOn)
	if err != nil {
		return nil, err
	}
	lines, net, tax, total, err := buildLines(req.Items)
	if err != nil {
		return nil, err
	}

	var detail *InvoiceResponse
	err = kernel.WithTx(ctx, s.pool, func(tx pgx.Tx) error {
		qtx := s.queries.WithTx(tx)

		existing, err := qtx.GetInvoice(ctx, invoicesdb.GetInvoiceParams{ID: invID, OrganisationID: authOrgID})
		if err != nil {
			if errors.Is(err, pgx.ErrNoRows) {
				return kernel.ErrNotFound("invoice", id)
			}
			return kernel.ErrInternal(err)
		}
		if existing.CreatedByUserID != authUserID && !kernel.IsOrgAdmin(role) {
			return kernel.ErrForbidden("you do not have access to this invoice")
		}
		if existing.Status != StatusDraft {
			return kernel.ErrConflict("only draft invoices can be edited")
		}

		if _, err := qtx.UpdateInvoice(ctx, invoicesdb.UpdateInvoiceParams{
			ID:             invID,
			OrganisationID: authOrgID,
			ContactID:      contactID,
			DatedOn:        datedOn,
			DueOn:          dueOn,
			Reference:      pgtype.Text{String: ref, Valid: true},
			Currency:       normaliseCurrency(req.Currency),
		}); err != nil {
			if kernel.IsUniqueViolation(err) {
				return kernel.ErrConflict("an invoice with reference " + ref + " already exists")
			}
			return kernel.ErrInternal(err)
		}

		// Replace the lines: delete all, re-insert the submitted set.
		if err := qtx.DeleteInvoiceItemsForInvoice(ctx, invoicesdb.DeleteInvoiceItemsForInvoiceParams{
			InvoiceID:      invID,
			OrganisationID: authOrgID,
		}); err != nil {
			return kernel.ErrInternal(err)
		}
		if err := insertLines(ctx, qtx, invID, authOrgID, lines); err != nil {
			return err
		}

		updated, err := qtx.UpdateInvoiceTotals(ctx, invoicesdb.UpdateInvoiceTotalsParams{
			ID:                 invID,
			OrganisationID:     authOrgID,
			NetValueMinor:      net,
			SalesTaxValueMinor: tax,
			TotalValueMinor:    total,
		})
		if err != nil {
			return kernel.ErrInternal(err)
		}

		detail, err = s.buildDetail(ctx, qtx, updated)
		return err
	})
	if err != nil {
		return nil, err
	}
	return detail, nil
}

// =============================================================================
// DELETE
// =============================================================================

// DeleteInvoice soft-deletes an invoice (sets deleted_at). Allowed to the creator
// or an owner/admin; only a DRAFT may be deleted (else 409). Load + guards + write
// run in one transaction.
func (s *Service) DeleteInvoice(
	ctx context.Context,
	authUserID uuid.UUID,
	authOrgID uuid.UUID,
	id string,
) error {
	invID, err := uuid.Parse(id)
	if err != nil {
		return kernel.ErrValidation("id is not a valid UUID", err)
	}
	role, err := s.authorize(ctx, authUserID, authOrgID)
	if err != nil {
		return err
	}

	return kernel.WithTx(ctx, s.pool, func(tx pgx.Tx) error {
		qtx := s.queries.WithTx(tx)

		existing, err := qtx.GetInvoice(ctx, invoicesdb.GetInvoiceParams{ID: invID, OrganisationID: authOrgID})
		if err != nil {
			if errors.Is(err, pgx.ErrNoRows) {
				return kernel.ErrNotFound("invoice", id)
			}
			return kernel.ErrInternal(err)
		}
		if existing.CreatedByUserID != authUserID && !kernel.IsOrgAdmin(role) {
			return kernel.ErrForbidden("you do not have access to this invoice")
		}
		if existing.Status != StatusDraft {
			return kernel.ErrConflict("only draft invoices can be deleted")
		}

		if err := qtx.SoftDeleteInvoice(ctx, invoicesdb.SoftDeleteInvoiceParams{ID: invID, OrganisationID: authOrgID}); err != nil {
			return kernel.ErrInternal(err)
		}
		return nil
	})
}

// =============================================================================
// STATUS
// =============================================================================

// ChangeStatus drives the stored lifecycle via an action discriminator (see
// status.go). Allowed to the creator or an owner/admin. An action that is illegal
// from the current status is a 409. Load + guard + write run in one transaction.
func (s *Service) ChangeStatus(
	ctx context.Context,
	authUserID uuid.UUID,
	authOrgID uuid.UUID,
	id string,
	action string,
) (*InvoiceResponse, error) {
	invID, err := uuid.Parse(id)
	if err != nil {
		return nil, kernel.ErrValidation("id is not a valid UUID", err)
	}
	role, err := s.authorize(ctx, authUserID, authOrgID)
	if err != nil {
		return nil, err
	}

	var detail *InvoiceResponse
	err = kernel.WithTx(ctx, s.pool, func(tx pgx.Tx) error {
		qtx := s.queries.WithTx(tx)

		existing, err := qtx.GetInvoice(ctx, invoicesdb.GetInvoiceParams{ID: invID, OrganisationID: authOrgID})
		if err != nil {
			if errors.Is(err, pgx.ErrNoRows) {
				return kernel.ErrNotFound("invoice", id)
			}
			return kernel.ErrInternal(err)
		}
		if existing.CreatedByUserID != authUserID && !kernel.IsOrgAdmin(role) {
			return kernel.ErrForbidden("you do not have access to this invoice")
		}

		target, ok := resolveTransition(action, existing.Status)
		if !ok {
			return kernel.ErrConflict(fmt.Sprintf("cannot %q an invoice in status %s", action, existing.Status))
		}

		updated, err := qtx.UpdateInvoiceStatus(ctx, invoicesdb.UpdateInvoiceStatusParams{
			ID:             invID,
			OrganisationID: authOrgID,
			Status:         target,
		})
		if err != nil {
			return kernel.ErrInternal(err)
		}

		detail, err = s.buildDetail(ctx, qtx, updated)
		return err
	})
	if err != nil {
		return nil, err
	}
	return detail, nil
}

// =============================================================================
// MONEY ROLL-UP (lines → totals)
// =============================================================================

// lineCalc is a validated, ready-to-store line plus the computed amounts that feed
// the header totals. quantity is kept as a normalised decimal string for the NUMERIC
// column; priceMinor / rateBps are the stored integer forms.
type lineCalc struct {
	description string
	quantity    string
	priceMinor  int64
	rateBps     int32
}

// buildLines validates each request line, converts pounds→pence and percent→bps,
// computes the line net (quantity × unit price, rounded to whole pence) and line VAT
// (added on top), and returns the lines plus the header net / tax / total. An empty
// item list is allowed (a zero-value draft) and yields zero totals.
func buildLines(items []InvoiceItemRequest) (lines []lineCalc, net, tax, total int64, err error) {
	lines = make([]lineCalc, 0, len(items))
	for i, it := range items {
		n := i + 1 // 1-based for human-friendly error messages

		desc := strings.TrimSpace(it.Description)
		if desc == "" {
			return nil, 0, 0, 0, kernel.ErrValidation(fmt.Sprintf("item %d: description is required", n), nil)
		}
		priceMinor, err := money.PoundsToMinor(strings.TrimSpace(it.Price))
		if err != nil {
			return nil, 0, 0, 0, kernel.ErrValidation(fmt.Sprintf("item %d: price is not a valid amount", n), err)
		}
		rateBps, err := money.PercentToBps(it.SalesTaxRate)
		if err != nil {
			return nil, 0, 0, 0, kernel.ErrValidation(fmt.Sprintf("item %d: sales_tax_rate is not a valid percentage", n), err)
		}
		lineNet, lineTax, err := computeLineMinor(it.Quantity, priceMinor, rateBps)
		if err != nil {
			return nil, 0, 0, 0, kernel.ErrValidation(fmt.Sprintf("item %d: quantity is not a valid number", n), err)
		}

		net += lineNet
		tax += lineTax
		lines = append(lines, lineCalc{
			description: desc,
			quantity:    normaliseDecimalString(it.Quantity),
			priceMinor:  priceMinor,
			rateBps:     rateBps,
		})
	}
	return lines, net, tax, net + tax, nil
}

// computeLineMinor derives a line's net and VAT (in pence) from its stored inputs.
// SINGLE source of truth, used both when writing (buildLines) and when reading
// (itemToResponse), so a line's amounts are computed identically everywhere.
// net = round(quantity × unit price) to whole pence; VAT is added on top.
func computeLineMinor(quantity string, priceMinor int64, rateBps int32) (netMinor, vatMinor int64, err error) {
	qty, err := decimal.NewFromString(strings.TrimSpace(quantity))
	if err != nil {
		return 0, 0, err
	}
	netMinor = qty.Mul(decimal.NewFromInt(priceMinor)).Round(0).IntPart()
	vatMinor = money.AddOnVAT(netMinor, rateBps)
	return netMinor, vatMinor, nil
}

// insertLines writes the validated lines for an invoice, numbering position from 1.
func insertLines(ctx context.Context, q *invoicesdb.Queries, invoiceID, orgID uuid.UUID, lines []lineCalc) error {
	for i, ln := range lines {
		if _, err := q.CreateInvoiceItem(ctx, invoicesdb.CreateInvoiceItemParams{
			InvoiceID:       invoiceID,
			OrganisationID:  orgID,
			Position:        int32(i + 1),
			Description:     ln.description,
			Quantity:        ln.quantity,
			PriceMinor:      ln.priceMinor,
			SalesTaxRateBps: ln.rateBps,
		}); err != nil {
			return kernel.ErrInternal(err)
		}
	}
	return nil
}

// =============================================================================
// RESPONSE BUILDERS
// =============================================================================

// buildDetail fetches an invoice's line items and assembles the full detail
// response. q is either the pooled query set or the tx-scoped one (both *Queries).
func (s *Service) buildDetail(ctx context.Context, q *invoicesdb.Queries, inv invoicesdb.Invoice) (*InvoiceResponse, error) {
	items, err := q.ListInvoiceItems(ctx, invoicesdb.ListInvoiceItemsParams{
		InvoiceID:      inv.ID,
		OrganisationID: inv.OrganisationID,
	})
	if err != nil {
		return nil, kernel.ErrInternal(err)
	}
	resp := invoiceToResponse(inv)
	resp.Items = make([]InvoiceItemResponse, 0, len(items))
	for _, it := range items {
		ir, err := itemToResponse(it)
		if err != nil {
			return nil, kernel.ErrInternal(err)
		}
		resp.Items = append(resp.Items, ir)
	}
	return resp, nil
}

// invoiceToResponse maps a header row to the API shape (pence→pounds strings,
// stored status + derived display status). It does NOT include line items — callers
// that need the detail use buildDetail.
func invoiceToResponse(inv invoicesdb.Invoice) *InvoiceResponse {
	return &InvoiceResponse{
		ID:              inv.ID.String(),
		OrganisationID:  inv.OrganisationID.String(),
		CreatedByUserID: inv.CreatedByUserID.String(),
		ContactID:       inv.ContactID.String(),
		DatedOn:         inv.DatedOn.Time.Format("2006-01-02"),
		DueOn:           dateToStringPtr(inv.DueOn),
		Reference:       kernel.NullTextToPtr(inv.Reference),
		Currency:        inv.Currency,
		Status:          inv.Status,
		DisplayStatus:   deriveDisplayStatus(inv),
		NetValue:        money.MinorToPounds(inv.NetValueMinor),
		SalesTaxValue:   money.MinorToPounds(inv.SalesTaxValueMinor),
		TotalValue:      money.MinorToPounds(inv.TotalValueMinor),
		PaidValue:       money.MinorToPounds(inv.PaidValueMinor),
		DueValue:        money.MinorToPounds(dueValueMinor(inv)),
		CreatedAt:       inv.CreatedAt.Time.Format(time.RFC3339),
		UpdatedAt:       inv.UpdatedAt.Time.Format(time.RFC3339),
	}
}

// itemToResponse maps a stored line to the API shape, recomputing its net/VAT/total
// from the inputs (the same computeLineMinor used when writing).
func itemToResponse(it invoicesdb.InvoiceItem) (InvoiceItemResponse, error) {
	netMinor, vatMinor, err := computeLineMinor(it.Quantity, it.PriceMinor, it.SalesTaxRateBps)
	if err != nil {
		return InvoiceItemResponse{}, err
	}
	return InvoiceItemResponse{
		ID:            it.ID.String(),
		Position:      it.Position,
		Description:   it.Description,
		Quantity:      normaliseDecimalString(it.Quantity),
		Price:         money.MinorToPounds(it.PriceMinor),
		SalesTaxRate:  money.BpsToPercentString(it.SalesTaxRateBps),
		NetValue:      money.MinorToPounds(netMinor),
		SalesTaxValue: money.MinorToPounds(vatMinor),
		TotalValue:    money.MinorToPounds(netMinor + vatMinor),
	}, nil
}

// deriveDisplayStatus computes the user-facing status from the stored lifecycle +
// money + due date. The stored states pass through; once SENT the presentation
// depends on payment and the due date (see invoices_schema.sql).
func deriveDisplayStatus(inv invoicesdb.Invoice) string {
	switch inv.Status {
	case StatusDraft:
		return "Draft"
	case StatusScheduled:
		return "Scheduled"
	case StatusWrittenOff:
		return "Written off"
	case StatusRefunded:
		return "Refunded"
	case StatusSent:
		switch {
		case inv.TotalValueMinor == 0:
			return "Zero Value"
		case inv.PaidValueMinor > inv.TotalValueMinor:
			return "Overpaid"
		case inv.PaidValueMinor == inv.TotalValueMinor:
			return "Paid"
		case inv.DueOn.Valid && inv.DueOn.Time.Before(todayUTC()):
			return "Overdue"
		default:
			return "Open"
		}
	default:
		return inv.Status
	}
}

// =============================================================================
// SMALL HELPERS
// =============================================================================

// parseDate parses a required YYYY-MM-DD string into a pgtype.Date. field names the
// JSON field for the error message.
func parseDate(field, s string) (pgtype.Date, error) {
	t, err := time.Parse("2006-01-02", strings.TrimSpace(s))
	if err != nil {
		return pgtype.Date{}, kernel.ErrValidation(field+" must be a valid date in YYYY-MM-DD format", err)
	}
	return pgtype.Date{Time: t, Valid: true}, nil
}

// parseOptionalDate parses an optional YYYY-MM-DD pointer; nil/blank → SQL NULL.
func parseOptionalDate(field string, s *string) (pgtype.Date, error) {
	if s == nil || strings.TrimSpace(*s) == "" {
		return pgtype.Date{}, nil
	}
	return parseDate(field, *s)
}

// normaliseCurrency upper-cases the currency and defaults a blank to GBP.
func normaliseCurrency(c string) string {
	c = strings.ToUpper(strings.TrimSpace(c))
	if c == "" {
		return "GBP"
	}
	return c
}

// validateReference trims the (now required) invoice reference and rejects an empty
// / whitespace-only value (422). The handler's `required` binding already rejects a
// missing/empty field as a 400; this guards a whitespace-only one and the
// service-direct callers.
func validateReference(raw string) (string, error) {
	ref := strings.TrimSpace(raw)
	if ref == "" {
		return "", kernel.ErrValidation("reference is required", nil)
	}
	return ref, nil
}

// formatInvoiceNumber renders the org's invoice counter as a zero-padded reference:
// 1 → "001", 42 → "042", 1000 → "1000" (minimum width 3).
func formatInvoiceNumber(n int32) string {
	if n < 1 {
		n = 1
	}
	return fmt.Sprintf("%03d", n)
}

// raiseInvoiceCounter advances the org's invoice-counter floor to one PAST the
// just-used numeric reference, so the next suggestion stays monotonic — a number is
// never re-suggested once used, even after the invoice is deleted. It parses the
// reference as an integer ("001" → 1); a non-numeric / custom reference leaves the
// counter alone. GREATEST (in RaiseInvoiceNumber) only ever moves the floor UP, so
// this is safe to call unconditionally and under concurrency.
func raiseInvoiceCounter(ctx context.Context, tx pgx.Tx, orgID uuid.UUID, reference string) error {
	n, err := strconv.Atoi(strings.TrimSpace(reference))
	if err != nil || n < 1 {
		return nil // custom / out-of-sequence reference — don't move the counter
	}
	if err := auth.New(tx).RaiseInvoiceNumber(ctx, auth.RaiseInvoiceNumberParams{
		ID:      orgID,
		AtLeast: int32(n) + 1,
	}); err != nil {
		return kernel.ErrInternal(err)
	}
	return nil
}

// normaliseDecimalString trims trailing zeros from a numeric string for display
// ("10.0000" → "10", "2.5000" → "2.5"). Falls back to the input if it can't parse.
func normaliseDecimalString(s string) string {
	d, err := decimal.NewFromString(strings.TrimSpace(s))
	if err != nil {
		return s
	}
	return d.String()
}

// dateToStringPtr renders a nullable date as a YYYY-MM-DD *string; nil when NULL.
func dateToStringPtr(d pgtype.Date) *string {
	if !d.Valid {
		return nil
	}
	s := d.Time.Format("2006-01-02")
	return &s
}

// dueValueMinor returns the outstanding amount. due_value_minor is a generated
// column (read-only, nullable in Go as pgtype.Int8); fall back to total − paid if
// the driver didn't populate it.
func dueValueMinor(inv invoicesdb.Invoice) int64 {
	if inv.DueValueMinor.Valid {
		return inv.DueValueMinor.Int64
	}
	return inv.TotalValueMinor - inv.PaidValueMinor
}

// todayUTC is midnight today in UTC — the cutoff for "overdue" (an invoice due
// strictly before today is overdue; due today is not).
func todayUTC() time.Time {
	now := time.Now().UTC()
	return time.Date(now.Year(), now.Month(), now.Day(), 0, 0, 0, 0, time.UTC)
}
