package expenses

// expense_service.go
// =============================================================================
// Service — the business logic layer for expensesdb.
//
// The three layers of this application and what each owns:
//
//   HTTP handler (server.go)
//     ↓  request parsing, response formatting
//   Service (this file)
//     ↓  business rules, validation, transactions, unit conversion
//   *expensesdb.Queries (db/expenses/query.sql.go — generated by sqlc)
//     ↓  SQL execution only, no business logic
//   PostgreSQL
//
// The service layer is the most important one to understand. It is the place
// where your accounting rules live. The handler and the database layer are
// relatively mechanical; this is where judgment is applied.
// =============================================================================

import (
	"context"
	"errors"
	"fmt"
	"strings"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/shopspring/decimal"

	auth "github.com/operationfb/accounting-saas/db/auth"
	categoriesdb "github.com/operationfb/accounting-saas/db/categories"
	expensesdb "github.com/operationfb/accounting-saas/db/expenses"
	vatdb "github.com/operationfb/accounting-saas/db/vat"
	kernel "github.com/operationfb/accounting-saas/internal/kernel"
	"github.com/operationfb/accounting-saas/money"
)

// Service holds a reference to both the connection pool and the
// sqlc-generated Queries struct.
//
// Why do we need BOTH?
//
//   - *expensesdb.Queries wraps the pool for normal single-statement queries.
//     When you call q.GetExpense(ctx, id, orgID), it borrows one connection
//     from the pool, runs the query, and returns it.
//
//   - *pgxpool.Pool is needed when we want a TRANSACTION. A transaction must
//     pin all its statements to the SAME connection. We begin a transaction
//     on the pool (pool.Begin), which gives us a pgx.Tx. We then call
//     expensesdb.New(tx) to get a *Queries that runs inside that transaction.
//     See the withTransaction helper below for the full picture.
type Service struct {
	pool        *pgxpool.Pool
	queries     *expensesdb.Queries
	authQueries auth.Querier

	// categoryQueries reads the shared Chart of Accounts (categories) — the expense
	// category picker (ListSpendingCategories) and the write-time validateCategory
	// guard. Expenses were unified onto this CoA (2026-06-30); the old per-module
	// expense_categories table is gone. Same seam bills uses.
	categoryQueries categoriesdb.Querier

	// vatQueries is the read-only VAT lookup behind the filed-period lock: approving
	// an expense ADDS its input VAT to that period's return, so an expense dated in an
	// already-filed period can no longer be approved (assertNotFiled). Optional/nil-safe.
	vatQueries *vatdb.Queries

	// rates is the cross-domain FX-rate read seam (internal/fxrates): when a foreign
	// expense arrives WITHOUT an explicit exchange_rate, nativeAmounts auto-fills it
	// from the stored daily rate for the expense date. Nil-guarded — with no rate
	// service wired, a foreign expense without an explicit rate is a 422 (same as
	// invoices). A native-currency expense never touches it.
	rates RateLookup

	// publisher emits domain events (currently "expense.approved", which drives the
	// external FreeAgent push). Optional: nil = publishing disabled. It is set in
	// main.go AFTER construction (the publisher is wired later), so it stays out of
	// NewService — tests leave it nil.
	publisher EventPublisher
}

// RateLookup is the read seam over the exchange-rate service. Given a currency and a
// date it returns the rate (HOME units per 1 unit of currency) effective on or before
// that date; the bool is false when no rate is stored. fxrates.Service satisfies this.
// (Copied from the invoices domain, which uses the identical seam.)
type RateLookup interface {
	RateOnOrBefore(ctx context.Context, currency string, on time.Time) (decimal.Decimal, bool, error)
}

// NewService is the constructor. Called once in main.go.
// authQueries is the auth module's query interface — the service uses it to
// resolve the caller's organisation membership/role for authorisation.
// categoryQueries reads the shared Chart of Accounts (the expense category picker
// + the spending-account write guard).
// vatQueries powers the filed-period lock; pass nil to disable it (the lock is then off).
// rates auto-fills a foreign expense's exchange_rate from the stored daily rate; pass
// nil to disable auto-fill (a foreign expense then requires an explicit exchange_rate).
func NewService(pool *pgxpool.Pool, queries *expensesdb.Queries, authQueries auth.Querier, categoryQueries categoriesdb.Querier, vatQueries *vatdb.Queries, rates RateLookup) *Service {
	return &Service{
		pool:            pool,
		queries:         queries,
		authQueries:     authQueries,
		categoryQueries: categoryQueries,
		vatQueries:      vatQueries,
		rates:           rates,
	}
}

// assertNotFiled refuses the operation (409 conflict) when the given date falls
// inside a FILED VAT period — approving an expense dated in a submitted return would
// change that return's input VAT after the fact. Nil-safe: with no vat querier wired
// (or an invalid date), the lock is simply inactive. Mirrors the bills/banking guard.
func (s *Service) assertNotFiled(ctx context.Context, orgID uuid.UUID, dated pgtype.Date) error {
	if s.vatQueries == nil || !dated.Valid {
		return nil
	}
	locked, err := s.vatQueries.IsDateInFiledPeriod(ctx, vatdb.IsDateInFiledPeriodParams{OrganisationID: orgID, DatedOn: dated})
	if err != nil {
		return kernel.ErrInternal(err)
	}
	if locked {
		return kernel.ErrConflict("this expense is dated in a VAT period that has been filed, so it can no longer be approved")
	}
	return nil
}

// SetPublisher wires the domain-event publisher AFTER construction. main builds
// the Pub/Sub publisher conditionally (only when a topic is configured) and tests
// inject a fake; nil leaves publishing disabled. This replaces main.go's old
// direct field assignment now that the publisher field is package-private.
func (s *Service) SetPublisher(p EventPublisher) { s.publisher = p }

// =============================================================================
// AUTHORIZATION
// =============================================================================

// authorize confirms the caller is an ACTIVE member of the organisation and
// returns their role. Every expense operation runs this first so that a user
// who isn't an active member of the org is refused (403), and the role can
// drive what they're allowed to see (owner/admin read all).
//
// GetMembership does not filter by status, so we check status == "active" here.
func (s *Service) authorize(ctx context.Context, userID, orgID uuid.UUID) (auth.OrganisationRole, error) {
	return kernel.AuthorizeMember(ctx, s.authQueries, userID, orgID)
}

// validateCategory confirms category_id is a SPENDING account in the caller's org —
// the same filter ListSpendingCategories applies to the picker, enforced here at
// write time so an expense can never post to an income / balance-sheet / system
// account. Mirrors internal/bills' validateCategory (the shared CoA, one rule).
func (s *Service) validateCategory(ctx context.Context, orgID, categoryID uuid.UUID) error {
	cat, err := s.categoryQueries.GetCategory(ctx, categoriesdb.GetCategoryParams{ID: categoryID, OrganisationID: orgID})
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return kernel.ErrValidation("category_id does not exist or does not belong to this organisation", nil)
		}
		return kernel.ErrInternal(err)
	}
	if !cat.IsActive || cat.IsSystemManaged || !isSpendingAccount(cat.AccountType) {
		return kernel.ErrValidation("category_id is not a valid spending category", nil)
	}
	return nil
}

// isSpendingAccount reports whether a CoA account_type is one an expense may post
// to — the same set ListSpendingCategories filters the picker to (shared with bills).
func isSpendingAccount(accountType string) bool {
	switch accountType {
	case "COST_OF_SALES", "ADMIN_EXPENSE", "CAPITAL_ASSET":
		return true
	default:
		return false
	}
}

// =============================================================================
// TRANSACTION HELPER
// =============================================================================

// withTransaction runs a function inside a PostgreSQL transaction.
//
// Why do we need this?
//
// Creating an expense is not one database write — it's potentially three:
//  1. INSERT INTO expenses
//  2. INSERT INTO expense_mileage  (if mileage claim)
//  3. INSERT INTO expense_audit_log
//
// If write 1 succeeds but write 2 fails (e.g. a constraint violation), we
// would have a corrupt expense record in the database with no mileage row.
// A transaction guarantees atomicity: either ALL writes succeed, or NONE do.
// PostgreSQL rolls back everything if any step returns an error.
//
// How it works:
//  1. Begin a transaction → get a pgx.Tx (a connection pinned to this transaction)
//  2. Wrap the tx in a *expensesdb.Queries so sqlc methods run inside it
//  3. Call the provided function `fn` with the transaction-scoped Queries
//  4. If fn returns nil error → COMMIT (all writes become permanent)
//  5. If fn returns an error → ROLLBACK (all writes are undone)
//
// The `fn` signature takes *expensesdb.Queries so callers work with the same
// type whether inside a transaction or not.
func (s *Service) withTransaction(ctx context.Context, fn func(*expensesdb.Queries) error) error {
	// Delegates to the shared, generic kernel.WithTx; we just wrap the pgx.Tx with
	// the expenses Queries so every call site here stays unchanged.
	return kernel.WithTx(ctx, s.pool, func(tx pgx.Tx) error {
		return fn(expensesdb.New(tx))
	})
}

// =============================================================================
// VAT
// =============================================================================

// vatResult holds the resolved VAT fields, ready to drop into the Create/Update
// params struct.
type vatResult struct {
	RateID     pgtype.UUID
	RateBps    pgtype.Int4
	ValueMinor int32
}

// resolveVAT turns the request's vat_rate_id (+ optional vat_amount) into the
// stored VAT fields:
//   - no rate selected     → no VAT (NULL rate id/bps, value 0)
//   - fixed-ratio rate     → VAT EXTRACTED from the VAT-inclusive total (see
//     money.ComputeFixedVAT); any client amount is IGNORED (not an error)
//   - non-fixed-ratio rate → value = the client-supplied amount (0 if omitted)
//
// The selected rate must belong to the caller's organisation's country (the
// frontend only offers rates for that country); a mismatch is a validation error.
// Shared by CreateExpense and UpdateExpense so the rule lives in one place.
func (s *Service) resolveVAT(
	ctx context.Context,
	authOrgID uuid.UUID,
	grossMinor int32,
	vatRateID *string,
	vatAmount *string,
) (vatResult, error) {
	// No VAT rate selected → no VAT.
	if vatRateID == nil || *vatRateID == "" {
		return vatResult{}, nil
	}

	rateUUID, err := uuid.Parse(*vatRateID)
	if err != nil {
		return vatResult{}, kernel.ErrValidation("vat_rate_id is not a valid UUID", err)
	}

	rate, err := s.queries.GetVatRate(ctx, rateUUID)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return vatResult{}, kernel.ErrValidation("vat_rate_id not found", nil)
		}
		return vatResult{}, kernel.ErrInternal(err)
	}

	// The rate must be for the caller's organisation's country. The token carries
	// only the org id; the country_code lives on the organisation (auth domain).
	org, err := s.authQueries.GetOrganisation(ctx, authOrgID)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return vatResult{}, kernel.ErrNotFound("organisation", authOrgID.String())
		}
		return vatResult{}, kernel.ErrInternal(err)
	}
	if rate.CountryCode != org.CountryCode {
		return vatResult{}, kernel.ErrValidation("selected VAT rate is not valid for your organisation's country", nil)
	}

	var valueMinor int32
	if rate.IsFixedRatio {
		// Rate-locked: extract the VAT from the inclusive total; ignore any
		// client-supplied amount.
		valueMinor = money.ComputeFixedVAT(grossMinor, rate.RateBps)
	} else if vatAmount != nil {
		// Custom rate: accept the client's amount as-is (pounds → pence).
		minor, err := money.PoundsToMinor(*vatAmount)
		if err != nil {
			return vatResult{}, kernel.ErrValidation(fmt.Sprintf("vat_amount %q is not a valid decimal number", *vatAmount), err)
		}
		valueMinor = int32(minor)
	}

	return vatResult{
		RateID:     pgNullUUID(vatRateID),
		RateBps:    pgtype.Int4{Int32: rate.RateBps, Valid: true},
		ValueMinor: valueMinor,
	}, nil
}

// =============================================================================
// NATIVE-CURRENCY CONVERSION (FX — prep for the general ledger)
//
// An expense stores its money twice: in the transaction currency (gross_value_minor,
// vat_value_minor) and in the organisation's native/home currency (native_*_minor),
// plus the exchange_rate used. The GL posts in the base (native) currency, so these
// must be populated on write. This mirrors the invoices domain's nativeAmounts.
// =============================================================================

// normaliseCurrency upper-cases the currency and defaults a blank to GBP. The DB
// requires upper-cased ISO 4217 codes (currencies.code CHECK), and the same-currency
// comparison below must be case-insensitive. Mirrors invoices.normaliseCurrency.
func normaliseCurrency(c string) string {
	c = strings.ToUpper(strings.TrimSpace(c))
	if c == "" {
		return "GBP"
	}
	return c
}

// nativeAmounts converts an expense's gross + VAT (in the transaction currency `cur`)
// into the organisation's native (home) currency, and returns the exchange_rate to
// store. `cur` must already be normalised (upper-cased / defaulted).
//
//   - Same currency as the org's home currency → native == transaction, rate NULL
//     ("native_* stored unconverted, rate NULL" — the common GBP-in-a-GBP-org case).
//   - Foreign → the caller may supply an explicit rate; otherwise we AUTO-FILL it from
//     the stored daily rate for the expense date (so the user needn't hand-type it).
//     Only when neither is available is it a 422. The amounts are converted via
//     money.ConvertMinor using each currency's minor_unit, then clamped back to the
//     INTEGER (int32) column range.
//
// VAT is extracted in the transaction currency BEFORE this call (see resolveVAT /
// money.ComputeFixedVAT) and converted here — the same order invoices uses.
func (s *Service) nativeAmounts(
	ctx context.Context, orgID uuid.UUID,
	cur, rateInput string, datedOn time.Time, grossMinor, vatMinor int32,
) (rate pgtype.Numeric, nativeCurrency string, nativeGross, nativeVat int32, err error) {
	org, gerr := s.authQueries.GetOrganisation(ctx, orgID)
	if gerr != nil {
		return rate, "", 0, 0, kernel.ErrInternal(gerr)
	}
	nativeCurrency = org.NativeCurrency

	// Same currency as the org's home currency: native == transaction, no rate.
	if strings.EqualFold(cur, nativeCurrency) {
		return pgtype.Numeric{}, nativeCurrency, grossMinor, vatMinor, nil
	}

	// A foreign expense needs a rate: an explicit one, else the stored daily rate.
	rateStr := strings.TrimSpace(rateInput)
	if rateStr == "" {
		filled, ferr := s.autoFillRate(ctx, cur, datedOn)
		if ferr != nil {
			return rate, nativeCurrency, 0, 0, ferr
		}
		rateStr = filled
	}
	rateDec, derr := decimal.NewFromString(rateStr)
	if derr != nil || !rateDec.IsPositive() {
		return rate, nativeCurrency, 0, 0, kernel.ErrValidation("exchange_rate must be a positive number", derr)
	}

	fromExp, ferr := s.currencyExp(ctx, cur)
	if ferr != nil {
		return rate, nativeCurrency, 0, 0, ferr
	}
	toExp, terr := s.currencyExp(ctx, nativeCurrency)
	if terr != nil {
		return rate, nativeCurrency, 0, 0, terr
	}

	// Expense money columns are INTEGER (int32); money.ConvertMinor is int64-based, so
	// widen, convert, then clamp back (guards the ±£21.4m int32 ceiling defensively).
	nativeGross = money.ClampToInt32(money.ConvertMinor(int64(grossMinor), fromExp, toExp, rateDec))
	nativeVat = money.ClampToInt32(money.ConvertMinor(int64(vatMinor), fromExp, toExp, rateDec))
	if serr := rate.Scan(rateStr); serr != nil {
		return rate, nativeCurrency, 0, 0, kernel.ErrInternal(serr)
	}
	return rate, nativeCurrency, nativeGross, nativeVat, nil
}

// autoFillRate looks up the stored daily rate for a foreign expense when the request
// omitted an explicit exchange_rate. Returns the rate as a decimal string (for the
// NUMERIC scan path) or a 422 when no rate source is wired or none is stored for the
// currency on/before the expense date.
func (s *Service) autoFillRate(ctx context.Context, cur string, datedOn time.Time) (string, error) {
	if s.rates == nil {
		return "", kernel.ErrValidation("exchange_rate is required for an expense not in the organisation's native currency", nil)
	}
	rateDec, ok, err := s.rates.RateOnOrBefore(ctx, cur, datedOn)
	if err != nil {
		return "", err
	}
	if !ok {
		return "", kernel.ErrValidation("no exchange rate is available for "+cur+" on the expense date — please enter one", nil)
	}
	return rateDec.String(), nil
}

// currencyExp returns a currency's minor_unit (decimal places) for money.ConvertMinor.
func (s *Service) currencyExp(ctx context.Context, code string) (int, error) {
	c, err := s.queries.GetCurrency(ctx, code)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return 0, kernel.ErrValidation("unknown currency "+code, nil)
		}
		return 0, kernel.ErrInternal(err)
	}
	return int(c.MinorUnit), nil
}

// =============================================================================
// CREATEEXPENSE
// =============================================================================

// CreateExpense is the service method that handles creating a new expense.
//
// It does the following:
//  1. Validate inputs that can't be expressed as struct tags (e.g. date format)
//  2. Convert the gross value from a pounds string to integer pence
//  3. Compute VAT if a rate was given
//  4. Run both the expense INSERT and the audit log INSERT in a transaction
//  5. Return a formatted response
//
// The method signature takes the raw request from the handler and returns the
// formatted response the handler will write to JSON. The service owns the
// conversion between "what the API sees" and "what the database stores".
func (s *Service) CreateExpense(
	ctx context.Context,
	authUserID uuid.UUID,
	authOrgID uuid.UUID,
	req CreateExpenseRequest,
) (*ExpenseResponse, error) {

	// -------------------------------------------------------------------------
	// Step 1: Parse and validate inputs
	// -------------------------------------------------------------------------

	// Authorisation: the caller must be an active member of the organisation.
	// We capture their role so we can gate the "on behalf of" path below
	// (owner/admin only); authorize already refuses non-members and deactivated
	// members.
	role, err := s.authorize(ctx, authUserID, authOrgID)
	if err != nil {
		return nil, err
	}

	// The organisation comes from the authenticated token, never the request body.
	organisationUUID := authOrgID

	// Resolve the claimant (whose expense this is). Default: the caller records it
	// for themselves — claimant == caller, which is the overwhelming common case.
	// An owner/admin MAY record on behalf of another active member by passing
	// user_id; we still keep created_by_user_id = caller below (who actually typed it).
	claimantUUID := authUserID
	if req.UserID != nil && *req.UserID != "" {
		parsed, err := uuid.Parse(*req.UserID) // binding already validated shape; parse for the value
		if err != nil {
			return nil, kernel.ErrValidation("user_id is not a valid UUID", err)
		}
		if parsed != authUserID {
			// On-behalf entry. Only owners/admins may do it.
			if !kernel.IsOrgAdmin(role) {
				return nil, kernel.ErrForbidden("only organisation owners and admins can record an expense on behalf of another user")
			}
			// The claimant must be an ACTIVE member of THIS organisation. The lookup
			// is org-scoped, so a user id from another tenant simply isn't found.
			m, err := s.authQueries.GetMembership(ctx, auth.GetMembershipParams{
				OrganisationID: authOrgID,
				UserID:         parsed,
			})
			if err != nil {
				if errors.Is(err, pgx.ErrNoRows) {
					return nil, kernel.ErrValidation("user_id is not a member of this organisation", err)
				}
				return nil, kernel.ErrInternal(err)
			}
			if m.Status != "active" {
				return nil, kernel.ErrValidation("user_id is not an active member of this organisation", nil)
			}
			claimantUUID = parsed
		}
	}

	categoryUUID, err := uuid.Parse(req.CategoryID)
	if err != nil {
		return nil, kernel.ErrValidation("category_id is not a valid UUID", err)
	}
	// The category must be a spending account in this org (the FK alone can't
	// distinguish a spending account from an income/control one).
	if err := s.validateCategory(ctx, authOrgID, categoryUUID); err != nil {
		return nil, err
	}

	// Parse the date. Go's time.Parse requires an exact reference time as the
	// layout — this is Go's quirky but memorable approach: the reference is
	// Mon Jan 2 15:04:05 MST 2006. "2006-01-02" means YYYY-MM-DD.
	datedOn, err := time.Parse("2006-01-02", req.DatedOn)
	if err != nil {
		return nil, kernel.ErrValidation("dated_on must be a valid date in YYYY-MM-DD format", err)
	}

	// -------------------------------------------------------------------------
	// Step 2: Convert money from pounds (string) to pence (integer)
	//
	// Why string input → integer storage?
	//
	//   The API accepts "42.50" as a string to avoid JavaScript float precision
	//   issues (JS uses float64 for all numbers; 42.1 in JS is actually
	//   42.09999999999999716...). We parse it with shopspring/decimal which
	//   is an arbitrary-precision decimal library, then convert to pence by
	//   multiplying by 100. We store as INTEGER pence in PostgreSQL.
	//
	//   42.50 → decimal("42.50") → multiply by 100 → decimal("4250") → int32(4250)
	// -------------------------------------------------------------------------
	// Convert pounds (string) → pence via the shared money kernel (rounds
	// half-up). Stored as int32 because the column is PostgreSQL INTEGER.
	grossMinorInt64, err := money.PoundsToMinor(req.GrossValuePounds)
	if err != nil {
		return nil, kernel.ErrValidation(fmt.Sprintf("gross_value %q is not a valid decimal number", req.GrossValuePounds), err)
	}
	grossMinor := int32(grossMinorInt64)

	// Normalise the currency (upper-case; blank → GBP). Upper-casing matters: the
	// currencies.code FK/CHECK stores only upper-cased ISO codes.
	currency := normaliseCurrency(req.CurrencyCode)

	// -------------------------------------------------------------------------
	// Step 3: Resolve VAT.
	// The entered gross is the VAT-inclusive total. Fixed-ratio rates EXTRACT the
	// VAT from it (any client amount is ignored); non-fixed rates take the
	// client-supplied vat_amount. See resolveVAT.
	// -------------------------------------------------------------------------
	vat, err := s.resolveVAT(ctx, authOrgID, grossMinor, req.VATRateID, req.VATAmount)
	if err != nil {
		return nil, err
	}

	// Convert gross + VAT to the org's native (home) currency for the GL. A
	// same-currency expense passes through with a NULL rate; a foreign one resolves
	// (or auto-fills) an exchange_rate and converts. See nativeAmounts.
	exchangeRate, nativeCurrency, nativeGross, nativeVat, err := s.nativeAmounts(
		ctx, authOrgID, currency, req.ExchangeRate, datedOn, grossMinor, vat.ValueMinor)
	if err != nil {
		return nil, err
	}

	// -------------------------------------------------------------------------
	// Step 4: Build the database parameters struct
	//
	// expensesdb.CreateExpenseParams is generated by sqlc from the query in
	// query.sql. Every field here maps to a $1, $2, ... parameter in the SQL.
	// The field names and types come from the column definitions in schema.sql.
	// -------------------------------------------------------------------------
	params := expensesdb.CreateExpenseParams{
		OrganisationID:        organisationUUID,
		UserID:                claimantUUID, // the claimant (may be someone else for admin-on-behalf entry)
		CreatedByUserID:       authUserID,   // always the caller — audit of who actually recorded it
		CategoryID:            categoryUUID,
		DatedOn:               PgDateFromTime(datedOn), // helper below converts time.Time → pgx date
		Description:           req.Description,
		Currency:              currency,
		NativeCurrency:        nativeCurrency, // the org's home currency
		ExchangeRate:          exchangeRate,   // NULL when same currency; the FX rate otherwise
		GrossValueMinor:       grossMinor,
		NativeGrossValueMinor: nativeGross, // == gross when same currency; converted otherwise
		VatRateID:             vat.RateID,
		VatRateBps:            vat.RateBps,
		VatValueMinor:         vat.ValueMinor,
		NativeVatValueMinor:   nativeVat,   // == VAT when same currency; converted otherwise
		VatStatus:             "TAXABLE",   // TODO: derive EXEMPT/OUT_OF_SCOPE from the rate
		EcStatus:              "UK_NON_EC", // correct default for post-2021 UK expenses

		// Optional string fields: convert *string to pgtype.Text
		// kernel.NullText is a small helper defined at the bottom of this file.
		// It returns a pgtype.Text with Valid=false when the pointer is nil,
		// which maps to NULL in PostgreSQL.
		ReceiptReference:  kernel.NullText(req.ReceiptReference),
		SupplierName:      kernel.NullText(req.SupplierName),
		SupplierVatNumber: kernel.NullText(req.SupplierVATNo),
		InvoiceNumber:     kernel.NullText(req.InvoiceNumber),

		// Project rebilling
		ProjectID:    pgNullUUID(req.ProjectID),
		RebillType:   kernel.NullText(req.RebillType),
		RebillFactor: pgNullNumeric(req.RebillFactor),
	}

	// -------------------------------------------------------------------------
	// Step 5: Write to the database inside a transaction
	//
	// We use withTransaction so that the expense INSERT and the audit INSERT
	// are atomic. If either fails, both are rolled back.
	// -------------------------------------------------------------------------
	var created expensesdb.Expense // will hold the row returned by RETURNING *

	err = s.withTransaction(ctx, func(qtx *expensesdb.Queries) error {
		// Write 1: create the expense record
		row, err := qtx.CreateExpense(ctx, params)
		if err != nil {
			return fmt.Errorf("insert expense: %w", err)
		}
		created = row

		// Write 2: append to the audit log
		// The audit log records who did what and when. Even for a CREATE we
		// write a row so there's a complete history from birth.
		// We pass nil for old_data (nothing existed before) and the new row
		// serialised as JSON for new_data.
		// TODO: implement CreateAuditEntry query and call it here.
		// For now this is a clear marker of where it belongs.
		_ = created // used above; keeping variable in scope for audit TODO

		return nil
	})
	if err != nil {
		return nil, fmt.Errorf("create expense: %w", err)
	}

	// -------------------------------------------------------------------------
	// Step 6: Format and return the response
	// -------------------------------------------------------------------------
	return expenseToResponse(created), nil
}

// =============================================================================
// UPDATEEXPENSE
// =============================================================================

// UpdateExpense performs a full update of an existing expense's editable fields
// (PUT semantics). Authorisation mirrors GetExpenseDetail: the caller must own
// the expense, or be an owner/admin of the organisation. The expense must also
// still be editable — only DRAFT or REJECTED expenses may be changed.
//
// The fetch, the ownership/status checks, and the UPDATE all run inside one
// transaction so the row can't change status between the check and the write.
func (s *Service) UpdateExpense(
	ctx context.Context,
	authUserID uuid.UUID,
	authOrgID uuid.UUID,
	id string,
	req UpdateExpenseRequest,
) (*ExpenseResponse, error) {
	expenseUUID, err := uuid.Parse(id)
	if err != nil {
		return nil, kernel.ErrValidation("id is not a valid UUID", err)
	}

	// Confirm the caller is an active member and get their role.
	role, err := s.authorize(ctx, authUserID, authOrgID)
	if err != nil {
		return nil, err
	}

	// Parse + convert the editable fields — same conversions as CreateExpense.
	categoryUUID, err := uuid.Parse(req.CategoryID)
	if err != nil {
		return nil, kernel.ErrValidation("category_id is not a valid UUID", err)
	}
	if err := s.validateCategory(ctx, authOrgID, categoryUUID); err != nil {
		return nil, err
	}
	datedOn, err := time.Parse("2006-01-02", req.DatedOn)
	if err != nil {
		return nil, kernel.ErrValidation("dated_on must be a valid date in YYYY-MM-DD format", err)
	}
	grossMinorInt64, err := money.PoundsToMinor(req.GrossValuePounds)
	if err != nil {
		return nil, kernel.ErrValidation(fmt.Sprintf("gross_value %q is not a valid decimal number", req.GrossValuePounds), err)
	}
	grossMinor := int32(grossMinorInt64)

	currency := normaliseCurrency(req.CurrencyCode)

	// Resolve VAT (extract from the inclusive total for fixed-ratio, accept the
	// client amount for custom) — same rule as CreateExpense, via resolveVAT.
	vat, err := s.resolveVAT(ctx, authOrgID, grossMinor, req.VATRateID, req.VATAmount)
	if err != nil {
		return nil, err
	}

	// Convert to the org's native currency (same rule as CreateExpense). A currency
	// or amount change on edit re-derives native_* and the exchange_rate.
	exchangeRate, nativeCurrency, nativeGross, nativeVat, err := s.nativeAmounts(
		ctx, authOrgID, currency, req.ExchangeRate, datedOn, grossMinor, vat.ValueMinor)
	if err != nil {
		return nil, err
	}

	// Fetch + authorise + status-check + update inside one transaction so the row
	// can't change between the checks and the write (avoids a TOCTOU gap).
	var updated expensesdb.Expense
	err = s.withTransaction(ctx, func(qtx *expensesdb.Queries) error {
		existing, err := qtx.GetExpense(ctx, expensesdb.GetExpenseParams{
			ID:             expenseUUID,
			OrganisationID: authOrgID,
		})
		if err != nil {
			if errors.Is(err, pgx.ErrNoRows) {
				return kernel.ErrNotFound("expense", id)
			}
			return kernel.ErrInternal(err)
		}

		// Ownership: own expense, or owner/admin of the org (mirrors GetExpenseDetail).
		if existing.UserID != authUserID && !kernel.IsOrgAdmin(role) {
			return kernel.ErrForbidden("you do not have access to this expense")
		}

		// Editable only while DRAFT or REJECTED.
		if existing.Status != StatusDraft && existing.Status != StatusRejected {
			return kernel.ErrConflict("expense can only be edited while it is in DRAFT or REJECTED status")
		}

		updated, err = qtx.UpdateExpense(ctx, expensesdb.UpdateExpenseParams{
			ID:                    expenseUUID,
			OrganisationID:        authOrgID,
			CategoryID:            categoryUUID,
			DatedOn:               PgDateFromTime(datedOn),
			Description:           req.Description,
			Currency:              currency,
			NativeCurrency:        nativeCurrency,
			ExchangeRate:          exchangeRate,
			GrossValueMinor:       grossMinor,
			NativeGrossValueMinor: nativeGross,
			VatRateID:             vat.RateID,
			VatRateBps:            vat.RateBps,
			VatValueMinor:         vat.ValueMinor,
			NativeVatValueMinor:   nativeVat,
			VatStatus:             "TAXABLE",
			EcStatus:              "UK_NON_EC",
			ReceiptReference:      kernel.NullText(req.ReceiptReference),
			SupplierName:          kernel.NullText(req.SupplierName),
			SupplierVatNumber:     kernel.NullText(req.SupplierVATNo),
			InvoiceNumber:         kernel.NullText(req.InvoiceNumber),
			ProjectID:             pgNullUUID(req.ProjectID),
			RebillType:            kernel.NullText(req.RebillType),
			RebillFactor:          pgNullNumeric(req.RebillFactor),
		})
		if err != nil {
			return kernel.ErrInternal(err)
		}
		return nil
	})
	if err != nil {
		return nil, err
	}

	return expenseToResponse(updated), nil
}

// =============================================================================
// DELETEEXPENSE
// =============================================================================

// DeleteExpense soft-deletes an expense (sets deleted_at) so it disappears from
// every list and the review inbox while the row is retained for audit. The
// motivating case is the frontend removing an abandoned Smart Upload capture, but
// it works for any deletable expense.
//
// Authorisation mirrors UpdateExpense: the caller must own the expense, or be an
// owner/admin of the organisation. Only DRAFT or REJECTED expenses may be deleted
// — once an expense has entered the approval workflow (SUBMITTED and beyond) it is
// a financial record that must not simply vanish.
//
// The fetch, the ownership/status checks, and the soft-delete all run inside one
// transaction so the row can't change status between the check and the write.
func (s *Service) DeleteExpense(
	ctx context.Context,
	authUserID uuid.UUID,
	authOrgID uuid.UUID,
	id string,
) error {
	expenseUUID, err := uuid.Parse(id)
	if err != nil {
		return kernel.ErrValidation("id is not a valid UUID", err)
	}

	// Confirm the caller is an active member and get their role.
	role, err := s.authorize(ctx, authUserID, authOrgID)
	if err != nil {
		return err
	}

	return s.withTransaction(ctx, func(qtx *expensesdb.Queries) error {
		existing, err := qtx.GetExpense(ctx, expensesdb.GetExpenseParams{
			ID:             expenseUUID,
			OrganisationID: authOrgID,
		})
		if err != nil {
			// No live row for this id in the org — also covers an already-deleted
			// expense, since GetExpense filters deleted_at IS NULL → 404.
			if errors.Is(err, pgx.ErrNoRows) {
				return kernel.ErrNotFound("expense", id)
			}
			return kernel.ErrInternal(err)
		}

		// Ownership: own expense, or owner/admin of the org (mirrors UpdateExpense).
		if existing.UserID != authUserID && !kernel.IsOrgAdmin(role) {
			return kernel.ErrForbidden("you do not have access to this expense")
		}

		// Deletable only while DRAFT or REJECTED — never once it has entered the
		// approval workflow.
		if existing.Status != StatusDraft && existing.Status != StatusRejected {
			return kernel.ErrConflict("expense can only be deleted while it is in DRAFT or REJECTED status")
		}

		if err := qtx.SoftDeleteExpense(ctx, expensesdb.SoftDeleteExpenseParams{
			ID:             expenseUUID,
			OrganisationID: authOrgID,
		}); err != nil {
			return kernel.ErrInternal(err)
		}
		return nil
	})
}

// =============================================================================
// GETEXPENSE
// =============================================================================

// GetExpenseDetail fetches one expense with all its joined detail (category,
// VAT, FX, mileage) from the v_expenses_full view, scoped to an organisation.
// Single read — no transaction needed.
func (s *Service) GetExpenseDetail(
	ctx context.Context,
	authUserID uuid.UUID,
	authOrgID uuid.UUID,
	id string,
) (*ExpenseDetailResponse, error) {
	expenseUUID, err := uuid.Parse(id)
	if err != nil {
		return nil, kernel.ErrValidation("id is not a valid UUID", err)
	}

	// Confirm the caller is an active member and get their role.
	role, err := s.authorize(ctx, authUserID, authOrgID)
	if err != nil {
		return nil, err
	}

	// v_expenses_full joins the category (and mileage) so one read returns far
	// more than the lean list response — category name, VAT rate/status, FX, etc.
	row, err := s.queries.GetExpenseWithDetails(ctx, expensesdb.GetExpenseWithDetailsParams{
		ID:             expenseUUID,
		OrganisationID: authOrgID,
	})
	if err != nil {
		// No row for this id within the org → 404.
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, kernel.ErrNotFound("expense", id)
		}
		return nil, kernel.ErrInternal(err)
	}

	// Ownership: a user may read only their own expense, unless they are an
	// owner/admin of the organisation (who may read all).
	if row.UserID != authUserID && !kernel.IsOrgAdmin(role) {
		return nil, kernel.ErrForbidden("you do not have access to this expense")
	}

	// Map the detail row, then attach the file list. The Smart Upload frontend
	// polls the primary attachment's ocr_status here to know when OCR has filled
	// the form, so the attachments must travel with the detail response.
	resp := expenseDetailToResponse(row)
	atts, err := attachmentResponsesFor(ctx, s.queries, expenseUUID)
	if err != nil {
		return nil, err
	}
	resp.Attachments = atts
	return resp, nil
}

// =============================================================================
// LISTEXPENSES
// =============================================================================

// ListExpenses returns the expenses the caller is allowed to see:
//   - owner/admin: every expense in the organisation
//   - everyone else: only their own expenses
func (s *Service) ListExpenses(
	ctx context.Context,
	authUserID uuid.UUID,
	authOrgID uuid.UUID,
) ([]*ExpenseResponse, error) {
	role, err := s.authorize(ctx, authUserID, authOrgID)
	if err != nil {
		return nil, err
	}

	var rows []expensesdb.Expense
	if kernel.IsOrgAdmin(role) {
		rows, err = s.queries.ListExpenses(ctx, authOrgID)
	} else {
		rows, err = s.queries.ListExpensesByUser(ctx, expensesdb.ListExpensesByUserParams{
			OrganisationID: authOrgID,
			UserID:         authUserID,
		})
	}
	if err != nil {
		return nil, kernel.ErrInternal(err)
	}

	out := make([]*ExpenseResponse, 0, len(rows))
	for _, row := range rows {
		out = append(out, expenseToResponse(row))
	}
	return out, nil
}

// =============================================================================
// EXPORTEXPENSES (CSV download)
// =============================================================================

// ExpenseExportHeader is the CSV column order for the expense export. It is also
// the header of the import template shipped at web/public/expense_import_template.csv
// — keep the two in lockstep so a file exported here can be re-imported unchanged
// once the import endpoint lands.
var ExpenseExportHeader = []string{
	"claimant_email", "category", "date", "currency", "gross_value",
	"description", "supplier_name", "receipt_reference", "invoice_number",
	"sales_tax_rate", "sales_tax_value", "ec_status",
}

// ExpenseExportRow is one CSV data row, already converted to the EXTERNAL
// representation: money as 2dp pound strings, the VAT rate as a bare percent
// number, the date as DD/MM/YYYY. Field order matches ExpenseExportHeader; the
// handler turns it into a record via record().
type ExpenseExportRow struct {
	ClaimantEmail    string
	Category         string
	Date             string
	Currency         string
	GrossValue       string
	Description      string
	SupplierName     string
	ReceiptReference string
	InvoiceNumber    string
	SalesTaxRate     string
	SalesTaxValue    string
	ECStatus         string
}

// record renders the row as an ordered slice for encoding/csv. The order MUST
// match ExpenseExportHeader.
func (r ExpenseExportRow) record() []string {
	return []string{
		r.ClaimantEmail, r.Category, r.Date, r.Currency, r.GrossValue,
		r.Description, r.SupplierName, r.ReceiptReference, r.InvoiceNumber,
		r.SalesTaxRate, r.SalesTaxValue, r.ECStatus,
	}
}

// ExportExpenses returns expenses as export rows, ready for the handler to stream
// as CSV. Money minors become pound strings, VAT basis points a bare percent, and
// the date DD/MM/YYYY — the external shapes documented in the import template's
// field guide.
//
// Two modes, distinguished by ids:
//   - ids == nil → export everything the caller may see, the same rule as
//     ListExpenses: owners/admins get the whole organisation, everyone else only
//     the expenses they are the claimant on.
//   - ids != nil → export EXACTLY those expenses — the rows the list view filtered
//     for display, whose ids the SPA sends. The query is org-scoped (cross-tenant
//     ids drop out) and a non-admin still only ever sees their own rows, so a
//     crafted id list can't widen what a member exports. An empty list is a valid
//     "nothing matched the filters" and yields a header-only CSV.
func (s *Service) ExportExpenses(
	ctx context.Context,
	authUserID uuid.UUID,
	authOrgID uuid.UUID,
	ids []uuid.UUID,
) ([]ExpenseExportRow, error) {
	role, err := s.authorize(ctx, authUserID, authOrgID)
	if err != nil {
		return nil, err
	}
	admin := kernel.IsOrgAdmin(role)

	// We read the rich v_expenses_full view in every mode so we have the category
	// name, ec_status and VAT rate that the lean expenses row doesn't carry.
	var rows []expensesdb.VExpensesFull
	switch {
	case ids != nil:
		rows, err = s.queries.ListExpensesFullByIDs(ctx, expensesdb.ListExpensesFullByIDsParams{
			OrganisationID: authOrgID,
			Ids:            ids,
		})
	case admin:
		rows, err = s.queries.ListExpensesFull(ctx, authOrgID)
	default:
		rows, err = s.queries.ListExpensesFullByUser(ctx, expensesdb.ListExpensesFullByUserParams{
			OrganisationID: authOrgID,
			UserID:         authUserID,
		})
	}
	if err != nil {
		return nil, kernel.ErrInternal(err)
	}

	// The view carries only the claimant's user_id; the human-readable email
	// lives on the auth side. Resolve it once for the whole org (reusing the same
	// member-listing query MemberService uses). A claimant who is no longer a
	// member exports with a blank email rather than failing the whole download.
	emailByUser, err := s.claimantEmails(ctx, authOrgID)
	if err != nil {
		return nil, err
	}

	out := make([]ExpenseExportRow, 0, len(rows))
	for _, e := range rows {
		// member-sees-own: drop any row the caller doesn't own. The all/own queries
		// above already scope correctly, so this only bites on the id-driven path
		// (a non-admin who put someone else's id in the list).
		if !admin && e.UserID != authUserID {
			continue
		}
		out = append(out, ExpenseExportRow{
			ClaimantEmail: emailByUser[e.UserID],
			Category:      sanitizeCSVField(e.CategoryName),
			Date:          e.DatedOn.Time.Format("02/01/2006"), // DD/MM/YYYY
			Currency:      e.Currency,
			GrossValue:    money.MinorToPounds(int64(e.GrossValueMinor)),
			Description:   sanitizeCSVField(e.Description),
			// Free-text, user-controlled → guard against CSV/formula injection.
			SupplierName:     sanitizeCSVField(textOrEmpty(e.SupplierName)),
			ReceiptReference: sanitizeCSVField(textOrEmpty(e.ReceiptReference)),
			InvoiceNumber:    sanitizeCSVField(textOrEmpty(e.InvoiceNumber)),
			// Numeric columns are NEVER sanitised — a money value legitimately
			// begins with '-' (an amount owed to the employee).
			SalesTaxRate:  bpsToPlainPercent(e.VatRateBps),
			SalesTaxValue: money.MinorToPounds(int64(e.VatValueMinor)),
			ECStatus:      e.EcStatus,
		})
	}
	return out, nil
}

// claimantEmails builds a user_id → email map for the organisation's members,
// used to fill the export's claimant_email column. It reads the same member list
// MemberService does; org-scoped by the query's WHERE clause.
func (s *Service) claimantEmails(ctx context.Context, orgID uuid.UUID) (map[uuid.UUID]string, error) {
	members, err := s.authQueries.ListMembersByOrganisation(ctx, orgID)
	if err != nil {
		return nil, kernel.ErrInternal(err)
	}
	m := make(map[uuid.UUID]string, len(members))
	for _, mem := range members {
		m[mem.UserID] = mem.Email
	}
	return m, nil
}

// textOrEmpty returns the value of a nullable text column, or "" when NULL.
func textOrEmpty(t pgtype.Text) string {
	if !t.Valid {
		return ""
	}
	return t.String
}

// bpsToPlainPercent renders a nullable VAT rate in basis points as a BARE percent
// number for the CSV ("2000" → "20", "1750" → "17.5"); "" when no rate. Unlike
// bpsToPercent it omits the trailing "%" so the value round-trips as sales_tax_rate.
func bpsToPlainPercent(b pgtype.Int4) string {
	if !b.Valid {
		return ""
	}
	return decimal.NewFromInt(int64(b.Int32)).Div(decimal.NewFromInt(100)).String()
}

// sanitizeCSVField guards against CSV / formula injection: a spreadsheet may
// execute a cell whose first character is = + - @ (or a leading tab/CR) as a
// formula. Prefixing a single quote neutralises that while staying readable.
// Applied only to free-text columns — never the numeric money/rate columns,
// whose values legitimately begin with '-'.
func sanitizeCSVField(s string) string {
	if s == "" {
		return s
	}
	switch s[0] {
	case '=', '+', '-', '@', '\t', '\r':
		return "'" + s
	}
	return s
}

// =============================================================================
// LISTINBOX (Smart Upload review queue)
// =============================================================================

// ListInbox returns the captured expenses awaiting human review (needs_review=
// TRUE) — the Smart Upload inbox. Like ListExpenses, owners/admins see the whole
// organisation's inbox; everyone else sees only the captures they created. The
// query is org-scoped for tenant isolation; the per-user filter applies the same
// ownership rule used elsewhere.
func (s *Service) ListInbox(
	ctx context.Context,
	authUserID uuid.UUID,
	authOrgID uuid.UUID,
) ([]*ExpenseResponse, error) {
	role, err := s.authorize(ctx, authUserID, authOrgID)
	if err != nil {
		return nil, err
	}

	rows, err := s.queries.ListExpensesNeedingReview(ctx, authOrgID)
	if err != nil {
		return nil, kernel.ErrInternal(err)
	}

	admin := kernel.IsOrgAdmin(role)
	out := make([]*ExpenseResponse, 0, len(rows))
	for _, row := range rows {
		if admin || row.UserID == authUserID {
			out = append(out, expenseToResponse(row))
		}
	}
	return out, nil
}

// =============================================================================
// LISTEXPENSECATEGORIES
// =============================================================================

// ListExpenseCategories returns the SPENDING subset of the org's Chart of Accounts
// (the expense category picker) — the same list bills offers, via the shared
// ListSpendingCategories query. Authorisation: any ACTIVE member of the
// organisation may read it — it's shared reference data needed to file expenses —
// so we authorise on membership, not role. The org scope comes from the
// authenticated token, never the request body.
func (s *Service) ListExpenseCategories(
	ctx context.Context,
	authUserID uuid.UUID,
	authOrgID uuid.UUID,
) ([]*ExpenseCategoryResponse, error) {
	if _, err := s.authorize(ctx, authUserID, authOrgID); err != nil {
		return nil, err
	}

	rows, err := s.categoryQueries.ListSpendingCategories(ctx, authOrgID)
	if err != nil {
		return nil, kernel.ErrInternal(err)
	}

	out := make([]*ExpenseCategoryResponse, 0, len(rows))
	for _, row := range rows {
		out = append(out, expenseCategoryToResponse(row))
	}
	return out, nil
}

// =============================================================================
// LISTVATRATES
// =============================================================================

// ListVATRates returns the VAT rates valid TODAY for the caller's organisation's
// country (for the VAT rate picker).
//
// VAT rates are GLOBAL reference data keyed by country_code, not per-organisation.
// The country is resolved from the caller's organisation (via the auth token),
// never from the request — so a client cannot read another country's rates by
// passing a different code. This mirrors how ListExpenseCategories scopes to the
// caller's org.
//
// Authorisation: any ACTIVE member of the organisation may read the VAT rates —
// they are shared reference data needed to file expenses — so we authorise on
// membership, not role.
func (s *Service) ListVATRates(
	ctx context.Context,
	authUserID uuid.UUID,
	authOrgID uuid.UUID,
) ([]*VATRateResponse, error) {
	if _, err := s.authorize(ctx, authUserID, authOrgID); err != nil {
		return nil, err
	}

	// Resolve the organisation's country. The token carries only the org id; the
	// country_code lives on the organisation row (auth domain).
	org, err := s.authQueries.GetOrganisation(ctx, authOrgID)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, kernel.ErrNotFound("organisation", authOrgID.String())
		}
		return nil, kernel.ErrInternal(err)
	}

	// ListVatRatesByCountry already filters to rates whose effective window covers
	// today, so the picker only ever shows currently-applicable rates.
	rows, err := s.queries.ListVatRatesByCountry(ctx, org.CountryCode)
	if err != nil {
		return nil, kernel.ErrInternal(err)
	}

	out := make([]*VATRateResponse, 0, len(rows))
	for _, row := range rows {
		out = append(out, vatRateToResponse(row))
	}
	return out, nil
}

// =============================================================================
// RESPONSE FORMATTER
// =============================================================================

// expenseToResponse converts a database Expense row (pence integers, UUIDs,
// pgx types) into the API response shape (pound strings, plain strings).
//
// This is the inverse of the conversion we did in CreateExpense.
// It lives here in the service because the service owns the mapping between
// database representation and API representation.
func expenseToResponse(e expensesdb.Expense) *ExpenseResponse {
	// Convert integer pence back to a decimal pound string.
	// 4250 pence → decimal(4250) ÷ 100 → decimal(42.50) → "42.50"
	grossPounds := money.MinorToPounds(int64(e.GrossValueMinor))
	nativeGrossPounds := money.MinorToPounds(int64(e.NativeGrossValueMinor))
	vatPounds := money.MinorToPounds(int64(e.VatValueMinor))

	return &ExpenseResponse{
		ID:               e.ID.String(),
		OrganisationID:   e.OrganisationID.String(),
		UserID:           e.UserID.String(),
		CategoryID:       e.CategoryID.String(),
		DatedOn:          e.DatedOn.Time.Format("2006-01-02"),
		Description:      e.Description,
		Currency:         e.Currency,
		GrossValue:       grossPounds,
		NativeGrossValue: nativeGrossPounds,
		VATValue:         vatPounds,
		Status:           e.Status,
		NeedsReview:      e.NeedsReview, // TRUE while a Smart Upload capture awaits confirmation
		CreatedAt:        e.CreatedAt.Time.Format(time.RFC3339),
		UpdatedAt:        e.UpdatedAt.Time.Format(time.RFC3339),

		// Optional fields: convert pgtype.Text back to *string
		ReceiptReference:  kernel.NullTextToPtr(e.ReceiptReference),
		SupplierName:      kernel.NullTextToPtr(e.SupplierName),
		SupplierVATNumber: kernel.NullTextToPtr(e.SupplierVatNumber),
		InvoiceNumber:     kernel.NullTextToPtr(e.InvoiceNumber),
	}
}

// expenseCategoryToResponse maps a shared-CoA spending-category row to the API
// shape (UUID → string, nullable pgtype.Text → *string via kernel.NullTextToPtr).
func expenseCategoryToResponse(c categoriesdb.ListSpendingCategoriesRow) *ExpenseCategoryResponse {
	return &ExpenseCategoryResponse{
		ID:          c.ID.String(),
		NominalCode: c.NominalCode,
		Name:        c.Name,
		AccountType: c.AccountType,
		ApiGroup:    kernel.NullTextToPtr(c.ApiGroup),
		DefaultVat:  kernel.NullTextToPtr(c.DefaultVat),
	}
}

// vatRateToResponse maps a ListVatRatesByCountryRow to the API shape. The rate
// is exposed both as canonical basis points (for exact client-side computation)
// and as a human display string ("20%").
func vatRateToResponse(r expensesdb.ListVatRatesByCountryRow) *VATRateResponse {
	return &VATRateResponse{
		ID:           r.ID.String(),
		Name:         r.Name,
		RateBps:      r.RateBps,
		Rate:         money.BpsToPercent(r.RateBps),
		IsFixedRatio: r.IsFixedRatio,
	}
}

// expenseDetailToResponse maps a rich v_expenses_full row to the detail DTO.
// Money minors → pound strings; VAT basis points → a percentage; nullable
// NUMERIC / timestamp / UUID columns → optional strings (nil when NULL).
func expenseDetailToResponse(e expensesdb.VExpensesFull) *ExpenseDetailResponse {
	return &ExpenseDetailResponse{
		ID:          e.ID.String(),
		UserID:      e.UserID.String(), // claimant — lets the edit form prefill the "on behalf of" picker
		Status:      e.Status,
		DatedOn:     e.DatedOn.Time.Format("2006-01-02"),
		Description: e.Description,

		CategoryName:        e.CategoryName,
		CategoryNominalCode: e.CategoryNominalCode,
		CategoryID:          e.CategoryID.String(),

		Currency:   e.Currency,
		GrossValue: money.MinorToPounds(int64(e.GrossValueMinor)),

		VATRateID: uuidToStringPtr(e.VatRateID),
		VATRate:   bpsToPercentPtr(e.VatRateBps),
		VATStatus: e.VatStatus,
		VATValue:  money.MinorToPounds(int64(e.VatValueMinor)),

		NativeCurrency:   e.NativeCurrency,
		NativeGrossValue: money.MinorToPounds(int64(e.NativeGrossValueMinor)),
		NativeVATValue:   money.MinorToPounds(int64(e.NativeVatValueMinor)),
		ExchangeRate:     numericToStringPtr(e.ExchangeRate),

		ECStatus: e.EcStatus,

		SupplierName:      kernel.NullTextToPtr(e.SupplierName),
		SupplierVATNumber: kernel.NullTextToPtr(e.SupplierVatNumber),
		InvoiceNumber:     kernel.NullTextToPtr(e.InvoiceNumber),
		ReceiptReference:  kernel.NullTextToPtr(e.ReceiptReference),

		ProjectID:    uuidToStringPtr(e.ProjectID),
		RebillType:   kernel.NullTextToPtr(e.RebillType),
		RebillFactor: numericToStringPtr(e.RebillFactor),

		SubmittedAt:      kernel.TimestampToStringPtr(e.SubmittedAt),
		ApprovedAt:       kernel.TimestampToStringPtr(e.ApprovedAt),
		ApprovedByUserID: uuidToStringPtr(e.ApprovedByUserID), // nil when never approved
		PaidAt:           kernel.TimestampToStringPtr(e.PaidAt),
		RejectionNote:    kernel.NullTextToPtr(e.RejectionNote), // nil unless REJECTED

		// Capture / OCR. needs_review drives the review inbox; the confidence +
		// processed-at let the detail screen flag a low-confidence capture.
		NeedsReview:    e.NeedsReview,
		OCRConfidence:  numericToStringPtr(e.OcrConfidence),
		OCRProcessedAt: kernel.TimestampToStringPtr(e.OcrProcessedAt),

		CreatedAt: e.CreatedAt.Time.Format(time.RFC3339),
		UpdatedAt: e.UpdatedAt.Time.Format(time.RFC3339),
	}
}

// =============================================================================
// EXPENSE DETAIL ASSEMBLY (view + attachments)
// =============================================================================

// attachmentResponsesFor loads an expense's attachments and maps them to the API
// shape (primary first — ListExpenseAttachments orders them). The expense itself
// must already have been authorised by the caller.
func attachmentResponsesFor(ctx context.Context, q *expensesdb.Queries, expenseID uuid.UUID) ([]*AttachmentResponse, error) {
	atts, err := q.ListExpenseAttachments(ctx, expenseID)
	if err != nil {
		return nil, kernel.ErrInternal(err)
	}
	out := make([]*AttachmentResponse, 0, len(atts))
	for _, a := range atts {
		out = append(out, AttachmentToResponse(a))
	}
	return out, nil
}

// BuildExpenseDetail fetches the full detail view + attachments for an expense
// and maps them to the API shape. It performs NO authorisation — callers must
// have already authorised (or, like CaptureFromReceipt, just created the row as
// the caller). Used so the capture flow returns the exact same shape the
// frontend later polls via GET /expenses/:id.
func BuildExpenseDetail(ctx context.Context, q *expensesdb.Queries, orgID, expenseID uuid.UUID) (*ExpenseDetailResponse, error) {
	row, err := q.GetExpenseWithDetails(ctx, expensesdb.GetExpenseWithDetailsParams{
		ID:             expenseID,
		OrganisationID: orgID,
	})
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, kernel.ErrNotFound("expense", expenseID.String())
		}
		return nil, kernel.ErrInternal(err)
	}
	resp := expenseDetailToResponse(row)
	atts, err := attachmentResponsesFor(ctx, q, expenseID)
	if err != nil {
		return nil, err
	}
	resp.Attachments = atts
	return resp, nil
}

// bpsToPercentPtr turns a nullable VAT rate in basis points into a percentage
// string (2000 → "20%", 1750 → "17.5%"); nil when no rate is set. The non-null
// formatting is delegated to the shared money kernel.
func bpsToPercentPtr(b pgtype.Int4) *string {
	if !b.Valid {
		return nil
	}
	s := money.BpsToPercent(b.Int32)
	return &s
}

// numericToStringPtr renders a nullable NUMERIC (exchange_rate, rebill_factor)
// as a display string; nil when NULL.
func numericToStringPtr(n pgtype.Numeric) *string {
	if !n.Valid {
		return nil
	}
	v, err := n.Value()
	if err != nil {
		return nil
	}
	if s, ok := v.(string); ok {
		return &s
	}
	s := fmt.Sprintf("%v", v)
	return &s
}

// uuidToStringPtr renders a nullable UUID as a string; nil when NULL.
func uuidToStringPtr(u pgtype.UUID) *string {
	if !u.Valid {
		return nil
	}
	id, err := uuid.FromBytes(u.Bytes[:])
	if err != nil {
		return nil
	}
	s := id.String()
	return &s
}

// =============================================================================
// PGX TYPE HELPERS
//
// pgx uses its own types for nullable values instead of Go's standard
// sql.NullString etc. These tiny helpers convert between plain Go types
// and pgx types so the service code reads cleanly without pgtype.* noise
// everywhere.
//
// pgtype.Text has two fields:
//   String string  — the actual value
//   Valid  bool    — true if the value is non-NULL
//
// When Valid is false, pgx sends NULL to PostgreSQL regardless of String.
// =============================================================================

// NOTE: kernel.NullText / kernel.NullTextToPtr / kernel.NullInt32 moved to internal/kernel
// (kernel.NullText / NullTextToPtr / NullInt32) — they are widely shared. They
// remain callable here under the same names via the aliases in aliases.go. The
// UUID/Numeric/Date helpers below are expense-local for now and stay put.

// pgNullUUID converts a *string UUID to pgtype.UUID.
// If the string is nil or fails to parse, returns an invalid (NULL) UUID.
func pgNullUUID(s *string) pgtype.UUID {
	if s == nil {
		return pgtype.UUID{Valid: false}
	}
	id, err := uuid.Parse(*s)
	if err != nil {
		return pgtype.UUID{Valid: false}
	}
	var b [16]byte
	copy(b[:], id[:])
	return pgtype.UUID{Bytes: b, Valid: true}
}

// pgNullNumeric converts a *string decimal to pgtype.Numeric.
// Used for rebill_factor which is stored as NUMERIC in PostgreSQL.
// Returns invalid if the string is nil or not a valid decimal.
func pgNullNumeric(s *string) pgtype.Numeric {
	if s == nil {
		return pgtype.Numeric{Valid: false}
	}
	var n pgtype.Numeric
	if err := n.Scan(*s); err != nil {
		return pgtype.Numeric{Valid: false}
	}
	return n
}

// PgDateFromTime converts a time.Time to pgtype.Date.
// pgx represents DATE columns as pgtype.Date, not time.Time directly.
func PgDateFromTime(t time.Time) pgtype.Date {
	return pgtype.Date{Time: t, Valid: true}
}
