package main

// contact_service.go
// =============================================================================
// ContactService — the business logic layer for contacts.
//
// A "contact" is a customer/supplier an organisation invoices or buys from. This
// service is the contacts equivalent of ExpenseService: it owns authorisation,
// validation, the mapping between the API shape (plain/optional strings) and the
// database shape (pgx types), and the calls into the sqlc-generated contacts
// package.
//
// It deliberately reuses the helpers already defined in expense_service.go
// (same `main` package): pgNullText / nullTextToPtr for nullable text, isOrgAdmin
// for the admin check, and the AppError constructors from errors.go. Only the
// integer helpers that contacts need and expenses didn't (a 0-PRESERVING
// *int32 ↔ pgtype.Int4 pair) are added here.
//
//   HTTP handler (server.go)
//     ↓
//   ContactService (this file)
//     ↓
//   *contacts.Queries (db/contacts — generated by sqlc)
//     ↓
//   PostgreSQL
//
// Note: contacts hold NO money, so there is no pence conversion here. The only
// numeric field, default_payment_terms_days, is a count of DAYS where 0 ("Due on
// Receipt") is distinct from NULL ("no contact-level terms") — hence the
// 0-preserving helper rather than the expenses' pgNullInt32 (which maps 0→NULL).
// =============================================================================

import (
	"context"
	"errors"
	"strings"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/jackc/pgx/v5/pgxpool"

	auth "github.com/operationfb/accounting-saas/db/auth"
	contacts "github.com/operationfb/accounting-saas/db/contacts"
)

// validChargeVAT is the set the charge_vat field is restricted to. It mirrors the
// CHECK constraint in contacts_schema.sql and the form's three dropdown options.
var validChargeVAT = map[string]bool{
	"ALWAYS":       true, // charge VAT to this contact on every invoice
	"NEVER":        true, // never charge VAT to this contact
	"SAME_COUNTRY": true, // only when the contact is in our country/VAT area
}

// ContactService holds the connection pool, the contacts query set, and the auth
// query set used to resolve the caller's membership/role.
type ContactService struct {
	pool        *pgxpool.Pool
	queries     *contacts.Queries
	authQueries auth.Querier
}

// NewContactService is the constructor, called once in main.go.
func NewContactService(pool *pgxpool.Pool, queries *contacts.Queries, authQueries auth.Querier) *ContactService {
	return &ContactService{
		pool:        pool,
		queries:     queries,
		authQueries: authQueries,
	}
}

// =============================================================================
// AUTHORIZATION
// =============================================================================

// authorize confirms the caller is an ACTIVE member of the organisation and
// returns their role. Mirrors ExpenseService.authorize — every contact operation
// runs this first so non-members / deactivated members are refused (403), and the
// role can gate who may modify a contact (see the update/delete ownership rule).
func (s *ContactService) authorize(ctx context.Context, userID, orgID uuid.UUID) (auth.OrganisationRole, error) {
	return authorizeMember(ctx, s.authQueries, userID, orgID)
}

// =============================================================================
// CREATE
// =============================================================================

// CreateContact validates + normalises the request and inserts one contact. The
// owning organisation and the creator come from the authenticated token, never
// from the body. A single-table INSERT needs no transaction.
//
// Any active member may create a contact (contacts are shared business data).
func (s *ContactService) CreateContact(
	ctx context.Context,
	authUserID uuid.UUID,
	authOrgID uuid.UUID,
	req CreateContactRequest,
) (*ContactResponse, error) {
	if _, err := s.authorize(ctx, authUserID, authOrgID); err != nil {
		return nil, err
	}

	countryCode, err := normaliseCountryCode(req.CountryCode)
	if err != nil {
		return nil, err
	}

	chargeVAT, err := normaliseChargeVAT(req.ChargeVAT)
	if err != nil {
		return nil, err
	}

	// invoice_language defaults to 'en'; display_contact_name defaults to TRUE
	// (the form's checked-by-default box, so a nil pointer means "checked").
	invoiceLanguage := strings.TrimSpace(req.InvoiceLanguage)
	if invoiceLanguage == "" {
		invoiceLanguage = "en"
	}
	displayContactName := true
	if req.DisplayContactName != nil {
		displayContactName = *req.DisplayContactName
	}

	params := contacts.CreateContactParams{
		OrganisationID:                  authOrgID,
		CreatedByUserID:                 authUserID,
		FirstName:                       pgNullText(req.FirstName),
		LastName:                        pgNullText(req.LastName),
		OrganisationName:                pgNullText(req.OrganisationName),
		Email:                           pgNullText(req.Email),
		BillingEmail:                    pgNullText(req.BillingEmail),
		Telephone:                       pgNullText(req.Telephone),
		Mobile:                          pgNullText(req.Mobile),
		AddressLine1:                    pgNullText(req.AddressLine1),
		AddressLine2:                    pgNullText(req.AddressLine2),
		AddressLine3:                    pgNullText(req.AddressLine3),
		Town:                            pgNullText(req.Town),
		Region:                          pgNullText(req.Region),
		Postcode:                        pgNullText(req.Postcode),
		CountryCode:                     countryCode,
		DefaultPaymentTermsDays:         pgInt32FromPtr(req.DefaultPaymentTermsDays),
		UsesContactLevelEmailSettings:   req.UsesContactLevelEmailSettings,
		UsesContactLevelInvoiceSequence: req.UsesContactLevelInvoiceSequence,
		DisplayContactName:              displayContactName,
		ChargeVat:                       chargeVAT,
		VatRegistrationNumber:           pgNullText(req.VATRegistrationNumber),
		InvoiceLanguage:                 invoiceLanguage,
		BankSortCode:                    pgNullText(req.BankSortCode),
		BankAccountNumber:               pgNullText(req.BankAccountNumber),
		BankRecipientName:               pgNullText(req.BankRecipientName),
	}

	created, err := s.queries.CreateContact(ctx, params)
	if err != nil {
		return nil, ErrInternal(err)
	}
	return contactToResponse(created), nil
}

// =============================================================================
// GET
// =============================================================================

// GetContact fetches one contact by id, org-scoped. Any active member may read a
// contact (shared business data) — single read, no transaction.
func (s *ContactService) GetContact(
	ctx context.Context,
	authUserID uuid.UUID,
	authOrgID uuid.UUID,
	id string,
) (*ContactResponse, error) {
	contactUUID, err := uuid.Parse(id)
	if err != nil {
		return nil, ErrValidation("id is not a valid UUID", err)
	}
	if _, err := s.authorize(ctx, authUserID, authOrgID); err != nil {
		return nil, err
	}

	row, err := s.queries.GetContact(ctx, contacts.GetContactParams{
		ID:             contactUUID,
		OrganisationID: authOrgID,
	})
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, ErrNotFound("contact", id)
		}
		return nil, ErrInternal(err)
	}
	return contactToResponse(row), nil
}

// =============================================================================
// LIST
// =============================================================================

// ListContacts returns every active contact in the caller's organisation
// (contacts are shared, so there is no per-user filtering like expenses have).
// Any active member may list.
func (s *ContactService) ListContacts(
	ctx context.Context,
	authUserID uuid.UUID,
	authOrgID uuid.UUID,
) ([]*ContactResponse, error) {
	if _, err := s.authorize(ctx, authUserID, authOrgID); err != nil {
		return nil, err
	}

	rows, err := s.queries.ListContacts(ctx, authOrgID)
	if err != nil {
		return nil, ErrInternal(err)
	}

	out := make([]*ContactResponse, 0, len(rows))
	for _, row := range rows {
		out = append(out, contactToResponse(row))
	}
	return out, nil
}

// =============================================================================
// UPDATE
// =============================================================================

// UpdateContact performs a full update of a contact's editable fields (PUT
// semantics). Authorisation: the caller must be the contact's creator, or an
// owner/admin of the organisation (mirrors the expense ownership rule). The
// fetch (for the ownership check + 404) and the update are two org-scoped,
// soft-delete-aware statements; created_by can't change, so no transaction is
// needed to avoid a race.
func (s *ContactService) UpdateContact(
	ctx context.Context,
	authUserID uuid.UUID,
	authOrgID uuid.UUID,
	id string,
	req UpdateContactRequest,
) (*ContactResponse, error) {
	contactUUID, err := uuid.Parse(id)
	if err != nil {
		return nil, ErrValidation("id is not a valid UUID", err)
	}

	role, err := s.authorize(ctx, authUserID, authOrgID)
	if err != nil {
		return nil, err
	}

	countryCode, err := normaliseCountryCode(req.CountryCode)
	if err != nil {
		return nil, err
	}
	chargeVAT, err := normaliseChargeVAT(req.ChargeVAT)
	if err != nil {
		return nil, err
	}
	invoiceLanguage := strings.TrimSpace(req.InvoiceLanguage)
	if invoiceLanguage == "" {
		invoiceLanguage = "en"
	}
	displayContactName := true
	if req.DisplayContactName != nil {
		displayContactName = *req.DisplayContactName
	}

	// Fetch first: 404 if it doesn't exist in this org, then enforce ownership.
	existing, err := s.queries.GetContact(ctx, contacts.GetContactParams{
		ID:             contactUUID,
		OrganisationID: authOrgID,
	})
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, ErrNotFound("contact", id)
		}
		return nil, ErrInternal(err)
	}
	if existing.CreatedByUserID != authUserID && !isOrgAdmin(role) {
		return nil, ErrForbidden("you do not have access to this contact")
	}

	updated, err := s.queries.UpdateContact(ctx, contacts.UpdateContactParams{
		ID:                              contactUUID,
		OrganisationID:                  authOrgID,
		FirstName:                       pgNullText(req.FirstName),
		LastName:                        pgNullText(req.LastName),
		OrganisationName:                pgNullText(req.OrganisationName),
		Email:                           pgNullText(req.Email),
		BillingEmail:                    pgNullText(req.BillingEmail),
		Telephone:                       pgNullText(req.Telephone),
		Mobile:                          pgNullText(req.Mobile),
		AddressLine1:                    pgNullText(req.AddressLine1),
		AddressLine2:                    pgNullText(req.AddressLine2),
		AddressLine3:                    pgNullText(req.AddressLine3),
		Town:                            pgNullText(req.Town),
		Region:                          pgNullText(req.Region),
		Postcode:                        pgNullText(req.Postcode),
		CountryCode:                     countryCode,
		DefaultPaymentTermsDays:         pgInt32FromPtr(req.DefaultPaymentTermsDays),
		UsesContactLevelEmailSettings:   req.UsesContactLevelEmailSettings,
		UsesContactLevelInvoiceSequence: req.UsesContactLevelInvoiceSequence,
		DisplayContactName:              displayContactName,
		ChargeVat:                       chargeVAT,
		VatRegistrationNumber:           pgNullText(req.VATRegistrationNumber),
		InvoiceLanguage:                 invoiceLanguage,
		BankSortCode:                    pgNullText(req.BankSortCode),
		BankAccountNumber:               pgNullText(req.BankAccountNumber),
		BankRecipientName:               pgNullText(req.BankRecipientName),
	})
	if err != nil {
		// The row was live a moment ago; ErrNoRows means it was deleted in between.
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, ErrNotFound("contact", id)
		}
		return nil, ErrInternal(err)
	}
	return contactToResponse(updated), nil
}

// =============================================================================
// DELETE
// =============================================================================

// DeleteContact soft-deletes a contact (sets deleted_at) so it disappears from
// lists and reads while the row is retained for audit / referencing invoices.
// Authorisation mirrors UpdateContact: the caller must be the creator or an
// owner/admin of the organisation.
func (s *ContactService) DeleteContact(
	ctx context.Context,
	authUserID uuid.UUID,
	authOrgID uuid.UUID,
	id string,
) error {
	contactUUID, err := uuid.Parse(id)
	if err != nil {
		return ErrValidation("id is not a valid UUID", err)
	}

	role, err := s.authorize(ctx, authUserID, authOrgID)
	if err != nil {
		return err
	}

	existing, err := s.queries.GetContact(ctx, contacts.GetContactParams{
		ID:             contactUUID,
		OrganisationID: authOrgID,
	})
	if err != nil {
		// Covers an unknown id and an already-deleted contact (GetContact filters
		// deleted_at IS NULL) → 404.
		if errors.Is(err, pgx.ErrNoRows) {
			return ErrNotFound("contact", id)
		}
		return ErrInternal(err)
	}
	if existing.CreatedByUserID != authUserID && !isOrgAdmin(role) {
		return ErrForbidden("you do not have access to this contact")
	}

	if err := s.queries.SoftDeleteContact(ctx, contacts.SoftDeleteContactParams{
		ID:             contactUUID,
		OrganisationID: authOrgID,
	}); err != nil {
		return ErrInternal(err)
	}
	return nil
}

// =============================================================================
// VALIDATION / NORMALISATION HELPERS
// =============================================================================

// normaliseCountryCode upper-cases + trims the country code and defaults it to
// 'GB' when blank. It must be exactly two letters (matches the CHAR(2) column and
// the uppercase CHECK). Binding also enforces len=2, but we re-check after
// trimming so a service-level caller (e.g. a test) is validated too.
func normaliseCountryCode(raw string) (string, error) {
	code := strings.ToUpper(strings.TrimSpace(raw))
	if code == "" {
		return "GB", nil
	}
	if len(code) != 2 {
		return "", ErrValidation("country_code must be a 2-letter ISO 3166-1 alpha-2 code", nil)
	}
	return code, nil
}

// normaliseChargeVAT defaults a blank value to 'SAME_COUNTRY' (the form's default)
// and rejects anything outside the allowed set. This is defence-in-depth behind
// the handler's `oneof` binding and the DB CHECK, so the service is correct even
// when called directly.
func normaliseChargeVAT(raw string) (string, error) {
	v := strings.TrimSpace(raw)
	if v == "" {
		return "SAME_COUNTRY", nil
	}
	if !validChargeVAT[v] {
		return "", ErrValidation("charge_vat must be one of ALWAYS, NEVER, SAME_COUNTRY", nil)
	}
	return v, nil
}

// =============================================================================
// RESPONSE FORMATTER
// =============================================================================

// contactToResponse converts a database Contact row (pgx types, UUIDs) into the
// API response shape (plain/optional strings). Reuses nullTextToPtr from
// expense_service.go for the nullable text columns.
func contactToResponse(c contacts.Contact) *ContactResponse {
	return &ContactResponse{
		ID:                              c.ID.String(),
		OrganisationID:                  c.OrganisationID.String(),
		CreatedByUserID:                 c.CreatedByUserID.String(),
		FirstName:                       nullTextToPtr(c.FirstName),
		LastName:                        nullTextToPtr(c.LastName),
		OrganisationName:                nullTextToPtr(c.OrganisationName),
		Email:                           nullTextToPtr(c.Email),
		BillingEmail:                    nullTextToPtr(c.BillingEmail),
		Telephone:                       nullTextToPtr(c.Telephone),
		Mobile:                          nullTextToPtr(c.Mobile),
		AddressLine1:                    nullTextToPtr(c.AddressLine1),
		AddressLine2:                    nullTextToPtr(c.AddressLine2),
		AddressLine3:                    nullTextToPtr(c.AddressLine3),
		Town:                            nullTextToPtr(c.Town),
		Region:                          nullTextToPtr(c.Region),
		Postcode:                        nullTextToPtr(c.Postcode),
		CountryCode:                     c.CountryCode,
		DefaultPaymentTermsDays:         nullInt32ToPtr(c.DefaultPaymentTermsDays),
		UsesContactLevelEmailSettings:   c.UsesContactLevelEmailSettings,
		UsesContactLevelInvoiceSequence: c.UsesContactLevelInvoiceSequence,
		DisplayContactName:              c.DisplayContactName,
		ChargeVAT:                       c.ChargeVat,
		VATRegistrationNumber:           nullTextToPtr(c.VatRegistrationNumber),
		InvoiceLanguage:                 c.InvoiceLanguage,
		BankSortCode:                    nullTextToPtr(c.BankSortCode),
		BankAccountNumber:               nullTextToPtr(c.BankAccountNumber),
		BankRecipientName:               nullTextToPtr(c.BankRecipientName),
		IsActive:                        c.IsActive,
		CreatedAt:                       c.CreatedAt.Time.Format(time.RFC3339),
		UpdatedAt:                       c.UpdatedAt.Time.Format(time.RFC3339),
	}
}

// =============================================================================
// PGX INTEGER HELPERS (0-preserving)
//
// These complement the helpers in expense_service.go. Crucially they DIFFER from
// pgNullInt32 there: pgNullInt32 maps 0→NULL (right for vat_rate_bps, where 0
// means "no rate"), but for default_payment_terms_days a 0 means "Due on Receipt"
// and must be PRESERVED — only a nil pointer becomes NULL.
// =============================================================================

// pgInt32FromPtr converts a *int32 to pgtype.Int4 preserving 0.
// nil pointer → NULL; non-nil pointer → its value (including 0).
func pgInt32FromPtr(n *int32) pgtype.Int4 {
	if n == nil {
		return pgtype.Int4{Valid: false}
	}
	return pgtype.Int4{Int32: *n, Valid: true}
}

// nullInt32ToPtr is the reverse: pgtype.Int4 → *int32.
// NULL → nil; otherwise a pointer to the value (0 is kept, not dropped).
func nullInt32ToPtr(n pgtype.Int4) *int32 {
	if !n.Valid {
		return nil
	}
	v := n.Int32
	return &v
}
