package main

// expense_service.go
// =============================================================================
// ExpenseService — the business logic layer for expenses.
//
// The three layers of this application and what each owns:
//
//   HTTP handler (server.go)
//     ↓  request parsing, response formatting
//   ExpenseService (this file)
//     ↓  business rules, validation, transactions, unit conversion
//   *expenses.Queries (db/expenses/query.sql.go — generated by sqlc)
//     ↓  SQL execution only, no business logic
//   PostgreSQL
//
// The service layer is the most important one to understand. It is the place
// where your accounting rules live. The handler and the database layer are
// relatively mechanical; this is where judgment is applied.
// =============================================================================

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/shopspring/decimal"

	auth "github.com/operationfb/accounting-saas/db/auth"
	expenses "github.com/operationfb/accounting-saas/db/expenses"
)

// ExpenseService holds a reference to both the connection pool and the
// sqlc-generated Queries struct.
//
// Why do we need BOTH?
//
//   - *expenses.Queries wraps the pool for normal single-statement queries.
//     When you call q.GetExpense(ctx, id, orgID), it borrows one connection
//     from the pool, runs the query, and returns it.
//
//   - *pgxpool.Pool is needed when we want a TRANSACTION. A transaction must
//     pin all its statements to the SAME connection. We begin a transaction
//     on the pool (pool.Begin), which gives us a pgx.Tx. We then call
//     expenses.New(tx) to get a *Queries that runs inside that transaction.
//     See the withTransaction helper below for the full picture.
type ExpenseService struct {
	pool        *pgxpool.Pool
	queries     *expenses.Queries
	authQueries auth.Querier
}

// NewExpenseService is the constructor. Called once in main.go.
// authQueries is the auth module's query interface — the service uses it to
// resolve the caller's organisation membership/role for authorisation.
func NewExpenseService(pool *pgxpool.Pool, queries *expenses.Queries, authQueries auth.Querier) *ExpenseService {
	return &ExpenseService{
		pool:        pool,
		queries:     queries,
		authQueries: authQueries,
	}
}

// =============================================================================
// AUTHORIZATION
// =============================================================================

// authorize confirms the caller is an ACTIVE member of the organisation and
// returns their role. Every expense operation runs this first so that a user
// who isn't an active member of the org is refused (403), and the role can
// drive what they're allowed to see (owner/admin read all).
//
// GetMembership does not filter by status, so we check status == "active" here.
func (s *ExpenseService) authorize(ctx context.Context, userID, orgID uuid.UUID) (auth.OrganisationRole, error) {
	m, err := s.authQueries.GetMembership(ctx, auth.GetMembershipParams{
		OrganisationID: orgID,
		UserID:         userID,
	})
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return "", ErrForbidden("you are not a member of this organisation")
		}
		return "", ErrInternal(err)
	}
	if m.Status != "active" {
		return "", ErrForbidden("your organisation membership is not active")
	}
	return m.Role, nil
}

// isOrgAdmin reports whether a role may read ALL expenses in the organisation.
// Per product decision this is owner and admin only; member/accountant/read_only
// are limited to their own expenses.
func isOrgAdmin(role auth.OrganisationRole) bool {
	return role == auth.OrganisationRoleOwner || role == auth.OrganisationRoleAdmin
}

// =============================================================================
// TRANSACTION HELPER
// =============================================================================

// withTransaction runs a function inside a PostgreSQL transaction.
//
// Why do we need this?
//
// Creating an expense is not one database write — it's potentially three:
//  1. INSERT INTO expenses
//  2. INSERT INTO expense_mileage  (if mileage claim)
//  3. INSERT INTO expense_audit_log
//
// If write 1 succeeds but write 2 fails (e.g. a constraint violation), we
// would have a corrupt expense record in the database with no mileage row.
// A transaction guarantees atomicity: either ALL writes succeed, or NONE do.
// PostgreSQL rolls back everything if any step returns an error.
//
// How it works:
//  1. Begin a transaction → get a pgx.Tx (a connection pinned to this transaction)
//  2. Wrap the tx in a *expenses.Queries so sqlc methods run inside it
//  3. Call the provided function `fn` with the transaction-scoped Queries
//  4. If fn returns nil error → COMMIT (all writes become permanent)
//  5. If fn returns an error → ROLLBACK (all writes are undone)
//
// The `fn` signature takes *expenses.Queries so callers work with the same
// type whether inside a transaction or not.
func (s *ExpenseService) withTransaction(ctx context.Context, fn func(*expenses.Queries) error) error {
	// Begin acquires a connection from the pool and starts a transaction on it.
	tx, err := s.pool.Begin(ctx)
	if err != nil {
		return fmt.Errorf("begin transaction: %w", err)
	}

	// expenses.New(tx) creates a Queries struct that uses the transaction
	// connection instead of the pool. Every query run through qtx is part
	// of this transaction.
	qtx := expenses.New(tx)

	// Run the caller's function. If it returns an error, roll back.
	if err := fn(qtx); err != nil {
		// Rollback undoes all writes made inside fn.
		// We log the rollback error but return the original error from fn
		// because that's what the caller cares about.
		_ = tx.Rollback(ctx)
		return err
	}

	// Commit makes all writes permanent.
	return tx.Commit(ctx)
}

// =============================================================================
// CREATEEXPENSE
// =============================================================================

// CreateExpense is the service method that handles creating a new expense.
//
// It does the following:
//  1. Validate inputs that can't be expressed as struct tags (e.g. date format)
//  2. Convert the gross value from a pounds string to integer pence
//  3. Compute VAT if a rate was given
//  4. Run both the expense INSERT and the audit log INSERT in a transaction
//  5. Return a formatted response
//
// The method signature takes the raw request from the handler and returns the
// formatted response the handler will write to JSON. The service owns the
// conversion between "what the API sees" and "what the database stores".
func (s *ExpenseService) CreateExpense(
	ctx context.Context,
	authUserID uuid.UUID,
	authOrgID uuid.UUID,
	req CreateExpenseRequest,
) (*ExpenseResponse, error) {

	// -------------------------------------------------------------------------
	// Step 1: Parse and validate inputs
	// -------------------------------------------------------------------------

	// Authorisation: the caller must be an active member of the organisation.
	// We don't use the role for creation (everyone creates only for themselves),
	// but this refuses non-members and deactivated members.
	if _, err := s.authorize(ctx, authUserID, authOrgID); err != nil {
		return nil, err
	}

	// The claimant and the organisation come from the authenticated token, not
	// from the request body — a user can only create expenses for themselves.
	organisationUUID := authOrgID
	userUUID := authUserID

	categoryUUID, err := uuid.Parse(req.CategoryID)
	if err != nil {
		return nil, ErrValidation("category_id is not a valid UUID", err)
	}

	// Parse the date. Go's time.Parse requires an exact reference time as the
	// layout — this is Go's quirky but memorable approach: the reference is
	// Mon Jan 2 15:04:05 MST 2006. "2006-01-02" means YYYY-MM-DD.
	datedOn, err := time.Parse("2006-01-02", req.DatedOn)
	if err != nil {
		return nil, ErrValidation("dated_on must be a valid date in YYYY-MM-DD format", err)
	}

	// -------------------------------------------------------------------------
	// Step 2: Convert money from pounds (string) to pence (integer)
	//
	// Why string input → integer storage?
	//
	//   The API accepts "42.50" as a string to avoid JavaScript float precision
	//   issues (JS uses float64 for all numbers; 42.1 in JS is actually
	//   42.09999999999999716...). We parse it with shopspring/decimal which
	//   is an arbitrary-precision decimal library, then convert to pence by
	//   multiplying by 100. We store as INTEGER pence in PostgreSQL.
	//
	//   42.50 → decimal("42.50") → multiply by 100 → decimal("4250") → int32(4250)
	// -------------------------------------------------------------------------
	grossDecimal, err := decimal.NewFromString(req.GrossValuePounds)
	if err != nil {
		return nil, ErrValidation(fmt.Sprintf("gross_value %q is not a valid decimal number", req.GrossValuePounds), err)
	}

	// Convert to pence. Mul returns a new decimal; Int32() truncates to int32.
	// We use int32 because PostgreSQL INTEGER is 4 bytes = int32 in Go.
	hundred := decimal.NewFromInt(100)
	grossPence := grossDecimal.Mul(hundred).IntPart() // IntPart() returns int64; cast below
	grossMinor := int32(grossPence)

	// Default currency to GBP if not provided
	currency := req.CurrencyCode
	if currency == "" {
		currency = "GBP"
	}

	// -------------------------------------------------------------------------
	// Step 3: Compute VAT
	//
	// Very simplified for now — we'll expand this when we build the VAT service.
	// If a VAT rate ID was provided, we look up the rate and compute the amount.
	// For now we just store zeroes and leave this as a clear TODO.
	// -------------------------------------------------------------------------
	var vatRateBPS int32 = 0
	var vatValueMinor int32 = 0
	var nativeVATValueMinor int32 = 0
	// TODO: When VATRateID is provided, fetch the rate from vat_rates table,
	// compute vatValueMinor = grossMinor * rate_bps / 10000, and store it.
	// This will be built in the VAT service.

	// -------------------------------------------------------------------------
	// Step 4: Build the database parameters struct
	//
	// expenses.CreateExpenseParams is generated by sqlc from the query in
	// query.sql. Every field here maps to a $1, $2, ... parameter in the SQL.
	// The field names and types come from the column definitions in schema.sql.
	// -------------------------------------------------------------------------
	params := expenses.CreateExpenseParams{
		OrganisationID:        organisationUUID,
		UserID:                userUUID,
		CreatedByUserID:       userUUID, // same as claimant for now; admin entry handled later
		CategoryID:            categoryUUID,
		DatedOn:               pgDateFromTime(datedOn), // helper below converts time.Time → pgx date
		Description:           req.Description,
		Currency:              currency,
		NativeCurrency:        "GBP", // hardcoded for UK MVP
		GrossValueMinor:       grossMinor,
		NativeGrossValueMinor: grossMinor, // same as gross for GBP; FX conversion added later
		VatRateBps:            pgNullInt32(vatRateBPS),
		VatValueMinor:         vatValueMinor,
		NativeVatValueMinor:   nativeVATValueMinor,
		VatStatus:             "TAXABLE",   // default; overridden when VAT service is built
		EcStatus:              "UK_NON_EC", // correct default for post-2021 UK expenses

		// Optional string fields: convert *string to pgtype.Text
		// pgNullText is a small helper defined at the bottom of this file.
		// It returns a pgtype.Text with Valid=false when the pointer is nil,
		// which maps to NULL in PostgreSQL.
		ReceiptReference:  pgNullText(req.ReceiptReference),
		SupplierName:      pgNullText(req.SupplierName),
		SupplierVatNumber: pgNullText(req.SupplierVATNo),
		InvoiceNumber:     pgNullText(req.InvoiceNumber),

		// Project rebilling
		ProjectID:    pgNullUUID(req.ProjectID),
		RebillType:   pgNullText(req.RebillType),
		RebillFactor: pgNullNumeric(req.RebillFactor),
	}

	// -------------------------------------------------------------------------
	// Step 5: Write to the database inside a transaction
	//
	// We use withTransaction so that the expense INSERT and the audit INSERT
	// are atomic. If either fails, both are rolled back.
	// -------------------------------------------------------------------------
	var created expenses.Expense // will hold the row returned by RETURNING *

	err = s.withTransaction(ctx, func(qtx *expenses.Queries) error {
		// Write 1: create the expense record
		row, err := qtx.CreateExpense(ctx, params)
		if err != nil {
			return fmt.Errorf("insert expense: %w", err)
		}
		created = row

		// Write 2: append to the audit log
		// The audit log records who did what and when. Even for a CREATE we
		// write a row so there's a complete history from birth.
		// We pass nil for old_data (nothing existed before) and the new row
		// serialised as JSON for new_data.
		// TODO: implement CreateAuditEntry query and call it here.
		// For now this is a clear marker of where it belongs.
		_ = created // used above; keeping variable in scope for audit TODO

		return nil
	})
	if err != nil {
		return nil, fmt.Errorf("create expense: %w", err)
	}

	// -------------------------------------------------------------------------
	// Step 6: Format and return the response
	// -------------------------------------------------------------------------
	return expenseToResponse(created), nil
}

// =============================================================================
// GETEXPENSE
// =============================================================================

// GetExpense fetches a single expense by ID, scoped to an organisation.
// No transaction needed here — it's a single read.
func (s *ExpenseService) GetExpense(
	ctx context.Context,
	authUserID uuid.UUID,
	authOrgID uuid.UUID,
	id string,
) (*ExpenseResponse, error) {
	expenseUUID, err := uuid.Parse(id)
	if err != nil {
		return nil, ErrValidation("id is not a valid UUID", err)
	}

	// Confirm the caller is an active member and get their role.
	role, err := s.authorize(ctx, authUserID, authOrgID)
	if err != nil {
		return nil, err
	}

	row, err := s.queries.GetExpense(ctx, expenses.GetExpenseParams{ID: expenseUUID, OrganisationID: authOrgID})
	if err != nil {
		// No row for this id within the org → 404 (previously surfaced as 500).
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, ErrNotFound("expense", id)
		}
		return nil, ErrInternal(err)
	}

	// Ownership: a user may read only their own expense, unless they are an
	// owner/admin of the organisation (who may read all).
	if row.UserID != authUserID && !isOrgAdmin(role) {
		return nil, ErrForbidden("you do not have access to this expense")
	}

	return expenseToResponse(row), nil
}

// =============================================================================
// LISTEXPENSES
// =============================================================================

// ListExpenses returns the expenses the caller is allowed to see:
//   - owner/admin: every expense in the organisation
//   - everyone else: only their own expenses
func (s *ExpenseService) ListExpenses(
	ctx context.Context,
	authUserID uuid.UUID,
	authOrgID uuid.UUID,
) ([]*ExpenseResponse, error) {
	role, err := s.authorize(ctx, authUserID, authOrgID)
	if err != nil {
		return nil, err
	}

	var rows []expenses.Expense
	if isOrgAdmin(role) {
		rows, err = s.queries.ListExpenses(ctx, authOrgID)
	} else {
		rows, err = s.queries.ListExpensesByUser(ctx, expenses.ListExpensesByUserParams{
			OrganisationID: authOrgID,
			UserID:         authUserID,
		})
	}
	if err != nil {
		return nil, ErrInternal(err)
	}

	out := make([]*ExpenseResponse, 0, len(rows))
	for _, row := range rows {
		out = append(out, expenseToResponse(row))
	}
	return out, nil
}

// =============================================================================
// RESPONSE FORMATTER
// =============================================================================

// expenseToResponse converts a database Expense row (pence integers, UUIDs,
// pgx types) into the API response shape (pound strings, plain strings).
//
// This is the inverse of the conversion we did in CreateExpense.
// It lives here in the service because the service owns the mapping between
// database representation and API representation.
func expenseToResponse(e expenses.Expense) *ExpenseResponse {
	// Convert integer pence back to a decimal pound string.
	// 4250 pence → decimal(4250) ÷ 100 → decimal(42.50) → "42.50"
	grossPounds := decimal.NewFromInt(int64(e.GrossValueMinor)).
		Div(decimal.NewFromInt(100)).
		StringFixed(2) // StringFixed(2) always gives 2 decimal places: "42.50" not "42.5"

	nativeGrossPounds := decimal.NewFromInt(int64(e.NativeGrossValueMinor)).
		Div(decimal.NewFromInt(100)).
		StringFixed(2)

	vatPounds := decimal.NewFromInt(int64(e.VatValueMinor)).
		Div(decimal.NewFromInt(100)).
		StringFixed(2)

	return &ExpenseResponse{
		ID:               e.ID.String(),
		OrganisationID:   e.OrganisationID.String(),
		UserID:           e.UserID.String(),
		CategoryID:       e.CategoryID.String(),
		DatedOn:          e.DatedOn.Time.Format("2006-01-02"),
		Description:      e.Description,
		Currency:         e.Currency,
		GrossValue:       grossPounds,
		NativeGrossValue: nativeGrossPounds,
		VATValue:         vatPounds,
		Status:           e.Status,
		CreatedAt:        e.CreatedAt.Time.Format(time.RFC3339),
		UpdatedAt:        e.UpdatedAt.Time.Format(time.RFC3339),

		// Optional fields: convert pgtype.Text back to *string
		ReceiptReference:  nullTextToPtr(e.ReceiptReference),
		SupplierName:      nullTextToPtr(e.SupplierName),
		SupplierVATNumber: nullTextToPtr(e.SupplierVatNumber),
		InvoiceNumber:     nullTextToPtr(e.InvoiceNumber),
	}
}

// =============================================================================
// PGX TYPE HELPERS
//
// pgx uses its own types for nullable values instead of Go's standard
// sql.NullString etc. These tiny helpers convert between plain Go types
// and pgx types so the service code reads cleanly without pgtype.* noise
// everywhere.
//
// pgtype.Text has two fields:
//   String string  — the actual value
//   Valid  bool    — true if the value is non-NULL
//
// When Valid is false, pgx sends NULL to PostgreSQL regardless of String.
// =============================================================================

// pgNullText converts a *string to pgtype.Text.
// nil pointer → NULL in the database.
// non-nil pointer → the string value.
func pgNullText(s *string) pgtype.Text {
	if s == nil {
		return pgtype.Text{Valid: false}
	}
	return pgtype.Text{String: *s, Valid: true}
}

// nullTextToPtr is the reverse: pgtype.Text → *string.
// Invalid (NULL) → nil. Valid → pointer to string.
func nullTextToPtr(t pgtype.Text) *string {
	if !t.Valid {
		return nil
	}
	return &t.String
}

// pgNullInt32 wraps an int32 in pgtype.Int4.
// Used for nullable integer columns (e.g. vat_rate_bps when no VAT).
func pgNullInt32(n int32) pgtype.Int4 {
	return pgtype.Int4{Int32: n, Valid: n != 0}
}

// pgNullUUID converts a *string UUID to pgtype.UUID.
// If the string is nil or fails to parse, returns an invalid (NULL) UUID.
func pgNullUUID(s *string) pgtype.UUID {
	if s == nil {
		return pgtype.UUID{Valid: false}
	}
	id, err := uuid.Parse(*s)
	if err != nil {
		return pgtype.UUID{Valid: false}
	}
	var b [16]byte
	copy(b[:], id[:])
	return pgtype.UUID{Bytes: b, Valid: true}
}

// pgNullNumeric converts a *string decimal to pgtype.Numeric.
// Used for rebill_factor which is stored as NUMERIC in PostgreSQL.
// Returns invalid if the string is nil or not a valid decimal.
func pgNullNumeric(s *string) pgtype.Numeric {
	if s == nil {
		return pgtype.Numeric{Valid: false}
	}
	var n pgtype.Numeric
	if err := n.Scan(*s); err != nil {
		return pgtype.Numeric{Valid: false}
	}
	return n
}

// pgDateFromTime converts a time.Time to pgtype.Date.
// pgx represents DATE columns as pgtype.Date, not time.Time directly.
func pgDateFromTime(t time.Time) pgtype.Date {
	return pgtype.Date{Time: t, Valid: true}
}
