package main

// expense_service.go
// =============================================================================
// ExpenseService — the business logic layer for expenses.
//
// The three layers of this application and what each owns:
//
//   HTTP handler (server.go)
//     ↓  request parsing, response formatting
//   ExpenseService (this file)
//     ↓  business rules, validation, transactions, unit conversion
//   *expenses.Queries (db/expenses/query.sql.go — generated by sqlc)
//     ↓  SQL execution only, no business logic
//   PostgreSQL
//
// The service layer is the most important one to understand. It is the place
// where your accounting rules live. The handler and the database layer are
// relatively mechanical; this is where judgment is applied.
// =============================================================================

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/shopspring/decimal"

	auth "github.com/operationfb/accounting-saas/db/auth"
	expenses "github.com/operationfb/accounting-saas/db/expenses"
)

// ExpenseService holds a reference to both the connection pool and the
// sqlc-generated Queries struct.
//
// Why do we need BOTH?
//
//   - *expenses.Queries wraps the pool for normal single-statement queries.
//     When you call q.GetExpense(ctx, id, orgID), it borrows one connection
//     from the pool, runs the query, and returns it.
//
//   - *pgxpool.Pool is needed when we want a TRANSACTION. A transaction must
//     pin all its statements to the SAME connection. We begin a transaction
//     on the pool (pool.Begin), which gives us a pgx.Tx. We then call
//     expenses.New(tx) to get a *Queries that runs inside that transaction.
//     See the withTransaction helper below for the full picture.
type ExpenseService struct {
	pool        *pgxpool.Pool
	queries     *expenses.Queries
	authQueries auth.Querier
}

// NewExpenseService is the constructor. Called once in main.go.
// authQueries is the auth module's query interface — the service uses it to
// resolve the caller's organisation membership/role for authorisation.
func NewExpenseService(pool *pgxpool.Pool, queries *expenses.Queries, authQueries auth.Querier) *ExpenseService {
	return &ExpenseService{
		pool:        pool,
		queries:     queries,
		authQueries: authQueries,
	}
}

// =============================================================================
// AUTHORIZATION
// =============================================================================

// authorize confirms the caller is an ACTIVE member of the organisation and
// returns their role. Every expense operation runs this first so that a user
// who isn't an active member of the org is refused (403), and the role can
// drive what they're allowed to see (owner/admin read all).
//
// GetMembership does not filter by status, so we check status == "active" here.
func (s *ExpenseService) authorize(ctx context.Context, userID, orgID uuid.UUID) (auth.OrganisationRole, error) {
	m, err := s.authQueries.GetMembership(ctx, auth.GetMembershipParams{
		OrganisationID: orgID,
		UserID:         userID,
	})
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return "", ErrForbidden("you are not a member of this organisation")
		}
		return "", ErrInternal(err)
	}
	if m.Status != "active" {
		return "", ErrForbidden("your organisation membership is not active")
	}
	return m.Role, nil
}

// isOrgAdmin reports whether a role may read ALL expenses in the organisation.
// Per product decision this is owner and admin only; member/accountant/read_only
// are limited to their own expenses.
func isOrgAdmin(role auth.OrganisationRole) bool {
	return role == auth.OrganisationRoleOwner || role == auth.OrganisationRoleAdmin
}

// =============================================================================
// TRANSACTION HELPER
// =============================================================================

// withTransaction runs a function inside a PostgreSQL transaction.
//
// Why do we need this?
//
// Creating an expense is not one database write — it's potentially three:
//  1. INSERT INTO expenses
//  2. INSERT INTO expense_mileage  (if mileage claim)
//  3. INSERT INTO expense_audit_log
//
// If write 1 succeeds but write 2 fails (e.g. a constraint violation), we
// would have a corrupt expense record in the database with no mileage row.
// A transaction guarantees atomicity: either ALL writes succeed, or NONE do.
// PostgreSQL rolls back everything if any step returns an error.
//
// How it works:
//  1. Begin a transaction → get a pgx.Tx (a connection pinned to this transaction)
//  2. Wrap the tx in a *expenses.Queries so sqlc methods run inside it
//  3. Call the provided function `fn` with the transaction-scoped Queries
//  4. If fn returns nil error → COMMIT (all writes become permanent)
//  5. If fn returns an error → ROLLBACK (all writes are undone)
//
// The `fn` signature takes *expenses.Queries so callers work with the same
// type whether inside a transaction or not.
func (s *ExpenseService) withTransaction(ctx context.Context, fn func(*expenses.Queries) error) error {
	// Begin acquires a connection from the pool and starts a transaction on it.
	tx, err := s.pool.Begin(ctx)
	if err != nil {
		return fmt.Errorf("begin transaction: %w", err)
	}

	// expenses.New(tx) creates a Queries struct that uses the transaction
	// connection instead of the pool. Every query run through qtx is part
	// of this transaction.
	qtx := expenses.New(tx)

	// Run the caller's function. If it returns an error, roll back.
	if err := fn(qtx); err != nil {
		// Rollback undoes all writes made inside fn.
		// We log the rollback error but return the original error from fn
		// because that's what the caller cares about.
		_ = tx.Rollback(ctx)
		return err
	}

	// Commit makes all writes permanent.
	return tx.Commit(ctx)
}

// =============================================================================
// VAT
// =============================================================================

// vatResult holds the resolved VAT fields, ready to drop into the Create/Update
// params struct.
type vatResult struct {
	RateID     pgtype.UUID
	RateBps    pgtype.Int4
	ValueMinor int32
}

// resolveVAT turns the request's vat_rate_id (+ optional vat_amount) into the
// stored VAT fields:
//   - no rate selected     → no VAT (NULL rate id/bps, value 0)
//   - fixed-ratio rate     → VAT EXTRACTED from the VAT-inclusive total (see
//     computeFixedVAT); any client amount is IGNORED (not an error)
//   - non-fixed-ratio rate → value = the client-supplied amount (0 if omitted)
//
// The selected rate must belong to the caller's organisation's country (the
// frontend only offers rates for that country); a mismatch is a validation error.
// Shared by CreateExpense and UpdateExpense so the rule lives in one place.
func (s *ExpenseService) resolveVAT(
	ctx context.Context,
	authOrgID uuid.UUID,
	grossMinor int32,
	vatRateID *string,
	vatAmount *string,
) (vatResult, error) {
	// No VAT rate selected → no VAT.
	if vatRateID == nil || *vatRateID == "" {
		return vatResult{}, nil
	}

	rateUUID, err := uuid.Parse(*vatRateID)
	if err != nil {
		return vatResult{}, ErrValidation("vat_rate_id is not a valid UUID", err)
	}

	rate, err := s.queries.GetVatRate(ctx, rateUUID)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return vatResult{}, ErrValidation("vat_rate_id not found", nil)
		}
		return vatResult{}, ErrInternal(err)
	}

	// The rate must be for the caller's organisation's country. The token carries
	// only the org id; the country_code lives on the organisation (auth domain).
	org, err := s.authQueries.GetOrganisation(ctx, authOrgID)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return vatResult{}, ErrNotFound("organisation", authOrgID.String())
		}
		return vatResult{}, ErrInternal(err)
	}
	if rate.CountryCode != org.CountryCode {
		return vatResult{}, ErrValidation("selected VAT rate is not valid for your organisation's country", nil)
	}

	var valueMinor int32
	if rate.IsFixedRatio {
		// Rate-locked: extract the VAT from the inclusive total; ignore any
		// client-supplied amount.
		valueMinor = computeFixedVAT(grossMinor, rate.RateBps)
	} else if vatAmount != nil {
		// Custom rate: accept the client's amount as-is (pounds → pence).
		amt, err := decimal.NewFromString(*vatAmount)
		if err != nil {
			return vatResult{}, ErrValidation(fmt.Sprintf("vat_amount %q is not a valid decimal number", *vatAmount), err)
		}
		valueMinor = int32(amt.Mul(decimal.NewFromInt(100)).Round(0).IntPart())
	}

	return vatResult{
		RateID:     pgNullUUID(vatRateID),
		RateBps:    pgtype.Int4{Int32: rate.RateBps, Valid: true},
		ValueMinor: valueMinor,
	}, nil
}

// computeFixedVAT returns the VAT contained in a VAT-INCLUSIVE total for a
// fixed-ratio rate. The entered gross is the total invoice/receipt amount, which
// already includes VAT, so we EXTRACT the VAT rather than add it on top:
//
//	total = net + vat,  vat = net × rate   ⇒   vat = total × rate / (100 + rate)
//
// In basis points: vat = total × rate_bps / (10000 + rate_bps). This is the
// standard HMRC "VAT fraction" (20% → 2000/12000 = 1/6; 5% → 500/10500 = 1/21).
// The denominator is always ≥ 10000, so a 0% (zero) rate safely yields 0.
// Result is rounded half-up (half away from zero) to the nearest penny.
// Example: £120.00 (12000p) incl. 20% → 12000 × 2000 / 12000 = 2000p = £20.00.
func computeFixedVAT(grossMinor, rateBps int32) int32 {
	v := decimal.NewFromInt(int64(grossMinor)).
		Mul(decimal.NewFromInt(int64(rateBps))).
		// Denominator is 10000 + rate_bps (NOT 10000): the gross is VAT-inclusive,
		// so we extract the VAT fraction rather than add the rate on top.
		Div(decimal.NewFromInt(int64(10000 + rateBps))).
		Round(0) // whole pence, half away from zero
	return int32(v.IntPart())
}

// =============================================================================
// CREATEEXPENSE
// =============================================================================

// CreateExpense is the service method that handles creating a new expense.
//
// It does the following:
//  1. Validate inputs that can't be expressed as struct tags (e.g. date format)
//  2. Convert the gross value from a pounds string to integer pence
//  3. Compute VAT if a rate was given
//  4. Run both the expense INSERT and the audit log INSERT in a transaction
//  5. Return a formatted response
//
// The method signature takes the raw request from the handler and returns the
// formatted response the handler will write to JSON. The service owns the
// conversion between "what the API sees" and "what the database stores".
func (s *ExpenseService) CreateExpense(
	ctx context.Context,
	authUserID uuid.UUID,
	authOrgID uuid.UUID,
	req CreateExpenseRequest,
) (*ExpenseResponse, error) {

	// -------------------------------------------------------------------------
	// Step 1: Parse and validate inputs
	// -------------------------------------------------------------------------

	// Authorisation: the caller must be an active member of the organisation.
	// We capture their role so we can gate the "on behalf of" path below
	// (owner/admin only); authorize already refuses non-members and deactivated
	// members.
	role, err := s.authorize(ctx, authUserID, authOrgID)
	if err != nil {
		return nil, err
	}

	// The organisation comes from the authenticated token, never the request body.
	organisationUUID := authOrgID

	// Resolve the claimant (whose expense this is). Default: the caller records it
	// for themselves — claimant == caller, which is the overwhelming common case.
	// An owner/admin MAY record on behalf of another active member by passing
	// user_id; we still keep created_by_user_id = caller below (who actually typed it).
	claimantUUID := authUserID
	if req.UserID != nil && *req.UserID != "" {
		parsed, err := uuid.Parse(*req.UserID) // binding already validated shape; parse for the value
		if err != nil {
			return nil, ErrValidation("user_id is not a valid UUID", err)
		}
		if parsed != authUserID {
			// On-behalf entry. Only owners/admins may do it.
			if !isOrgAdmin(role) {
				return nil, ErrForbidden("only organisation owners and admins can record an expense on behalf of another user")
			}
			// The claimant must be an ACTIVE member of THIS organisation. The lookup
			// is org-scoped, so a user id from another tenant simply isn't found.
			m, err := s.authQueries.GetMembership(ctx, auth.GetMembershipParams{
				OrganisationID: authOrgID,
				UserID:         parsed,
			})
			if err != nil {
				if errors.Is(err, pgx.ErrNoRows) {
					return nil, ErrValidation("user_id is not a member of this organisation", err)
				}
				return nil, ErrInternal(err)
			}
			if m.Status != "active" {
				return nil, ErrValidation("user_id is not an active member of this organisation", nil)
			}
			claimantUUID = parsed
		}
	}

	categoryUUID, err := uuid.Parse(req.CategoryID)
	if err != nil {
		return nil, ErrValidation("category_id is not a valid UUID", err)
	}

	// Parse the date. Go's time.Parse requires an exact reference time as the
	// layout — this is Go's quirky but memorable approach: the reference is
	// Mon Jan 2 15:04:05 MST 2006. "2006-01-02" means YYYY-MM-DD.
	datedOn, err := time.Parse("2006-01-02", req.DatedOn)
	if err != nil {
		return nil, ErrValidation("dated_on must be a valid date in YYYY-MM-DD format", err)
	}

	// -------------------------------------------------------------------------
	// Step 2: Convert money from pounds (string) to pence (integer)
	//
	// Why string input → integer storage?
	//
	//   The API accepts "42.50" as a string to avoid JavaScript float precision
	//   issues (JS uses float64 for all numbers; 42.1 in JS is actually
	//   42.09999999999999716...). We parse it with shopspring/decimal which
	//   is an arbitrary-precision decimal library, then convert to pence by
	//   multiplying by 100. We store as INTEGER pence in PostgreSQL.
	//
	//   42.50 → decimal("42.50") → multiply by 100 → decimal("4250") → int32(4250)
	// -------------------------------------------------------------------------
	grossDecimal, err := decimal.NewFromString(req.GrossValuePounds)
	if err != nil {
		return nil, ErrValidation(fmt.Sprintf("gross_value %q is not a valid decimal number", req.GrossValuePounds), err)
	}

	// Convert to pence. Mul returns a new decimal; Int32() truncates to int32.
	// We use int32 because PostgreSQL INTEGER is 4 bytes = int32 in Go.
	hundred := decimal.NewFromInt(100)
	grossPence := grossDecimal.Mul(hundred).IntPart() // IntPart() returns int64; cast below
	grossMinor := int32(grossPence)

	// Default currency to GBP if not provided
	currency := req.CurrencyCode
	if currency == "" {
		currency = "GBP"
	}

	// -------------------------------------------------------------------------
	// Step 3: Resolve VAT.
	// The entered gross is the VAT-inclusive total. Fixed-ratio rates EXTRACT the
	// VAT from it (any client amount is ignored); non-fixed rates take the
	// client-supplied vat_amount. See resolveVAT.
	// -------------------------------------------------------------------------
	vat, err := s.resolveVAT(ctx, authOrgID, grossMinor, req.VATRateID, req.VATAmount)
	if err != nil {
		return nil, err
	}

	// -------------------------------------------------------------------------
	// Step 4: Build the database parameters struct
	//
	// expenses.CreateExpenseParams is generated by sqlc from the query in
	// query.sql. Every field here maps to a $1, $2, ... parameter in the SQL.
	// The field names and types come from the column definitions in schema.sql.
	// -------------------------------------------------------------------------
	params := expenses.CreateExpenseParams{
		OrganisationID:        organisationUUID,
		UserID:                claimantUUID, // the claimant (may be someone else for admin-on-behalf entry)
		CreatedByUserID:       authUserID,   // always the caller — audit of who actually recorded it
		CategoryID:            categoryUUID,
		DatedOn:               pgDateFromTime(datedOn), // helper below converts time.Time → pgx date
		Description:           req.Description,
		Currency:              currency,
		NativeCurrency:        "GBP", // hardcoded for UK MVP
		GrossValueMinor:       grossMinor,
		NativeGrossValueMinor: grossMinor, // same as gross for GBP; FX conversion added later
		VatRateID:             vat.RateID,
		VatRateBps:            vat.RateBps,
		VatValueMinor:         vat.ValueMinor,
		NativeVatValueMinor:   vat.ValueMinor, // GBP: native VAT == expense-currency VAT
		VatStatus:             "TAXABLE",      // TODO: derive EXEMPT/OUT_OF_SCOPE from the rate
		EcStatus:              "UK_NON_EC",    // correct default for post-2021 UK expenses

		// Optional string fields: convert *string to pgtype.Text
		// pgNullText is a small helper defined at the bottom of this file.
		// It returns a pgtype.Text with Valid=false when the pointer is nil,
		// which maps to NULL in PostgreSQL.
		ReceiptReference:  pgNullText(req.ReceiptReference),
		SupplierName:      pgNullText(req.SupplierName),
		SupplierVatNumber: pgNullText(req.SupplierVATNo),
		InvoiceNumber:     pgNullText(req.InvoiceNumber),

		// Project rebilling
		ProjectID:    pgNullUUID(req.ProjectID),
		RebillType:   pgNullText(req.RebillType),
		RebillFactor: pgNullNumeric(req.RebillFactor),
	}

	// -------------------------------------------------------------------------
	// Step 5: Write to the database inside a transaction
	//
	// We use withTransaction so that the expense INSERT and the audit INSERT
	// are atomic. If either fails, both are rolled back.
	// -------------------------------------------------------------------------
	var created expenses.Expense // will hold the row returned by RETURNING *

	err = s.withTransaction(ctx, func(qtx *expenses.Queries) error {
		// Write 1: create the expense record
		row, err := qtx.CreateExpense(ctx, params)
		if err != nil {
			return fmt.Errorf("insert expense: %w", err)
		}
		created = row

		// Write 2: append to the audit log
		// The audit log records who did what and when. Even for a CREATE we
		// write a row so there's a complete history from birth.
		// We pass nil for old_data (nothing existed before) and the new row
		// serialised as JSON for new_data.
		// TODO: implement CreateAuditEntry query and call it here.
		// For now this is a clear marker of where it belongs.
		_ = created // used above; keeping variable in scope for audit TODO

		return nil
	})
	if err != nil {
		return nil, fmt.Errorf("create expense: %w", err)
	}

	// -------------------------------------------------------------------------
	// Step 6: Format and return the response
	// -------------------------------------------------------------------------
	return expenseToResponse(created), nil
}

// =============================================================================
// UPDATEEXPENSE
// =============================================================================

// UpdateExpense performs a full update of an existing expense's editable fields
// (PUT semantics). Authorisation mirrors GetExpenseDetail: the caller must own
// the expense, or be an owner/admin of the organisation. The expense must also
// still be editable — only DRAFT or REJECTED expenses may be changed.
//
// The fetch, the ownership/status checks, and the UPDATE all run inside one
// transaction so the row can't change status between the check and the write.
func (s *ExpenseService) UpdateExpense(
	ctx context.Context,
	authUserID uuid.UUID,
	authOrgID uuid.UUID,
	id string,
	req UpdateExpenseRequest,
) (*ExpenseResponse, error) {
	expenseUUID, err := uuid.Parse(id)
	if err != nil {
		return nil, ErrValidation("id is not a valid UUID", err)
	}

	// Confirm the caller is an active member and get their role.
	role, err := s.authorize(ctx, authUserID, authOrgID)
	if err != nil {
		return nil, err
	}

	// Parse + convert the editable fields — same conversions as CreateExpense.
	categoryUUID, err := uuid.Parse(req.CategoryID)
	if err != nil {
		return nil, ErrValidation("category_id is not a valid UUID", err)
	}
	datedOn, err := time.Parse("2006-01-02", req.DatedOn)
	if err != nil {
		return nil, ErrValidation("dated_on must be a valid date in YYYY-MM-DD format", err)
	}
	grossDecimal, err := decimal.NewFromString(req.GrossValuePounds)
	if err != nil {
		return nil, ErrValidation(fmt.Sprintf("gross_value %q is not a valid decimal number", req.GrossValuePounds), err)
	}
	grossMinor := int32(grossDecimal.Mul(decimal.NewFromInt(100)).IntPart())

	currency := req.CurrencyCode
	if currency == "" {
		currency = "GBP"
	}

	// Resolve VAT (extract from the inclusive total for fixed-ratio, accept the
	// client amount for custom) — same rule as CreateExpense, via resolveVAT.
	vat, err := s.resolveVAT(ctx, authOrgID, grossMinor, req.VATRateID, req.VATAmount)
	if err != nil {
		return nil, err
	}

	// Fetch + authorise + status-check + update inside one transaction so the row
	// can't change between the checks and the write (avoids a TOCTOU gap).
	var updated expenses.Expense
	err = s.withTransaction(ctx, func(qtx *expenses.Queries) error {
		existing, err := qtx.GetExpense(ctx, expenses.GetExpenseParams{
			ID:             expenseUUID,
			OrganisationID: authOrgID,
		})
		if err != nil {
			if errors.Is(err, pgx.ErrNoRows) {
				return ErrNotFound("expense", id)
			}
			return ErrInternal(err)
		}

		// Ownership: own expense, or owner/admin of the org (mirrors GetExpenseDetail).
		if existing.UserID != authUserID && !isOrgAdmin(role) {
			return ErrForbidden("you do not have access to this expense")
		}

		// Editable only while DRAFT or REJECTED.
		if existing.Status != StatusDraft && existing.Status != StatusRejected {
			return ErrConflict("expense can only be edited while it is in DRAFT or REJECTED status")
		}

		updated, err = qtx.UpdateExpense(ctx, expenses.UpdateExpenseParams{
			ID:                    expenseUUID,
			OrganisationID:        authOrgID,
			CategoryID:            categoryUUID,
			DatedOn:               pgDateFromTime(datedOn),
			Description:           req.Description,
			Currency:              currency,
			NativeCurrency:        "GBP",
			GrossValueMinor:       grossMinor,
			NativeGrossValueMinor: grossMinor,
			VatRateID:             vat.RateID,
			VatRateBps:            vat.RateBps,
			VatValueMinor:         vat.ValueMinor,
			NativeVatValueMinor:   vat.ValueMinor, // GBP: native VAT == expense-currency VAT
			VatStatus:             "TAXABLE",
			EcStatus:              "UK_NON_EC",
			ReceiptReference:      pgNullText(req.ReceiptReference),
			SupplierName:          pgNullText(req.SupplierName),
			SupplierVatNumber:     pgNullText(req.SupplierVATNo),
			InvoiceNumber:         pgNullText(req.InvoiceNumber),
			ProjectID:             pgNullUUID(req.ProjectID),
			RebillType:            pgNullText(req.RebillType),
			RebillFactor:          pgNullNumeric(req.RebillFactor),
		})
		if err != nil {
			return ErrInternal(err)
		}
		return nil
	})
	if err != nil {
		return nil, err
	}

	return expenseToResponse(updated), nil
}

// =============================================================================
// DELETEEXPENSE
// =============================================================================

// DeleteExpense soft-deletes an expense (sets deleted_at) so it disappears from
// every list and the review inbox while the row is retained for audit. The
// motivating case is the frontend removing an abandoned Smart Upload capture, but
// it works for any deletable expense.
//
// Authorisation mirrors UpdateExpense: the caller must own the expense, or be an
// owner/admin of the organisation. Only DRAFT or REJECTED expenses may be deleted
// — once an expense has entered the approval workflow (SUBMITTED and beyond) it is
// a financial record that must not simply vanish.
//
// The fetch, the ownership/status checks, and the soft-delete all run inside one
// transaction so the row can't change status between the check and the write.
func (s *ExpenseService) DeleteExpense(
	ctx context.Context,
	authUserID uuid.UUID,
	authOrgID uuid.UUID,
	id string,
) error {
	expenseUUID, err := uuid.Parse(id)
	if err != nil {
		return ErrValidation("id is not a valid UUID", err)
	}

	// Confirm the caller is an active member and get their role.
	role, err := s.authorize(ctx, authUserID, authOrgID)
	if err != nil {
		return err
	}

	return s.withTransaction(ctx, func(qtx *expenses.Queries) error {
		existing, err := qtx.GetExpense(ctx, expenses.GetExpenseParams{
			ID:             expenseUUID,
			OrganisationID: authOrgID,
		})
		if err != nil {
			// No live row for this id in the org — also covers an already-deleted
			// expense, since GetExpense filters deleted_at IS NULL → 404.
			if errors.Is(err, pgx.ErrNoRows) {
				return ErrNotFound("expense", id)
			}
			return ErrInternal(err)
		}

		// Ownership: own expense, or owner/admin of the org (mirrors UpdateExpense).
		if existing.UserID != authUserID && !isOrgAdmin(role) {
			return ErrForbidden("you do not have access to this expense")
		}

		// Deletable only while DRAFT or REJECTED — never once it has entered the
		// approval workflow.
		if existing.Status != StatusDraft && existing.Status != StatusRejected {
			return ErrConflict("expense can only be deleted while it is in DRAFT or REJECTED status")
		}

		if err := qtx.SoftDeleteExpense(ctx, expenses.SoftDeleteExpenseParams{
			ID:             expenseUUID,
			OrganisationID: authOrgID,
		}); err != nil {
			return ErrInternal(err)
		}
		return nil
	})
}

// =============================================================================
// GETEXPENSE
// =============================================================================

// GetExpenseDetail fetches one expense with all its joined detail (category,
// VAT, FX, mileage) from the v_expenses_full view, scoped to an organisation.
// Single read — no transaction needed.
func (s *ExpenseService) GetExpenseDetail(
	ctx context.Context,
	authUserID uuid.UUID,
	authOrgID uuid.UUID,
	id string,
) (*ExpenseDetailResponse, error) {
	expenseUUID, err := uuid.Parse(id)
	if err != nil {
		return nil, ErrValidation("id is not a valid UUID", err)
	}

	// Confirm the caller is an active member and get their role.
	role, err := s.authorize(ctx, authUserID, authOrgID)
	if err != nil {
		return nil, err
	}

	// v_expenses_full joins the category (and mileage) so one read returns far
	// more than the lean list response — category name, VAT rate/status, FX, etc.
	row, err := s.queries.GetExpenseWithDetails(ctx, expenses.GetExpenseWithDetailsParams{
		ID:             expenseUUID,
		OrganisationID: authOrgID,
	})
	if err != nil {
		// No row for this id within the org → 404.
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, ErrNotFound("expense", id)
		}
		return nil, ErrInternal(err)
	}

	// Ownership: a user may read only their own expense, unless they are an
	// owner/admin of the organisation (who may read all).
	if row.UserID != authUserID && !isOrgAdmin(role) {
		return nil, ErrForbidden("you do not have access to this expense")
	}

	// Map the detail row, then attach the file list. The Smart Upload frontend
	// polls the primary attachment's ocr_status here to know when OCR has filled
	// the form, so the attachments must travel with the detail response.
	resp := expenseDetailToResponse(row)
	atts, err := attachmentResponsesFor(ctx, s.queries, expenseUUID)
	if err != nil {
		return nil, err
	}
	resp.Attachments = atts
	return resp, nil
}

// =============================================================================
// LISTEXPENSES
// =============================================================================

// ListExpenses returns the expenses the caller is allowed to see:
//   - owner/admin: every expense in the organisation
//   - everyone else: only their own expenses
func (s *ExpenseService) ListExpenses(
	ctx context.Context,
	authUserID uuid.UUID,
	authOrgID uuid.UUID,
) ([]*ExpenseResponse, error) {
	role, err := s.authorize(ctx, authUserID, authOrgID)
	if err != nil {
		return nil, err
	}

	var rows []expenses.Expense
	if isOrgAdmin(role) {
		rows, err = s.queries.ListExpenses(ctx, authOrgID)
	} else {
		rows, err = s.queries.ListExpensesByUser(ctx, expenses.ListExpensesByUserParams{
			OrganisationID: authOrgID,
			UserID:         authUserID,
		})
	}
	if err != nil {
		return nil, ErrInternal(err)
	}

	out := make([]*ExpenseResponse, 0, len(rows))
	for _, row := range rows {
		out = append(out, expenseToResponse(row))
	}
	return out, nil
}

// =============================================================================
// LISTINBOX (Smart Upload review queue)
// =============================================================================

// ListInbox returns the captured expenses awaiting human review (needs_review=
// TRUE) — the Smart Upload inbox. Like ListExpenses, owners/admins see the whole
// organisation's inbox; everyone else sees only the captures they created. The
// query is org-scoped for tenant isolation; the per-user filter applies the same
// ownership rule used elsewhere.
func (s *ExpenseService) ListInbox(
	ctx context.Context,
	authUserID uuid.UUID,
	authOrgID uuid.UUID,
) ([]*ExpenseResponse, error) {
	role, err := s.authorize(ctx, authUserID, authOrgID)
	if err != nil {
		return nil, err
	}

	rows, err := s.queries.ListExpensesNeedingReview(ctx, authOrgID)
	if err != nil {
		return nil, ErrInternal(err)
	}

	admin := isOrgAdmin(role)
	out := make([]*ExpenseResponse, 0, len(rows))
	for _, row := range rows {
		if admin || row.UserID == authUserID {
			out = append(out, expenseToResponse(row))
		}
	}
	return out, nil
}

// =============================================================================
// LISTEXPENSECATEGORIES
// =============================================================================

// ListExpenseCategories returns the active expense categories for the caller's
// organisation (for the category picker). Authorisation: any ACTIVE member of
// the organisation may read its categories — they are shared reference data
// needed to file expenses — so we authorise on membership, not role. The org
// scope comes from the authenticated token, never the request body.
func (s *ExpenseService) ListExpenseCategories(
	ctx context.Context,
	authUserID uuid.UUID,
	authOrgID uuid.UUID,
) ([]*ExpenseCategoryResponse, error) {
	if _, err := s.authorize(ctx, authUserID, authOrgID); err != nil {
		return nil, err
	}

	rows, err := s.queries.ListExpenseCategories(ctx, authOrgID)
	if err != nil {
		return nil, ErrInternal(err)
	}

	out := make([]*ExpenseCategoryResponse, 0, len(rows))
	for _, row := range rows {
		out = append(out, expenseCategoryToResponse(row))
	}
	return out, nil
}

// =============================================================================
// LISTVATRATES
// =============================================================================

// ListVATRates returns the VAT rates valid TODAY for the caller's organisation's
// country (for the VAT rate picker).
//
// VAT rates are GLOBAL reference data keyed by country_code, not per-organisation.
// The country is resolved from the caller's organisation (via the auth token),
// never from the request — so a client cannot read another country's rates by
// passing a different code. This mirrors how ListExpenseCategories scopes to the
// caller's org.
//
// Authorisation: any ACTIVE member of the organisation may read the VAT rates —
// they are shared reference data needed to file expenses — so we authorise on
// membership, not role.
func (s *ExpenseService) ListVATRates(
	ctx context.Context,
	authUserID uuid.UUID,
	authOrgID uuid.UUID,
) ([]*VATRateResponse, error) {
	if _, err := s.authorize(ctx, authUserID, authOrgID); err != nil {
		return nil, err
	}

	// Resolve the organisation's country. The token carries only the org id; the
	// country_code lives on the organisation row (auth domain).
	org, err := s.authQueries.GetOrganisation(ctx, authOrgID)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, ErrNotFound("organisation", authOrgID.String())
		}
		return nil, ErrInternal(err)
	}

	// ListVatRatesByCountry already filters to rates whose effective window covers
	// today, so the picker only ever shows currently-applicable rates.
	rows, err := s.queries.ListVatRatesByCountry(ctx, org.CountryCode)
	if err != nil {
		return nil, ErrInternal(err)
	}

	out := make([]*VATRateResponse, 0, len(rows))
	for _, row := range rows {
		out = append(out, vatRateToResponse(row))
	}
	return out, nil
}

// =============================================================================
// RESPONSE FORMATTER
// =============================================================================

// expenseToResponse converts a database Expense row (pence integers, UUIDs,
// pgx types) into the API response shape (pound strings, plain strings).
//
// This is the inverse of the conversion we did in CreateExpense.
// It lives here in the service because the service owns the mapping between
// database representation and API representation.
func expenseToResponse(e expenses.Expense) *ExpenseResponse {
	// Convert integer pence back to a decimal pound string.
	// 4250 pence → decimal(4250) ÷ 100 → decimal(42.50) → "42.50"
	grossPounds := decimal.NewFromInt(int64(e.GrossValueMinor)).
		Div(decimal.NewFromInt(100)).
		StringFixed(2) // StringFixed(2) always gives 2 decimal places: "42.50" not "42.5"

	nativeGrossPounds := decimal.NewFromInt(int64(e.NativeGrossValueMinor)).
		Div(decimal.NewFromInt(100)).
		StringFixed(2)

	vatPounds := decimal.NewFromInt(int64(e.VatValueMinor)).
		Div(decimal.NewFromInt(100)).
		StringFixed(2)

	return &ExpenseResponse{
		ID:               e.ID.String(),
		OrganisationID:   e.OrganisationID.String(),
		UserID:           e.UserID.String(),
		CategoryID:       e.CategoryID.String(),
		DatedOn:          e.DatedOn.Time.Format("2006-01-02"),
		Description:      e.Description,
		Currency:         e.Currency,
		GrossValue:       grossPounds,
		NativeGrossValue: nativeGrossPounds,
		VATValue:         vatPounds,
		Status:           e.Status,
		NeedsReview:      e.NeedsReview, // TRUE while a Smart Upload capture awaits confirmation
		CreatedAt:        e.CreatedAt.Time.Format(time.RFC3339),
		UpdatedAt:        e.UpdatedAt.Time.Format(time.RFC3339),

		// Optional fields: convert pgtype.Text back to *string
		ReceiptReference:  nullTextToPtr(e.ReceiptReference),
		SupplierName:      nullTextToPtr(e.SupplierName),
		SupplierVATNumber: nullTextToPtr(e.SupplierVatNumber),
		InvoiceNumber:     nullTextToPtr(e.InvoiceNumber),
	}
}

// expenseCategoryToResponse maps a generated ExpenseCategory row to the API
// shape (UUID → string, nullable pgtype.Text → *string via nullTextToPtr).
func expenseCategoryToResponse(c expenses.ExpenseCategory) *ExpenseCategoryResponse {
	return &ExpenseCategoryResponse{
		ID:              c.ID.String(),
		NominalCode:     c.NominalCode,
		Name:            c.Name,
		CategoryGroup:   nullTextToPtr(c.CategoryGroup),
		Description:     nullTextToPtr(c.Description),
		IsMileage:       c.IsMileage,
		IsCapitalAsset:  c.IsCapitalAsset,
		IsStockPurchase: c.IsStockPurchase,
	}
}

// vatRateToResponse maps a ListVatRatesByCountryRow to the API shape. The rate
// is exposed both as canonical basis points (for exact client-side computation)
// and as a human display string ("20%").
func vatRateToResponse(r expenses.ListVatRatesByCountryRow) *VATRateResponse {
	return &VATRateResponse{
		ID:           r.ID.String(),
		Name:         r.Name,
		RateBps:      r.RateBps,
		Rate:         bpsToPercent(r.RateBps),
		IsFixedRatio: r.IsFixedRatio,
	}
}

// expenseDetailToResponse maps a rich v_expenses_full row to the detail DTO.
// Money minors → pound strings; VAT basis points → a percentage; nullable
// NUMERIC / timestamp / UUID columns → optional strings (nil when NULL).
func expenseDetailToResponse(e expenses.VExpensesFull) *ExpenseDetailResponse {
	return &ExpenseDetailResponse{
		ID:          e.ID.String(),
		UserID:      e.UserID.String(), // claimant — lets the edit form prefill the "on behalf of" picker
		Status:      e.Status,
		DatedOn:     e.DatedOn.Time.Format("2006-01-02"),
		Description: e.Description,

		CategoryName:        e.CategoryName,
		CategoryNominalCode: e.CategoryNominalCode,
		CategoryID:          e.CategoryID.String(),

		Currency:   e.Currency,
		GrossValue: minorToPounds(e.GrossValueMinor),

		VATRateID: uuidToStringPtr(e.VatRateID),
		VATRate:   bpsToPercentPtr(e.VatRateBps),
		VATStatus: e.VatStatus,
		VATValue:  minorToPounds(e.VatValueMinor),

		NativeCurrency:   e.NativeCurrency,
		NativeGrossValue: minorToPounds(e.NativeGrossValueMinor),
		NativeVATValue:   minorToPounds(e.NativeVatValueMinor),
		ExchangeRate:     numericToStringPtr(e.ExchangeRate),

		ECStatus: e.EcStatus,

		SupplierName:      nullTextToPtr(e.SupplierName),
		SupplierVATNumber: nullTextToPtr(e.SupplierVatNumber),
		InvoiceNumber:     nullTextToPtr(e.InvoiceNumber),
		ReceiptReference:  nullTextToPtr(e.ReceiptReference),

		ProjectID:    uuidToStringPtr(e.ProjectID),
		RebillType:   nullTextToPtr(e.RebillType),
		RebillFactor: numericToStringPtr(e.RebillFactor),

		SubmittedAt: timestampToStringPtr(e.SubmittedAt),
		ApprovedAt:  timestampToStringPtr(e.ApprovedAt),
		PaidAt:      timestampToStringPtr(e.PaidAt),

		// Capture / OCR. needs_review drives the review inbox; the confidence +
		// processed-at let the detail screen flag a low-confidence capture.
		NeedsReview:    e.NeedsReview,
		OCRConfidence:  numericToStringPtr(e.OcrConfidence),
		OCRProcessedAt: timestampToStringPtr(e.OcrProcessedAt),

		CreatedAt: e.CreatedAt.Time.Format(time.RFC3339),
		UpdatedAt: e.UpdatedAt.Time.Format(time.RFC3339),
	}
}

// =============================================================================
// EXPENSE DETAIL ASSEMBLY (view + attachments)
// =============================================================================

// attachmentResponsesFor loads an expense's attachments and maps them to the API
// shape (primary first — ListExpenseAttachments orders them). The expense itself
// must already have been authorised by the caller.
func attachmentResponsesFor(ctx context.Context, q *expenses.Queries, expenseID uuid.UUID) ([]*AttachmentResponse, error) {
	atts, err := q.ListExpenseAttachments(ctx, expenseID)
	if err != nil {
		return nil, ErrInternal(err)
	}
	out := make([]*AttachmentResponse, 0, len(atts))
	for _, a := range atts {
		out = append(out, attachmentToResponse(a))
	}
	return out, nil
}

// buildExpenseDetail fetches the full detail view + attachments for an expense
// and maps them to the API shape. It performs NO authorisation — callers must
// have already authorised (or, like CaptureFromReceipt, just created the row as
// the caller). Used so the capture flow returns the exact same shape the
// frontend later polls via GET /expenses/:id.
func buildExpenseDetail(ctx context.Context, q *expenses.Queries, orgID, expenseID uuid.UUID) (*ExpenseDetailResponse, error) {
	row, err := q.GetExpenseWithDetails(ctx, expenses.GetExpenseWithDetailsParams{
		ID:             expenseID,
		OrganisationID: orgID,
	})
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, ErrNotFound("expense", expenseID.String())
		}
		return nil, ErrInternal(err)
	}
	resp := expenseDetailToResponse(row)
	atts, err := attachmentResponsesFor(ctx, q, expenseID)
	if err != nil {
		return nil, err
	}
	resp.Attachments = atts
	return resp, nil
}

// minorToPounds converts integer pence to a 2dp pound string ("4250" → "42.50").
func minorToPounds(minor int32) string {
	return decimal.NewFromInt(int64(minor)).Div(decimal.NewFromInt(100)).StringFixed(2)
}

// bpsToPercent renders a VAT rate in basis points as a percentage string:
// 2000 → "20%", 1750 → "17.5%", 0 → "0%".
func bpsToPercent(bps int32) string {
	return decimal.NewFromInt(int64(bps)).Div(decimal.NewFromInt(100)).String() + "%"
}

// bpsToPercentPtr turns a nullable VAT rate in basis points into a percentage
// string (2000 → "20%", 1750 → "17.5%"); nil when no rate is set.
func bpsToPercentPtr(b pgtype.Int4) *string {
	if !b.Valid {
		return nil
	}
	s := bpsToPercent(b.Int32)
	return &s
}

// numericToStringPtr renders a nullable NUMERIC (exchange_rate, rebill_factor)
// as a display string; nil when NULL.
func numericToStringPtr(n pgtype.Numeric) *string {
	if !n.Valid {
		return nil
	}
	v, err := n.Value()
	if err != nil {
		return nil
	}
	if s, ok := v.(string); ok {
		return &s
	}
	s := fmt.Sprintf("%v", v)
	return &s
}

// timestampToStringPtr renders a nullable timestamp as RFC3339; nil when NULL.
func timestampToStringPtr(t pgtype.Timestamptz) *string {
	if !t.Valid {
		return nil
	}
	s := t.Time.Format(time.RFC3339)
	return &s
}

// uuidToStringPtr renders a nullable UUID as a string; nil when NULL.
func uuidToStringPtr(u pgtype.UUID) *string {
	if !u.Valid {
		return nil
	}
	id, err := uuid.FromBytes(u.Bytes[:])
	if err != nil {
		return nil
	}
	s := id.String()
	return &s
}

// =============================================================================
// PGX TYPE HELPERS
//
// pgx uses its own types for nullable values instead of Go's standard
// sql.NullString etc. These tiny helpers convert between plain Go types
// and pgx types so the service code reads cleanly without pgtype.* noise
// everywhere.
//
// pgtype.Text has two fields:
//   String string  — the actual value
//   Valid  bool    — true if the value is non-NULL
//
// When Valid is false, pgx sends NULL to PostgreSQL regardless of String.
// =============================================================================

// pgNullText converts a *string to pgtype.Text.
// nil pointer → NULL in the database.
// non-nil pointer → the string value.
func pgNullText(s *string) pgtype.Text {
	if s == nil {
		return pgtype.Text{Valid: false}
	}
	return pgtype.Text{String: *s, Valid: true}
}

// nullTextToPtr is the reverse: pgtype.Text → *string.
// Invalid (NULL) → nil. Valid → pointer to string.
func nullTextToPtr(t pgtype.Text) *string {
	if !t.Valid {
		return nil
	}
	return &t.String
}

// pgNullInt32 wraps an int32 in pgtype.Int4.
// Used for nullable integer columns (e.g. vat_rate_bps when no VAT).
func pgNullInt32(n int32) pgtype.Int4 {
	return pgtype.Int4{Int32: n, Valid: n != 0}
}

// pgNullUUID converts a *string UUID to pgtype.UUID.
// If the string is nil or fails to parse, returns an invalid (NULL) UUID.
func pgNullUUID(s *string) pgtype.UUID {
	if s == nil {
		return pgtype.UUID{Valid: false}
	}
	id, err := uuid.Parse(*s)
	if err != nil {
		return pgtype.UUID{Valid: false}
	}
	var b [16]byte
	copy(b[:], id[:])
	return pgtype.UUID{Bytes: b, Valid: true}
}

// pgNullNumeric converts a *string decimal to pgtype.Numeric.
// Used for rebill_factor which is stored as NUMERIC in PostgreSQL.
// Returns invalid if the string is nil or not a valid decimal.
func pgNullNumeric(s *string) pgtype.Numeric {
	if s == nil {
		return pgtype.Numeric{Valid: false}
	}
	var n pgtype.Numeric
	if err := n.Scan(*s); err != nil {
		return pgtype.Numeric{Valid: false}
	}
	return n
}

// pgDateFromTime converts a time.Time to pgtype.Date.
// pgx represents DATE columns as pgtype.Date, not time.Time directly.
func pgDateFromTime(t time.Time) pgtype.Date {
	return pgtype.Date{Time: t, Valid: true}
}
