package main

// member_service.go
// =============================================================================
// MemberService — the business logic layer for organisation members.
//
// A "member" is a user's membership in an organisation (the row in
// organisation_memberships joined to their users row). This is the first service
// in the auth/membership domain; until now that domain only had auth_handler.go
// (login). It is structured exactly like ContactService / ExpenseService:
//
//   HTTP handler (server.go)
//     ↓
//   MemberService (this file)
//     ↓
//   auth.Querier (db/auth — generated by sqlc)
//     ↓
//   PostgreSQL
//
// The one behavioural difference from the "any active member" services: listing
// members is privileged — only an owner or admin of the organisation may see it
// (it backs a future "Team / Manage users" screen). The gate is on the CALLER,
// not on which members are returned.
//
// It reuses helpers already defined in expense_service.go (same `main` package):
// isOrgAdmin for the owner/admin check, nullTextToPtr / timestampToStringPtr for
// the nullable columns, and the AppError constructors from errors.go. Nothing new
// to add — this is a thin, read-only service with no money and no transaction.
// =============================================================================

import (
	"context"
	"errors"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"

	auth "github.com/operationfb/accounting-saas/db/auth"
)

// MemberService holds only the auth query set: listing members is a single
// read-only query, so there is no pool/transaction to keep (unlike the services
// that write across tables).
type MemberService struct {
	authQueries auth.Querier
}

// NewMemberService is the constructor, called once in main.go. authQueries is the
// same auth.Querier already shared with the other services.
func NewMemberService(authQueries auth.Querier) *MemberService {
	return &MemberService{authQueries: authQueries}
}

// =============================================================================
// AUTHORIZATION
// =============================================================================

// authorize confirms the caller is an ACTIVE member of the organisation and
// returns their role. Mirrors ExpenseService.authorize / ContactService.authorize
// (deliberately kept per-service for consistency; a shared helper is a future
// DRY-up). Non-members and deactivated members are refused (403). The returned
// role lets ListMembers gate the list to owners/admins.
func (s *MemberService) authorize(ctx context.Context, userID, orgID uuid.UUID) (auth.OrganisationRole, error) {
	m, err := s.authQueries.GetMembership(ctx, auth.GetMembershipParams{
		OrganisationID: orgID,
		UserID:         userID,
	})
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return "", ErrForbidden("you are not a member of this organisation")
		}
		return "", ErrInternal(err)
	}
	if m.Status != "active" {
		return "", ErrForbidden("your organisation membership is not active")
	}
	return m.Role, nil
}

// =============================================================================
// LIST
// =============================================================================

// ListMembers returns every member of the caller's organisation, restricted to
// callers who are an owner or admin. The organisation is taken from the
// authenticated token (authOrgID), never a request param, so a caller can only
// ever list their own org's members.
//
// The underlying query returns members of ALL statuses (active / invited /
// suspended / deactivated) as long as the user is not soft-deleted; the Status
// field on each row lets the UI distinguish them.
func (s *MemberService) ListMembers(
	ctx context.Context,
	authUserID uuid.UUID,
	authOrgID uuid.UUID,
) ([]*MemberResponse, error) {
	// Step 1: the caller must be an active member, and specifically an owner/admin.
	role, err := s.authorize(ctx, authUserID, authOrgID)
	if err != nil {
		return nil, err
	}
	if !isOrgAdmin(role) {
		return nil, ErrForbidden("only owners and admins can view the members list")
	}

	// Step 2: fetch the org's members (org-scoped by the query's WHERE clause).
	rows, err := s.authQueries.ListMembersByOrganisation(ctx, authOrgID)
	if err != nil {
		return nil, ErrInternal(err)
	}

	// Step 3: convert the DB rows into the API response shape.
	out := make([]*MemberResponse, 0, len(rows))
	for _, r := range rows {
		out = append(out, memberToResponse(r))
	}
	return out, nil
}

// =============================================================================
// RESPONSE FORMATTER
// =============================================================================

// memberToResponse converts a database row (pgx types, UUIDs, enum) into the API
// response shape (plain/optional strings). MemberSince comes from the membership's
// NOT NULL created_at, so it formats directly; AvatarUrl and LastLoginAt are
// nullable and use the shared null-aware helpers from expense_service.go.
func memberToResponse(r auth.ListMembersByOrganisationRow) *MemberResponse {
	return &MemberResponse{
		MembershipID: r.MembershipID.String(),
		UserID:       r.UserID.String(),
		Email:        r.Email,
		FirstName:    r.FirstName,
		LastName:     r.LastName,
		Role:         string(r.Role),
		Status:       r.Status,
		AvatarURL:    nullTextToPtr(r.AvatarUrl),
		MemberSince:  r.MemberSince.Time.Format(time.RFC3339),
		LastLoginAt:  timestampToStringPtr(r.LastLoginAt),
	}
}
