package main

// organisation_service.go
// =============================================================================
// OrganisationService — the business logic layer for an organisation's own
// "Company Details" (the settings screen modelled on FreeAgent's Company
// Details: company type, name, registered address, UK tax references, invoice
// contact details, and a short business profile).
//
// All of this data lives on the organisations table (db/schema/auth_schema.sql),
// so this service is a thin layer over the existing auth queries — exactly like
// MemberService:
//
//   HTTP handler (server.go)
//     ↓
//   OrganisationService (this file)
//     ↓
//   auth.Querier (db/auth — generated by sqlc)
//     ↓
//   PostgreSQL
//
// There is always exactly ONE organisation in scope — the caller's, taken from
// the bearer token (authOrgID), never a path/body param — so there is no list
// and no id to pass. A caller can therefore only ever read or edit their OWN
// organisation; multi-tenant isolation is inherent.
//
// Access rules:
//   - GET  : any ACTIVE member may view the company details.
//   - PUT  : only an OWNER or ADMIN may edit them (isOrgAdmin).
//
// It reuses helpers already defined in the package: the authorize/membership
// pattern from MemberService, isOrgAdmin (expense_service.go), normaliseCountryCode
// (contact_service.go), pgNullText / nullTextToPtr (expense_service.go), and the
// AppError constructors (errors.go). There is no money here, so no pence/decimal
// conversion.
// =============================================================================

import (
	"context"
	"errors"
	"strings"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"

	auth "github.com/operationfb/accounting-saas/db/auth"
)

// validCompanyType is the set company_type is restricted to. It mirrors the CHECK
// constraint in auth_schema.sql and the form's "Company type" dropdown. Codes are
// snake_case; the frontend maps them to labels ("Limited Company", etc.).
var validCompanyType = map[string]bool{
	"limited":     true, // limited company
	"sole_trader": true,
	"partnership": true,
	"landlord":    true, // unincorporated landlord
	"corporation": true,
}

// OrganisationService holds only the auth query set: reading and updating the
// organisation are single-table, single-statement operations, so there is no
// pool/transaction to keep (same shape as MemberService).
type OrganisationService struct {
	authQueries auth.Querier
}

// NewOrganisationService is the constructor, called once in main.go. authQueries
// is the same auth.Querier already shared with the other services.
func NewOrganisationService(authQueries auth.Querier) *OrganisationService {
	return &OrganisationService{authQueries: authQueries}
}

// =============================================================================
// AUTHORIZATION
// =============================================================================

// authorize confirms the caller is an ACTIVE member of the organisation and
// returns their role. Mirrors MemberService.authorize / ContactService.authorize
// (kept per-service for consistency). Non-members and deactivated members are
// refused (403); the returned role lets UpdateOrganisation gate editing to
// owners/admins.
func (s *OrganisationService) authorize(ctx context.Context, userID, orgID uuid.UUID) (auth.OrganisationRole, error) {
	m, err := s.authQueries.GetMembership(ctx, auth.GetMembershipParams{
		OrganisationID: orgID,
		UserID:         userID,
	})
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return "", ErrForbidden("you are not a member of this organisation")
		}
		return "", ErrInternal(err)
	}
	if m.Status != "active" {
		return "", ErrForbidden("your organisation membership is not active")
	}
	return m.Role, nil
}

// =============================================================================
// GET
// =============================================================================

// GetOrganisation returns the caller's organisation company details. Any active
// member may read them. The organisation is taken from the authenticated token,
// so a caller can only ever read their own org.
func (s *OrganisationService) GetOrganisation(
	ctx context.Context,
	authUserID uuid.UUID,
	authOrgID uuid.UUID,
) (*OrganisationDetailsResponse, error) {
	if _, err := s.authorize(ctx, authUserID, authOrgID); err != nil {
		return nil, err
	}

	org, err := s.authQueries.GetOrganisation(ctx, authOrgID)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, ErrNotFound("organisation", authOrgID.String())
		}
		return nil, ErrInternal(err)
	}
	return organisationToResponse(org), nil
}

// =============================================================================
// UPDATE
// =============================================================================

// UpdateOrganisation updates the company-details fields (PUT semantics). Only an
// owner or admin may edit. The organisation is taken from the token, so it always
// targets the caller's own org.
//
// This is a read-modify-write: a few organisation columns are NOT part of the
// Company Details form (slug, native_currency, timezone, and — until VAT is added
// to the form — vrn). We fetch the existing row first and pass those through
// unchanged so a PUT from this form can't wipe them. A future "general settings"
// or "VAT" screen will set them via their own request fields.
func (s *OrganisationService) UpdateOrganisation(
	ctx context.Context,
	authUserID uuid.UUID,
	authOrgID uuid.UUID,
	req UpdateOrganisationRequest,
) (*OrganisationDetailsResponse, error) {
	role, err := s.authorize(ctx, authUserID, authOrgID)
	if err != nil {
		return nil, err
	}
	if !isOrgAdmin(role) {
		return nil, ErrForbidden("only owners and admins can edit company details")
	}

	// Validate / normalise. name is the org's NOT NULL primary name, so it is
	// required (the form's "Company name"). The binding `required` tag catches a
	// missing value at the HTTP edge; this re-check covers direct/test callers.
	name := strings.TrimSpace(req.Name)
	if name == "" {
		return nil, ErrValidation("name is required", nil)
	}
	countryCode, err := normaliseCountryCode(req.CountryCode)
	if err != nil {
		return nil, err
	}
	companyType, err := normaliseCompanyType(req.CompanyType)
	if err != nil {
		return nil, err
	}

	// Read first so we can preserve the fields this form does not edit (and to
	// 404 if the org was soft-deleted).
	existing, err := s.authQueries.GetOrganisation(ctx, authOrgID)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, ErrNotFound("organisation", authOrgID.String())
		}
		return nil, ErrInternal(err)
	}

	updated, err := s.authQueries.UpdateOrganisation(ctx, auth.UpdateOrganisationParams{
		ID:   authOrgID,
		Name: name,

		// Preserved — not on the Company Details form.
		Slug:           existing.Slug,
		Vrn:            existing.Vrn,
		NativeCurrency: existing.NativeCurrency,
		Timezone:       existing.Timezone,

		// Identity & UK company/tax references.
		LegalName:               pgNullText(req.LegalName),
		CompanyType:             pgNullText(companyType),
		CompaniesHouseNumber:    pgNullText(req.CompaniesHouseNumber),
		Utr:                     pgNullText(req.Utr), // "Corporation Tax Reference"
		PayeReference:           pgNullText(req.PayeReference),
		AccountsOfficeReference: pgNullText(req.AccountsOfficeReference),

		// Structured address.
		AddressLine1: pgNullText(req.AddressLine1),
		AddressLine2: pgNullText(req.AddressLine2),
		AddressLine3: pgNullText(req.AddressLine3),
		Town:         pgNullText(req.Town),
		Region:       pgNullText(req.Region),
		Postcode:     pgNullText(req.Postcode),
		CountryCode:  countryCode,

		// Invoice contact details + business profile.
		BusinessPhone:       pgNullText(req.BusinessPhone),
		ContactEmail:        pgNullText(req.ContactEmail),
		ContactPhone:        pgNullText(req.ContactPhone),
		Website:             pgNullText(req.Website),
		BusinessCategory:    pgNullText(req.BusinessCategory),
		BusinessDescription: pgNullText(req.BusinessDescription),
	})
	if err != nil {
		// The row was live a moment ago; ErrNoRows means it was soft-deleted in between.
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, ErrNotFound("organisation", authOrgID.String())
		}
		return nil, ErrInternal(err)
	}
	return organisationToResponse(updated), nil
}

// =============================================================================
// VALIDATION / NORMALISATION HELPERS
// =============================================================================

// normaliseCompanyType trims + lower-cases the company type and treats a nil or
// blank value as NULL (no type set). Anything else must be in the allowed set.
// Defence-in-depth behind the handler's `oneof` binding and the DB CHECK, so the
// service is correct even when called directly (e.g. from a test).
func normaliseCompanyType(raw *string) (*string, error) {
	if raw == nil {
		return nil, nil
	}
	v := strings.ToLower(strings.TrimSpace(*raw))
	if v == "" {
		return nil, nil
	}
	if !validCompanyType[v] {
		return nil, ErrValidation("company_type must be one of limited, sole_trader, partnership, landlord, corporation", nil)
	}
	return &v, nil
}

// =============================================================================
// RESPONSE FORMATTER
// =============================================================================

// organisationToResponse converts a database Organisation row (pgx types, UUIDs)
// into the API response shape (plain/optional strings). Nullable columns use the
// shared nullTextToPtr helper from expense_service.go. The legacy free-text
// registered_address column is intentionally NOT exposed (superseded by the
// structured address). native_currency / timezone / plan are returned read-only
// for the frontend's convenience even though this screen doesn't edit them.
func organisationToResponse(o auth.Organisation) *OrganisationDetailsResponse {
	return &OrganisationDetailsResponse{
		ID:          o.ID.String(),
		Name:        o.Name,
		Slug:        nullTextToPtr(o.Slug),
		LegalName:   nullTextToPtr(o.LegalName),
		CompanyType: nullTextToPtr(o.CompanyType),

		CompaniesHouseNumber:    nullTextToPtr(o.CompaniesHouseNumber),
		Utr:                     nullTextToPtr(o.Utr),
		Vrn:                     nullTextToPtr(o.Vrn),
		PayeReference:           nullTextToPtr(o.PayeReference),
		AccountsOfficeReference: nullTextToPtr(o.AccountsOfficeReference),

		AddressLine1: nullTextToPtr(o.AddressLine1),
		AddressLine2: nullTextToPtr(o.AddressLine2),
		AddressLine3: nullTextToPtr(o.AddressLine3),
		Town:         nullTextToPtr(o.Town),
		Region:       nullTextToPtr(o.Region),
		Postcode:     nullTextToPtr(o.Postcode),
		CountryCode:  o.CountryCode,

		BusinessPhone:       nullTextToPtr(o.BusinessPhone),
		ContactEmail:        nullTextToPtr(o.ContactEmail),
		ContactPhone:        nullTextToPtr(o.ContactPhone),
		Website:             nullTextToPtr(o.Website),
		BusinessCategory:    nullTextToPtr(o.BusinessCategory),
		BusinessDescription: nullTextToPtr(o.BusinessDescription),

		NativeCurrency: o.NativeCurrency,
		Timezone:       o.Timezone,
		Plan:           o.Plan,
		IsActive:       o.IsActive,
		CreatedAt:      o.CreatedAt.Time.Format(time.RFC3339),
		UpdatedAt:      o.UpdatedAt.Time.Format(time.RFC3339),
	}
}
