package main

// project_service.go
// =============================================================================
// ProjectService — the business logic layer for projects.
//
// A "project" is a billable work unit for a contact. This service follows the
// same pattern as ExpenseService and ContactService: it owns authorisation,
// validation, the mapping between the API shape and the DB shape (pgx types),
// and the calls into the sqlc-generated projects package.
//
//   HTTP handler (server.go)
//     ↓
//   ProjectService (this file)
//     ↓
//   *projects.Queries (db/projects — generated by sqlc)
//     ↓
//   PostgreSQL
//
// Shared money helpers from the money package:
//   money.PoundsToMinor — "100.00" → 10000 pence (int64), rounds half-up
//   money.MinorToPounds — 10000 → "100.00"
//
// Shared helpers from expense_service.go (same package):
//   pgNullText / nullTextToPtr  — nullable text
//
// Shared helpers from contact_service.go (same package):
//   pgInt32FromPtr / nullInt32ToPtr — 0-preserving *int32 ↔ pgtype.Int4
//
// New helpers defined here:
//   hhmmToMinutes / minutesToHHMM   — "8:00" ↔ 480 minutes
//   poundsStringToInt64             — "" → 0 guard around money.PoundsToMinor
// =============================================================================

import (
	"context"
	"errors"
	"fmt"
	"strconv"
	"strings"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/jackc/pgx/v5/pgxpool"

	auth "github.com/operationfb/accounting-saas/db/auth"
	contacts "github.com/operationfb/accounting-saas/db/contacts"
	projects "github.com/operationfb/accounting-saas/db/projects"
	"github.com/operationfb/accounting-saas/money"
)

// validProjectStatus, validBudgetType, validBillingRateUnit mirror the CHECK
// constraints in projects_schema.sql. Validated here so errors come back as
// 422 Validation rather than a raw DB error.
var validProjectStatus = map[string]bool{
	"active":    true,
	"inactive":  true,
	"completed": true,
	"cancelled": true,
}
var validBudgetType = map[string]bool{
	"hours": true,
	"days":  true,
	"money": true,
}
var validBillingRateUnit = map[string]bool{
	"per_hour": true,
	"per_day":  true,
}

// ProjectService holds the connection pool, the projects query set, the auth
// query set (for membership checks), and the contacts query set (to validate
// that a contact_id belongs to the org before linking it to a project).
type ProjectService struct {
	pool           *pgxpool.Pool
	queries        *projects.Queries
	authQueries    auth.Querier
	contactQueries contacts.Querier
}

// NewProjectService is the constructor, called once in main.go.
func NewProjectService(pool *pgxpool.Pool, queries *projects.Queries, authQueries auth.Querier, contactQueries contacts.Querier) *ProjectService {
	return &ProjectService{
		pool:           pool,
		queries:        queries,
		authQueries:    authQueries,
		contactQueries: contactQueries,
	}
}

// =============================================================================
// AUTHORIZATION
// =============================================================================

// authorize confirms the caller is an active member of the organisation and
// returns their role. Mirrors ContactService.authorize — every project
// operation runs this first.
func (s *ProjectService) authorize(ctx context.Context, userID, orgID uuid.UUID) (auth.OrganisationRole, error) {
	m, err := s.authQueries.GetMembership(ctx, auth.GetMembershipParams{
		OrganisationID: orgID,
		UserID:         userID,
	})
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return "", ErrForbidden("you are not a member of this organisation")
		}
		return "", ErrInternal(err)
	}
	if m.Status != "active" {
		return "", ErrForbidden("your organisation membership is not active")
	}
	return m.Role, nil
}

// validateContact confirms that the given contactID exists in the organisation
// and is not soft-deleted. GetContact already filters by org + deleted_at IS
// NULL, so a single query does both checks.
func (s *ProjectService) validateContact(ctx context.Context, contactID, orgID uuid.UUID) error {
	_, err := s.contactQueries.GetContact(ctx, contacts.GetContactParams{
		ID:             contactID,
		OrganisationID: orgID,
	})
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return ErrValidation("contact_id does not exist or does not belong to this organisation", nil)
		}
		return ErrInternal(err)
	}
	return nil
}

// =============================================================================
// CREATE
// =============================================================================

// CreateProject validates + normalises the request and inserts one project.
// Any active org member may create a project (like contacts, they are shared
// business data). Single-table INSERT, no transaction needed.
func (s *ProjectService) CreateProject(
	ctx context.Context,
	authUserID uuid.UUID,
	authOrgID uuid.UUID,
	req CreateProjectRequest,
) (*ProjectResponse, error) {
	if _, err := s.authorize(ctx, authUserID, authOrgID); err != nil {
		return nil, err
	}

	contactID, err := uuid.Parse(req.ContactID)
	if err != nil {
		return nil, ErrValidation("contact_id is not a valid UUID", err)
	}
	if err := s.validateContact(ctx, contactID, authOrgID); err != nil {
		return nil, err
	}

	params, err := buildCreateProjectParams(authOrgID, contactID, req)
	if err != nil {
		return nil, err
	}

	row, err := s.queries.CreateProject(ctx, params)
	if err != nil {
		return nil, ErrInternal(err)
	}
	return projectToResponse(row), nil
}

// =============================================================================
// GET
// =============================================================================

// GetProject fetches one project by id, scoped to the org. Any active member
// may read a project.
func (s *ProjectService) GetProject(
	ctx context.Context,
	authUserID uuid.UUID,
	authOrgID uuid.UUID,
	id string,
) (*ProjectResponse, error) {
	projectID, err := uuid.Parse(id)
	if err != nil {
		return nil, ErrValidation("id is not a valid UUID", err)
	}
	if _, err := s.authorize(ctx, authUserID, authOrgID); err != nil {
		return nil, err
	}

	row, err := s.queries.GetProject(ctx, projects.GetProjectParams{
		ID:             projectID,
		OrganisationID: authOrgID,
	})
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, ErrNotFound("project", id)
		}
		return nil, ErrInternal(err)
	}
	return projectToResponse(row), nil
}

// =============================================================================
// LIST
// =============================================================================

// ListProjects returns every project in the caller's organisation, newest
// first. Any active member may list.
func (s *ProjectService) ListProjects(
	ctx context.Context,
	authUserID uuid.UUID,
	authOrgID uuid.UUID,
) ([]*ProjectResponse, error) {
	if _, err := s.authorize(ctx, authUserID, authOrgID); err != nil {
		return nil, err
	}

	rows, err := s.queries.ListProjects(ctx, authOrgID)
	if err != nil {
		return nil, ErrInternal(err)
	}

	out := make([]*ProjectResponse, 0, len(rows))
	for _, row := range rows {
		out = append(out, projectToResponse(row))
	}
	return out, nil
}

// =============================================================================
// UPDATE
// =============================================================================

// UpdateProject performs a full update of all editable fields (PUT semantics).
// Any active member may update a project (no per-user ownership rule, unlike
// expenses).
func (s *ProjectService) UpdateProject(
	ctx context.Context,
	authUserID uuid.UUID,
	authOrgID uuid.UUID,
	id string,
	req UpdateProjectRequest,
) (*ProjectResponse, error) {
	projectID, err := uuid.Parse(id)
	if err != nil {
		return nil, ErrValidation("id is not a valid UUID", err)
	}
	if _, err := s.authorize(ctx, authUserID, authOrgID); err != nil {
		return nil, err
	}

	// 404 check before doing any further work.
	if _, err := s.queries.GetProject(ctx, projects.GetProjectParams{
		ID:             projectID,
		OrganisationID: authOrgID,
	}); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, ErrNotFound("project", id)
		}
		return nil, ErrInternal(err)
	}

	contactID, err := uuid.Parse(req.ContactID)
	if err != nil {
		return nil, ErrValidation("contact_id is not a valid UUID", err)
	}
	if err := s.validateContact(ctx, contactID, authOrgID); err != nil {
		return nil, err
	}

	params, err := buildUpdateProjectParams(projectID, authOrgID, contactID, req)
	if err != nil {
		return nil, err
	}

	row, err := s.queries.UpdateProject(ctx, params)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, ErrNotFound("project", id)
		}
		return nil, ErrInternal(err)
	}
	return projectToResponse(row), nil
}

// =============================================================================
// DELETE
// =============================================================================

// DeleteProject hard-deletes a project row. Safe for now because projects are
// not yet referenced by invoice lines. When that FK is added, switch to soft-
// delete (deleted_at). Any active member may delete (no ownership rule yet).
func (s *ProjectService) DeleteProject(
	ctx context.Context,
	authUserID uuid.UUID,
	authOrgID uuid.UUID,
	id string,
) error {
	projectID, err := uuid.Parse(id)
	if err != nil {
		return ErrValidation("id is not a valid UUID", err)
	}
	if _, err := s.authorize(ctx, authUserID, authOrgID); err != nil {
		return err
	}

	// 404 check so we return NotFound rather than a silent no-op.
	if _, err := s.queries.GetProject(ctx, projects.GetProjectParams{
		ID:             projectID,
		OrganisationID: authOrgID,
	}); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return ErrNotFound("project", id)
		}
		return ErrInternal(err)
	}

	if err := s.queries.DeleteProject(ctx, projects.DeleteProjectParams{
		ID:             projectID,
		OrganisationID: authOrgID,
	}); err != nil {
		return ErrInternal(err)
	}
	return nil
}

// =============================================================================
// PARAM BUILDERS
// =============================================================================

func buildCreateProjectParams(orgID, contactID uuid.UUID, req CreateProjectRequest) (projects.CreateProjectParams, error) {
	status, budgetType, billingUnit, err := validateProjectEnums(req.Status, req.BudgetType, req.BillingRateUnit)
	if err != nil {
		return projects.CreateProjectParams{}, err
	}

	billingRatePence, err := poundsStringToInt64(req.BillingRate)
	if err != nil {
		return projects.CreateProjectParams{}, ErrValidation(fmt.Sprintf("billing_rate %q is not a valid amount", req.BillingRate), err)
	}

	budgetHours, budgetDays, budgetMoney, err := resolveBudgetFields(budgetType, req.BudgetHours, req.BudgetDays, req.BudgetMoney)
	if err != nil {
		return projects.CreateProjectParams{}, err
	}

	hoursPerDay, err := parseOptionalHHMM(req.HoursPerDay, "hours_per_day")
	if err != nil {
		return projects.CreateProjectParams{}, err
	}

	startDate, endDate, err := parseOptionalDates(req.StartDate, req.EndDate)
	if err != nil {
		return projects.CreateProjectParams{}, err
	}

	currency := strings.TrimSpace(req.Currency)
	if currency == "" {
		currency = "GBP"
	}

	return projects.CreateProjectParams{
		OrganisationID:         orgID,
		ContactID:              contactID,
		Name:                   req.Name,
		Status:                 status,
		ContractPoNumber:       pgNullText(req.ContractPONumber),
		ProjectInvoiceSequence: req.ProjectInvoiceSequence,
		Currency:               currency,
		BudgetType:             pgNullText(budgetType),
		BudgetHoursMinutes:     budgetHours,
		BudgetDays:             budgetDays,
		BudgetMoneyPence:       budgetMoney,
		HoursPerDayMinutes:     hoursPerDay,
		BillingRatePence:       pgtype.Int8{Int64: billingRatePence, Valid: true},
		BillingRateUnit:        pgNullText(billingUnit),
		BillingRatePlusVat:     req.BillingRatePlusVAT,
		IsIr35:                 req.IsIR35,
		StartDate:              startDate,
		EndDate:                endDate,
		IncludeUnbillableTime:  req.IncludeUnbillableTime,
	}, nil
}

func buildUpdateProjectParams(projectID, orgID, contactID uuid.UUID, req UpdateProjectRequest) (projects.UpdateProjectParams, error) {
	status, budgetType, billingUnit, err := validateProjectEnums(req.Status, req.BudgetType, req.BillingRateUnit)
	if err != nil {
		return projects.UpdateProjectParams{}, err
	}

	billingRatePence, err := poundsStringToInt64(req.BillingRate)
	if err != nil {
		return projects.UpdateProjectParams{}, ErrValidation(fmt.Sprintf("billing_rate %q is not a valid amount", req.BillingRate), err)
	}

	budgetHours, budgetDays, budgetMoney, err := resolveBudgetFields(budgetType, req.BudgetHours, req.BudgetDays, req.BudgetMoney)
	if err != nil {
		return projects.UpdateProjectParams{}, err
	}

	hoursPerDay, err := parseOptionalHHMM(req.HoursPerDay, "hours_per_day")
	if err != nil {
		return projects.UpdateProjectParams{}, err
	}

	startDate, endDate, err := parseOptionalDates(req.StartDate, req.EndDate)
	if err != nil {
		return projects.UpdateProjectParams{}, err
	}

	currency := strings.TrimSpace(req.Currency)
	if currency == "" {
		currency = "GBP"
	}

	return projects.UpdateProjectParams{
		ID:                     projectID,
		OrganisationID:         orgID,
		ContactID:              contactID,
		Name:                   req.Name,
		Status:                 status,
		ContractPoNumber:       pgNullText(req.ContractPONumber),
		ProjectInvoiceSequence: req.ProjectInvoiceSequence,
		Currency:               currency,
		BudgetType:             pgNullText(budgetType),
		BudgetHoursMinutes:     budgetHours,
		BudgetDays:             budgetDays,
		BudgetMoneyPence:       budgetMoney,
		HoursPerDayMinutes:     hoursPerDay,
		BillingRatePence:       pgtype.Int8{Int64: billingRatePence, Valid: true},
		BillingRateUnit:        pgNullText(billingUnit),
		BillingRatePlusVat:     req.BillingRatePlusVAT,
		IsIr35:                 req.IsIR35,
		StartDate:              startDate,
		EndDate:                endDate,
		IncludeUnbillableTime:  req.IncludeUnbillableTime,
	}, nil
}

// =============================================================================
// VALIDATION / NORMALISATION HELPERS
// =============================================================================

// validateProjectEnums validates the three enum-like fields against their
// allowed sets (mirrors the CHECK constraints in the schema). Returns
// (status, budgetType *string, billingRateUnit *string, error).
func validateProjectEnums(rawStatus string, rawBudgetType *string, rawBillingUnit *string) (string, *string, *string, error) {
	status := strings.TrimSpace(rawStatus)
	if status == "" {
		status = "active"
	}
	if !validProjectStatus[status] {
		return "", nil, nil, ErrValidation("status must be one of: active, inactive, completed, cancelled", nil)
	}

	var budgetType *string
	if rawBudgetType != nil {
		v := strings.TrimSpace(*rawBudgetType)
		if v != "" {
			if !validBudgetType[v] {
				return "", nil, nil, ErrValidation("budget_type must be one of: hours, days, money", nil)
			}
			budgetType = &v
		}
	}

	var billingUnit *string
	if rawBillingUnit != nil {
		v := strings.TrimSpace(*rawBillingUnit)
		if v != "" {
			if !validBillingRateUnit[v] {
				return "", nil, nil, ErrValidation("billing_rate_unit must be one of: per_hour, per_day", nil)
			}
			billingUnit = &v
		}
	}

	return status, budgetType, billingUnit, nil
}

// resolveBudgetFields sets the correct budget column based on budget_type,
// leaving the others as NULL. Returns (budgetHoursMinutes, budgetDays,
// budgetMoneyPence, error).
func resolveBudgetFields(budgetType *string, hoursStr *string, daysPtr *int32, moneyStr *string) (pgtype.Int4, pgtype.Int4, pgtype.Int8, error) {
	var hoursMinutes pgtype.Int4
	var days pgtype.Int4
	var moneyPence pgtype.Int8

	if budgetType == nil {
		// No budget set — all three columns stay NULL.
		return hoursMinutes, days, moneyPence, nil
	}

	switch *budgetType {
	case "hours":
		if hoursStr == nil || strings.TrimSpace(*hoursStr) == "" {
			return hoursMinutes, days, moneyPence, ErrValidation("budget_hours is required when budget_type is 'hours'", nil)
		}
		mins, err := hhmmToMinutes(*hoursStr)
		if err != nil {
			return hoursMinutes, days, moneyPence, err
		}
		hoursMinutes = pgtype.Int4{Int32: mins, Valid: true}

	case "days":
		if daysPtr == nil {
			return hoursMinutes, days, moneyPence, ErrValidation("budget_days is required when budget_type is 'days'", nil)
		}
		days = pgtype.Int4{Int32: *daysPtr, Valid: true}

	case "money":
		if moneyStr == nil || strings.TrimSpace(*moneyStr) == "" {
			return hoursMinutes, days, moneyPence, ErrValidation("budget_money is required when budget_type is 'money'", nil)
		}
		pence, err := poundsStringToInt64(*moneyStr)
		if err != nil {
			return hoursMinutes, days, moneyPence, ErrValidation(fmt.Sprintf("budget_money %q is not a valid amount", *moneyStr), err)
		}
		moneyPence = pgtype.Int8{Int64: pence, Valid: true}
	}

	return hoursMinutes, days, moneyPence, nil
}

// parseOptionalHHMM parses a nullable HH:MM (or decimal) hours string to
// total minutes as a nullable pgtype.Int4. Returns an error with the fieldName
// in the message so callers get a clear validation error.
func parseOptionalHHMM(s *string, fieldName string) (pgtype.Int4, error) {
	if s == nil || strings.TrimSpace(*s) == "" {
		return pgtype.Int4{Valid: false}, nil
	}
	mins, err := hhmmToMinutes(*s)
	if err != nil {
		return pgtype.Int4{}, ErrValidation(fmt.Sprintf("%s %q is not a valid HH:MM or decimal hours value", fieldName, *s), err)
	}
	return pgtype.Int4{Int32: mins, Valid: true}, nil
}

// parseOptionalDates parses two nullable "YYYY-MM-DD" date strings.
func parseOptionalDates(startStr, endStr *string) (pgtype.Date, pgtype.Date, error) {
	var startDate, endDate pgtype.Date
	if startStr != nil && strings.TrimSpace(*startStr) != "" {
		t, err := time.Parse("2006-01-02", *startStr)
		if err != nil {
			return startDate, endDate, ErrValidation("start_date must be a valid date in YYYY-MM-DD format", err)
		}
		startDate = pgtype.Date{Time: t, Valid: true}
	}
	if endStr != nil && strings.TrimSpace(*endStr) != "" {
		t, err := time.Parse("2006-01-02", *endStr)
		if err != nil {
			return startDate, endDate, ErrValidation("end_date must be a valid date in YYYY-MM-DD format", err)
		}
		endDate = pgtype.Date{Time: t, Valid: true}
	}
	return startDate, endDate, nil
}

// =============================================================================
// RESPONSE FORMATTER
// =============================================================================

// projectToResponse converts a database Project row (pgx types) into the API
// response shape (plain strings, human-readable amounts and times).
func projectToResponse(p projects.Project) *ProjectResponse {
	// Budget: only populate the field matching budget_type; leave others nil.
	var budgetType *string
	var budgetHours *string
	var budgetDays *int32
	var budgetMoney *string

	if p.BudgetType.Valid {
		v := p.BudgetType.String
		budgetType = &v
		switch v {
		case "hours":
			if p.BudgetHoursMinutes.Valid {
				s := minutesToHHMM(p.BudgetHoursMinutes.Int32)
				budgetHours = &s
			}
		case "days":
			if p.BudgetDays.Valid {
				d := p.BudgetDays.Int32
				budgetDays = &d
			}
		case "money":
			if p.BudgetMoneyPence.Valid {
				s := money.MinorToPounds(p.BudgetMoneyPence.Int64)
				budgetMoney = &s
			}
		}
	}

	var hoursPerDay *string
	if p.HoursPerDayMinutes.Valid {
		s := minutesToHHMM(p.HoursPerDayMinutes.Int32)
		hoursPerDay = &s
	}

	var billingRateUnit *string
	if p.BillingRateUnit.Valid {
		s := p.BillingRateUnit.String
		billingRateUnit = &s
	}

	// billing_rate is always set (0 if the user didn't enter one).
	billingRate := "0.00"
	if p.BillingRatePence.Valid {
		billingRate = money.MinorToPounds(p.BillingRatePence.Int64)
	}

	var startDate, endDate *string
	if p.StartDate.Valid {
		s := p.StartDate.Time.Format("2006-01-02")
		startDate = &s
	}
	if p.EndDate.Valid {
		s := p.EndDate.Time.Format("2006-01-02")
		endDate = &s
	}

	return &ProjectResponse{
		ID:                     p.ID.String(),
		OrganisationID:         p.OrganisationID.String(),
		ContactID:              p.ContactID.String(),
		Name:                   p.Name,
		Status:                 p.Status,
		ContractPONumber:       nullTextToPtr(p.ContractPoNumber),
		ProjectInvoiceSequence: p.ProjectInvoiceSequence,
		Currency:               p.Currency,
		BudgetType:             budgetType,
		BudgetHours:            budgetHours,
		BudgetDays:             budgetDays,
		BudgetMoney:            budgetMoney,
		HoursPerDay:            hoursPerDay,
		BillingRate:            billingRate,
		BillingRateUnit:        billingRateUnit,
		BillingRatePlusVAT:     p.BillingRatePlusVat,
		IsIR35:                 p.IsIr35,
		StartDate:              startDate,
		EndDate:                endDate,
		IncludeUnbillableTime:  p.IncludeUnbillableTime,
		CreatedAt:              p.CreatedAt.Time.Format(time.RFC3339),
		UpdatedAt:              p.UpdatedAt.Time.Format(time.RFC3339),
	}
}

// =============================================================================
// TIME / MONEY HELPERS (projects-specific)
// =============================================================================

// hhmmToMinutes converts an "H:MM" or decimal hours string to total minutes.
// Examples: "8:00" → 480, "1:30" → 90, "8.5" → 510, "8" → 480.
func hhmmToMinutes(s string) (int32, error) {
	s = strings.TrimSpace(s)
	if strings.Contains(s, ":") {
		parts := strings.SplitN(s, ":", 2)
		h, err1 := strconv.Atoi(strings.TrimSpace(parts[0]))
		m, err2 := strconv.Atoi(strings.TrimSpace(parts[1]))
		if err1 != nil || err2 != nil || h < 0 || m < 0 || m >= 60 {
			return 0, ErrValidation(fmt.Sprintf("%q is not a valid HH:MM value", s), nil)
		}
		return int32(h*60 + m), nil
	}
	// Decimal or integer hours (e.g. "8.5" or "8").
	f, err := strconv.ParseFloat(s, 64)
	if err != nil || f < 0 {
		return 0, ErrValidation(fmt.Sprintf("%q is not a valid hours value", s), nil)
	}
	// Round to nearest minute. Adding 0.5 before truncation gives round-half-up.
	return int32(f*60 + 0.5), nil
}

// minutesToHHMM converts total minutes to "H:MM" display format.
// 480 → "8:00", 90 → "1:30", 0 → "0:00".
func minutesToHHMM(minutes int32) string {
	h := minutes / 60
	m := minutes % 60
	return fmt.Sprintf("%d:%02d", h, m)
}

// poundsStringToInt64 parses a decimal pound string to integer pence (int64).
// "100.00" → 10000, "0" → 0. A blank string is a no-op (0) — billing fields are
// optional here — which is the one convenience the shared kernel doesn't provide,
// so this thin wrapper keeps it and delegates the actual parse/round to
// money.PoundsToMinor (half-up rounding, never float).
func poundsStringToInt64(s string) (int64, error) {
	s = strings.TrimSpace(s)
	if s == "" {
		return 0, nil
	}
	return money.PoundsToMinor(s)
}
