// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: banking.sql

package banking

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createBankAccount = `-- name: CreateBankAccount :one



INSERT INTO bank_accounts (
    organisation_id,
    created_by_user_id,
    name,
    currency,
    status,
    is_personal,
    is_primary,
    bank_name,
    account_number,
    sort_code,
    routing_number,
    bank_account_type,
    iban,
    bic,
    show_on_invoices,
    opening_balance_minor,
    opening_balance_date,
    guess_explanations
) VALUES (
    $1,   -- organisation_id        UUID (tenant that owns the account)
    $2,   -- created_by_user_id     UUID (audit)
    $3,   -- name                   VARCHAR (required)
    $4,   -- currency               CHAR(3) e.g. 'GBP'
    $5,   -- status                 VARCHAR 'active'|'closed'
    $6,   -- is_personal            BOOLEAN
    $7,   -- is_primary             BOOLEAN (≤1 live primary per org — enforced by index)
    $8,   -- bank_name              VARCHAR (nullable)
    $9,   -- account_number         VARCHAR (nullable)
    $10,  -- sort_code              VARCHAR (nullable; UK)
    $11,  -- routing_number         VARCHAR (nullable; US)
    $12,  -- bank_account_type      VARCHAR (nullable; 'checking'|'savings', US)
    $13,  -- iban                   VARCHAR (nullable; international)
    $14,  -- bic                    VARCHAR (nullable; SWIFT/BIC)
    $15,  -- show_on_invoices       BOOLEAN
    $16,  -- opening_balance_minor  BIGINT (pence)
    $17,  -- opening_balance_date   DATE (nullable)
    $18   -- guess_explanations     BOOLEAN
)
RETURNING id, organisation_id, created_by_user_id, name, currency, status, is_personal, is_primary, bank_name, account_number, sort_code, routing_number, bank_account_type, iban, bic, show_on_invoices, opening_balance_minor, opening_balance_date, guess_explanations, deleted_at, created_at, updated_at
`

type CreateBankAccountParams struct {
	OrganisationID      uuid.UUID   `json:"organisation_id"`
	CreatedByUserID     uuid.UUID   `json:"created_by_user_id"`
	Name                string      `json:"name"`
	Currency            string      `json:"currency"`
	Status              string      `json:"status"`
	IsPersonal          bool        `json:"is_personal"`
	IsPrimary           bool        `json:"is_primary"`
	BankName            pgtype.Text `json:"bank_name"`
	AccountNumber       pgtype.Text `json:"account_number"`
	SortCode            pgtype.Text `json:"sort_code"`
	RoutingNumber       pgtype.Text `json:"routing_number"`
	BankAccountType     pgtype.Text `json:"bank_account_type"`
	Iban                pgtype.Text `json:"iban"`
	Bic                 pgtype.Text `json:"bic"`
	ShowOnInvoices      bool        `json:"show_on_invoices"`
	OpeningBalanceMinor int64       `json:"opening_balance_minor"`
	OpeningBalanceDate  pgtype.Date `json:"opening_balance_date"`
	GuessExplanations   bool        `json:"guess_explanations"`
}

// =============================================================================
// BANKING MODULE — SQLC QUERIES
// File: db/queries/banking.sql
//
// Type-safe Go for the bank_accounts + bank_transactions tables defined in
// db/schema/banking_schema.sql. Generated by a DEDICATED sqlc block (see
// sqlc.yaml) into package `banking` at db/banking — separate from the other
// domains so types don't bleed across modules.
//
// Annotation / parameter syntax is identical to db/queries/contacts.sql:
//
//	-- name: FuncName :one|:many|:exec
//	$1, $2 ...  positional params, typed from the schema columns.
//
// Every query is ORGANISATION-SCOPED (multi-tenancy) and SOFT-DELETE-AWARE
// (deleted_at IS NULL).
//
// Money note: amounts are BIGINT minor units (pence) → Go int64. The List/Get
// account queries DERIVE current_balance_minor (opening + SUM of the account's
// live transactions); it is never stored. amount_minor is SIGNED (+ in / - out),
// so the SUM is the net movement.
// =============================================================================
// #############################################################################
// BANK ACCOUNTS
// #############################################################################
// -----------------------------------------------------------------------------
// CreateBankAccount  (the "setter")
// Inserts a new bank account and returns the full row via RETURNING *. id,
// status/flag defaults, created_at, updated_at and deleted_at are filled by
// schema defaults, so we only supply the caller-provided columns.
//
// organisation_id and created_by_user_id come from the authenticated token in
// the service layer, never from the request body. RETURNING * gives the base row
// (no derived balance — a fresh account's balance is just its opening balance).
// -----------------------------------------------------------------------------
func (q *Queries) CreateBankAccount(ctx context.Context, arg CreateBankAccountParams) (BankAccount, error) {
	row := q.db.QueryRow(ctx, createBankAccount,
		arg.OrganisationID,
		arg.CreatedByUserID,
		arg.Name,
		arg.Currency,
		arg.Status,
		arg.IsPersonal,
		arg.IsPrimary,
		arg.BankName,
		arg.AccountNumber,
		arg.SortCode,
		arg.RoutingNumber,
		arg.BankAccountType,
		arg.Iban,
		arg.Bic,
		arg.ShowOnInvoices,
		arg.OpeningBalanceMinor,
		arg.OpeningBalanceDate,
		arg.GuessExplanations,
	)
	var i BankAccount
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.CreatedByUserID,
		&i.Name,
		&i.Currency,
		&i.Status,
		&i.IsPersonal,
		&i.IsPrimary,
		&i.BankName,
		&i.AccountNumber,
		&i.SortCode,
		&i.RoutingNumber,
		&i.BankAccountType,
		&i.Iban,
		&i.Bic,
		&i.ShowOnInvoices,
		&i.OpeningBalanceMinor,
		&i.OpeningBalanceDate,
		&i.GuessExplanations,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createBankTransaction = `-- name: CreateBankTransaction :one

INSERT INTO bank_transactions (
    organisation_id,
    bank_account_id,
    created_by_user_id,
    dated_on,
    amount_minor,
    description,
    bank_memo,
    balance_minor,
    status,
    source,
    external_id,
    transaction_type
) VALUES (
    $1,   -- organisation_id     UUID (tenant; denormalised from the account)
    $2,   -- bank_account_id     UUID (the account this line belongs to)
    $3,   -- created_by_user_id  UUID (nullable; NULL = from feed)
    $4,   -- dated_on            DATE
    $5,   -- amount_minor        BIGINT signed (+ in / - out)
    $6,   -- description         VARCHAR (nullable)
    $7,   -- bank_memo           TEXT (nullable; raw bank narrative)
    $8,   -- balance_minor       BIGINT (nullable; running statement balance)
    $9,   -- status              VARCHAR 'unexplained'|'explained'|'for_approval'
    $10,  -- source              VARCHAR 'feed'|'manual'|'statement'
    $11,  -- external_id         VARCHAR (nullable; provider txn id for dedupe)
    $12   -- transaction_type    VARCHAR (nullable; OFX type, e.g. CREDIT/DEBIT)
)
RETURNING id, organisation_id, bank_account_id, created_by_user_id, dated_on, amount_minor, description, bank_memo, balance_minor, unexplained_amount_minor, status, source, transaction_type, external_id, deleted_at, created_at, updated_at
`

type CreateBankTransactionParams struct {
	OrganisationID  uuid.UUID   `json:"organisation_id"`
	BankAccountID   uuid.UUID   `json:"bank_account_id"`
	CreatedByUserID pgtype.UUID `json:"created_by_user_id"`
	DatedOn         pgtype.Date `json:"dated_on"`
	AmountMinor     int64       `json:"amount_minor"`
	Description     pgtype.Text `json:"description"`
	BankMemo        pgtype.Text `json:"bank_memo"`
	BalanceMinor    pgtype.Int8 `json:"balance_minor"`
	Status          string      `json:"status"`
	Source          string      `json:"source"`
	ExternalID      pgtype.Text `json:"external_id"`
	TransactionType pgtype.Text `json:"transaction_type"`
}

// #############################################################################
// BANK TRANSACTIONS
// #############################################################################
// -----------------------------------------------------------------------------
// CreateBankTransaction  (the "setter")
// Inserts one statement line and returns the full row. organisation_id is passed
// explicitly (denormalised onto the line) so every later query is org-scoped
// without a join. created_by_user_id is NULL for a feed line, set for a manual
// one. amount_minor is SIGNED (+ in / - out).
// -----------------------------------------------------------------------------
func (q *Queries) CreateBankTransaction(ctx context.Context, arg CreateBankTransactionParams) (BankTransaction, error) {
	row := q.db.QueryRow(ctx, createBankTransaction,
		arg.OrganisationID,
		arg.BankAccountID,
		arg.CreatedByUserID,
		arg.DatedOn,
		arg.AmountMinor,
		arg.Description,
		arg.BankMemo,
		arg.BalanceMinor,
		arg.Status,
		arg.Source,
		arg.ExternalID,
		arg.TransactionType,
	)
	var i BankTransaction
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.BankAccountID,
		&i.CreatedByUserID,
		&i.DatedOn,
		&i.AmountMinor,
		&i.Description,
		&i.BankMemo,
		&i.BalanceMinor,
		&i.UnexplainedAmountMinor,
		&i.Status,
		&i.Source,
		&i.TransactionType,
		&i.ExternalID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createExplanation = `-- name: CreateExplanation :one

INSERT INTO bank_transaction_explanations (
    organisation_id, bank_transaction_id, created_by_user_id, dated_on, description,
    type, gross_value_minor, category_id,
    sales_tax_status, sales_tax_rate_id, sales_tax_value_minor, is_manual_sales_tax,
    ec_status, place_of_supply,
    transfer_bank_account_id, paid_user_id, paid_invoice_id,
    marked_for_review, cheque_number, receipt_reference,
    paid_bill_id
) VALUES (
    $1,  $2,  $3,  $4,  $5,
    $6,  $7,  $8,
    $9,  $10, $11, $12,
    $13, $14,
    $15, $16, $17,
    $18, $19, $20,
    $21
)
RETURNING id, organisation_id, bank_transaction_id, created_by_user_id, dated_on, description, type, gross_value_minor, category_id, sales_tax_status, sales_tax_rate_id, sales_tax_value_minor, is_manual_sales_tax, ec_status, place_of_supply, transfer_bank_account_id, paid_user_id, paid_invoice_id, paid_bill_id, marked_for_review, cheque_number, receipt_reference, deleted_at, created_at, updated_at
`

type CreateExplanationParams struct {
	OrganisationID        uuid.UUID   `json:"organisation_id"`
	BankTransactionID     uuid.UUID   `json:"bank_transaction_id"`
	CreatedByUserID       pgtype.UUID `json:"created_by_user_id"`
	DatedOn               pgtype.Date `json:"dated_on"`
	Description           pgtype.Text `json:"description"`
	Type                  string      `json:"type"`
	GrossValueMinor       int64       `json:"gross_value_minor"`
	CategoryID            pgtype.UUID `json:"category_id"`
	SalesTaxStatus        string      `json:"sales_tax_status"`
	SalesTaxRateID        pgtype.UUID `json:"sales_tax_rate_id"`
	SalesTaxValueMinor    int64       `json:"sales_tax_value_minor"`
	IsManualSalesTax      bool        `json:"is_manual_sales_tax"`
	EcStatus              pgtype.Text `json:"ec_status"`
	PlaceOfSupply         pgtype.Text `json:"place_of_supply"`
	TransferBankAccountID pgtype.UUID `json:"transfer_bank_account_id"`
	PaidUserID            pgtype.UUID `json:"paid_user_id"`
	PaidInvoiceID         pgtype.UUID `json:"paid_invoice_id"`
	MarkedForReview       bool        `json:"marked_for_review"`
	ChequeNumber          pgtype.Text `json:"cheque_number"`
	ReceiptReference      pgtype.Text `json:"receipt_reference"`
	PaidBillID            pgtype.UUID `json:"paid_bill_id"`
}

// =============================================================================
// BANK TRANSACTION EXPLANATIONS (the reconcile record)
// A transaction can have MANY explanations (splitting). On every insert/update/
// delete the recompute_bank_transaction_explained_state() trigger refreshes the
// parent bank_transaction's unexplained_amount_minor + status — so these queries
// never touch those columns themselves. Org-scoped + soft-deleted throughout.
// =============================================================================
// -----------------------------------------------------------------------------
// CreateExplanation — add one explanation (a whole transaction or a split portion).
// gross_value_minor is SIGNED (+ in / - out). category_id is NULL for entity-link
// types; the entity-link / VAT fields are set as the chosen type requires. :one.
// -----------------------------------------------------------------------------
func (q *Queries) CreateExplanation(ctx context.Context, arg CreateExplanationParams) (BankTransactionExplanation, error) {
	row := q.db.QueryRow(ctx, createExplanation,
		arg.OrganisationID,
		arg.BankTransactionID,
		arg.CreatedByUserID,
		arg.DatedOn,
		arg.Description,
		arg.Type,
		arg.GrossValueMinor,
		arg.CategoryID,
		arg.SalesTaxStatus,
		arg.SalesTaxRateID,
		arg.SalesTaxValueMinor,
		arg.IsManualSalesTax,
		arg.EcStatus,
		arg.PlaceOfSupply,
		arg.TransferBankAccountID,
		arg.PaidUserID,
		arg.PaidInvoiceID,
		arg.MarkedForReview,
		arg.ChequeNumber,
		arg.ReceiptReference,
		arg.PaidBillID,
	)
	var i BankTransactionExplanation
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.BankTransactionID,
		&i.CreatedByUserID,
		&i.DatedOn,
		&i.Description,
		&i.Type,
		&i.GrossValueMinor,
		&i.CategoryID,
		&i.SalesTaxStatus,
		&i.SalesTaxRateID,
		&i.SalesTaxValueMinor,
		&i.IsManualSalesTax,
		&i.EcStatus,
		&i.PlaceOfSupply,
		&i.TransferBankAccountID,
		&i.PaidUserID,
		&i.PaidInvoiceID,
		&i.PaidBillID,
		&i.MarkedForReview,
		&i.ChequeNumber,
		&i.ReceiptReference,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBankAccount = `-- name: GetBankAccount :one
SELECT
    a.id, a.organisation_id, a.created_by_user_id, a.name, a.currency, a.status, a.is_personal, a.is_primary, a.bank_name, a.account_number, a.sort_code, a.routing_number, a.bank_account_type, a.iban, a.bic, a.show_on_invoices, a.opening_balance_minor, a.opening_balance_date, a.guess_explanations, a.deleted_at, a.created_at, a.updated_at,
    (a.opening_balance_minor + COALESCE(SUM(t.amount_minor), 0))::bigint AS current_balance_minor,
    -- Number of live transactions. Drives the "opening balance is locked once the
    -- account has transactions" rule (count(t.id) ignores the LEFT JOIN's NULLs).
    count(t.id) AS transaction_count
FROM bank_accounts a
LEFT JOIN bank_transactions t
       ON t.bank_account_id = a.id
      AND t.deleted_at IS NULL
WHERE a.id              = $1   -- account UUID
  AND a.organisation_id = $2   -- tenant scope — never skip this
  AND a.deleted_at IS NULL     -- soft delete filter
GROUP BY a.id
`

type GetBankAccountParams struct {
	ID             uuid.UUID `json:"id"`
	OrganisationID uuid.UUID `json:"organisation_id"`
}

type GetBankAccountRow struct {
	ID                  uuid.UUID          `json:"id"`
	OrganisationID      uuid.UUID          `json:"organisation_id"`
	CreatedByUserID     uuid.UUID          `json:"created_by_user_id"`
	Name                string             `json:"name"`
	Currency            string             `json:"currency"`
	Status              string             `json:"status"`
	IsPersonal          bool               `json:"is_personal"`
	IsPrimary           bool               `json:"is_primary"`
	BankName            pgtype.Text        `json:"bank_name"`
	AccountNumber       pgtype.Text        `json:"account_number"`
	SortCode            pgtype.Text        `json:"sort_code"`
	RoutingNumber       pgtype.Text        `json:"routing_number"`
	BankAccountType     pgtype.Text        `json:"bank_account_type"`
	Iban                pgtype.Text        `json:"iban"`
	Bic                 pgtype.Text        `json:"bic"`
	ShowOnInvoices      bool               `json:"show_on_invoices"`
	OpeningBalanceMinor int64              `json:"opening_balance_minor"`
	OpeningBalanceDate  pgtype.Date        `json:"opening_balance_date"`
	GuessExplanations   bool               `json:"guess_explanations"`
	DeletedAt           pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	CurrentBalanceMinor int64              `json:"current_balance_minor"`
	TransactionCount    int64              `json:"transaction_count"`
}

// -----------------------------------------------------------------------------
// GetBankAccount  (the "getter", with derived balance)
// Fetch a single account by id, scoped to the organisation, with its DERIVED
// current_balance_minor = opening + SUM(live transactions). We ALWAYS scope by
// organisation_id — never fetch by id alone. The LEFT JOIN keeps the row even
// when the account has no transactions (its deleted_at filter lives in the ON
// clause, not WHERE, so it doesn't turn the LEFT JOIN into an INNER one). The
// whole sum is cast to BIGINT so it maps to Go int64 (SUM of bigint is numeric).
// -----------------------------------------------------------------------------
func (q *Queries) GetBankAccount(ctx context.Context, arg GetBankAccountParams) (GetBankAccountRow, error) {
	row := q.db.QueryRow(ctx, getBankAccount, arg.ID, arg.OrganisationID)
	var i GetBankAccountRow
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.CreatedByUserID,
		&i.Name,
		&i.Currency,
		&i.Status,
		&i.IsPersonal,
		&i.IsPrimary,
		&i.BankName,
		&i.AccountNumber,
		&i.SortCode,
		&i.RoutingNumber,
		&i.BankAccountType,
		&i.Iban,
		&i.Bic,
		&i.ShowOnInvoices,
		&i.OpeningBalanceMinor,
		&i.OpeningBalanceDate,
		&i.GuessExplanations,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CurrentBalanceMinor,
		&i.TransactionCount,
	)
	return i, err
}

const getBankTransaction = `-- name: GetBankTransaction :one
SELECT id, organisation_id, bank_account_id, created_by_user_id, dated_on, amount_minor, description, bank_memo, balance_minor, unexplained_amount_minor, status, source, transaction_type, external_id, deleted_at, created_at, updated_at FROM bank_transactions
WHERE id              = $1   -- transaction UUID
  AND organisation_id = $2   -- tenant scope — never skip this
  AND deleted_at IS NULL
`

type GetBankTransactionParams struct {
	ID             uuid.UUID `json:"id"`
	OrganisationID uuid.UUID `json:"organisation_id"`
}

// -----------------------------------------------------------------------------
// GetBankTransaction  (the "getter")
// Fetch a single transaction by id, scoped to the organisation. deleted_at
// IS NULL hides soft-deleted lines.
// -----------------------------------------------------------------------------
func (q *Queries) GetBankTransaction(ctx context.Context, arg GetBankTransactionParams) (BankTransaction, error) {
	row := q.db.QueryRow(ctx, getBankTransaction, arg.ID, arg.OrganisationID)
	var i BankTransaction
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.BankAccountID,
		&i.CreatedByUserID,
		&i.DatedOn,
		&i.AmountMinor,
		&i.Description,
		&i.BankMemo,
		&i.BalanceMinor,
		&i.UnexplainedAmountMinor,
		&i.Status,
		&i.Source,
		&i.TransactionType,
		&i.ExternalID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBankTransactionByExternalID = `-- name: GetBankTransactionByExternalID :one
SELECT id, organisation_id, bank_account_id, created_by_user_id, dated_on, amount_minor, description, bank_memo, balance_minor, unexplained_amount_minor, status, source, transaction_type, external_id, deleted_at, created_at, updated_at FROM bank_transactions
WHERE bank_account_id = $1   -- the account
  AND external_id     = $2   -- the provider's transaction id
  AND deleted_at IS NULL
`

type GetBankTransactionByExternalIDParams struct {
	BankAccountID uuid.UUID   `json:"bank_account_id"`
	ExternalID    pgtype.Text `json:"external_id"`
}

// -----------------------------------------------------------------------------
// GetBankTransactionByExternalID  (feed dedupe lookup)
// Used by the future bank-feed ingestion to skip a transaction it already has.
// Keyed on (bank_account_id, external_id) — exactly the columns of the partial
// unique index idx_bank_transactions_external — so it is an index lookup. The
// account already implies the org (it was loaded org-scoped). :one.
// -----------------------------------------------------------------------------
func (q *Queries) GetBankTransactionByExternalID(ctx context.Context, arg GetBankTransactionByExternalIDParams) (BankTransaction, error) {
	row := q.db.QueryRow(ctx, getBankTransactionByExternalID, arg.BankAccountID, arg.ExternalID)
	var i BankTransaction
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.BankAccountID,
		&i.CreatedByUserID,
		&i.DatedOn,
		&i.AmountMinor,
		&i.Description,
		&i.BankMemo,
		&i.BalanceMinor,
		&i.UnexplainedAmountMinor,
		&i.Status,
		&i.Source,
		&i.TransactionType,
		&i.ExternalID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExplanation = `-- name: GetExplanation :one
SELECT id, organisation_id, bank_transaction_id, created_by_user_id, dated_on, description, type, gross_value_minor, category_id, sales_tax_status, sales_tax_rate_id, sales_tax_value_minor, is_manual_sales_tax, ec_status, place_of_supply, transfer_bank_account_id, paid_user_id, paid_invoice_id, paid_bill_id, marked_for_review, cheque_number, receipt_reference, deleted_at, created_at, updated_at FROM bank_transaction_explanations
WHERE id              = $1
  AND organisation_id = $2
  AND deleted_at IS NULL
`

type GetExplanationParams struct {
	ID             uuid.UUID `json:"id"`
	OrganisationID uuid.UUID `json:"organisation_id"`
}

// -----------------------------------------------------------------------------
// GetExplanation — one explanation by id, org-scoped, live only. :one.
// -----------------------------------------------------------------------------
func (q *Queries) GetExplanation(ctx context.Context, arg GetExplanationParams) (BankTransactionExplanation, error) {
	row := q.db.QueryRow(ctx, getExplanation, arg.ID, arg.OrganisationID)
	var i BankTransactionExplanation
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.BankTransactionID,
		&i.CreatedByUserID,
		&i.DatedOn,
		&i.Description,
		&i.Type,
		&i.GrossValueMinor,
		&i.CategoryID,
		&i.SalesTaxStatus,
		&i.SalesTaxRateID,
		&i.SalesTaxValueMinor,
		&i.IsManualSalesTax,
		&i.EcStatus,
		&i.PlaceOfSupply,
		&i.TransferBankAccountID,
		&i.PaidUserID,
		&i.PaidInvoiceID,
		&i.PaidBillID,
		&i.MarkedForReview,
		&i.ChequeNumber,
		&i.ReceiptReference,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBankAccountTransactions = `-- name: ListBankAccountTransactions :many
SELECT t.id, t.organisation_id, t.bank_account_id, t.created_by_user_id, t.dated_on, t.amount_minor, t.description, t.bank_memo, t.balance_minor, t.unexplained_amount_minor, t.status, t.source, t.transaction_type, t.external_id, t.deleted_at, t.created_at, t.updated_at,
    -- A searchable digest of the line's explanations — category names, the transfer
    -- account / paid-user names, and any notes — so the statement search matches across
    -- explanations as well as the description/bank_memo. '' when a line has none.
    COALESCE((
        SELECT string_agg(trim(
                   COALESCE(c.name, '')        || ' ' ||
                   COALESCE(ta.name, '')       || ' ' ||
                   COALESCE(u.first_name, '')  || ' ' ||
                   COALESCE(u.last_name, '')   || ' ' ||
                   COALESCE(e.description, '')), ' | ')
        FROM bank_transaction_explanations e
        LEFT JOIN categories    c  ON c.id  = e.category_id
        LEFT JOIN bank_accounts ta ON ta.id = e.transfer_bank_account_id
        LEFT JOIN users         u  ON u.id  = e.paid_user_id
        WHERE e.bank_transaction_id = t.id AND e.deleted_at IS NULL
    ), '')::text AS explanation_summary
FROM bank_transactions t
WHERE t.organisation_id = $1   -- tenant scope
  AND t.bank_account_id = $2   -- which account's statement
  AND t.deleted_at IS NULL
ORDER BY t.dated_on ASC, t.created_at ASC, t.id ASC
`

type ListBankAccountTransactionsParams struct {
	OrganisationID uuid.UUID `json:"organisation_id"`
	BankAccountID  uuid.UUID `json:"bank_account_id"`
}

type ListBankAccountTransactionsRow struct {
	BankTransaction    BankTransaction `json:"bank_transaction"`
	ExplanationSummary string          `json:"explanation_summary"`
}

// -----------------------------------------------------------------------------
// ListBankAccountTransactions  (the statement view — OLDEST first, all rows)
// Powers the read-only transactions page. Unlike ListBankTransactions (newest
// first, paginated), this returns the account's whole live statement in
// CHRONOLOGICAL order so the service can fold a running balance over it
// (opening + Σ amount_minor). The (dated_on, created_at, id) ordering is fully
// deterministic so same-dated lines accumulate in a stable order. v1 has no
// LIMIT — the running balance needs the full ordered set; pagination is deferred.
// -----------------------------------------------------------------------------
func (q *Queries) ListBankAccountTransactions(ctx context.Context, arg ListBankAccountTransactionsParams) ([]ListBankAccountTransactionsRow, error) {
	rows, err := q.db.Query(ctx, listBankAccountTransactions, arg.OrganisationID, arg.BankAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBankAccountTransactionsRow
	for rows.Next() {
		var i ListBankAccountTransactionsRow
		if err := rows.Scan(
			&i.BankTransaction.ID,
			&i.BankTransaction.OrganisationID,
			&i.BankTransaction.BankAccountID,
			&i.BankTransaction.CreatedByUserID,
			&i.BankTransaction.DatedOn,
			&i.BankTransaction.AmountMinor,
			&i.BankTransaction.Description,
			&i.BankTransaction.BankMemo,
			&i.BankTransaction.BalanceMinor,
			&i.BankTransaction.UnexplainedAmountMinor,
			&i.BankTransaction.Status,
			&i.BankTransaction.Source,
			&i.BankTransaction.TransactionType,
			&i.BankTransaction.ExternalID,
			&i.BankTransaction.DeletedAt,
			&i.BankTransaction.CreatedAt,
			&i.BankTransaction.UpdatedAt,
			&i.ExplanationSummary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBankAccounts = `-- name: ListBankAccounts :many
SELECT
    a.id, a.organisation_id, a.created_by_user_id, a.name, a.currency, a.status, a.is_personal, a.is_primary, a.bank_name, a.account_number, a.sort_code, a.routing_number, a.bank_account_type, a.iban, a.bic, a.show_on_invoices, a.opening_balance_minor, a.opening_balance_date, a.guess_explanations, a.deleted_at, a.created_at, a.updated_at,
    (a.opening_balance_minor + COALESCE(SUM(t.amount_minor), 0))::bigint AS current_balance_minor,
    count(t.id) AS transaction_count
FROM bank_accounts a
LEFT JOIN bank_transactions t
       ON t.bank_account_id = a.id
      AND t.deleted_at IS NULL
WHERE a.organisation_id = $1
  AND a.deleted_at IS NULL
GROUP BY a.id
ORDER BY a.is_primary DESC, a.name
`

type ListBankAccountsRow struct {
	ID                  uuid.UUID          `json:"id"`
	OrganisationID      uuid.UUID          `json:"organisation_id"`
	CreatedByUserID     uuid.UUID          `json:"created_by_user_id"`
	Name                string             `json:"name"`
	Currency            string             `json:"currency"`
	Status              string             `json:"status"`
	IsPersonal          bool               `json:"is_personal"`
	IsPrimary           bool               `json:"is_primary"`
	BankName            pgtype.Text        `json:"bank_name"`
	AccountNumber       pgtype.Text        `json:"account_number"`
	SortCode            pgtype.Text        `json:"sort_code"`
	RoutingNumber       pgtype.Text        `json:"routing_number"`
	BankAccountType     pgtype.Text        `json:"bank_account_type"`
	Iban                pgtype.Text        `json:"iban"`
	Bic                 pgtype.Text        `json:"bic"`
	ShowOnInvoices      bool               `json:"show_on_invoices"`
	OpeningBalanceMinor int64              `json:"opening_balance_minor"`
	OpeningBalanceDate  pgtype.Date        `json:"opening_balance_date"`
	GuessExplanations   bool               `json:"guess_explanations"`
	DeletedAt           pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	CurrentBalanceMinor int64              `json:"current_balance_minor"`
	TransactionCount    int64              `json:"transaction_count"`
}

// -----------------------------------------------------------------------------
// ListBankAccounts  (the "list", with derived balance)
// All live accounts for an organisation, each with its derived current balance,
// for the bank-accounts list page. Primary account first (the form note: "appear
// at the top of Banking lists and dropdowns"), then by name.
// -----------------------------------------------------------------------------
func (q *Queries) ListBankAccounts(ctx context.Context, organisationID uuid.UUID) ([]ListBankAccountsRow, error) {
	rows, err := q.db.Query(ctx, listBankAccounts, organisationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBankAccountsRow
	for rows.Next() {
		var i ListBankAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganisationID,
			&i.CreatedByUserID,
			&i.Name,
			&i.Currency,
			&i.Status,
			&i.IsPersonal,
			&i.IsPrimary,
			&i.BankName,
			&i.AccountNumber,
			&i.SortCode,
			&i.RoutingNumber,
			&i.BankAccountType,
			&i.Iban,
			&i.Bic,
			&i.ShowOnInvoices,
			&i.OpeningBalanceMinor,
			&i.OpeningBalanceDate,
			&i.GuessExplanations,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CurrentBalanceMinor,
			&i.TransactionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBankTransactionExternalIDs = `-- name: ListBankTransactionExternalIDs :many
SELECT external_id FROM bank_transactions
WHERE bank_account_id = $1
  AND external_id IS NOT NULL
  AND deleted_at IS NULL
`

// -----------------------------------------------------------------------------
// ListBankTransactionExternalIDs  (statement-import dedupe set)
// All non-null external_ids currently on an account's live lines. Statement
// import fetches this once into a set to skip lines it has already imported
// (each imported line's external_id is a stable per-line hash). :many.
// -----------------------------------------------------------------------------
func (q *Queries) ListBankTransactionExternalIDs(ctx context.Context, bankAccountID uuid.UUID) ([]pgtype.Text, error) {
	rows, err := q.db.Query(ctx, listBankTransactionExternalIDs, bankAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Text
	for rows.Next() {
		var external_id pgtype.Text
		if err := rows.Scan(&external_id); err != nil {
			return nil, err
		}
		items = append(items, external_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBankTransactions = `-- name: ListBankTransactions :many
SELECT id, organisation_id, bank_account_id, created_by_user_id, dated_on, amount_minor, description, bank_memo, balance_minor, unexplained_amount_minor, status, source, transaction_type, external_id, deleted_at, created_at, updated_at FROM bank_transactions
WHERE organisation_id = $1   -- tenant scope
  AND bank_account_id = $2   -- which account's statement
  AND deleted_at IS NULL
ORDER BY dated_on DESC, created_at DESC
LIMIT $3 OFFSET $4
`

type ListBankTransactionsParams struct {
	OrganisationID uuid.UUID `json:"organisation_id"`
	BankAccountID  uuid.UUID `json:"bank_account_id"`
	Limit          int32     `json:"limit"`
	Offset         int32     `json:"offset"`
}

// -----------------------------------------------------------------------------
// ListBankTransactions  (the "list", paginated)
// The statement lines for ONE account, newest first, for the transactions page.
// Scoped by org AND account. Paginated with LIMIT/OFFSET (the list shows a page
// size selector). created_at is the tiebreaker so same-dated lines are stable.
// -----------------------------------------------------------------------------
func (q *Queries) ListBankTransactions(ctx context.Context, arg ListBankTransactionsParams) ([]BankTransaction, error) {
	rows, err := q.db.Query(ctx, listBankTransactions,
		arg.OrganisationID,
		arg.BankAccountID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BankTransaction
	for rows.Next() {
		var i BankTransaction
		if err := rows.Scan(
			&i.ID,
			&i.OrganisationID,
			&i.BankAccountID,
			&i.CreatedByUserID,
			&i.DatedOn,
			&i.AmountMinor,
			&i.Description,
			&i.BankMemo,
			&i.BalanceMinor,
			&i.UnexplainedAmountMinor,
			&i.Status,
			&i.Source,
			&i.TransactionType,
			&i.ExternalID,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExplanationsForTransaction = `-- name: ListExplanationsForTransaction :many
SELECT id, organisation_id, bank_transaction_id, created_by_user_id, dated_on, description, type, gross_value_minor, category_id, sales_tax_status, sales_tax_rate_id, sales_tax_value_minor, is_manual_sales_tax, ec_status, place_of_supply, transfer_bank_account_id, paid_user_id, paid_invoice_id, paid_bill_id, marked_for_review, cheque_number, receipt_reference, deleted_at, created_at, updated_at FROM bank_transaction_explanations
WHERE bank_transaction_id = $1
  AND organisation_id     = $2
  AND deleted_at IS NULL
ORDER BY created_at ASC, id ASC
`

type ListExplanationsForTransactionParams struct {
	BankTransactionID uuid.UUID `json:"bank_transaction_id"`
	OrganisationID    uuid.UUID `json:"organisation_id"`
}

// -----------------------------------------------------------------------------
// ListExplanationsForTransaction — a transaction's live explanations, oldest
// first. Backs the per-transaction explain panel. Org-scoped. :many.
// -----------------------------------------------------------------------------
func (q *Queries) ListExplanationsForTransaction(ctx context.Context, arg ListExplanationsForTransactionParams) ([]BankTransactionExplanation, error) {
	rows, err := q.db.Query(ctx, listExplanationsForTransaction, arg.BankTransactionID, arg.OrganisationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BankTransactionExplanation
	for rows.Next() {
		var i BankTransactionExplanation
		if err := rows.Scan(
			&i.ID,
			&i.OrganisationID,
			&i.BankTransactionID,
			&i.CreatedByUserID,
			&i.DatedOn,
			&i.Description,
			&i.Type,
			&i.GrossValueMinor,
			&i.CategoryID,
			&i.SalesTaxStatus,
			&i.SalesTaxRateID,
			&i.SalesTaxValueMinor,
			&i.IsManualSalesTax,
			&i.EcStatus,
			&i.PlaceOfSupply,
			&i.TransferBankAccountID,
			&i.PaidUserID,
			&i.PaidInvoiceID,
			&i.PaidBillID,
			&i.MarkedForReview,
			&i.ChequeNumber,
			&i.ReceiptReference,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExplanationsForTransactionDetailed = `-- name: ListExplanationsForTransactionDetailed :many
SELECT
    e.id, e.organisation_id, e.bank_transaction_id, e.created_by_user_id, e.dated_on, e.description, e.type, e.gross_value_minor, e.category_id, e.sales_tax_status, e.sales_tax_rate_id, e.sales_tax_value_minor, e.is_manual_sales_tax, e.ec_status, e.place_of_supply, e.transfer_bank_account_id, e.paid_user_id, e.paid_invoice_id, e.paid_bill_id, e.marked_for_review, e.cheque_number, e.receipt_reference, e.deleted_at, e.created_at, e.updated_at,
    c.name         AS category_name,
    c.nominal_code AS category_nominal_code,
    ta.name        AS transfer_account_name,
    u.first_name   AS paid_user_first_name,
    u.last_name    AS paid_user_last_name,
    vr.name        AS vat_rate_name,
    vr.rate_bps    AS vat_rate_bps,
    inv.reference  AS invoice_reference,
    bl.reference   AS bill_reference
FROM bank_transaction_explanations e
LEFT JOIN categories    c   ON c.id   = e.category_id
LEFT JOIN bank_accounts ta  ON ta.id  = e.transfer_bank_account_id
LEFT JOIN users         u   ON u.id   = e.paid_user_id
LEFT JOIN vat_rates     vr  ON vr.id  = e.sales_tax_rate_id
LEFT JOIN invoices      inv ON inv.id = e.paid_invoice_id
LEFT JOIN bills         bl  ON bl.id  = e.paid_bill_id
WHERE e.bank_transaction_id = $1
  AND e.organisation_id     = $2
  AND e.deleted_at IS NULL
ORDER BY e.created_at ASC, e.id ASC
`

type ListExplanationsForTransactionDetailedParams struct {
	BankTransactionID uuid.UUID `json:"bank_transaction_id"`
	OrganisationID    uuid.UUID `json:"organisation_id"`
}

type ListExplanationsForTransactionDetailedRow struct {
	ID                    uuid.UUID          `json:"id"`
	OrganisationID        uuid.UUID          `json:"organisation_id"`
	BankTransactionID     uuid.UUID          `json:"bank_transaction_id"`
	CreatedByUserID       pgtype.UUID        `json:"created_by_user_id"`
	DatedOn               pgtype.Date        `json:"dated_on"`
	Description           pgtype.Text        `json:"description"`
	Type                  string             `json:"type"`
	GrossValueMinor       int64              `json:"gross_value_minor"`
	CategoryID            pgtype.UUID        `json:"category_id"`
	SalesTaxStatus        string             `json:"sales_tax_status"`
	SalesTaxRateID        pgtype.UUID        `json:"sales_tax_rate_id"`
	SalesTaxValueMinor    int64              `json:"sales_tax_value_minor"`
	IsManualSalesTax      bool               `json:"is_manual_sales_tax"`
	EcStatus              pgtype.Text        `json:"ec_status"`
	PlaceOfSupply         pgtype.Text        `json:"place_of_supply"`
	TransferBankAccountID pgtype.UUID        `json:"transfer_bank_account_id"`
	PaidUserID            pgtype.UUID        `json:"paid_user_id"`
	PaidInvoiceID         pgtype.UUID        `json:"paid_invoice_id"`
	PaidBillID            pgtype.UUID        `json:"paid_bill_id"`
	MarkedForReview       bool               `json:"marked_for_review"`
	ChequeNumber          pgtype.Text        `json:"cheque_number"`
	ReceiptReference      pgtype.Text        `json:"receipt_reference"`
	DeletedAt             pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	CategoryName          pgtype.Text        `json:"category_name"`
	CategoryNominalCode   pgtype.Text        `json:"category_nominal_code"`
	TransferAccountName   pgtype.Text        `json:"transfer_account_name"`
	PaidUserFirstName     pgtype.Text        `json:"paid_user_first_name"`
	PaidUserLastName      pgtype.Text        `json:"paid_user_last_name"`
	VatRateName           pgtype.Text        `json:"vat_rate_name"`
	VatRateBps            pgtype.Int4        `json:"vat_rate_bps"`
	InvoiceReference      pgtype.Text        `json:"invoice_reference"`
	BillReference         pgtype.Text        `json:"bill_reference"`
}

// -----------------------------------------------------------------------------
// ListExplanationsForTransactionDetailed — a line's live explanations with the
// resolved display names in ONE query: the category (name + nominal), the transfer
// account name, the paid user's name, and the VAT rate (name + bps). LEFT JOINs so
// entity-link explanations (NULL category) still return. Backs the explain panel +
// every explain mutation's response. Org-scoped, oldest first. :many.
// -----------------------------------------------------------------------------
func (q *Queries) ListExplanationsForTransactionDetailed(ctx context.Context, arg ListExplanationsForTransactionDetailedParams) ([]ListExplanationsForTransactionDetailedRow, error) {
	rows, err := q.db.Query(ctx, listExplanationsForTransactionDetailed, arg.BankTransactionID, arg.OrganisationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExplanationsForTransactionDetailedRow
	for rows.Next() {
		var i ListExplanationsForTransactionDetailedRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganisationID,
			&i.BankTransactionID,
			&i.CreatedByUserID,
			&i.DatedOn,
			&i.Description,
			&i.Type,
			&i.GrossValueMinor,
			&i.CategoryID,
			&i.SalesTaxStatus,
			&i.SalesTaxRateID,
			&i.SalesTaxValueMinor,
			&i.IsManualSalesTax,
			&i.EcStatus,
			&i.PlaceOfSupply,
			&i.TransferBankAccountID,
			&i.PaidUserID,
			&i.PaidInvoiceID,
			&i.PaidBillID,
			&i.MarkedForReview,
			&i.ChequeNumber,
			&i.ReceiptReference,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryName,
			&i.CategoryNominalCode,
			&i.TransferAccountName,
			&i.PaidUserFirstName,
			&i.PaidUserLastName,
			&i.VatRateName,
			&i.VatRateBps,
			&i.InvoiceReference,
			&i.BillReference,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteBankAccount = `-- name: SoftDeleteBankAccount :exec
UPDATE bank_accounts SET
    deleted_at = now(),
    updated_at = now()
WHERE id              = $1
  AND organisation_id = $2
  AND deleted_at IS NULL
`

type SoftDeleteBankAccountParams struct {
	ID             uuid.UUID `json:"id"`
	OrganisationID uuid.UUID `json:"organisation_id"`
}

// -----------------------------------------------------------------------------
// SoftDeleteBankAccount  (the "delete")
// Marks the account deleted (financial records are never hard-removed; its
// transactions stay for audit). :exec. Idempotent — deleting an already-deleted
// account matches no live row and is a no-op.
// -----------------------------------------------------------------------------
func (q *Queries) SoftDeleteBankAccount(ctx context.Context, arg SoftDeleteBankAccountParams) error {
	_, err := q.db.Exec(ctx, softDeleteBankAccount, arg.ID, arg.OrganisationID)
	return err
}

const softDeleteBankTransaction = `-- name: SoftDeleteBankTransaction :exec
UPDATE bank_transactions SET
    deleted_at = now(),
    updated_at = now()
WHERE id              = $1
  AND organisation_id = $2
  AND deleted_at IS NULL
`

type SoftDeleteBankTransactionParams struct {
	ID             uuid.UUID `json:"id"`
	OrganisationID uuid.UUID `json:"organisation_id"`
}

// -----------------------------------------------------------------------------
// SoftDeleteBankTransaction  (the "delete")
// Marks a line deleted (e.g. removing a manually-added transaction). Org-scoped.
// :exec. Idempotent — an already-deleted line matches nothing and is a no-op.
// -----------------------------------------------------------------------------
func (q *Queries) SoftDeleteBankTransaction(ctx context.Context, arg SoftDeleteBankTransactionParams) error {
	_, err := q.db.Exec(ctx, softDeleteBankTransaction, arg.ID, arg.OrganisationID)
	return err
}

const softDeleteExplanation = `-- name: SoftDeleteExplanation :exec
UPDATE bank_transaction_explanations SET
    deleted_at = now()
WHERE id              = $1
  AND organisation_id = $2
  AND deleted_at IS NULL
`

type SoftDeleteExplanationParams struct {
	ID             uuid.UUID `json:"id"`
	OrganisationID uuid.UUID `json:"organisation_id"`
}

// -----------------------------------------------------------------------------
// SoftDeleteExplanation — remove one explanation (un-explain part of a line).
// The recompute trigger bumps the parent back toward 'unexplained'. Org-scoped.
// :exec. Idempotent — an already-deleted row matches nothing.
// -----------------------------------------------------------------------------
func (q *Queries) SoftDeleteExplanation(ctx context.Context, arg SoftDeleteExplanationParams) error {
	_, err := q.db.Exec(ctx, softDeleteExplanation, arg.ID, arg.OrganisationID)
	return err
}

const sumBillPaymentsForBill = `-- name: SumBillPaymentsForBill :one
SELECT COALESCE(-SUM(gross_value_minor), 0)::bigint AS total_minor
FROM bank_transaction_explanations
WHERE paid_bill_id     = $1
  AND organisation_id  = $2
  AND type             = 'BILL_PAYMENT'
  AND deleted_at IS NULL
`

type SumBillPaymentsForBillParams struct {
	PaidBillID     pgtype.UUID `json:"paid_bill_id"`
	OrganisationID uuid.UUID   `json:"organisation_id"`
}

// -----------------------------------------------------------------------------
// SumBillPaymentsForBill — the total paid against ONE bill by live BILL_PAYMENT
// explanations (the new paid_value_minor for that bill). Mirror of
// SumInvoiceReceiptsForInvoice, but BILL_PAYMENT is money-OUT so gross_value_minor is
// NEGATIVE — we NEGATE the sum so bills.paid_value_minor is the POSITIVE amount paid.
// The explain service recomputes this inside the explanation's transaction and pushes
// it onto bills.paid_value_minor (UpdateBillPaidValue), so the figure is drift-free
// across split/edit/re-point/delete. Org-scoped. :one.
// -----------------------------------------------------------------------------
func (q *Queries) SumBillPaymentsForBill(ctx context.Context, arg SumBillPaymentsForBillParams) (int64, error) {
	row := q.db.QueryRow(ctx, sumBillPaymentsForBill, arg.PaidBillID, arg.OrganisationID)
	var total_minor int64
	err := row.Scan(&total_minor)
	return total_minor, err
}

const sumInvoiceReceiptsForInvoice = `-- name: SumInvoiceReceiptsForInvoice :one
SELECT COALESCE(SUM(gross_value_minor), 0)::bigint AS total_minor
FROM bank_transaction_explanations
WHERE paid_invoice_id  = $1
  AND organisation_id  = $2
  AND type             = 'INVOICE_RECEIPT'
  AND deleted_at IS NULL
`

type SumInvoiceReceiptsForInvoiceParams struct {
	PaidInvoiceID  pgtype.UUID `json:"paid_invoice_id"`
	OrganisationID uuid.UUID   `json:"organisation_id"`
}

// -----------------------------------------------------------------------------
// SumInvoiceReceiptsForInvoice — the total settled against ONE invoice by live
// INVOICE_RECEIPT explanations (the new paid_value_minor for that invoice). The
// explain service recomputes this inside the same transaction as the explanation
// write and pushes it onto invoices.paid_value_minor (UpdateInvoicePaidValue), so
// the figure is drift-free across split/edit/re-point/delete. gross_value_minor is
// positive for a money-in receipt, so the SUM is the amount received. Org-scoped. :one.
// -----------------------------------------------------------------------------
func (q *Queries) SumInvoiceReceiptsForInvoice(ctx context.Context, arg SumInvoiceReceiptsForInvoiceParams) (int64, error) {
	row := q.db.QueryRow(ctx, sumInvoiceReceiptsForInvoice, arg.PaidInvoiceID, arg.OrganisationID)
	var total_minor int64
	err := row.Scan(&total_minor)
	return total_minor, err
}

const unsetPrimaryBankAccounts = `-- name: UnsetPrimaryBankAccounts :exec
UPDATE bank_accounts SET
    is_primary = FALSE,
    updated_at = now()
WHERE organisation_id = $1
  AND is_primary
  AND deleted_at IS NULL
`

// -----------------------------------------------------------------------------
// UnsetPrimaryBankAccounts  (clear the org's current primary)
// Sets is_primary = FALSE on whichever live account is currently primary for the
// org. Called inside a transaction BEFORE marking a new primary, so the partial
// unique index (≤1 live primary per org) is never transiently violated. :exec.
// Idempotent — if there is no current primary it simply matches no rows.
// -----------------------------------------------------------------------------
func (q *Queries) UnsetPrimaryBankAccounts(ctx context.Context, organisationID uuid.UUID) error {
	_, err := q.db.Exec(ctx, unsetPrimaryBankAccounts, organisationID)
	return err
}

const updateBankAccount = `-- name: UpdateBankAccount :one
UPDATE bank_accounts SET
    name                  = $3,
    currency              = $4,
    status                = $5,
    is_personal           = $6,
    is_primary            = $7,
    bank_name             = $8,
    account_number        = $9,
    sort_code             = $10,
    routing_number        = $11,
    bank_account_type     = $12,
    iban                  = $13,
    bic                   = $14,
    show_on_invoices      = $15,
    opening_balance_minor = $16,
    opening_balance_date  = $17,
    guess_explanations    = $18,
    updated_at            = now()
WHERE id              = $1   -- account UUID
  AND organisation_id = $2   -- tenant scope
  AND deleted_at IS NULL     -- can't update a deleted account
RETURNING id, organisation_id, created_by_user_id, name, currency, status, is_personal, is_primary, bank_name, account_number, sort_code, routing_number, bank_account_type, iban, bic, show_on_invoices, opening_balance_minor, opening_balance_date, guess_explanations, deleted_at, created_at, updated_at
`

type UpdateBankAccountParams struct {
	ID                  uuid.UUID   `json:"id"`
	OrganisationID      uuid.UUID   `json:"organisation_id"`
	Name                string      `json:"name"`
	Currency            string      `json:"currency"`
	Status              string      `json:"status"`
	IsPersonal          bool        `json:"is_personal"`
	IsPrimary           bool        `json:"is_primary"`
	BankName            pgtype.Text `json:"bank_name"`
	AccountNumber       pgtype.Text `json:"account_number"`
	SortCode            pgtype.Text `json:"sort_code"`
	RoutingNumber       pgtype.Text `json:"routing_number"`
	BankAccountType     pgtype.Text `json:"bank_account_type"`
	Iban                pgtype.Text `json:"iban"`
	Bic                 pgtype.Text `json:"bic"`
	ShowOnInvoices      bool        `json:"show_on_invoices"`
	OpeningBalanceMinor int64       `json:"opening_balance_minor"`
	OpeningBalanceDate  pgtype.Date `json:"opening_balance_date"`
	GuessExplanations   bool        `json:"guess_explanations"`
}

// -----------------------------------------------------------------------------
// UpdateBankAccount  (the "update")
// Full update of an account's editable fields (PUT semantics). organisation_id
// and created_by_user_id are NOT editable. updated_at is set explicitly in
// addition to the trigger (belt-and-suspenders). RETURNING * echoes the row.
//
// Note: setting is_primary = TRUE while another live primary exists violates
// idx_bank_accounts_one_primary; the service unsets the old primary first
// (UnsetPrimaryBankAccounts), inside one transaction.
// -----------------------------------------------------------------------------
func (q *Queries) UpdateBankAccount(ctx context.Context, arg UpdateBankAccountParams) (BankAccount, error) {
	row := q.db.QueryRow(ctx, updateBankAccount,
		arg.ID,
		arg.OrganisationID,
		arg.Name,
		arg.Currency,
		arg.Status,
		arg.IsPersonal,
		arg.IsPrimary,
		arg.BankName,
		arg.AccountNumber,
		arg.SortCode,
		arg.RoutingNumber,
		arg.BankAccountType,
		arg.Iban,
		arg.Bic,
		arg.ShowOnInvoices,
		arg.OpeningBalanceMinor,
		arg.OpeningBalanceDate,
		arg.GuessExplanations,
	)
	var i BankAccount
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.CreatedByUserID,
		&i.Name,
		&i.Currency,
		&i.Status,
		&i.IsPersonal,
		&i.IsPrimary,
		&i.BankName,
		&i.AccountNumber,
		&i.SortCode,
		&i.RoutingNumber,
		&i.BankAccountType,
		&i.Iban,
		&i.Bic,
		&i.ShowOnInvoices,
		&i.OpeningBalanceMinor,
		&i.OpeningBalanceDate,
		&i.GuessExplanations,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBankTransaction = `-- name: UpdateBankTransaction :one
UPDATE bank_transactions SET
    dated_on     = $3,
    amount_minor = $4,
    description  = $5,
    bank_memo    = $6,
    updated_at   = now()
WHERE id              = $1   -- transaction UUID
  AND organisation_id = $2   -- tenant scope
  AND deleted_at IS NULL
RETURNING id, organisation_id, bank_account_id, created_by_user_id, dated_on, amount_minor, description, bank_memo, balance_minor, unexplained_amount_minor, status, source, transaction_type, external_id, deleted_at, created_at, updated_at
`

type UpdateBankTransactionParams struct {
	ID             uuid.UUID   `json:"id"`
	OrganisationID uuid.UUID   `json:"organisation_id"`
	DatedOn        pgtype.Date `json:"dated_on"`
	AmountMinor    int64       `json:"amount_minor"`
	Description    pgtype.Text `json:"description"`
	BankMemo       pgtype.Text `json:"bank_memo"`
}

// -----------------------------------------------------------------------------
// UpdateBankTransaction  (the "update", manual lines only)
// Updates a transaction's user-editable fields. The service restricts this to
// source='manual' lines (a feed/statement line is the bank's truth and immutable);
// status / source / external_id / transaction_type are NOT changed on edit.
// updated_at is set explicitly in addition to the trigger. RETURNING * echoes the row.
// -----------------------------------------------------------------------------
func (q *Queries) UpdateBankTransaction(ctx context.Context, arg UpdateBankTransactionParams) (BankTransaction, error) {
	row := q.db.QueryRow(ctx, updateBankTransaction,
		arg.ID,
		arg.OrganisationID,
		arg.DatedOn,
		arg.AmountMinor,
		arg.Description,
		arg.BankMemo,
	)
	var i BankTransaction
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.BankAccountID,
		&i.CreatedByUserID,
		&i.DatedOn,
		&i.AmountMinor,
		&i.Description,
		&i.BankMemo,
		&i.BalanceMinor,
		&i.UnexplainedAmountMinor,
		&i.Status,
		&i.Source,
		&i.TransactionType,
		&i.ExternalID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateExplanation = `-- name: UpdateExplanation :one
UPDATE bank_transaction_explanations SET
    dated_on                 = $3,
    description              = $4,
    type                     = $5,
    gross_value_minor        = $6,
    category_id              = $7,
    sales_tax_status         = $8,
    sales_tax_rate_id        = $9,
    sales_tax_value_minor    = $10,
    is_manual_sales_tax      = $11,
    ec_status                = $12,
    place_of_supply          = $13,
    transfer_bank_account_id = $14,
    paid_user_id             = $15,
    paid_invoice_id          = $16,
    marked_for_review        = $17,
    cheque_number            = $18,
    receipt_reference        = $19,
    paid_bill_id             = $20
WHERE id              = $1
  AND organisation_id = $2
  AND deleted_at IS NULL
RETURNING id, organisation_id, bank_transaction_id, created_by_user_id, dated_on, description, type, gross_value_minor, category_id, sales_tax_status, sales_tax_rate_id, sales_tax_value_minor, is_manual_sales_tax, ec_status, place_of_supply, transfer_bank_account_id, paid_user_id, paid_invoice_id, paid_bill_id, marked_for_review, cheque_number, receipt_reference, deleted_at, created_at, updated_at
`

type UpdateExplanationParams struct {
	ID                    uuid.UUID   `json:"id"`
	OrganisationID        uuid.UUID   `json:"organisation_id"`
	DatedOn               pgtype.Date `json:"dated_on"`
	Description           pgtype.Text `json:"description"`
	Type                  string      `json:"type"`
	GrossValueMinor       int64       `json:"gross_value_minor"`
	CategoryID            pgtype.UUID `json:"category_id"`
	SalesTaxStatus        string      `json:"sales_tax_status"`
	SalesTaxRateID        pgtype.UUID `json:"sales_tax_rate_id"`
	SalesTaxValueMinor    int64       `json:"sales_tax_value_minor"`
	IsManualSalesTax      bool        `json:"is_manual_sales_tax"`
	EcStatus              pgtype.Text `json:"ec_status"`
	PlaceOfSupply         pgtype.Text `json:"place_of_supply"`
	TransferBankAccountID pgtype.UUID `json:"transfer_bank_account_id"`
	PaidUserID            pgtype.UUID `json:"paid_user_id"`
	PaidInvoiceID         pgtype.UUID `json:"paid_invoice_id"`
	MarkedForReview       bool        `json:"marked_for_review"`
	ChequeNumber          pgtype.Text `json:"cheque_number"`
	ReceiptReference      pgtype.Text `json:"receipt_reference"`
	PaidBillID            pgtype.UUID `json:"paid_bill_id"`
}

// -----------------------------------------------------------------------------
// UpdateExplanation — edit a live explanation (re-categorise, fix amount/VAT,
// confirm a guess). bank_transaction_id is NOT editable (no re-parenting). The
// recompute trigger refreshes the parent afterwards. Org-scoped. :one.
// -----------------------------------------------------------------------------
func (q *Queries) UpdateExplanation(ctx context.Context, arg UpdateExplanationParams) (BankTransactionExplanation, error) {
	row := q.db.QueryRow(ctx, updateExplanation,
		arg.ID,
		arg.OrganisationID,
		arg.DatedOn,
		arg.Description,
		arg.Type,
		arg.GrossValueMinor,
		arg.CategoryID,
		arg.SalesTaxStatus,
		arg.SalesTaxRateID,
		arg.SalesTaxValueMinor,
		arg.IsManualSalesTax,
		arg.EcStatus,
		arg.PlaceOfSupply,
		arg.TransferBankAccountID,
		arg.PaidUserID,
		arg.PaidInvoiceID,
		arg.MarkedForReview,
		arg.ChequeNumber,
		arg.ReceiptReference,
		arg.PaidBillID,
	)
	var i BankTransactionExplanation
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.BankTransactionID,
		&i.CreatedByUserID,
		&i.DatedOn,
		&i.Description,
		&i.Type,
		&i.GrossValueMinor,
		&i.CategoryID,
		&i.SalesTaxStatus,
		&i.SalesTaxRateID,
		&i.SalesTaxValueMinor,
		&i.IsManualSalesTax,
		&i.EcStatus,
		&i.PlaceOfSupply,
		&i.TransferBankAccountID,
		&i.PaidUserID,
		&i.PaidInvoiceID,
		&i.PaidBillID,
		&i.MarkedForReview,
		&i.ChequeNumber,
		&i.ReceiptReference,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
