// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package integrations

import (
	"context"
)

type Querier interface {
	// -----------------------------------------------------------------------------
	// ClearIntegrationTokens
	// Disconnect: drop the tokens but KEEP the client credentials (so reconnecting
	// doesn't require re-entering them). Also used when a refresh fails — clearing
	// connected_at surfaces "needs reconnect" on the settings screen.
	// -----------------------------------------------------------------------------
	ClearIntegrationTokens(ctx context.Context, arg ClearIntegrationTokensParams) error
	// -----------------------------------------------------------------------------
	// DeleteIntegration
	// Remove the connection entirely (credentials included). ON DELETE CASCADE
	// cleans up the integration_expense_pushes rows. Disconnect (above) is the
	// softer option; this is a full removal.
	// -----------------------------------------------------------------------------
	DeleteIntegration(ctx context.Context, arg DeleteIntegrationParams) error
	// -----------------------------------------------------------------------------
	// GetExpenseForPush
	// Assemble the provider-neutral data the workflow needs to build a push payload,
	// in one round-trip: the expense's money (as pence integers — the Go handler
	// formats them to decimal strings), its category's nominal_code, and the
	// claimant's email (the key the workflow matches against the external system's
	// users). Org-scoped + soft-delete-aware. ec_status is returned RAW; the
	// provider-specific vocabulary mapping happens in the workflow.
	// -----------------------------------------------------------------------------
	GetExpenseForPush(ctx context.Context, arg GetExpenseForPushParams) (GetExpenseForPushRow, error)
	// -----------------------------------------------------------------------------
	// GetExpensePushResult
	// Read the outcome row for an (integration, expense). The internal expense-read
	// endpoint uses this to compute `already_pushed` (a row whose external_expense_ref
	// is non-NULL means a prior push succeeded → the workflow exits early). :one —
	// pgx.ErrNoRows means "never attempted".
	// -----------------------------------------------------------------------------
	GetExpensePushResult(ctx context.Context, arg GetExpensePushResultParams) (IntegrationExpensePush, error)
	// -----------------------------------------------------------------------------
	// GetIntegration
	// The org's connection for a provider. Backed by the unique (organisation_id,
	// provider) index. Used everywhere we need the client creds, the tokens, or just
	// the integration_id (the internal endpoints all resolve org -> integration_id
	// through here). :one — callers treat pgx.ErrNoRows as "not configured".
	// -----------------------------------------------------------------------------
	GetIntegration(ctx context.Context, arg GetIntegrationParams) (OrganisationIntegration, error)
	// -----------------------------------------------------------------------------
	// SetIntegrationTokens
	// Store the tokens obtained from the OAuth token endpoint — on the initial
	// connect AND on every server-side refresh. Stamps connected_at = now() so the
	// status flips to "connected" (and a refresh keeps it connected).
	// -----------------------------------------------------------------------------
	SetIntegrationTokens(ctx context.Context, arg SetIntegrationTokensParams) error
	// -----------------------------------------------------------------------------
	// UpsertExpensePushResult
	// Record the outcome of a push, one row per (integration, expense). On success
	// external_expense_ref is the external URL and push_error is NULL; on failure
	// it's the reverse. The unique (integration_id, expense_id) key makes this an
	// UPSERT, so an Eventarc retry or a manual re-push updates the same row instead
	// of duplicating — this is the idempotency anchor for the whole flow.
	// -----------------------------------------------------------------------------
	UpsertExpensePushResult(ctx context.Context, arg UpsertExpensePushResultParams) error
	// =============================================================================
	// INTEGRATIONS MODULE — SQLC QUERIES
	// File: db/queries/integrations.sql
	//
	// Type-safe Go for the integrations tables defined in
	// db/schema/integrations_schema.sql. Generated by a DEDICATED sqlc block (see
	// sqlc.yaml) into package `integrations` at db/integrations.
	//
	// Named parameters (@name) are used throughout for clarity, matching the style
	// already used in db/queries/query.sql.
	//
	// Every query is ORGANISATION-SCOPED (multi-tenancy): the credential/token
	// queries key on (organisation_id, provider); the push-result queries reach the
	// tenant through integration_id; GetExpenseForPush re-checks organisation_id.
	// =============================================================================
	// -----------------------------------------------------------------------------
	// UpsertIntegrationCredentials
	// Save (or replace) the OAuth app credentials an admin enters on the settings
	// screen. Idempotent per (org, provider) via the unique key, so re-saving just
	// updates. Returns the row so the handler can report has_credentials/connected.
	// Tokens are deliberately NOT touched here — they are only set by the OAuth
	// connect flow (SetIntegrationTokens).
	// -----------------------------------------------------------------------------
	UpsertIntegrationCredentials(ctx context.Context, arg UpsertIntegrationCredentialsParams) (OrganisationIntegration, error)
}

var _ Querier = (*Queries)(nil)
