package bills

// service.go
// =============================================================================
// Service — the business logic layer for the bills domain.
//
// A bill is an accounts-PAYABLE record: a supplier's invoice the organisation
// owes. This service owns authorisation, validation, the VAT resolution and the
// mapping between the API shape (decimal pound strings) and the database shape
// (pence integers + pgx types). It is the payable twin of internal/invoices, but
// simpler: ONE flat spending line (no line items), NO auto-numbering, and NO
// status lifecycle.
//
//   HTTP handler (handler.go)
//     ↓
//   Service (this file)
//     ↓
//   *billsdb.Queries (db/bills — generated by sqlc)
//     ↓
//   PostgreSQL
//
// VAT (the EXPENSES pattern, see resolveVAT): the entered amount is the
// VAT-INCLUSIVE total. A fixed-ratio vat_rate has its VAT EXTRACTED from the total
// (money.ExtractVAT, the int64 twin of ComputeFixedVAT); a non-fixed-ratio
// ("manual") rate takes the VAT from the client's vat_amount. net = total − VAT.
//
// Lifecycle: none. A bill is editable/deletable only while UNPAID
// (paid_value_minor == 0); paid_value_minor is written by the banking module.
// Authorisation mirrors invoices/contacts: any active member may create/read/list;
// update/delete require the bill's creator OR an owner/admin.
// =============================================================================

import (
	"context"
	"errors"
	"fmt"
	"strings"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/jackc/pgx/v5/pgxpool"

	auth "github.com/operationfb/accounting-saas/db/auth"
	billsdb "github.com/operationfb/accounting-saas/db/bills"
	categoriesdb "github.com/operationfb/accounting-saas/db/categories"
	contactsdb "github.com/operationfb/accounting-saas/db/contacts"
	projectsdb "github.com/operationfb/accounting-saas/db/projects"
	vatdb "github.com/operationfb/accounting-saas/db/vat"
	"github.com/operationfb/accounting-saas/internal/kernel"
	"github.com/operationfb/accounting-saas/money"
)

// Service holds the connection pool, the bills query set, and the cross-domain
// query sets it needs to validate a bill's references: auth (membership/role + the
// org's country for VAT), contacts (the supplier), projects (the optional link),
// and categories (the spending account + the VAT rate it resolves).
type Service struct {
	pool            *pgxpool.Pool
	queries         *billsdb.Queries
	authQueries     auth.Querier
	contactQueries  contactsdb.Querier
	projectQueries  projectsdb.Querier
	categoryQueries categoriesdb.Querier
	vatQueries      *vatdb.Queries // the filed-period lock (IsDateInFiledPeriod)
}

// NewService is the constructor, called once in main.go. All the cross-domain
// queriers already exist there (shared with the other domains). vatQueries powers
// the filed-period lock: a bill dated in a filed VAT period can no longer change.
func NewService(
	pool *pgxpool.Pool,
	queries *billsdb.Queries,
	authQueries auth.Querier,
	contactQueries contactsdb.Querier,
	projectQueries projectsdb.Querier,
	categoryQueries categoriesdb.Querier,
	vatQueries *vatdb.Queries,
) *Service {
	return &Service{
		pool:            pool,
		queries:         queries,
		authQueries:     authQueries,
		contactQueries:  contactQueries,
		projectQueries:  projectQueries,
		categoryQueries: categoryQueries,
		vatQueries:      vatQueries,
	}
}

// assertNotFiled refuses the operation (409 conflict) when any of the given dates
// falls inside a FILED VAT period — a record that is part of a submitted VAT return
// must not change. Nil-safe: with no vat querier wired, the lock is simply inactive.
func (s *Service) assertNotFiled(ctx context.Context, orgID uuid.UUID, dates ...pgtype.Date) error {
	if s.vatQueries == nil {
		return nil
	}
	for _, d := range dates {
		if !d.Valid {
			continue
		}
		locked, err := s.vatQueries.IsDateInFiledPeriod(ctx, vatdb.IsDateInFiledPeriodParams{OrganisationID: orgID, DatedOn: d})
		if err != nil {
			return kernel.ErrInternal(err)
		}
		if locked {
			return kernel.ErrConflict("this bill is dated in a VAT period that has been filed, so it can no longer be changed")
		}
	}
	return nil
}

// =============================================================================
// AUTHORIZATION / VALIDATION
// =============================================================================

// authorize confirms the caller is an ACTIVE member of the organisation and
// returns their role (used to gate who may modify a bill).
func (s *Service) authorize(ctx context.Context, userID, orgID uuid.UUID) (auth.OrganisationRole, error) {
	return kernel.AuthorizeMember(ctx, s.authQueries, userID, orgID)
}

// validateContact confirms the supplier contact exists in the org (and isn't
// soft-deleted). GetContact already filters by org + deleted_at IS NULL.
func (s *Service) validateContact(ctx context.Context, contactID, orgID uuid.UUID) error {
	_, err := s.contactQueries.GetContact(ctx, contactsdb.GetContactParams{ID: contactID, OrganisationID: orgID})
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return kernel.ErrValidation("contact_id does not exist or does not belong to this organisation", nil)
		}
		return kernel.ErrInternal(err)
	}
	return nil
}

// validateCategory confirms category_id is a SPENDING account in the org — the same
// filter ListBillCategories applies to the picker, enforced here at write time so a
// bill can never point at an income / balance-sheet / system-managed account.
func (s *Service) validateCategory(ctx context.Context, categoryID, orgID uuid.UUID) error {
	cat, err := s.categoryQueries.GetCategory(ctx, categoriesdb.GetCategoryParams{ID: categoryID, OrganisationID: orgID})
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return kernel.ErrValidation("category_id does not exist or does not belong to this organisation", nil)
		}
		return kernel.ErrInternal(err)
	}
	if !cat.IsActive || cat.IsSystemManaged || !isSpendingAccount(cat.AccountType) {
		return kernel.ErrValidation("category_id is not a valid spending category", nil)
	}
	return nil
}

// resolveProject validates the optional project link and returns it as a pgtype.UUID
// (NULL when no project). A project_id that isn't in the caller's org is a 422.
func (s *Service) resolveProject(ctx context.Context, projectID *string, orgID uuid.UUID) (pgtype.UUID, error) {
	if projectID == nil || strings.TrimSpace(*projectID) == "" {
		return pgtype.UUID{}, nil
	}
	pid, err := uuid.Parse(strings.TrimSpace(*projectID))
	if err != nil {
		return pgtype.UUID{}, kernel.ErrValidation("project_id is not a valid UUID", err)
	}
	if _, err := s.projectQueries.GetProject(ctx, projectsdb.GetProjectParams{ID: pid, OrganisationID: orgID}); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return pgtype.UUID{}, kernel.ErrValidation("project_id does not exist or does not belong to this organisation", nil)
		}
		return pgtype.UUID{}, kernel.ErrInternal(err)
	}
	return pgUUID(pid), nil
}

// vatResult is the resolved VAT, ready to store on the bill row.
type vatResult struct {
	RateID     pgtype.UUID
	RateBps    pgtype.Int4
	ValueMinor int64
}

// resolveVAT turns the request's vat_rate_id (+ optional vat_amount) into the stored
// VAT fields — the EXPENSES pattern (see internal/expenses resolveVAT), but int64
// for BIGINT bill totals:
//   - no rate selected     → no VAT (NULL rate id/bps, value 0)
//   - fixed-ratio rate     → VAT EXTRACTED from the VAT-inclusive total
//     (money.ExtractVAT); any client amount is ignored (not an error)
//   - non-fixed-ratio rate → value = the client-supplied amount (0 if omitted)
//
// The selected rate must belong to the caller's organisation's country (the
// frontend only offers rates for that country); a mismatch is a validation error.
func (s *Service) resolveVAT(ctx context.Context, authOrgID uuid.UUID, grossMinor int64, vatRateID, vatAmount *string) (vatResult, error) {
	if vatRateID == nil || strings.TrimSpace(*vatRateID) == "" {
		return vatResult{}, nil
	}

	rateUUID, err := uuid.Parse(strings.TrimSpace(*vatRateID))
	if err != nil {
		return vatResult{}, kernel.ErrValidation("vat_rate_id is not a valid UUID", err)
	}

	rate, err := s.categoryQueries.GetVatRate(ctx, rateUUID)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return vatResult{}, kernel.ErrValidation("vat_rate_id not found", nil)
		}
		return vatResult{}, kernel.ErrInternal(err)
	}

	// The rate must be for the caller's organisation's country. The token carries
	// only the org id; the country_code lives on the organisation (auth domain).
	org, err := s.authQueries.GetOrganisation(ctx, authOrgID)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return vatResult{}, kernel.ErrNotFound("organisation", authOrgID.String())
		}
		return vatResult{}, kernel.ErrInternal(err)
	}
	if rate.CountryCode != org.CountryCode {
		return vatResult{}, kernel.ErrValidation("selected VAT rate is not valid for your organisation's country", nil)
	}

	var valueMinor int64
	if rate.IsFixedRatio {
		// Rate-locked: extract the VAT from the inclusive total; ignore any client amount.
		valueMinor = money.ExtractVAT(grossMinor, rate.RateBps)
	} else if vatAmount != nil {
		// Manual rate: accept the client's amount as-is (pounds → pence).
		minor, err := money.PoundsToMinor(strings.TrimSpace(*vatAmount))
		if err != nil {
			return vatResult{}, kernel.ErrValidation(fmt.Sprintf("vat_amount %q is not a valid decimal number", *vatAmount), err)
		}
		valueMinor = minor
	}

	return vatResult{
		RateID:     pgUUID(rateUUID),
		RateBps:    pgtype.Int4{Int32: rate.RateBps, Valid: true},
		ValueMinor: valueMinor,
	}, nil
}

// billInput is the validated, ready-to-store result of vetting a create/update body.
type billInput struct {
	contactID  uuid.UUID
	categoryID uuid.UUID
	projectID  pgtype.UUID
	reference  string
	datedOn    pgtype.Date
	dueOn      pgtype.Date
	currency   string
	comments   pgtype.Text
	hp         bool
	vat        vatResult
	net        int64
	total      int64
}

// vet validates every field of a create/update request (shared so the rules live in
// one place). All errors here are 400/422s independent of which bill is being saved.
func (s *Service) vet(ctx context.Context, authOrgID uuid.UUID, contactID, reference, datedOn string, dueOn *string, currency string, comments *string, hp bool, categoryID, total string, vatRateID, vatAmount, projectID *string) (billInput, error) {
	var in billInput

	ref, err := validateReference(reference)
	if err != nil {
		return in, err
	}
	in.reference = ref

	in.contactID, err = uuid.Parse(contactID)
	if err != nil {
		return in, kernel.ErrValidation("contact_id is not a valid UUID", err)
	}
	if err := s.validateContact(ctx, in.contactID, authOrgID); err != nil {
		return in, err
	}

	in.categoryID, err = uuid.Parse(categoryID)
	if err != nil {
		return in, kernel.ErrValidation("category_id is not a valid UUID", err)
	}
	if err := s.validateCategory(ctx, in.categoryID, authOrgID); err != nil {
		return in, err
	}

	in.projectID, err = s.resolveProject(ctx, projectID, authOrgID)
	if err != nil {
		return in, err
	}

	in.datedOn, err = parseDate("dated_on", datedOn)
	if err != nil {
		return in, err
	}
	in.dueOn, err = parseOptionalDate("due_on", dueOn)
	if err != nil {
		return in, err
	}

	in.total, err = money.PoundsToMinor(strings.TrimSpace(total))
	if err != nil {
		return in, kernel.ErrValidation("total is not a valid amount", err)
	}

	in.vat, err = s.resolveVAT(ctx, authOrgID, in.total, vatRateID, vatAmount)
	if err != nil {
		return in, err
	}
	in.net = in.total - in.vat.ValueMinor

	in.currency = normaliseCurrency(currency)
	in.comments = kernel.NullText(comments)
	in.hp = hp
	return in, nil
}

// =============================================================================
// CREATE
// =============================================================================

// CreateBill validates the request, resolves VAT and writes the bill. The owning
// org + creator come from the token. Any active member may create a bill.
func (s *Service) CreateBill(ctx context.Context, authUserID, authOrgID uuid.UUID, req CreateBillRequest) (*BillResponse, error) {
	if _, err := s.authorize(ctx, authUserID, authOrgID); err != nil {
		return nil, err
	}

	in, err := s.vet(ctx, authOrgID, req.ContactID, req.Reference, req.DatedOn, req.DueOn, req.Currency, req.Comments, req.IsHirePurchase, req.CategoryID, req.Total, req.VATRateID, req.VATAmount, req.ProjectID)
	if err != nil {
		return nil, err
	}

	// Can't create a bill dated inside an already-filed VAT period.
	if err := s.assertNotFiled(ctx, authOrgID, in.datedOn); err != nil {
		return nil, err
	}

	bill, err := s.queries.CreateBill(ctx, billsdb.CreateBillParams{
		OrganisationID:     authOrgID,
		CreatedByUserID:    authUserID,
		ContactID:          in.contactID,
		Reference:          pgtype.Text{String: in.reference, Valid: true},
		DatedOn:            in.datedOn,
		DueOn:              in.dueOn,
		Currency:           in.currency,
		Comments:           in.comments,
		IsHirePurchase:     in.hp,
		CategoryID:         in.categoryID,
		VatRateID:          in.vat.RateID,
		VatRateBps:         in.vat.RateBps,
		NetValueMinor:      in.net,
		SalesTaxValueMinor: in.vat.ValueMinor,
		TotalValueMinor:    in.total,
		ProjectID:          in.projectID,
	})
	if err != nil {
		return nil, kernel.ErrInternal(err)
	}
	return billToResponse(bill), nil
}

// =============================================================================
// GET / LIST
// =============================================================================

// GetBill fetches one bill, org-scoped. Any active member may read.
func (s *Service) GetBill(ctx context.Context, authUserID, authOrgID uuid.UUID, id string) (*BillResponse, error) {
	billID, err := uuid.Parse(id)
	if err != nil {
		return nil, kernel.ErrValidation("id is not a valid UUID", err)
	}
	if _, err := s.authorize(ctx, authUserID, authOrgID); err != nil {
		return nil, err
	}
	bill, err := s.queries.GetBill(ctx, billsdb.GetBillParams{ID: billID, OrganisationID: authOrgID})
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, kernel.ErrNotFound("bill", id)
		}
		return nil, kernel.ErrInternal(err)
	}
	return billToResponse(bill), nil
}

// ListBills returns the org's bills, newest first. Any active member may list.
func (s *Service) ListBills(ctx context.Context, authUserID, authOrgID uuid.UUID) ([]*BillResponse, error) {
	if _, err := s.authorize(ctx, authUserID, authOrgID); err != nil {
		return nil, err
	}
	rows, err := s.queries.ListBills(ctx, authOrgID)
	if err != nil {
		return nil, kernel.ErrInternal(err)
	}
	out := make([]*BillResponse, 0, len(rows))
	for _, b := range rows {
		out = append(out, billToResponse(b))
	}
	return out, nil
}

// ListOutstandingBills returns the org's bills that still owe money (due_value > 0),
// oldest first. Backs the banking "Bill Payment" explanation picker. Any active member.
func (s *Service) ListOutstandingBills(ctx context.Context, authUserID, authOrgID uuid.UUID) ([]*BillResponse, error) {
	if _, err := s.authorize(ctx, authUserID, authOrgID); err != nil {
		return nil, err
	}
	rows, err := s.queries.ListOutstandingBills(ctx, authOrgID)
	if err != nil {
		return nil, kernel.ErrInternal(err)
	}
	out := make([]*BillResponse, 0, len(rows))
	for _, b := range rows {
		out = append(out, billToResponse(b))
	}
	return out, nil
}

// =============================================================================
// UPDATE
// =============================================================================

// UpdateBill fully replaces a bill's editable fields. The load + ownership + unpaid
// guards run inside one transaction to close the check-then-write race. Allowed to
// the creator or an owner/admin; only an UNPAID bill may be edited (else 409).
func (s *Service) UpdateBill(ctx context.Context, authUserID, authOrgID uuid.UUID, id string, req UpdateBillRequest) (*BillResponse, error) {
	billID, err := uuid.Parse(id)
	if err != nil {
		return nil, kernel.ErrValidation("id is not a valid UUID", err)
	}
	role, err := s.authorize(ctx, authUserID, authOrgID)
	if err != nil {
		return nil, err
	}

	// Validate the request up-front (400/422s independent of DB state).
	in, err := s.vet(ctx, authOrgID, req.ContactID, req.Reference, req.DatedOn, req.DueOn, req.Currency, req.Comments, req.IsHirePurchase, req.CategoryID, req.Total, req.VATRateID, req.VATAmount, req.ProjectID)
	if err != nil {
		return nil, err
	}

	var resp *BillResponse
	err = kernel.WithTx(ctx, s.pool, func(tx pgx.Tx) error {
		qtx := s.queries.WithTx(tx)

		existing, err := qtx.GetBill(ctx, billsdb.GetBillParams{ID: billID, OrganisationID: authOrgID})
		if err != nil {
			if errors.Is(err, pgx.ErrNoRows) {
				return kernel.ErrNotFound("bill", id)
			}
			return kernel.ErrInternal(err)
		}
		if existing.CreatedByUserID != authUserID && !kernel.IsOrgAdmin(role) {
			return kernel.ErrForbidden("you do not have access to this bill")
		}
		if existing.PaidValueMinor != 0 {
			return kernel.ErrConflict("a bill that has payments recorded against it cannot be edited — remove the bank payment(s) first")
		}
		// Locked if the bill's CURRENT date is in a filed period, or it's being MOVED
		// into one.
		if err := s.assertNotFiled(ctx, authOrgID, existing.DatedOn, in.datedOn); err != nil {
			return err
		}

		updated, err := qtx.UpdateBill(ctx, billsdb.UpdateBillParams{
			ID:                 billID,
			OrganisationID:     authOrgID,
			ContactID:          in.contactID,
			Reference:          pgtype.Text{String: in.reference, Valid: true},
			DatedOn:            in.datedOn,
			DueOn:              in.dueOn,
			Currency:           in.currency,
			Comments:           in.comments,
			IsHirePurchase:     in.hp,
			CategoryID:         in.categoryID,
			VatRateID:          in.vat.RateID,
			VatRateBps:         in.vat.RateBps,
			NetValueMinor:      in.net,
			SalesTaxValueMinor: in.vat.ValueMinor,
			TotalValueMinor:    in.total,
			ProjectID:          in.projectID,
		})
		if err != nil {
			return kernel.ErrInternal(err)
		}
		resp = billToResponse(updated)
		return nil
	})
	if err != nil {
		return nil, err
	}
	return resp, nil
}

// =============================================================================
// DELETE
// =============================================================================

// DeleteBill soft-deletes a bill. Allowed to the creator or an owner/admin; only an
// UNPAID bill may be deleted (else 409). Load + guards + write run in one transaction.
func (s *Service) DeleteBill(ctx context.Context, authUserID, authOrgID uuid.UUID, id string) error {
	billID, err := uuid.Parse(id)
	if err != nil {
		return kernel.ErrValidation("id is not a valid UUID", err)
	}
	role, err := s.authorize(ctx, authUserID, authOrgID)
	if err != nil {
		return err
	}

	return kernel.WithTx(ctx, s.pool, func(tx pgx.Tx) error {
		qtx := s.queries.WithTx(tx)

		existing, err := qtx.GetBill(ctx, billsdb.GetBillParams{ID: billID, OrganisationID: authOrgID})
		if err != nil {
			if errors.Is(err, pgx.ErrNoRows) {
				return kernel.ErrNotFound("bill", id)
			}
			return kernel.ErrInternal(err)
		}
		if existing.CreatedByUserID != authUserID && !kernel.IsOrgAdmin(role) {
			return kernel.ErrForbidden("you do not have access to this bill")
		}
		if existing.PaidValueMinor != 0 {
			return kernel.ErrConflict("a bill that has payments recorded against it cannot be deleted — remove the bank payment(s) first")
		}
		if err := s.assertNotFiled(ctx, authOrgID, existing.DatedOn); err != nil {
			return err
		}

		if err := qtx.SoftDeleteBill(ctx, billsdb.SoftDeleteBillParams{ID: billID, OrganisationID: authOrgID}); err != nil {
			return kernel.ErrInternal(err)
		}
		return nil
	})
}

// =============================================================================
// CATEGORY PICKER
// =============================================================================

// ListBillCategories returns the SPENDING subset of the org's Chart of Accounts —
// the "Spending Category" dropdown on the bill form. Any active member may list.
func (s *Service) ListBillCategories(ctx context.Context, authUserID, authOrgID uuid.UUID) ([]*BillCategoryResponse, error) {
	if _, err := s.authorize(ctx, authUserID, authOrgID); err != nil {
		return nil, err
	}
	rows, err := s.queries.ListBillCategories(ctx, authOrgID)
	if err != nil {
		return nil, kernel.ErrInternal(err)
	}
	out := make([]*BillCategoryResponse, 0, len(rows))
	for _, r := range rows {
		out = append(out, &BillCategoryResponse{
			ID:          r.ID.String(),
			NominalCode: r.NominalCode,
			Name:        r.Name,
			AccountType: r.AccountType,
			ApiGroup:    kernel.NullTextToPtr(r.ApiGroup),
			DefaultVat:  kernel.NullTextToPtr(r.DefaultVat),
		})
	}
	return out, nil
}

// =============================================================================
// RESPONSE BUILDER + HELPERS
// =============================================================================

// billToResponse maps a bill row to the API shape (pence→pounds strings, derived
// display status).
func billToResponse(b billsdb.Bill) *BillResponse {
	return &BillResponse{
		ID:              b.ID.String(),
		OrganisationID:  b.OrganisationID.String(),
		CreatedByUserID: b.CreatedByUserID.String(),
		ContactID:       b.ContactID.String(),
		Reference:       kernel.NullTextToPtr(b.Reference),
		DatedOn:         b.DatedOn.Time.Format("2006-01-02"),
		DueOn:           dateToStringPtr(b.DueOn),
		Currency:        b.Currency,
		Comments:        kernel.NullTextToPtr(b.Comments),
		IsHirePurchase:  b.IsHirePurchase,
		CategoryID:      b.CategoryID.String(),
		VATRateID:       uuidToStringPtr(b.VatRateID),
		VATRate:         vatRateDisplay(b.VatRateBps),
		NetValue:        money.MinorToPounds(b.NetValueMinor),
		SalesTaxValue:   money.MinorToPounds(b.SalesTaxValueMinor),
		TotalValue:      money.MinorToPounds(b.TotalValueMinor),
		PaidValue:       money.MinorToPounds(b.PaidValueMinor),
		DueValue:        money.MinorToPounds(dueValueMinor(b)),
		DisplayStatus:   deriveDisplayStatus(b),
		ProjectID:       uuidToStringPtr(b.ProjectID),
		CreatedAt:       b.CreatedAt.Time.Format(time.RFC3339),
		UpdatedAt:       b.UpdatedAt.Time.Format(time.RFC3339),
	}
}

// deriveDisplayStatus computes the user-facing label from money + due date. There is
// no stored status; this is derived at read time so it never goes stale. paid is
// written by the banking module.
func deriveDisplayStatus(b billsdb.Bill) string {
	total := b.TotalValueMinor
	paid := b.PaidValueMinor
	switch {
	case total == 0:
		return "Zero Value"
	case paid >= total:
		return "Paid"
	case b.DueOn.Valid && b.DueOn.Time.Before(todayUTC()):
		return "Overdue"
	case paid > 0:
		return "Part paid"
	default:
		return "Unpaid"
	}
}

// isSpendingAccount reports whether a CoA account_type is a spending account a bill
// may post to — the same set ListBillCategories filters the picker to.
func isSpendingAccount(accountType string) bool {
	switch accountType {
	case "COST_OF_SALES", "ADMIN_EXPENSE", "CAPITAL_ASSET":
		return true
	default:
		return false
	}
}

// validateReference trims the (required) supplier reference and rejects an empty /
// whitespace-only value (422). The handler's `required` binding already rejects a
// missing/empty field as a 400; this guards a whitespace-only one.
func validateReference(raw string) (string, error) {
	ref := strings.TrimSpace(raw)
	if ref == "" {
		return "", kernel.ErrValidation("reference is required", nil)
	}
	return ref, nil
}

// parseDate parses a required YYYY-MM-DD string into a pgtype.Date.
func parseDate(field, s string) (pgtype.Date, error) {
	t, err := time.Parse("2006-01-02", strings.TrimSpace(s))
	if err != nil {
		return pgtype.Date{}, kernel.ErrValidation(field+" must be a valid date in YYYY-MM-DD format", err)
	}
	return pgtype.Date{Time: t, Valid: true}, nil
}

// parseOptionalDate parses an optional YYYY-MM-DD pointer; nil/blank → SQL NULL.
func parseOptionalDate(field string, s *string) (pgtype.Date, error) {
	if s == nil || strings.TrimSpace(*s) == "" {
		return pgtype.Date{}, nil
	}
	return parseDate(field, *s)
}

// normaliseCurrency upper-cases the currency and defaults a blank to GBP.
func normaliseCurrency(c string) string {
	c = strings.ToUpper(strings.TrimSpace(c))
	if c == "" {
		return "GBP"
	}
	return c
}

// dateToStringPtr renders a nullable date as a YYYY-MM-DD *string; nil when NULL.
func dateToStringPtr(d pgtype.Date) *string {
	if !d.Valid {
		return nil
	}
	s := d.Time.Format("2006-01-02")
	return &s
}

// dueValueMinor returns the outstanding amount. due_value_minor is a generated
// column (read-only, nullable in Go); fall back to total − paid if not populated.
func dueValueMinor(b billsdb.Bill) int64 {
	if b.DueValueMinor.Valid {
		return b.DueValueMinor.Int64
	}
	return b.TotalValueMinor - b.PaidValueMinor
}

// vatRateDisplay renders the stored rate snapshot as a percent string ("20%"); "" when
// no rate was selected.
func vatRateDisplay(bps pgtype.Int4) string {
	if !bps.Valid {
		return ""
	}
	return money.BpsToPercent(bps.Int32)
}

// pgUUID wraps a uuid.UUID as a non-null pgtype.UUID.
func pgUUID(u uuid.UUID) pgtype.UUID {
	return pgtype.UUID{Bytes: u, Valid: true}
}

// uuidToStringPtr renders a nullable pgtype.UUID as a *string; nil when NULL.
func uuidToStringPtr(u pgtype.UUID) *string {
	if !u.Valid {
		return nil
	}
	s := uuid.UUID(u.Bytes).String()
	return &s
}

// todayUTC is midnight today in UTC — the cutoff for "overdue" (a bill due strictly
// before today is overdue; due today is not).
func todayUTC() time.Time {
	now := time.Now().UTC()
	return time.Date(now.Year(), now.Month(), now.Day(), 0, 0, 0, 0, time.UTC)
}
