package members

// service.go
// =============================================================================
// Service — the business logic layer for organisation members.
//
// A "member" is a user's membership in an organisation (the row in
// organisation_memberships joined to their users row). This is the first service
// in the auth/membership domain; until now that domain only had auth_handler.go
// (login). It is structured exactly like ContactService / ExpenseService:
//
//   HTTP handler (server.go)
//     ↓
//   Service (this file)
//     ↓
//   auth.Querier (db/auth — generated by sqlc)
//     ↓
//   PostgreSQL
//
// The one behavioural difference from the "any active member" services: listing
// members is privileged — only an owner or admin of the organisation may see it
// (it backs a future "Team / Manage users" screen). The gate is on the CALLER,
// not on which members are returned.
//
// It reuses the shared kernel: kernel.AuthorizeMember / kernel.IsOrgAdmin for the
// membership+role check, kernel.NullTextToPtr / kernel.TimestampToStringPtr for the
// nullable columns, and the kernel.Err* constructors. Nothing new to add — this is
// a thin, read-only service with no money and no transaction.
// =============================================================================

import (
	"context"
	"errors"
	"strings"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/jackc/pgx/v5/pgxpool"
	"golang.org/x/crypto/bcrypt"

	auth "github.com/operationfb/accounting-saas/db/auth"
	"github.com/operationfb/accounting-saas/internal/kernel"
)

// Service holds the auth query set plus the pool. Listing/reading a member is a
// single read-only query (uses authQueries directly), but editing a member writes
// the users row AND the membership row, so UpdateMember runs them in one
// transaction via the pool (kernel.WithTx + auth.New(tx)).
type Service struct {
	pool        *pgxpool.Pool
	authQueries auth.Querier
}

// NewService is the constructor, called once in main.go. authQueries is the
// same auth.Querier already shared with the other services; pool is the shared
// pgx pool used by UpdateMember's transaction.
func NewService(pool *pgxpool.Pool, authQueries auth.Querier) *Service {
	return &Service{pool: pool, authQueries: authQueries}
}

// =============================================================================
// AUTHORIZATION
// =============================================================================

// authorize confirms the caller is an ACTIVE member of the organisation and
// returns their role; it delegates to the shared kernel.AuthorizeMember (authz.go).
// Non-members and deactivated members are refused (403). The returned role lets
// ListMembers gate the list to owners/admins.
func (s *Service) authorize(ctx context.Context, userID, orgID uuid.UUID) (auth.OrganisationRole, error) {
	return kernel.AuthorizeMember(ctx, s.authQueries, userID, orgID)
}

// =============================================================================
// LIST
// =============================================================================

// ListMembers returns every member of the caller's organisation, restricted to
// callers who are an owner or admin. The organisation is taken from the
// authenticated token (authOrgID), never a request param, so a caller can only
// ever list their own org's members.
//
// The underlying query returns members of ALL statuses (active / invited /
// suspended / deactivated) as long as the user is not soft-deleted; the Status
// field on each row lets the UI distinguish them.
func (s *Service) ListMembers(
	ctx context.Context,
	authUserID uuid.UUID,
	authOrgID uuid.UUID,
) ([]*MemberResponse, error) {
	// Step 1: the caller must be an active member, and specifically an owner/admin.
	role, err := s.authorize(ctx, authUserID, authOrgID)
	if err != nil {
		return nil, err
	}
	if !kernel.IsOrgAdmin(role) {
		return nil, kernel.ErrForbidden("only owners and admins can view the members list")
	}

	// Step 2: fetch the org's members (org-scoped by the query's WHERE clause).
	rows, err := s.authQueries.ListMembersByOrganisation(ctx, authOrgID)
	if err != nil {
		return nil, kernel.ErrInternal(err)
	}

	// Step 3: convert the DB rows into the API response shape.
	out := make([]*MemberResponse, 0, len(rows))
	for _, r := range rows {
		out = append(out, memberToResponse(r))
	}
	return out, nil
}

// =============================================================================
// RESPONSE FORMATTER
// =============================================================================

// memberToResponse converts a database row (pgx types, UUIDs, enum) into the API
// response shape (plain/optional strings). MemberSince comes from the membership's
// NOT NULL created_at, so it formats directly; AvatarUrl and LastLoginAt are
// nullable and use the shared null-aware helpers from expense_service.go.
func memberToResponse(r auth.ListMembersByOrganisationRow) *MemberResponse {
	return &MemberResponse{
		MembershipID: r.MembershipID.String(),
		UserID:       r.UserID.String(),
		Email:        r.Email,
		FirstName:    r.FirstName,
		LastName:     r.LastName,
		Role:         string(r.Role),
		Status:       r.Status,
		AvatarURL:    kernel.NullTextToPtr(r.AvatarUrl),
		MemberSince:  r.MemberSince.Time.Format(time.RFC3339),
		LastLoginAt:  kernel.TimestampToStringPtr(r.LastLoginAt),
	}
}

// =============================================================================
// CREATE (admin)
// =============================================================================

// CreateMember creates a brand-new user and attaches them to the caller's
// organisation as an ACTIVE member. Owner/admin only. The admin supplies an
// initial password (bcrypt-hashed here, like the reset-password path), so the new
// user can log in immediately — there is no email-invite step (that flow stays
// deferred; see BACKLOG).
//
// Scope: this only ever CREATES a fresh user. If the email already belongs to an
// existing user we return 409 rather than attaching that user to a second org
// (out of scope for now). The org is the caller's, from the token — never a param.
//
// The user row and the membership row are written in ONE transaction so a partial
// failure can't leave a user with no membership. The response is the same rich
// MemberDetailResponse that GetMember returns (re-read after commit).
func (s *Service) CreateMember(
	ctx context.Context,
	authUserID, authOrgID uuid.UUID,
	req CreateMemberRequest,
) (*MemberDetailResponse, error) {
	// Only owners/admins may add users.
	role, err := s.authorize(ctx, authUserID, authOrgID)
	if err != nil {
		return nil, err
	}
	if !kernel.IsOrgAdmin(role) {
		return nil, kernel.ErrForbidden("only owners and admins can add users")
	}

	// Names: binding catches missing; re-check after trim to reject whitespace-only.
	firstName := strings.TrimSpace(req.FirstName)
	lastName := strings.TrimSpace(req.LastName)
	if firstName == "" {
		return nil, kernel.ErrValidation("first_name is required", nil)
	}
	if lastName == "" {
		return nil, kernel.ErrValidation("last_name is required", nil)
	}
	// Email is stored/compared lowercase (the unique index and login both lowercase).
	email := strings.ToLower(strings.TrimSpace(req.Email))

	// Pre-check for an existing user with this email. The global users.email unique
	// index would reject a duplicate anyway, but checking first gives a clean 409.
	if _, err := s.authQueries.GetUserByEmail(ctx, email); err == nil {
		return nil, kernel.ErrConflict("a user with this email already exists")
	} else if !errors.Is(err, pgx.ErrNoRows) {
		return nil, kernel.ErrInternal(err)
	}

	// Hash the initial password (cost 12, same as login/reset).
	hash, err := bcrypt.GenerateFromPassword([]byte(req.Password), 12)
	if err != nil {
		return nil, kernel.ErrInternal(err)
	}

	// One transaction: create the user, then the active membership linking them to
	// this org. A unique violation on email (a race past the pre-check) maps to 409.
	var newUserID uuid.UUID
	err = kernel.WithTx(ctx, s.pool, func(tx pgx.Tx) error {
		qtx := auth.New(tx)

		user, err := qtx.CreateUser(ctx, auth.CreateUserParams{
			Email:        email,
			PasswordHash: pgtype.Text{String: string(hash), Valid: true},
			FirstName:    firstName,
			LastName:     lastName,
			Phone:        pgtype.Text{}, // not collected on this form
		})
		if err != nil {
			if kernel.IsUniqueViolation(err) {
				return kernel.ErrConflict("a user with this email already exists")
			}
			return kernel.ErrInternal(err)
		}
		newUserID = user.ID

		if _, err := qtx.CreateMembership(ctx, auth.CreateMembershipParams{
			OrganisationID: authOrgID,
			UserID:         user.ID,
			Role:           auth.OrganisationRole(req.Role),
			Status:         "active",
		}); err != nil {
			return kernel.ErrInternal(err)
		}
		return nil
	})
	if err != nil {
		return nil, err
	}

	// Re-read so the response reflects the committed state (member_since, etc.),
	// matching GetMember's shape.
	membership, user, err := s.loadMember(ctx, authOrgID, newUserID)
	if err != nil {
		return nil, err
	}
	resp := memberDetailToResponse(membership, user)
	resp.Payroll, err = s.loadPayrollDTO(ctx, authOrgID, newUserID)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

// =============================================================================
// GET ONE (admin)
// =============================================================================

// GetMember returns one member's full detail (profile + payroll + role/status)
// for the admin User Details screen. Owner/admin only. The org is the caller's
// (from the token); the target is composed from its membership row (role/status,
// member_since) joined in Go with its users row (names, email, payroll fields,
// last_login). A target that is not a member of the caller's org — including any
// cross-tenant user — has no membership row, so it 404s (multi-tenant isolation).
func (s *Service) GetMember(
	ctx context.Context,
	authUserID, authOrgID, targetUserID uuid.UUID,
) (*MemberDetailResponse, error) {
	role, err := s.authorize(ctx, authUserID, authOrgID)
	if err != nil {
		return nil, err
	}
	if !kernel.IsOrgAdmin(role) {
		return nil, kernel.ErrForbidden("only owners and admins can view user details")
	}

	membership, user, err := s.loadMember(ctx, authOrgID, targetUserID)
	if err != nil {
		return nil, err
	}
	resp := memberDetailToResponse(membership, user)
	resp.Payroll, err = s.loadPayrollDTO(ctx, authOrgID, targetUserID)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

// =============================================================================
// UPDATE (admin)
// =============================================================================

// UpdateMember edits another user's profile + payroll fields and their membership
// role/status. Owner/admin only; the target must be a member of the caller's org
// (else 404). Two safety guards beyond the role gate:
//
//   - Self lock-out: the caller may not change THEIR OWN role or status here (they
//     could otherwise demote/deactivate themselves). Editing your own name/payroll
//     is fine; the dedicated path is /api/v1/profile anyway.
//   - Owner protection: only an owner may assign the owner role or modify an
//     existing owner. An admin can manage everyone below them, not their owner.
//
// The users update and the two membership updates run in ONE transaction so a
// partial save can't leave role/status and the profile out of sync.
func (s *Service) UpdateMember(
	ctx context.Context,
	authUserID, authOrgID, targetUserID uuid.UUID,
	req UpdateMemberRequest,
) (*MemberDetailResponse, error) {
	callerRole, err := s.authorize(ctx, authUserID, authOrgID)
	if err != nil {
		return nil, err
	}
	if !kernel.IsOrgAdmin(callerRole) {
		return nil, kernel.ErrForbidden("only owners and admins can edit users")
	}

	// Names: binding catches missing; re-check after trim to reject whitespace-only.
	firstName := strings.TrimSpace(req.FirstName)
	lastName := strings.TrimSpace(req.LastName)
	if firstName == "" {
		return nil, kernel.ErrValidation("first_name is required", nil)
	}
	if lastName == "" {
		return nil, kernel.ErrValidation("last_name is required", nil)
	}
	newRole := auth.OrganisationRole(req.Role)

	// Payroll fields — same shared validators as the self path.
	nino, err := kernel.ParseNINO(req.NationalInsuranceNumber)
	if err != nil {
		return nil, err
	}
	utr, err := kernel.ParseUTR(req.UTR)
	if err != nil {
		return nil, err
	}
	dob, err := kernel.ParseDateOfBirth(req.DateOfBirth)
	if err != nil {
		return nil, err
	}

	// Optional payroll block — parse + validate (money→pence, enums, dates) up front
	// so a 422 is returned before we open the transaction. nil when not editing payroll.
	var payrollParams *auth.UpsertEmployeePayrollParams
	if req.Payroll != nil {
		p, perr := buildPayrollParams(authOrgID, targetUserID, req.Payroll)
		if perr != nil {
			return nil, perr
		}
		payrollParams = &p
	}

	// Load the target (404 if not a member of this org / soft-deleted).
	membership, _, err := s.loadMember(ctx, authOrgID, targetUserID)
	if err != nil {
		return nil, err
	}

	// Guard: self role/status change.
	if targetUserID == authUserID &&
		(newRole != membership.Role || req.Status != membership.Status) {
		return nil, kernel.ErrForbidden("you cannot change your own role or status")
	}

	// Guard: only an owner may touch the owner role (assign it, or edit an owner).
	if (membership.Role == auth.OrganisationRoleOwner || newRole == auth.OrganisationRoleOwner) &&
		callerRole != auth.OrganisationRoleOwner {
		return nil, kernel.ErrForbidden("only an owner can assign or modify the owner role")
	}

	// One transaction: profile/payroll on users, then role + status on the
	// membership. Read-modify-write preserves the user columns this form doesn't
	// own (phone, avatar_url).
	err = kernel.WithTx(ctx, s.pool, func(tx pgx.Tx) error {
		qtx := auth.New(tx)

		existing, err := qtx.GetUser(ctx, targetUserID)
		if err != nil {
			if errors.Is(err, pgx.ErrNoRows) {
				return kernel.ErrNotFound("user", targetUserID.String())
			}
			return kernel.ErrInternal(err)
		}

		if _, err := qtx.UpdateUser(ctx, auth.UpdateUserParams{
			ID:                      targetUserID,
			FirstName:               firstName,
			LastName:                lastName,
			Phone:                   existing.Phone,     // preserved
			AvatarUrl:               existing.AvatarUrl, // preserved
			NationalInsuranceNumber: nino,
			Utr:                     utr,
			DateOfBirth:             dob,
			AddressLine1:            kernel.NullText(req.AddressLine1),
			AddressLine2:            kernel.NullText(req.AddressLine2),
			AddressLine3:            kernel.NullText(req.AddressLine3),
			AddressLine4:            kernel.NullText(req.AddressLine4),
			Postcode:                kernel.NullText(req.Postcode),
		}); err != nil {
			return kernel.ErrInternal(err)
		}

		if err := qtx.UpdateMembershipRole(ctx, auth.UpdateMembershipRoleParams{
			OrganisationID: authOrgID,
			UserID:         targetUserID,
			Role:           newRole,
		}); err != nil {
			return kernel.ErrInternal(err)
		}

		if err := qtx.UpdateMembershipStatus(ctx, auth.UpdateMembershipStatusParams{
			OrganisationID: authOrgID,
			UserID:         targetUserID,
			Status:         req.Status,
		}); err != nil {
			return kernel.ErrInternal(err)
		}

		// Payroll, in the same transaction (upsert: creates on first save).
		if payrollParams != nil {
			if _, err := qtx.UpsertEmployeePayroll(ctx, *payrollParams); err != nil {
				return kernel.ErrInternal(err)
			}
		}
		return nil
	})
	if err != nil {
		return nil, err
	}

	// Re-read so the response reflects the committed state (including member_since
	// and avatar we didn't touch).
	membership, user, err := s.loadMember(ctx, authOrgID, targetUserID)
	if err != nil {
		return nil, err
	}
	resp := memberDetailToResponse(membership, user)
	resp.Payroll, err = s.loadPayrollDTO(ctx, authOrgID, targetUserID)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

// loadMember fetches the (membership, user) pair for a target in the caller's org,
// mapping a missing membership OR a soft-deleted user to a 404. Shared by GetMember
// and UpdateMember so the isolation rule lives in one place.
func (s *Service) loadMember(
	ctx context.Context,
	orgID, targetUserID uuid.UUID,
) (auth.OrganisationMembership, auth.User, error) {
	membership, err := s.authQueries.GetMembership(ctx, auth.GetMembershipParams{
		OrganisationID: orgID,
		UserID:         targetUserID,
	})
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			// Not a member of this org (or no such user) — don't leak existence.
			return auth.OrganisationMembership{}, auth.User{}, kernel.ErrNotFound("member", targetUserID.String())
		}
		return auth.OrganisationMembership{}, auth.User{}, kernel.ErrInternal(err)
	}
	user, err := s.authQueries.GetUser(ctx, targetUserID)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return auth.OrganisationMembership{}, auth.User{}, kernel.ErrNotFound("user", targetUserID.String())
		}
		return auth.OrganisationMembership{}, auth.User{}, kernel.ErrInternal(err)
	}
	return membership, user, nil
}

// memberDetailToResponse composes a membership row + its user row into the detail
// response. role/status/member_since come from the membership; the profile and
// payroll fields from the user.
func memberDetailToResponse(m auth.OrganisationMembership, u auth.User) *MemberDetailResponse {
	return &MemberDetailResponse{
		MembershipID:            m.ID.String(),
		UserID:                  u.ID.String(),
		Email:                   u.Email,
		FirstName:               u.FirstName,
		LastName:                u.LastName,
		Role:                    string(m.Role),
		Status:                  m.Status,
		AvatarURL:               kernel.NullTextToPtr(u.AvatarUrl),
		NationalInsuranceNumber: kernel.NullTextToPtr(u.NationalInsuranceNumber),
		UTR:                     kernel.NullTextToPtr(u.Utr),
		DateOfBirth:             kernel.DateToStringPtr(u.DateOfBirth),
		AddressLine1:            kernel.NullTextToPtr(u.AddressLine1),
		AddressLine2:            kernel.NullTextToPtr(u.AddressLine2),
		AddressLine3:            kernel.NullTextToPtr(u.AddressLine3),
		AddressLine4:            kernel.NullTextToPtr(u.AddressLine4),
		Postcode:                kernel.NullTextToPtr(u.Postcode),
		MemberSince:             m.CreatedAt.Time.Format(time.RFC3339),
		LastLoginAt:             kernel.TimestampToStringPtr(u.LastLoginAt),
	}
}
