package payroll

// service.go
// =============================================================================
// Service — the business logic for the payroll pay-run / payslip engine.
//
//   HTTP handler (handler.go)
//     ↓
//   Service (this file)  ── PAYE/NI engine (calc.go) + rates (rates.go)
//     ↓
//   *payrolldb.Queries (db/payroll — generated by sqlc) + auth.Querier
//     ↓
//   PostgreSQL
//
// Key rules (see db/schema/payroll_schema.sql):
//   - PAYROLL IS OWNER/ADMIN ONLY. Every endpoint requires an owner/admin caller.
//   - PERIODS ARE SEQUENTIAL. You prepare month N only after N-1 is completed, so
//     the cumulative PAYE/NI always has a settled prior YTD to build on.
//   - ONLY THE LATEST RUN IS EDITABLE/DELETABLE. Completing locks a run; to fix an
//     earlier month you delete the latest run(s) and re-run.
//   - Money is BIGINT pence inside; pound strings cross the API boundary (money pkg).
//   - RTI/HMRC filing is deferred — "complete" just finalises locally.
// =============================================================================

import (
	"context"
	"errors"
	"fmt"
	"strings"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/jackc/pgx/v5/pgxpool"

	auth "github.com/operationfb/accounting-saas/db/auth"
	payrolldb "github.com/operationfb/accounting-saas/db/payroll"
	"github.com/operationfb/accounting-saas/internal/kernel"
	"github.com/operationfb/accounting-saas/money"
)

// Service holds the pool, the payroll query set, and the auth query set (for the
// owner/admin check and resolving employee names).
type Service struct {
	pool        *pgxpool.Pool
	queries     *payrolldb.Queries
	authQueries auth.Querier
}

// NewService is the constructor, called once in main.go.
func NewService(pool *pgxpool.Pool, queries *payrolldb.Queries, authQueries auth.Querier) *Service {
	return &Service{pool: pool, queries: queries, authQueries: authQueries}
}

// requireAdmin confirms the caller is an active owner/admin of the org (payroll is
// sensitive — there is no "any active member" read path in v1).
func (s *Service) requireAdmin(ctx context.Context, userID, orgID uuid.UUID) error {
	role, err := kernel.AuthorizeMember(ctx, s.authQueries, userID, orgID)
	if err != nil {
		return err
	}
	if !kernel.IsOrgAdmin(role) {
		return kernel.ErrForbidden("only owners and admins can access payroll")
	}
	return nil
}

// resolveTaxYear returns the requested tax year, or the current one if unset.
func resolveTaxYear(req *int) int {
	if req != nil && *req > 0 {
		return *req
	}
	return currentTaxYearStart(time.Now().UTC())
}

// =============================================================================
// PREPARE PAY RUN
// =============================================================================

// PreparePayRun creates a draft run for a tax month and snapshots every active
// employee's payroll profile into a draft payslip, computing each via the engine.
// It enforces the sequential-period rule and the payment-date window. Re-preparing
// an already-prepared draft returns it unchanged (idempotent).
func (s *Service) PreparePayRun(ctx context.Context, authUserID, authOrgID uuid.UUID, req PreparePayRunRequest) (*PayRunResponse, error) {
	if err := s.requireAdmin(ctx, authUserID, authOrgID); err != nil {
		return nil, err
	}
	if req.Period < 1 || req.Period > 12 {
		return nil, kernel.ErrValidation("period must be between 1 and 12", nil)
	}
	taxYear := resolveTaxYear(req.TaxYear)

	paymentDate, err := parseDate("payment_date", req.PaymentDate)
	if err != nil {
		return nil, err
	}
	start, end := periodWindow(taxYear, req.Period)
	if !dateInWindow(paymentDate.Time, start, end) {
		return nil, kernel.ErrValidation(fmt.Sprintf(
			"payment_date must be between %s and %s for month %d",
			start.Format("2006-01-02"), end.Format("2006-01-02"), req.Period), nil)
	}

	rt, err := LoadRateTable(ctx, s.queries, int32(taxYear))
	if err != nil {
		return nil, err
	}

	var detail *PayRunResponse
	err = kernel.WithTx(ctx, s.pool, func(tx pgx.Tx) error {
		qtx := s.queries.WithTx(tx)

		// Sequencing: only one draft at a time, periods in order.
		latest, hasLatest, err := getLatestRun(ctx, qtx, authOrgID, taxYear)
		if err != nil {
			return err
		}
		if hasLatest && int(latest.Period) == req.Period {
			if latest.Status == "draft" {
				detail, err = s.buildPayRunDetail(ctx, qtx, latest, rt)
				return err
			}
			return kernel.ErrConflict(fmt.Sprintf("month %d payroll has already been completed", req.Period))
		}
		if !hasLatest {
			if req.Period != 1 {
				return kernel.ErrConflict("prepare month 1 first")
			}
		} else {
			if latest.Status != "completed" {
				return kernel.ErrConflict(fmt.Sprintf("finish or delete the current draft (month %d) first", latest.Period))
			}
			if req.Period != int(latest.Period)+1 {
				return kernel.ErrConflict(fmt.Sprintf("prepare months in order — the next month is %d", latest.Period+1))
			}
		}

		// Whether to claim the Employment Allowance is the org-level Company Details
		// setting; copy it onto the run so recomputeRunEA only offsets employer NI when
		// the company has opted in.
		orgSettings, err := qtx.GetOrganisationPayrollSettings(ctx, authOrgID)
		if err != nil {
			return kernel.ErrInternal(err)
		}

		run, err := qtx.CreatePayRun(ctx, payrolldb.CreatePayRunParams{
			OrganisationID:             authOrgID,
			CreatedByUserID:            authUserID,
			TaxYearStart:               int32(taxYear),
			Period:                     int32(req.Period),
			PeriodStart:                pgDate(start),
			PeriodEnd:                  pgDate(end),
			PaymentDate:                paymentDate,
			EmploymentAllowanceClaimed: orgSettings.ClaimsEmploymentAllowance,
		})
		if err != nil {
			if kernel.IsUniqueViolation(err) {
				return kernel.ErrConflict(fmt.Sprintf("month %d payroll already exists", req.Period))
			}
			return kernel.ErrInternal(err)
		}

		// Snapshot active employees into draft payslips. To keep this O(1) round-trips
		// regardless of headcount: fetch the employee list (1), fetch every employee's
		// cumulative PRIOR-period YTD in one grouped query (1), compute each payslip
		// IN-MEMORY via the engine, then bulk-insert them with their computed figures in
		// a single pipelined batch (1) — instead of an insert + YTD lookup + update per
		// employee.
		employees, err := qtx.ListActivePayrollEmployees(ctx, authOrgID)
		if err != nil {
			return kernel.ErrInternal(err)
		}
		priorByUser, err := s.ytdByUserUpToPeriod(ctx, qtx, authOrgID, taxYear, req.Period-1)
		if err != nil {
			return err
		}

		params := make([]payrolldb.CreatePayslipComputedParams, 0, len(employees))
		for _, emp := range employees {
			// Leavers & mid-year joiners: only pay employees who are employed DURING this
			// tax month. Skip anyone who hasn't started by the period end, or who left
			// before the period began. An employee whose leaving date falls within (or on)
			// the period gets their FINAL payslip (leaving_payslip = true).
			if emp.StartDate.Valid && emp.StartDate.Time.After(end) {
				continue // not started yet
			}
			if emp.LeavingDate.Valid && emp.LeavingDate.Time.Before(start) {
				continue // already left in an earlier period
			}
			leaving := emp.LeavingNextPayRun || (emp.LeavingDate.Valid && !emp.LeavingDate.Time.After(end))

			taxCode := emp.TaxCode
			if !taxCode.Valid || strings.TrimSpace(taxCode.String) == "" {
				taxCode = pgtype.Text{String: rt.DefaultTaxCode, Valid: true}
			}
			prior := priorByUser[emp.UserID] // zero value when the employee has no prior payslips
			inputs := PayslipInputs{
				BasicPay:              emp.BasicPayMinor,
				Allowance:             emp.AllowanceMinor,
				OtherPayments:         emp.OtherPaymentsMinor,
				PayNotSubjectToTaxNI:  emp.PayNotSubjectToTaxNiMinor,
				PayrollGiving:         emp.PayrollGivingMinor,
				OtherDeductionsNetPay: emp.OtherDeductionsNetPayMinor,
				ItemsClass1NicNotPaye: emp.ItemsClass1NicNotPayeMinor,
				SalarySacrifice:       emp.SalarySacrificeDeductionsMinor,
			}
			res, ok := ComputePayslip(rt, taxCodeOf(taxCode), emp.NiCategoryLetter, emp.NicCalculation, emp.Week1Month1Basis, req.Period,
				inputs,
				YTDPrior{TaxablePay: prior.TaxablePayMinor, TaxDeducted: prior.TaxDeductedMinor, NiablePay: prior.NiablePayMinor})
			if !ok {
				return kernel.ErrValidation("NI category "+emp.NiCategoryLetter+" is not configured for this tax year", nil)
			}
			params = append(params, payrolldb.CreatePayslipComputedParams{
				OrganisationID:                 authOrgID,
				PayRunID:                       run.ID,
				UserID:                         emp.UserID,
				TaxCode:                        taxCode,
				NiCategoryLetter:               emp.NiCategoryLetter,
				NicCalculation:                 emp.NicCalculation,
				Week1Month1Basis:               emp.Week1Month1Basis,
				StudentLoanUndergraduate:       emp.StudentLoanUndergraduate,
				StudentLoanPostgraduate:        emp.StudentLoanPostgraduate,
				BasicPayMinor:                  emp.BasicPayMinor,
				AllowanceMinor:                 emp.AllowanceMinor,
				OtherPaymentsMinor:             emp.OtherPaymentsMinor,
				PayNotSubjectToTaxNiMinor:      emp.PayNotSubjectToTaxNiMinor,
				PayrollGivingMinor:             emp.PayrollGivingMinor,
				OtherDeductionsNetPayMinor:     emp.OtherDeductionsNetPayMinor,
				ItemsClass1NicNotPayeMinor:     emp.ItemsClass1NicNotPayeMinor,
				SalarySacrificeDeductionsMinor: emp.SalarySacrificeDeductionsMinor,
				LeavingPayslip:                 leaving,
				GrossPayMinor:                  res.GrossPay,
				TaxablePayMinor:                res.TaxablePay,
				NiablePayMinor:                 res.NiablePay,
				TaxDeductedMinor:               res.TaxDeducted,
				EmployeeNiMinor:                res.EmployeeNI,
				EmployerNiMinor:                res.EmployerNI,
				NetPayMinor:                    res.NetPay,
			})
		}
		if err := bulkInsertPayslips(ctx, qtx, params); err != nil {
			return err
		}

		if _, err := s.recomputeRunEA(ctx, qtx, run, rt); err != nil {
			return err
		}
		// Re-read the run so EA is reflected.
		run, err = qtx.GetPayRun(ctx, payrolldb.GetPayRunParams{ID: run.ID, OrganisationID: authOrgID})
		if err != nil {
			return kernel.ErrInternal(err)
		}
		detail, err = s.buildPayRunDetail(ctx, qtx, run, rt)
		return err
	})
	if err != nil {
		return nil, err
	}
	return detail, nil
}

// =============================================================================
// GET / LIST
// =============================================================================

// GetPayRun returns a run with its payslips.
func (s *Service) GetPayRun(ctx context.Context, authUserID, authOrgID uuid.UUID, id string) (*PayRunResponse, error) {
	if err := s.requireAdmin(ctx, authUserID, authOrgID); err != nil {
		return nil, err
	}
	runID, err := uuid.Parse(id)
	if err != nil {
		return nil, kernel.ErrValidation("id is not a valid UUID", err)
	}
	run, err := s.queries.GetPayRun(ctx, payrolldb.GetPayRunParams{ID: runID, OrganisationID: authOrgID})
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, kernel.ErrNotFound("pay run", id)
		}
		return nil, kernel.ErrInternal(err)
	}
	rt, err := LoadRateTable(ctx, s.queries, run.TaxYearStart)
	if err != nil {
		return nil, err
	}
	return s.buildPayRunDetail(ctx, s.queries, run, rt)
}

// ListPayRuns returns the org's runs for a tax year (history; headers + totals only).
func (s *Service) ListPayRuns(ctx context.Context, authUserID, authOrgID uuid.UUID, taxYearReq *int) ([]*PayRunResponse, error) {
	if err := s.requireAdmin(ctx, authUserID, authOrgID); err != nil {
		return nil, err
	}
	taxYear := resolveTaxYear(taxYearReq)
	runs, err := s.queries.ListPayRuns(ctx, payrolldb.ListPayRunsParams{OrganisationID: authOrgID, TaxYearStart: int32(taxYear)})
	if err != nil {
		return nil, kernel.ErrInternal(err)
	}
	out := make([]*PayRunResponse, 0, len(runs))
	for _, run := range runs {
		hdr, err := s.payRunHeader(ctx, s.queries, run)
		if err != nil {
			return nil, err
		}
		out = append(out, hdr)
	}
	return out, nil
}

// GetPayslip returns one payslip (with its year-to-date block).
func (s *Service) GetPayslip(ctx context.Context, authUserID, authOrgID uuid.UUID, id string) (*PayslipResponse, error) {
	if err := s.requireAdmin(ctx, authUserID, authOrgID); err != nil {
		return nil, err
	}
	psID, err := uuid.Parse(id)
	if err != nil {
		return nil, kernel.ErrValidation("id is not a valid UUID", err)
	}
	ps, err := s.queries.GetPayslip(ctx, payrolldb.GetPayslipParams{ID: psID, OrganisationID: authOrgID})
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, kernel.ErrNotFound("payslip", id)
		}
		return nil, kernel.ErrInternal(err)
	}
	run, err := s.queries.GetPayRun(ctx, payrolldb.GetPayRunParams{ID: ps.PayRunID, OrganisationID: authOrgID})
	if err != nil {
		return nil, kernel.ErrInternal(err)
	}
	return s.buildPayslipResponse(ctx, s.queries, ps, int(run.Period), int(run.TaxYearStart))
}

// =============================================================================
// UPDATE PAYSLIP (the Edit Payslip screen)
// =============================================================================

// UpdatePayslip applies the editable inputs and recomputes the figures. Only a
// payslip on the LATEST, still-DRAFT run may be edited.
func (s *Service) UpdatePayslip(ctx context.Context, authUserID, authOrgID uuid.UUID, id string, req UpdatePayslipRequest) (*PayslipResponse, error) {
	if err := s.requireAdmin(ctx, authUserID, authOrgID); err != nil {
		return nil, err
	}
	psID, err := uuid.Parse(id)
	if err != nil {
		return nil, kernel.ErrValidation("id is not a valid UUID", err)
	}

	// Parse + validate the inputs up front (422 before the transaction).
	params, err := buildPayslipInputParams(psID, authOrgID, req)
	if err != nil {
		return nil, err
	}

	var resp *PayslipResponse
	err = kernel.WithTx(ctx, s.pool, func(tx pgx.Tx) error {
		qtx := s.queries.WithTx(tx)

		ps, err := qtx.GetPayslip(ctx, payrolldb.GetPayslipParams{ID: psID, OrganisationID: authOrgID})
		if err != nil {
			if errors.Is(err, pgx.ErrNoRows) {
				return kernel.ErrNotFound("payslip", id)
			}
			return kernel.ErrInternal(err)
		}
		run, err := qtx.GetPayRun(ctx, payrolldb.GetPayRunParams{ID: ps.PayRunID, OrganisationID: authOrgID})
		if err != nil {
			return kernel.ErrInternal(err)
		}
		if err := assertLatestEditable(ctx, qtx, run); err != nil {
			return err
		}

		rt, err := LoadRateTable(ctx, qtx, run.TaxYearStart)
		if err != nil {
			return err
		}

		updated, err := qtx.UpdatePayslipInputs(ctx, params)
		if err != nil {
			return kernel.ErrInternal(err)
		}
		computed, err := s.computeAndStore(ctx, qtx, rt, updated, int(run.TaxYearStart), int(run.Period))
		if err != nil {
			return err
		}
		// Editing a payslip changes the run's employer NI, so re-apply EA.
		if _, err := s.recomputeRunEA(ctx, qtx, run, rt); err != nil {
			return err
		}
		resp, err = s.buildPayslipResponse(ctx, qtx, computed, int(run.Period), int(run.TaxYearStart))
		return err
	})
	if err != nil {
		return nil, err
	}
	return resp, nil
}

// =============================================================================
// COMPLETE / DELETE
// =============================================================================

// CompletePayRun finalises the latest draft run ("Run & Report"). RTI filing is
// deferred — this only flips the status and locks in the Employment Allowance offset.
func (s *Service) CompletePayRun(ctx context.Context, authUserID, authOrgID uuid.UUID, id string) (*PayRunResponse, error) {
	if err := s.requireAdmin(ctx, authUserID, authOrgID); err != nil {
		return nil, err
	}
	runID, err := uuid.Parse(id)
	if err != nil {
		return nil, kernel.ErrValidation("id is not a valid UUID", err)
	}

	var detail *PayRunResponse
	err = kernel.WithTx(ctx, s.pool, func(tx pgx.Tx) error {
		qtx := s.queries.WithTx(tx)
		run, err := qtx.GetPayRun(ctx, payrolldb.GetPayRunParams{ID: runID, OrganisationID: authOrgID})
		if err != nil {
			if errors.Is(err, pgx.ErrNoRows) {
				return kernel.ErrNotFound("pay run", id)
			}
			return kernel.ErrInternal(err)
		}
		if run.Status != "draft" {
			return kernel.ErrConflict("this pay run has already been completed")
		}
		if err := assertLatestEditable(ctx, qtx, run); err != nil {
			return err
		}
		rt, err := LoadRateTable(ctx, qtx, run.TaxYearStart)
		if err != nil {
			return err
		}
		ea, err := s.recomputeRunEA(ctx, qtx, run, rt)
		if err != nil {
			return err
		}
		completed, err := qtx.CompletePayRun(ctx, payrolldb.CompletePayRunParams{
			ID:                             runID,
			OrganisationID:                 authOrgID,
			EmploymentAllowanceAmountMinor: ea,
		})
		if err != nil {
			return kernel.ErrInternal(err)
		}
		detail, err = s.buildPayRunDetail(ctx, qtx, completed, rt)
		return err
	})
	if err != nil {
		return nil, err
	}
	return detail, nil
}

// DeletePayRun soft-deletes the LATEST run for its year (the only one removable).
func (s *Service) DeletePayRun(ctx context.Context, authUserID, authOrgID uuid.UUID, id string) error {
	if err := s.requireAdmin(ctx, authUserID, authOrgID); err != nil {
		return err
	}
	runID, err := uuid.Parse(id)
	if err != nil {
		return kernel.ErrValidation("id is not a valid UUID", err)
	}
	return kernel.WithTx(ctx, s.pool, func(tx pgx.Tx) error {
		qtx := s.queries.WithTx(tx)
		run, err := qtx.GetPayRun(ctx, payrolldb.GetPayRunParams{ID: runID, OrganisationID: authOrgID})
		if err != nil {
			if errors.Is(err, pgx.ErrNoRows) {
				return kernel.ErrNotFound("pay run", id)
			}
			return kernel.ErrInternal(err)
		}
		if err := assertLatestEditable(ctx, qtx, run); err != nil {
			return err
		}
		return mapExec(qtx.SoftDeletePayRun(ctx, payrolldb.SoftDeletePayRunParams{ID: runID, OrganisationID: authOrgID}))
	})
}

// =============================================================================
// OVERVIEW
// =============================================================================

// GetOverview assembles the payroll landing page: Status, Year-to-date, History and
// the Employees table.
func (s *Service) GetOverview(ctx context.Context, authUserID, authOrgID uuid.UUID, taxYearReq *int) (*OverviewResponse, error) {
	if err := s.requireAdmin(ctx, authUserID, authOrgID); err != nil {
		return nil, err
	}
	taxYear := resolveTaxYear(taxYearReq)

	org, err := s.queries.GetOrganisationPayrollSettings(ctx, authOrgID)
	if err != nil && !errors.Is(err, pgx.ErrNoRows) {
		return nil, kernel.ErrInternal(err)
	}

	runs, err := s.queries.ListPayRuns(ctx, payrolldb.ListPayRunsParams{OrganisationID: authOrgID, TaxYearStart: int32(taxYear)})
	if err != nil {
		return nil, kernel.ErrInternal(err)
	}
	history := make([]PayRunResponse, 0, len(runs))
	for _, run := range runs {
		hdr, err := s.payRunHeader(ctx, s.queries, run)
		if err != nil {
			return nil, err
		}
		history = append(history, *hdr)
	}

	ytd, err := s.queries.SumOrgYearToDate(ctx, payrolldb.SumOrgYearToDateParams{OrganisationID: authOrgID, TaxYearStart: int32(taxYear)})
	if err != nil {
		return nil, kernel.ErrInternal(err)
	}

	// Status: runs are ordered newest period first, so runs[0] is the latest.
	status := OverviewStatus{}
	if len(runs) == 0 {
		next := 1
		status.State = "none"
		status.NextPeriod = &next
		status.CanPrepare = true
	} else {
		latest := runs[0]
		id := latest.ID.String()
		status.CurrentPeriod = int(latest.Period)
		status.CurrentRunID = &id
		status.FilingDeadline = dateToStringPtr(latest.PeriodEnd)
		if latest.Status == "draft" {
			status.State = "draft"
		} else {
			status.State = "completed_unfiled"
			if latest.Period < 12 {
				next := int(latest.Period) + 1
				status.NextPeriod = &next
				status.CanPrepare = true
			}
		}
	}

	employees, err := s.queries.ListActivePayrollEmployees(ctx, authOrgID)
	if err != nil {
		return nil, kernel.ErrInternal(err)
	}
	// One grouped query for every employee's whole-year YTD (avoids an N+1 over the
	// list); period 12 = the full tax year.
	ytdByUser, err := s.ytdByUserUpToPeriod(ctx, s.queries, authOrgID, taxYear, 12)
	if err != nil {
		return nil, err
	}
	empOut := make([]OverviewEmployee, 0, len(employees))
	for _, emp := range employees {
		ytd := ytdByUser[emp.UserID] // zero value when the employee has no payslips yet
		empOut = append(empOut, OverviewEmployee{
			UserID:        emp.UserID.String(),
			Name:          strings.TrimSpace(emp.FirstName + " " + emp.LastName),
			StartDate:     dateToStringPtr(emp.StartDate),
			MonthlyPay:    money.MinorToPounds(emp.BasicPayMinor + emp.AllowanceMinor + emp.OtherPaymentsMinor),
			TotalPay:      money.MinorToPounds(ytd.GrossPayMinor),
			TotalTax:      money.MinorToPounds(ytd.TaxDeductedMinor),
			AutoEnrolment: pensionLabel(emp.PensionStatus),
		})
	}

	companyName := ""
	if org.Name != "" {
		companyName = org.Name
	}
	return &OverviewResponse{
		TaxYear:      taxYear,
		TaxYearLabel: taxYearLabel(taxYear),
		CompanyName:  companyName,
		Status:       status,
		YearToDate: OverviewYTD{
			TotalPay:            money.MinorToPounds(ytd.GrossPayMinor),
			TotalTax:            money.MinorToPounds(ytd.TaxDeductedMinor),
			TotalNI:             money.MinorToPounds(ytd.TotalNiMinor),
			EmploymentAllowance: money.MinorToPounds(ytd.EmploymentAllowanceMinor),
		},
		History:   history,
		Employees: empOut,
	}, nil
}

// =============================================================================
// INTERNAL HELPERS
// =============================================================================

// getLatestRun wraps GetLatestPayRun, mapping no-rows to (zero, false, nil).
func getLatestRun(ctx context.Context, q *payrolldb.Queries, orgID uuid.UUID, taxYear int) (payrolldb.PayRun, bool, error) {
	run, err := q.GetLatestPayRun(ctx, payrolldb.GetLatestPayRunParams{OrganisationID: orgID, TaxYearStart: int32(taxYear)})
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return payrolldb.PayRun{}, false, nil
		}
		return payrolldb.PayRun{}, false, kernel.ErrInternal(err)
	}
	return run, true, nil
}

// assertLatestEditable refuses (409) editing/deleting a run that is not the most
// recent for its tax year — the cumulative-consistency lock.
func assertLatestEditable(ctx context.Context, q *payrolldb.Queries, run payrolldb.PayRun) error {
	latest, ok, err := getLatestRun(ctx, q, run.OrganisationID, int(run.TaxYearStart))
	if err != nil {
		return err
	}
	if !ok || latest.ID != run.ID {
		return kernel.ErrConflict("only the most recent pay run can be changed — delete later runs first")
	}
	return nil
}

// computeAndStore runs the engine for a payslip and writes the computed figures back.
func (s *Service) computeAndStore(ctx context.Context, q *payrolldb.Queries, rt RateTable, ps payrolldb.Payslip, taxYear, period int) (payrolldb.Payslip, error) {
	prior, err := q.SumYearToDateForUser(ctx, payrolldb.SumYearToDateForUserParams{
		OrganisationID: ps.OrganisationID,
		UserID:         ps.UserID,
		TaxYearStart:   int32(taxYear),
		Period:         int32(period - 1),
	})
	if err != nil {
		return payrolldb.Payslip{}, kernel.ErrInternal(err)
	}
	res, ok := ComputePayslip(rt, taxCodeOf(ps.TaxCode), ps.NiCategoryLetter, ps.NicCalculation, ps.Week1Month1Basis, period,
		inputsFromPayslip(ps),
		YTDPrior{TaxablePay: prior.TaxablePayMinor, TaxDeducted: prior.TaxDeductedMinor, NiablePay: prior.NiablePayMinor})
	if !ok {
		return payrolldb.Payslip{}, kernel.ErrValidation("NI category "+ps.NiCategoryLetter+" is not configured for this tax year", nil)
	}
	updated, err := q.UpdatePayslipComputed(ctx, payrolldb.UpdatePayslipComputedParams{
		ID:                   ps.ID,
		OrganisationID:       ps.OrganisationID,
		GrossPayMinor:        res.GrossPay,
		TaxablePayMinor:      res.TaxablePay,
		NiablePayMinor:       res.NiablePay,
		TaxDeductedMinor:     res.TaxDeducted,
		EmployeeNiMinor:      res.EmployeeNI,
		EmployerNiMinor:      res.EmployerNI,
		EmployeePensionMinor: res.EmployeePension,
		EmployerPensionMinor: 0,
		StudentLoanMinor:     res.StudentLoan,
		NetPayMinor:          res.NetPay,
	})
	if err != nil {
		return payrolldb.Payslip{}, kernel.ErrInternal(err)
	}
	return updated, nil
}

// recomputeRunEA recalculates the Employment Allowance offset for a run (the lesser
// of the run's employer NI and the remaining annual cap) and stores it. Returns the
// applied amount.
func (s *Service) recomputeRunEA(ctx context.Context, q *payrolldb.Queries, run payrolldb.PayRun, rt RateTable) (int64, error) {
	totals, err := q.SumPayRunTotals(ctx, payrolldb.SumPayRunTotalsParams{PayRunID: run.ID, OrganisationID: run.OrganisationID})
	if err != nil {
		return 0, kernel.ErrInternal(err)
	}
	var ea int64
	if run.EmploymentAllowanceClaimed {
		orgYTD, err := q.SumOrgYearToDate(ctx, payrolldb.SumOrgYearToDateParams{OrganisationID: run.OrganisationID, TaxYearStart: run.TaxYearStart})
		if err != nil {
			return 0, kernel.ErrInternal(err)
		}
		usedByOthers := orgYTD.EmploymentAllowanceMinor - run.EmploymentAllowanceAmountMinor
		remaining := rt.EmploymentAllowanceCapMinor - usedByOthers
		if remaining < 0 {
			remaining = 0
		}
		ea = totals.EmployerNiMinor
		if ea > remaining {
			ea = remaining
		}
	}
	if err := q.UpdatePayRunEmploymentAllowance(ctx, payrolldb.UpdatePayRunEmploymentAllowanceParams{
		ID:                             run.ID,
		OrganisationID:                 run.OrganisationID,
		EmploymentAllowanceAmountMinor: ea,
	}); err != nil {
		return 0, kernel.ErrInternal(err)
	}
	return ea, nil
}

// =============================================================================
// RESPONSE BUILDERS
// =============================================================================

// buildPayRunDetail builds a full run response including its payslips. It resolves
// the employee names and the per-payslip YTD with TWO grouped queries (a names map +
// a YTD-by-user map) rather than per-payslip lookups, so it stays O(1) round-trips
// regardless of headcount (this also speeds GetPayRun).
func (s *Service) buildPayRunDetail(ctx context.Context, q *payrolldb.Queries, run payrolldb.PayRun, rt RateTable) (*PayRunResponse, error) {
	hdr, err := s.payRunHeader(ctx, q, run)
	if err != nil {
		return nil, err
	}
	slips, err := q.ListPayslipsForRun(ctx, payrolldb.ListPayslipsForRunParams{PayRunID: run.ID, OrganisationID: run.OrganisationID})
	if err != nil {
		return nil, kernel.ErrInternal(err)
	}

	nameRows, err := q.ListRunPayslipNames(ctx, payrolldb.ListRunPayslipNamesParams{PayRunID: run.ID, OrganisationID: run.OrganisationID})
	if err != nil {
		return nil, kernel.ErrInternal(err)
	}
	names := make(map[uuid.UUID]string, len(nameRows))
	for _, n := range nameRows {
		names[n.UserID] = strings.TrimSpace(n.FirstName + " " + n.LastName)
	}
	// YTD through this run's period (includes the run's own just-written payslips).
	ytdMap, err := s.ytdByUserUpToPeriod(ctx, q, run.OrganisationID, int(run.TaxYearStart), int(run.Period))
	if err != nil {
		return nil, err
	}

	hdr.Payslips = make([]PayslipResponse, 0, len(slips))
	for _, ps := range slips {
		y := ytdMap[ps.UserID]
		hdr.Payslips = append(hdr.Payslips, *payslipToResponse(ps, names[ps.UserID], ytdTotals{
			Gross: y.GrossPayMinor, Tax: y.TaxDeductedMinor, EmployeeNI: y.EmployeeNiMinor, EmployerNI: y.EmployerNiMinor, Net: y.NetPayMinor,
		}))
	}
	return hdr, nil
}

// payRunHeader builds a run header + totals (no payslips).
func (s *Service) payRunHeader(ctx context.Context, q *payrolldb.Queries, run payrolldb.PayRun) (*PayRunResponse, error) {
	totals, err := q.SumPayRunTotals(ctx, payrolldb.SumPayRunTotalsParams{PayRunID: run.ID, OrganisationID: run.OrganisationID})
	if err != nil {
		return nil, kernel.ErrInternal(err)
	}
	due := totals.TaxDeductedMinor + totals.EmployeeNiMinor + totals.EmployerNiMinor - run.EmploymentAllowanceAmountMinor
	if due < 0 {
		due = 0
	}
	return &PayRunResponse{
		ID:                         run.ID.String(),
		OrganisationID:             run.OrganisationID.String(),
		TaxYearStart:               int(run.TaxYearStart),
		Period:                     int(run.Period),
		PeriodStart:                run.PeriodStart.Time.Format("2006-01-02"),
		PeriodEnd:                  run.PeriodEnd.Time.Format("2006-01-02"),
		PaymentDate:                run.PaymentDate.Time.Format("2006-01-02"),
		Status:                     run.Status,
		EmploymentAllowanceClaimed: run.EmploymentAllowanceClaimed,
		EmploymentAllowanceAmount:  money.MinorToPounds(run.EmploymentAllowanceAmountMinor),
		Totals: PayRunTotals{
			Pay:        money.MinorToPounds(totals.GrossPayMinor),
			Tax:        money.MinorToPounds(totals.TaxDeductedMinor),
			EmployeeNI: money.MinorToPounds(totals.EmployeeNiMinor),
			EmployerNI: money.MinorToPounds(totals.EmployerNiMinor),
			NetPay:     money.MinorToPounds(totals.NetPayMinor),
			DueToHmrc:  money.MinorToPounds(due),
		},
		CreatedAt: run.CreatedAt.Time.Format(time.RFC3339),
		UpdatedAt: run.UpdatedAt.Time.Format(time.RFC3339),
	}, nil
}

// ytdTotals is the year-to-date block a payslip response carries.
type ytdTotals struct {
	Gross, Tax, EmployeeNI, EmployerNI, Net int64
}

// buildPayslipResponse is the single-payslip path (GetPayslip): it resolves the name
// and YTD with one query each, then maps. The run-detail path uses payslipToResponse
// directly with batched maps.
func (s *Service) buildPayslipResponse(ctx context.Context, q *payrolldb.Queries, ps payrolldb.Payslip, period, taxYear int) (*PayslipResponse, error) {
	name, err := s.resolveName(ctx, ps.UserID)
	if err != nil {
		return nil, err
	}
	ytd, err := q.SumYearToDateForUser(ctx, payrolldb.SumYearToDateForUserParams{
		OrganisationID: ps.OrganisationID,
		UserID:         ps.UserID,
		TaxYearStart:   int32(taxYear),
		Period:         int32(period),
	})
	if err != nil {
		return nil, kernel.ErrInternal(err)
	}
	return payslipToResponse(ps, name, ytdTotals{
		Gross: ytd.GrossPayMinor, Tax: ytd.TaxDeductedMinor, EmployeeNI: ytd.EmployeeNiMinor, EmployerNI: ytd.EmployerNiMinor, Net: ytd.NetPayMinor,
	}), nil
}

// payslipToResponse is the pure mapper from a stored payslip + resolved name + YTD to
// the API shape.
func payslipToResponse(ps payrolldb.Payslip, name string, ytd ytdTotals) *PayslipResponse {
	return &PayslipResponse{
		ID:                              ps.ID.String(),
		PayRunID:                        ps.PayRunID.String(),
		UserID:                          ps.UserID.String(),
		EmployeeName:                    name,
		TaxCode:                         kernel.NullTextToPtr(ps.TaxCode),
		NiCategoryLetter:                ps.NiCategoryLetter,
		NicCalculation:                  ps.NicCalculation,
		Week1Month1Basis:                ps.Week1Month1Basis,
		StudentLoanUndergraduate:        ps.StudentLoanUndergraduate,
		StudentLoanPostgraduate:         ps.StudentLoanPostgraduate,
		BasicPay:                        money.MinorToPounds(ps.BasicPayMinor),
		Overtime:                        money.MinorToPounds(ps.OvertimeMinor),
		Bonus:                           money.MinorToPounds(ps.BonusMinor),
		Commission:                      money.MinorToPounds(ps.CommissionMinor),
		Allowance:                       money.MinorToPounds(ps.AllowanceMinor),
		AbsencePayments:                 money.MinorToPounds(ps.AbsencePaymentsMinor),
		HolidayPay:                      money.MinorToPounds(ps.HolidayPayMinor),
		OtherPayments:                   money.MinorToPounds(ps.OtherPaymentsMinor),
		PayNotSubjectToTaxNi:            money.MinorToPounds(ps.PayNotSubjectToTaxNiMinor),
		StatutorySickPay:                money.MinorToPounds(ps.StatutorySickPayMinor),
		StatutoryMaternityPay:           money.MinorToPounds(ps.StatutoryMaternityPayMinor),
		StatutoryPaternityPay:           money.MinorToPounds(ps.StatutoryPaternityPayMinor),
		StatutoryAdoptionPay:            money.MinorToPounds(ps.StatutoryAdoptionPayMinor),
		SharedParentalPay:               money.MinorToPounds(ps.SharedParentalPayMinor),
		StatutoryNeonatalCarePay:        money.MinorToPounds(ps.StatutoryNeonatalCarePayMinor),
		StatutoryParentalBereavementPay: money.MinorToPounds(ps.StatutoryParentalBereavementPayMinor),
		PayrollGiving:                   money.MinorToPounds(ps.PayrollGivingMinor),
		OtherDeductionsNetPay:           money.MinorToPounds(ps.OtherDeductionsNetPayMinor),
		ItemsClass1NicNotPaye:           money.MinorToPounds(ps.ItemsClass1NicNotPayeMinor),
		SalarySacrificeDeductions:       money.MinorToPounds(ps.SalarySacrificeDeductionsMinor),
		GrossPay:                        money.MinorToPounds(ps.GrossPayMinor),
		TaxablePay:                      money.MinorToPounds(ps.TaxablePayMinor),
		NiablePay:                       money.MinorToPounds(ps.NiablePayMinor),
		TaxDeducted:                     money.MinorToPounds(ps.TaxDeductedMinor),
		EmployeeNI:                      money.MinorToPounds(ps.EmployeeNiMinor),
		EmployerNI:                      money.MinorToPounds(ps.EmployerNiMinor),
		EmployeePension:                 money.MinorToPounds(ps.EmployeePensionMinor),
		EmployerPension:                 money.MinorToPounds(ps.EmployerPensionMinor),
		StudentLoan:                     money.MinorToPounds(ps.StudentLoanMinor),
		NetPay:                          money.MinorToPounds(ps.NetPayMinor),
		YearToDate: PayslipYTD{
			GrossPay:    money.MinorToPounds(ytd.Gross),
			TaxDeducted: money.MinorToPounds(ytd.Tax),
			EmployeeNI:  money.MinorToPounds(ytd.EmployeeNI),
			EmployerNI:  money.MinorToPounds(ytd.EmployerNI),
			NetPay:      money.MinorToPounds(ytd.Net),
		},
		HoursWorked:    numericToStringPtr(ps.HoursWorked),
		Comment:        kernel.NullTextToPtr(ps.Comment),
		LeavingPayslip: ps.LeavingPayslip,
	}
}

// resolveName fetches an employee's display name.
func (s *Service) resolveName(ctx context.Context, userID uuid.UUID) (string, error) {
	u, err := s.authQueries.GetUser(ctx, userID)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return "", nil
		}
		return "", kernel.ErrInternal(err)
	}
	return strings.TrimSpace(u.FirstName + " " + u.LastName), nil
}

// ytdByUserUpToPeriod returns each employee's cumulative YTD (summed over periods ≤
// periodLte) as a map, in ONE grouped query. periodLte ≤ 0 yields an empty map.
func (s *Service) ytdByUserUpToPeriod(ctx context.Context, q *payrolldb.Queries, orgID uuid.UUID, taxYear, periodLte int) (map[uuid.UUID]payrolldb.ListYearToDateByUserUpToPeriodRow, error) {
	rows, err := q.ListYearToDateByUserUpToPeriod(ctx, payrolldb.ListYearToDateByUserUpToPeriodParams{
		OrganisationID: orgID,
		TaxYearStart:   int32(taxYear),
		Period:         int32(periodLte),
	})
	if err != nil {
		return nil, kernel.ErrInternal(err)
	}
	m := make(map[uuid.UUID]payrolldb.ListYearToDateByUserUpToPeriodRow, len(rows))
	for _, r := range rows {
		m[r.UserID] = r
	}
	return m, nil
}

// bulkInsertPayslips inserts all payslips for a run in a single pipelined batch (one
// network round-trip), instead of an INSERT per employee.
func bulkInsertPayslips(ctx context.Context, q *payrolldb.Queries, params []payrolldb.CreatePayslipComputedParams) error {
	if len(params) == 0 {
		return nil
	}
	br := q.CreatePayslipComputed(ctx, params)
	var firstErr error
	br.Exec(func(_ int, err error) {
		if err != nil && firstErr == nil {
			firstErr = err
		}
	})
	if cerr := br.Close(); cerr != nil && firstErr == nil {
		firstErr = cerr
	}
	if firstErr != nil {
		return kernel.ErrInternal(firstErr)
	}
	return nil
}
