// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ledger.sql

package ledger

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAccountRoleNominal = `-- name: GetAccountRoleNominal :one
SELECT nominal_code
FROM gl_account_roles
WHERE role = $1
  AND (organisation_id = $2 OR organisation_id IS NULL)
  AND (country_code    = $3    OR country_code    IS NULL)
  AND (company_type    = $4    OR company_type = 'ALL')
ORDER BY
    (organisation_id IS NOT NULL) DESC,   -- org override beats everything
    (country_code    IS NOT NULL) DESC,   -- then a country override
    (company_type <> 'ALL')       DESC    -- then a company_type-specific default
LIMIT 1
`

type GetAccountRoleNominalParams struct {
	Role           string      `json:"role"`
	OrganisationID pgtype.UUID `json:"organisation_id"`
	CountryCode    pgtype.Text `json:"country_code"`
	CompanyType    string      `json:"company_type"`
}

// The nominal_code a FIXED control role resolves to, picking the MOST SPECIFIC scope
// that matches the caller: org-specific → country-specific → company_type-specific →
// global default. organisation_id / country_code IS NULL = a broader (global/country)
// default. The resolver then looks the returned nominal up in the caller's org
// categories. An empty country_code arg matches only the country-agnostic rows.
func (q *Queries) GetAccountRoleNominal(ctx context.Context, arg GetAccountRoleNominalParams) (string, error) {
	row := q.db.QueryRow(ctx, getAccountRoleNominal,
		arg.Role,
		arg.OrganisationID,
		arg.CountryCode,
		arg.CompanyType,
	)
	var nominal_code string
	err := row.Scan(&nominal_code)
	return nominal_code, err
}

const listPostingRules = `-- name: ListPostingRules :many

SELECT event_code, leg_no, account_role, amount_basis, direction,
       company_type, per_employee, employee_filter, description_template, display_order
FROM gl_posting_rules
ORDER BY event_code, company_type, leg_no
`

type ListPostingRulesRow struct {
	EventCode           string      `json:"event_code"`
	LegNo               int32       `json:"leg_no"`
	AccountRole         string      `json:"account_role"`
	AmountBasis         string      `json:"amount_basis"`
	Direction           string      `json:"direction"`
	CompanyType         string      `json:"company_type"`
	PerEmployee         bool        `json:"per_employee"`
	EmployeeFilter      string      `json:"employee_filter"`
	DescriptionTemplate pgtype.Text `json:"description_template"`
	DisplayOrder        int32       `json:"display_order"`
}

// =============================================================================
// GENERAL LEDGER — QUERIES (sqlc input)
// Generated into package `ledger` at db/ledger (see sqlc.yaml).
//
// ITERATION 1: read access to the posting-rules reference table only. The
// interpreter (poster) and the journal-entry writes land in a later iteration.
// =============================================================================
// All posting rules, ordered for a deterministic read (event, then leg). Backs
// the offline structural/cross-check tests and any "show me the mapping" view.
func (q *Queries) ListPostingRules(ctx context.Context) ([]ListPostingRulesRow, error) {
	rows, err := q.db.Query(ctx, listPostingRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPostingRulesRow
	for rows.Next() {
		var i ListPostingRulesRow
		if err := rows.Scan(
			&i.EventCode,
			&i.LegNo,
			&i.AccountRole,
			&i.AmountBasis,
			&i.Direction,
			&i.CompanyType,
			&i.PerEmployee,
			&i.EmployeeFilter,
			&i.DescriptionTemplate,
			&i.DisplayOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostingRulesForEvent = `-- name: ListPostingRulesForEvent :many
SELECT event_code, leg_no, account_role, amount_basis, direction,
       company_type, per_employee, employee_filter, description_template, display_order
FROM gl_posting_rules
WHERE event_code = $1
  AND company_type IN ('ALL', $2)
ORDER BY
    -- Prefer the company-type-specific leg over the 'ALL' default for the same leg_no.
    leg_no,
    CASE WHEN company_type = 'ALL' THEN 1 ELSE 0 END
`

type ListPostingRulesForEventParams struct {
	EventCode   string `json:"event_code"`
	CompanyType string `json:"company_type"`
}

type ListPostingRulesForEventRow struct {
	EventCode           string      `json:"event_code"`
	LegNo               int32       `json:"leg_no"`
	AccountRole         string      `json:"account_role"`
	AmountBasis         string      `json:"amount_basis"`
	Direction           string      `json:"direction"`
	CompanyType         string      `json:"company_type"`
	PerEmployee         bool        `json:"per_employee"`
	EmployeeFilter      string      `json:"employee_filter"`
	DescriptionTemplate pgtype.Text `json:"description_template"`
	DisplayOrder        int32       `json:"display_order"`
}

// The legs of ONE event for an org's company_type: the org-specific rule if one
// exists, else the 'ALL' default. This is the lookup the interpreter will use to
// build a journal entry. Ordered by leg_no so the legs come back in posting order.
func (q *Queries) ListPostingRulesForEvent(ctx context.Context, arg ListPostingRulesForEventParams) ([]ListPostingRulesForEventRow, error) {
	rows, err := q.db.Query(ctx, listPostingRulesForEvent, arg.EventCode, arg.CompanyType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPostingRulesForEventRow
	for rows.Next() {
		var i ListPostingRulesForEventRow
		if err := rows.Scan(
			&i.EventCode,
			&i.LegNo,
			&i.AccountRole,
			&i.AmountBasis,
			&i.Direction,
			&i.CompanyType,
			&i.PerEmployee,
			&i.EmployeeFilter,
			&i.DescriptionTemplate,
			&i.DisplayOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
