// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package ledger

import (
	"context"
)

type Querier interface {
	// The nominal_code a FIXED control role resolves to, picking the MOST SPECIFIC scope
	// that matches the caller: org-specific → country-specific → company_type-specific →
	// global default. organisation_id / country_code IS NULL = a broader (global/country)
	// default. The resolver then looks the returned nominal up in the caller's org
	// categories. An empty country_code arg matches only the country-agnostic rows.
	GetAccountRoleNominal(ctx context.Context, arg GetAccountRoleNominalParams) (string, error)
	// =============================================================================
	// GENERAL LEDGER — QUERIES (sqlc input)
	// Generated into package `ledger` at db/ledger (see sqlc.yaml).
	//
	// ITERATION 1: read access to the posting-rules reference table only. The
	// interpreter (poster) and the journal-entry writes land in a later iteration.
	// =============================================================================
	// All posting rules, ordered for a deterministic read (event, then leg). Backs
	// the offline structural/cross-check tests and any "show me the mapping" view.
	ListPostingRules(ctx context.Context) ([]ListPostingRulesRow, error)
	// The legs of ONE event for an org's company_type: the org-specific rule if one
	// exists, else the 'ALL' default. This is the lookup the interpreter will use to
	// build a journal entry. Ordered by leg_no so the legs come back in posting order.
	ListPostingRulesForEvent(ctx context.Context, arg ListPostingRulesForEventParams) ([]ListPostingRulesForEventRow, error)
}

var _ Querier = (*Queries)(nil)
