// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package expenses

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// -----------------------------------------------------------------------------
	// ApplySuggestedCategory
	// Set the category on an UNCONFIRMED capture from the dictionary suggestion. The
	// needs_review = TRUE guard is the safety rail: it means a human has not yet
	// chosen a category, so we can only ever replace the placeholder — never clobber
	// a category a person has confirmed. :exec (not :one) so that a no-op (e.g. the
	// capture was confirmed in the meantime → zero rows) is NOT treated as an error.
	// Org-scoped, soft-delete aware.
	// -----------------------------------------------------------------------------
	ApplySuggestedCategory(ctx context.Context, arg ApplySuggestedCategoryParams) error
	// -----------------------------------------------------------------------------
	// CountExpenseAttachments
	// How many files an expense already has. The service calls this when a new file
	// is uploaded: if the count is 0, this upload is the FIRST one and therefore
	// becomes the primary (default) attachment. Scoped by expense_id only — the
	// caller has already been authorised against the parent expense's organisation,
	// which is the same convention ListExpenseAttachments uses.
	// -----------------------------------------------------------------------------
	CountExpenseAttachments(ctx context.Context, expenseID uuid.UUID) (int64, error)
	// -----------------------------------------------------------------------------
	// CountExpensesByStatus
	// Count of expenses per status — used for the dashboard summary cards.
	// e.g. "3 Pending Approval", "12 Paid This Month"
	// -----------------------------------------------------------------------------
	CountExpensesByStatus(ctx context.Context, organisationID uuid.UUID) ([]CountExpensesByStatusRow, error)
	// =============================================================================
	// EXPENSES MODULE — SQLC QUERIES
	// File: db/queries/query.sql
	//
	// What is sqlc?
	//   sqlc reads this file plus your schema.sql and generates type-safe Go code.
	//   Every query here becomes a Go function with typed parameters and return
	//   values. You never write boilerplate database scan/row code by hand.
	//
	// Annotation syntax:
	//   Every query must have a comment in this exact format:
	//
	//     -- name: FunctionName :return_type
	//
	//   Return types:
	//     :one   → returns a single row (error if 0 or >1 rows)
	//     :many  → returns a slice of rows
	//     :exec  → returns only an error (for INSERT/UPDATE/DELETE with no rows back)
	//     :execresult → returns sql.Result + error (gives you rows affected)
	//
	// Parameter syntax:
	//   $1, $2, $3 ... are positional parameters. sqlc maps these to typed Go
	//   function arguments in order. So $1 becomes the first argument, $2 the
	//   second, etc. The types are inferred from your schema columns.
	//
	// sqlpkg: pgx/v5
	//   We use pgx/v5 not database/sql. pgx is faster, supports more PostgreSQL
	//   types natively (e.g. pgtype.UUID, pgtype.Numeric), and has better
	//   context/timeout support.
	// =============================================================================
	// =============================================================================
	// SECTION 1: EXPENSES — CORE CRUD
	// =============================================================================
	// -----------------------------------------------------------------------------
	// CreateExpense
	// Inserts a new expense row. Returns the full created row immediately via
	// RETURNING so the caller gets the generated id, created_at, and updated_at
	// without a second round-trip to the database.
	//
	// Note on money: all _minor parameters are INTEGER (pence). The application
	// layer converts from pounds/pence before calling this.
	// Note on status: defaults to 'DRAFT' in the schema, so we don't pass it here.
	// -----------------------------------------------------------------------------
	CreateExpense(ctx context.Context, arg CreateExpenseParams) (Expense, error)
	// =============================================================================
	// SECTION 3: EXPENSE ATTACHMENTS
	// =============================================================================
	// -----------------------------------------------------------------------------
	// CreateExpenseAttachment
	// Records metadata for an uploaded file. The actual file has already been
	// written to GCS by the time this is called. storage_path is the GCS object
	// path — never a signed URL (those are generated on-demand, not stored).
	// -----------------------------------------------------------------------------
	CreateExpenseAttachment(ctx context.Context, arg CreateExpenseAttachmentParams) (ExpenseAttachment, error)
	// idempotent: deleting an already-deleted record is a no-op
	// =============================================================================
	// SECTION 2: EXPENSE MILEAGE
	// =============================================================================
	// -----------------------------------------------------------------------------
	// CreateExpenseMileage
	// Inserts the mileage sub-record for a mileage claim.
	// Always called immediately after CreateExpense when category is_mileage = true.
	// The expense_id here is the UUID returned by CreateExpense.
	// -----------------------------------------------------------------------------
	CreateExpenseMileage(ctx context.Context, arg CreateExpenseMileageParams) (ExpenseMileage, error)
	// =============================================================================
	// SECTION 4: EXPENSE RECURRENCE
	// =============================================================================
	// -----------------------------------------------------------------------------
	// CreateExpenseRecurrence
	// Attaches a recurrence schedule to an expense template.
	// The parent expense row holds the financial values; this table holds the
	// schedule. The service layer reads next_recurs_on daily and creates new
	// expense rows as copies of the template.
	// -----------------------------------------------------------------------------
	CreateExpenseRecurrence(ctx context.Context, arg CreateExpenseRecurrenceParams) (ExpenseRecurrence, error)
	// ^ RETURNING * tells sqlc to map the full expenses row as the return type.
	//   sqlc will generate an Expense struct with all columns as fields.
	// -----------------------------------------------------------------------------
	// CreateSkeletonExpense
	// Creates the placeholder draft behind "Smart Upload": a receipt is dropped in
	// before any data is typed, so we insert a stub expense that OCR (and then the
	// user) fills in. needs_review is hardcoded TRUE — that is the whole point of
	// this row — which puts it in the review inbox until a human confirms it.
	//
	// The caller supplies placeholders for the NOT NULL columns: category_id is the
	// org's "Sundries" catch-all, dated_on is today, description is a marker like
	// 'Awaiting review', and the money values are 0 (OCR fills them via
	// FillExpenseFromOCR). Everything else uses its schema default (status DRAFT,
	// currency GBP, VAT 0). Returns the full row so the caller has the new id.
	// -----------------------------------------------------------------------------
	CreateSkeletonExpense(ctx context.Context, arg CreateSkeletonExpenseParams) (Expense, error)
	// -----------------------------------------------------------------------------
	// DeactivateExpenseRecurrence
	// Stops a recurrence. Sets is_active = false rather than deleting the row
	// so we retain the history of when it was active.
	// -----------------------------------------------------------------------------
	DeactivateExpenseRecurrence(ctx context.Context, arg DeactivateExpenseRecurrenceParams) error
	// -----------------------------------------------------------------------------
	// DeleteExpenseAttachment
	// Hard delete — attachments can be genuinely removed (they're not financial
	// records themselves, just supporting documents). The file in GCS must be
	// deleted separately by the application layer after this succeeds.
	// :exec returns only an error.
	// -----------------------------------------------------------------------------
	DeleteExpenseAttachment(ctx context.Context, arg DeleteExpenseAttachmentParams) error
	// -----------------------------------------------------------------------------
	// FillExpenseFromOCR
	// Writes OCR-extracted values onto a (skeleton) expense WITHOUT clobbering data
	// a human already entered — the golden rule of automated capture.
	//
	//   * Text fields use COALESCE(existing, new): the new value is applied only
	//     when the column is still NULL. A non-NULL value the user typed is kept;
	//     a NULL OCR value (field not found) is a no-op.
	//   * Money fields fill only when the current value is 0 (the skeleton's
	//     placeholder). The service passes 0 when OCR found nothing or the currency
	//     did not match, so a 0 stays 0.
	//   * dated_on uses COALESCE(new, existing): a skeleton's dated_on is always the
	//     placeholder "today", so we PREFER the OCR date when present. (OCR only ever
	//     runs on a freshly created skeleton, so there is no real user date to lose.)
	//   * ocr_confidence / ocr_processed_at are OCR metadata and always set.
	//
	// needs_review is intentionally left untouched: OCR finishing is NOT the same as
	// a human confirming, so the row stays in the inbox until the user saves it.
	// Org-scoped, soft-delete aware. RETURNING * so the caller can build the response.
	// -----------------------------------------------------------------------------
	FillExpenseFromOCR(ctx context.Context, arg FillExpenseFromOCRParams) (Expense, error)
	// -----------------------------------------------------------------------------
	// GetExpense
	// Fetch a single expense by its UUID, scoped to the organisation.
	// We ALWAYS scope by organisation_id — never fetch by id alone.
	// This prevents one tenant accidentally reading another's data if an id leaks.
	// deleted_at IS NULL ensures soft-deleted records are invisible.
	// -----------------------------------------------------------------------------
	GetExpense(ctx context.Context, arg GetExpenseParams) (Expense, error)
	// is_primary DESC: TRUE sorts before FALSE, so primary comes first
	// -----------------------------------------------------------------------------
	// GetExpenseAttachment
	// Single attachment by id — used when generating a signed download URL.
	// We scope by organisation_id to prevent cross-tenant access.
	// -----------------------------------------------------------------------------
	GetExpenseAttachment(ctx context.Context, arg GetExpenseAttachmentParams) (ExpenseAttachment, error)
	// -----------------------------------------------------------------------------
	// GetExpenseCategoryByNominalCode
	// Fetch one active category by its nominal code within an organisation. Smart
	// Upload uses this to resolve the org's placeholder category ('6021' Sundries)
	// for a skeleton expense, since category UUIDs are generated per-org and so
	// can't be hardcoded. Org-scoped — categories are per-tenant reference data.
	// -----------------------------------------------------------------------------
	GetExpenseCategoryByNominalCode(ctx context.Context, arg GetExpenseCategoryByNominalCodeParams) (ExpenseCategory, error)
	// -----------------------------------------------------------------------------
	// GetExpenseMileage
	// Fetch the mileage sub-record for a given expense.
	// Called when rendering the mileage claim detail view.
	// -----------------------------------------------------------------------------
	GetExpenseMileage(ctx context.Context, expenseID uuid.UUID) (ExpenseMileage, error)
	// -----------------------------------------------------------------------------
	// GetExpenseRecurrence
	// Fetch recurrence settings for a given expense.
	// -----------------------------------------------------------------------------
	GetExpenseRecurrence(ctx context.Context, expenseID uuid.UUID) (ExpenseRecurrence, error)
	// soft delete filter
	// -----------------------------------------------------------------------------
	// GetExpenseWithDetails
	// Fetches an expense joined with its category name and nominal code.
	// Uses the v_expenses_full view we defined in the schema.
	// This is the query you'd use for the "view expense" detail page.
	// -----------------------------------------------------------------------------
	GetExpenseWithDetails(ctx context.Context, arg GetExpenseWithDetailsParams) (VExpensesFull, error)
	// =============================================================================
	// SECTION 6b: SUPPLIER → CATEGORY DICTIONARY (auto-categorisation)
	//
	// The supplier_category_map table is POPULATED automatically by the
	// learn_supplier_category() trigger (see db/schema/schema.sql) from confirmed
	// expenses. These two queries are the CONSUME side: read a remembered category
	// for a supplier, and apply it to an unconfirmed Smart Upload capture.
	// =============================================================================
	// -----------------------------------------------------------------------------
	// GetSuggestedCategory
	// Look up the category this organisation usually files a supplier under. The
	// supplier name is normalised here with the SAME rule the trigger uses to build
	// supplier_key — lower(btrim(...)) — so reads and writes always match. Returns no
	// row when the supplier has never been seen (caller treats that as "no suggestion").
	// Org-scoped; uses the uq_supplier_category unique index.
	// -----------------------------------------------------------------------------
	GetSuggestedCategory(ctx context.Context, arg GetSuggestedCategoryParams) (uuid.UUID, error)
	// -----------------------------------------------------------------------------
	// GetVatRate
	// Fetch a single VAT rate by id — used when applying VAT to an expense. The
	// service validates the rate's country_code against the caller's organisation,
	// then reads rate_bps + is_fixed_ratio to compute (fixed) or accept (custom) the
	// VAT amount. Deliberately NOT date-filtered: an expense may legitimately
	// reference a rate outside its current effective window (e.g. editing a
	// historical expense whose rate has since lapsed).
	// -----------------------------------------------------------------------------
	GetVatRate(ctx context.Context, id uuid.UUID) (GetVatRateRow, error)
	// -----------------------------------------------------------------------------
	// ListDueRecurrences
	// Returns all active recurrences that are due today or overdue.
	// This is the query your cron job / scheduler runs daily to generate new
	// expense copies. It returns the recurrence rows; the service then fetches
	// the template expense and creates a new copy for each one.
	// -----------------------------------------------------------------------------
	ListDueRecurrences(ctx context.Context) ([]ExpenseRecurrence, error)
	// -----------------------------------------------------------------------------
	// ListExpenseAttachments
	// All attachments for one expense, primary file first.
	// The UI shows attachments in this order.
	// -----------------------------------------------------------------------------
	ListExpenseAttachments(ctx context.Context, expenseID uuid.UUID) ([]ExpenseAttachment, error)
	// =============================================================================
	// SECTION 6: EXPENSE CATEGORIES (reference data)
	// =============================================================================
	// -----------------------------------------------------------------------------
	// ListExpenseCategories
	// All ACTIVE categories for an organisation, for the expense category picker.
	// Scoped by organisation_id — categories are per-tenant reference data.
	// Ordered by category_group then nominal_code so the UI can render stable
	// sections (Admin expenses / Assets and stock / Cost of Sales).
	// -----------------------------------------------------------------------------
	ListExpenseCategories(ctx context.Context, organisationID uuid.UUID) ([]ExpenseCategory, error)
	// -----------------------------------------------------------------------------
	// ListExpenses
	// Returns all active expenses for an organisation, newest first.
	// This is the base query for the expenses list page with no filters.
	// -----------------------------------------------------------------------------
	ListExpenses(ctx context.Context, organisationID uuid.UUID) ([]Expense, error)
	// -----------------------------------------------------------------------------
	// ListExpensesByDateRange
	// Filter by date range — used on the expenses list page date picker.
	// Both from_date and to_date are inclusive (BETWEEN is inclusive in PostgreSQL).
	// -----------------------------------------------------------------------------
	ListExpensesByDateRange(ctx context.Context, arg ListExpensesByDateRangeParams) ([]Expense, error)
	// -----------------------------------------------------------------------------
	// ListExpensesByProject
	// All expenses linked to a specific project (for rebilling to a client).
	// -----------------------------------------------------------------------------
	ListExpensesByProject(ctx context.Context, arg ListExpensesByProjectParams) ([]Expense, error)
	// -----------------------------------------------------------------------------
	// ListExpensesByStatus
	// Filter by workflow status — e.g. fetch all 'SUBMITTED' expenses for the
	// manager approval queue.
	// -----------------------------------------------------------------------------
	ListExpensesByStatus(ctx context.Context, arg ListExpensesByStatusParams) ([]Expense, error)
	// -----------------------------------------------------------------------------
	// ListExpensesByUser
	// Expenses for a specific claimant (the "my expenses" view).
	// Useful for employee self-service: they only see their own claims.
	// -----------------------------------------------------------------------------
	ListExpensesByUser(ctx context.Context, arg ListExpensesByUserParams) ([]Expense, error)
	// oldest first so managers action the earliest claims first
	// -----------------------------------------------------------------------------
	// ListExpensesNeedingReview
	// The "Smart Upload review inbox": captured expenses a human has not yet
	// confirmed. Newest first (most recently dropped-in receipt at the top). Uses the
	// partial index idx_expenses_needs_review. Org-scoped, soft-delete aware.
	// -----------------------------------------------------------------------------
	ListExpensesNeedingReview(ctx context.Context, organisationID uuid.UUID) ([]Expense, error)
	// -----------------------------------------------------------------------------
	// ListExpensesUpdatedSince
	// Returns all expenses modified after a given timestamp.
	// Used for sync / webhook scenarios: "give me everything changed since X".
	// Note: we do NOT filter deleted_at here — we want to surface soft-deleted
	// records so the consumer can remove them from their local cache too.
	// -----------------------------------------------------------------------------
	ListExpensesUpdatedSince(ctx context.Context, arg ListExpensesUpdatedSinceParams) ([]Expense, error)
	// -----------------------------------------------------------------------------
	// ListRecentExpenses
	// Last 30 days of expenses — useful for the dashboard "recent activity" widget.
	// -----------------------------------------------------------------------------
	ListRecentExpenses(ctx context.Context, organisationID uuid.UUID) ([]Expense, error)
	// =============================================================================
	// SECTION 7: VAT RATES (reference data)
	// =============================================================================
	// -----------------------------------------------------------------------------
	// ListVatRatesByCountry
	// All VAT rates that are valid TODAY for a given country, for the VAT rate
	// picker. VAT rates are global reference data keyed by country_code (not per
	// organisation) — the caller passes the organisation's country.
	//
	// "Valid today" means the rate is in its effective window:
	//   - effective_from is on or before today (not a future rate), AND
	//   - effective_to is NULL (still active) or on/after today (not yet expired).
	// This is why the COVID 5% hospitality rate, for example, stops appearing once
	// its effective_to date has passed.
	//
	// Explicit column list (not SELECT *) per project convention. Uses
	// idx_vat_rates_country for the country_code lookup.
	// -----------------------------------------------------------------------------
	ListVatRatesByCountry(ctx context.Context, countryCode string) ([]ListVatRatesByCountryRow, error)
	// -----------------------------------------------------------------------------
	// MarkAttachmentOCRProcessing
	// Flips an attachment from PENDING to PROCESSING when the OCR worker picks it up.
	// Deliberately separate from UpdateAttachmentOCRStatus: this is a non-terminal
	// transition, so it does NOT set ocr_processed_at (that marks completion). Org-
	// scoped like every tenant write.
	// -----------------------------------------------------------------------------
	MarkAttachmentOCRProcessing(ctx context.Context, arg MarkAttachmentOCRProcessingParams) error
	// -----------------------------------------------------------------------------
	// SetAttachmentPrimary
	// Marks a single attachment as the primary one for its expense. Pair it with
	// UnsetExpensePrimary inside one transaction so the "exactly one primary"
	// invariant holds. organisation_id prevents cross-tenant writes.
	// -----------------------------------------------------------------------------
	SetAttachmentPrimary(ctx context.Context, arg SetAttachmentPrimaryParams) error
	// -----------------------------------------------------------------------------
	// SoftDeleteExpense
	// Sets deleted_at to mark the record as deleted. The row remains in the DB
	// for audit purposes but is invisible to all other queries.
	// Accounting records should never be hard-deleted once submitted.
	// :exec means the generated Go function returns only an error (no row back).
	// -----------------------------------------------------------------------------
	SoftDeleteExpense(ctx context.Context, arg SoftDeleteExpenseParams) error
	// =============================================================================
	// SECTION 5: REPORTING / AGGREGATION QUERIES
	// =============================================================================
	// -----------------------------------------------------------------------------
	// SumExpensesByCategory
	// Totals per category for a date range — used on the P&L and expense reports.
	// Returns category name, nominal code, and total gross + VAT in home currency.
	// These are INTEGER sums (pence); the service layer formats them for display.
	// -----------------------------------------------------------------------------
	SumExpensesByCategory(ctx context.Context, arg SumExpensesByCategoryParams) ([]SumExpensesByCategoryRow, error)
	// -----------------------------------------------------------------------------
	// SumExpensesByMonth
	// Month-by-month totals for a calendar year — used for trend charts.
	// DATE_TRUNC rounds each dated_on down to the first of its month, letting
	// GROUP BY aggregate by month cleanly.
	// -----------------------------------------------------------------------------
	SumExpensesByMonth(ctx context.Context, arg SumExpensesByMonthParams) ([]SumExpensesByMonthRow, error)
	// -----------------------------------------------------------------------------
	// UnsetExpensePrimary
	// Clears the primary flag on every attachment of an expense. Run inside a
	// transaction immediately BEFORE SetAttachmentPrimary so that exactly one row
	// ends up flagged primary. organisation_id keeps the update tenant-scoped.
	// -----------------------------------------------------------------------------
	UnsetExpensePrimary(ctx context.Context, arg UnsetExpensePrimaryParams) error
	// -----------------------------------------------------------------------------
	// UpdateAttachmentOCRStatus
	// Records a TERMINAL OCR result (COMPLETE / FAILED / SKIPPED) on an attachment.
	// ocr_extracted_data is JSONB — in Go this is a []byte the service marshals from
	// its ExtractionResult. ocr_processed_at is stamped now() because the attachment
	// has reached a terminal OCR state.
	// Scoped by organisation_id (not just id): every write that touches tenant data
	// is org-scoped, even on the internal OCR path, as defence in depth.
	// For the PENDING→PROCESSING transition use MarkAttachmentOCRProcessing instead,
	// which deliberately does NOT stamp ocr_processed_at.
	// -----------------------------------------------------------------------------
	UpdateAttachmentOCRStatus(ctx context.Context, arg UpdateAttachmentOCRStatusParams) (ExpenseAttachment, error)
	// -----------------------------------------------------------------------------
	// UpdateExpense
	// Updates the editable fields on an expense. Only allowed when status is
	// DRAFT or REJECTED (the application layer enforces this, not the DB).
	// We update updated_at explicitly here even though the trigger also does it —
	// belt-and-suspenders approach.
	// RETURNING * gives us the updated row back so the API can return it.
	// -----------------------------------------------------------------------------
	UpdateExpense(ctx context.Context, arg UpdateExpenseParams) (Expense, error)
	// -----------------------------------------------------------------------------
	// UpdateExpenseMileage
	// Update mileage fields — only valid while parent expense is DRAFT/REJECTED.
	// -----------------------------------------------------------------------------
	UpdateExpenseMileage(ctx context.Context, arg UpdateExpenseMileageParams) (ExpenseMileage, error)
	// -----------------------------------------------------------------------------
	// UpdateExpenseStatus
	// Dedicated query for status transitions only.
	// Separating this from UpdateExpense prevents accidental overwrite of all
	// fields during a status change (e.g. manager approving shouldn't change amounts).
	// The application layer validates the transition is legal before calling this.
	// -----------------------------------------------------------------------------
	UpdateExpenseStatus(ctx context.Context, arg UpdateExpenseStatusParams) (Expense, error)
	// -----------------------------------------------------------------------------
	// UpdateRecurrenceNextDate
	// After a recurrence fires and a new expense is created, advance the
	// next_recurs_on date. The service layer calculates the next date based on
	// frequency (e.g. add 1 month) and passes it here.
	// -----------------------------------------------------------------------------
	UpdateRecurrenceNextDate(ctx context.Context, arg UpdateRecurrenceNextDateParams) (ExpenseRecurrence, error)
}

var _ Querier = (*Queries)(nil)
