// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package expenses

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countExpensesByStatus = `-- name: CountExpensesByStatus :many
SELECT
    status,
    COUNT(*) AS count
FROM expenses
WHERE organisation_id = $1
  AND deleted_at IS NULL
GROUP BY status
`

type CountExpensesByStatusRow struct {
	Status string `json:"status"`
	Count  int64  `json:"count"`
}

// -----------------------------------------------------------------------------
// CountExpensesByStatus
// Count of expenses per status — used for the dashboard summary cards.
// e.g. "3 Pending Approval", "12 Paid This Month"
// -----------------------------------------------------------------------------
func (q *Queries) CountExpensesByStatus(ctx context.Context, organisationID uuid.UUID) ([]CountExpensesByStatusRow, error) {
	rows, err := q.db.Query(ctx, countExpensesByStatus, organisationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountExpensesByStatusRow
	for rows.Next() {
		var i CountExpensesByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createExpense = `-- name: CreateExpense :one



INSERT INTO expenses (
    organisation_id,
    user_id,
    created_by_user_id,
    category_id,
    dated_on,
    description,
    receipt_reference,
    invoice_number,
    supplier_name,
    supplier_vat_number,
    currency,
    native_currency,
    exchange_rate,
    gross_value_minor,
    native_gross_value_minor,
    vat_rate_id,
    vat_rate_bps,
    vat_value_minor,
    native_vat_value_minor,
    manual_vat_amount_minor,
    vat_status,
    ec_status,
    project_id,
    rebill_type,
    rebill_factor,
    stock_item_id,
    stock_item_description,
    stock_quantity,
    property_id
) VALUES (
    $1,   -- organisation_id       UUID
    $2,   -- user_id               UUID  (the claimant)
    $3,   -- created_by_user_id    UUID  (may differ from claimant if admin entering on behalf)
    $4,   -- category_id           UUID
    $5,   -- dated_on              DATE  (date on the receipt)
    $6,   -- description           TEXT
    $7,   -- receipt_reference     VARCHAR (nullable — use NULL if none)
    $8,   -- invoice_number        VARCHAR (nullable — supplier's invoice number)
    $9,   -- supplier_name         VARCHAR (nullable)
    $10,  -- supplier_vat_number   VARCHAR (nullable)
    $11,  -- currency              CHAR(3) e.g. 'GBP'
    $12,  -- native_currency       CHAR(3) e.g. 'GBP'
    $13,  -- exchange_rate         NUMERIC (nullable — NULL if same currency)
    $14,  -- gross_value_minor     INTEGER (pence, negative = owed to employee)
    $15,  -- native_gross_value_minor INTEGER (pence in home currency)
    $16,  -- vat_rate_id           UUID (nullable — NULL if no VAT)
    $17,  -- vat_rate_bps          INTEGER (nullable — snapshot of rate, e.g. 2000 = 20%)
    $18,  -- vat_value_minor       INTEGER (pence)
    $19,  -- native_vat_value_minor INTEGER (pence)
    $20,  -- manual_vat_amount_minor INTEGER (nullable — override for foreign currency expenses)
    $21,  -- vat_status            VARCHAR 'TAXABLE'|'EXEMPT'|'OUT_OF_SCOPE'
    $22,  -- ec_status             VARCHAR 'UK_NON_EC'|'EC_GOODS'|'EC_SERVICES'|'REVERSE_CHARGE'
    $23,  -- project_id            UUID (nullable)
    $24,  -- rebill_type           VARCHAR (nullable) 'cost'|'markup'|'price'
    $25,  -- rebill_factor         NUMERIC (nullable)
    $26,  -- stock_item_id         UUID (nullable)
    $27,  -- stock_item_description TEXT (nullable)
    $28,  -- stock_quantity        NUMERIC (nullable)
    $29   -- property_id           UUID (nullable)
)
RETURNING id, organisation_id, user_id, created_by_user_id, category_id, dated_on, description, receipt_reference, currency, native_currency, exchange_rate, gross_value_minor, native_gross_value_minor, vat_rate_id, vat_rate_bps, vat_value_minor, native_vat_value_minor, manual_vat_amount_minor, vat_status, ec_status, project_id, rebill_type, rebill_factor, rebilled_invoice_id, stock_item_id, stock_item_description, stock_quantity, capital_asset_id, property_id, status, submitted_at, approved_at, approved_by_user_id, paid_at, rejection_note, ocr_confidence, ocr_processed_at, supplier_name, supplier_vat_number, invoice_number, deleted_at, created_at, updated_at
`

type CreateExpenseParams struct {
	OrganisationID        uuid.UUID      `json:"organisation_id"`
	UserID                uuid.UUID      `json:"user_id"`
	CreatedByUserID       uuid.UUID      `json:"created_by_user_id"`
	CategoryID            uuid.UUID      `json:"category_id"`
	DatedOn               pgtype.Date    `json:"dated_on"`
	Description           string         `json:"description"`
	ReceiptReference      pgtype.Text    `json:"receipt_reference"`
	InvoiceNumber         pgtype.Text    `json:"invoice_number"`
	SupplierName          pgtype.Text    `json:"supplier_name"`
	SupplierVatNumber     pgtype.Text    `json:"supplier_vat_number"`
	Currency              string         `json:"currency"`
	NativeCurrency        string         `json:"native_currency"`
	ExchangeRate          pgtype.Numeric `json:"exchange_rate"`
	GrossValueMinor       int32          `json:"gross_value_minor"`
	NativeGrossValueMinor int32          `json:"native_gross_value_minor"`
	VatRateID             pgtype.UUID    `json:"vat_rate_id"`
	VatRateBps            pgtype.Int4    `json:"vat_rate_bps"`
	VatValueMinor         int32          `json:"vat_value_minor"`
	NativeVatValueMinor   int32          `json:"native_vat_value_minor"`
	ManualVatAmountMinor  pgtype.Int4    `json:"manual_vat_amount_minor"`
	VatStatus             string         `json:"vat_status"`
	EcStatus              string         `json:"ec_status"`
	ProjectID             pgtype.UUID    `json:"project_id"`
	RebillType            pgtype.Text    `json:"rebill_type"`
	RebillFactor          pgtype.Numeric `json:"rebill_factor"`
	StockItemID           pgtype.UUID    `json:"stock_item_id"`
	StockItemDescription  pgtype.Text    `json:"stock_item_description"`
	StockQuantity         pgtype.Numeric `json:"stock_quantity"`
	PropertyID            pgtype.UUID    `json:"property_id"`
}

// =============================================================================
// EXPENSES MODULE — SQLC QUERIES
// File: db/queries/query.sql
//
// What is sqlc?
//
//	sqlc reads this file plus your schema.sql and generates type-safe Go code.
//	Every query here becomes a Go function with typed parameters and return
//	values. You never write boilerplate database scan/row code by hand.
//
// Annotation syntax:
//
//	Every query must have a comment in this exact format:
//
//	  -- name: FunctionName :return_type
//
//	Return types:
//	  :one   → returns a single row (error if 0 or >1 rows)
//	  :many  → returns a slice of rows
//	  :exec  → returns only an error (for INSERT/UPDATE/DELETE with no rows back)
//	  :execresult → returns sql.Result + error (gives you rows affected)
//
// Parameter syntax:
//
//	$1, $2, $3 ... are positional parameters. sqlc maps these to typed Go
//	function arguments in order. So $1 becomes the first argument, $2 the
//	second, etc. The types are inferred from your schema columns.
//
// sqlpkg: pgx/v5
//
//	We use pgx/v5 not database/sql. pgx is faster, supports more PostgreSQL
//	types natively (e.g. pgtype.UUID, pgtype.Numeric), and has better
//	context/timeout support.
//
// =============================================================================
// =============================================================================
// SECTION 1: EXPENSES — CORE CRUD
// =============================================================================
// -----------------------------------------------------------------------------
// CreateExpense
// Inserts a new expense row. Returns the full created row immediately via
// RETURNING so the caller gets the generated id, created_at, and updated_at
// without a second round-trip to the database.
//
// Note on money: all _minor parameters are INTEGER (pence). The application
// layer converts from pounds/pence before calling this.
// Note on status: defaults to 'DRAFT' in the schema, so we don't pass it here.
// -----------------------------------------------------------------------------
func (q *Queries) CreateExpense(ctx context.Context, arg CreateExpenseParams) (Expense, error) {
	row := q.db.QueryRow(ctx, createExpense,
		arg.OrganisationID,
		arg.UserID,
		arg.CreatedByUserID,
		arg.CategoryID,
		arg.DatedOn,
		arg.Description,
		arg.ReceiptReference,
		arg.InvoiceNumber,
		arg.SupplierName,
		arg.SupplierVatNumber,
		arg.Currency,
		arg.NativeCurrency,
		arg.ExchangeRate,
		arg.GrossValueMinor,
		arg.NativeGrossValueMinor,
		arg.VatRateID,
		arg.VatRateBps,
		arg.VatValueMinor,
		arg.NativeVatValueMinor,
		arg.ManualVatAmountMinor,
		arg.VatStatus,
		arg.EcStatus,
		arg.ProjectID,
		arg.RebillType,
		arg.RebillFactor,
		arg.StockItemID,
		arg.StockItemDescription,
		arg.StockQuantity,
		arg.PropertyID,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.UserID,
		&i.CreatedByUserID,
		&i.CategoryID,
		&i.DatedOn,
		&i.Description,
		&i.ReceiptReference,
		&i.Currency,
		&i.NativeCurrency,
		&i.ExchangeRate,
		&i.GrossValueMinor,
		&i.NativeGrossValueMinor,
		&i.VatRateID,
		&i.VatRateBps,
		&i.VatValueMinor,
		&i.NativeVatValueMinor,
		&i.ManualVatAmountMinor,
		&i.VatStatus,
		&i.EcStatus,
		&i.ProjectID,
		&i.RebillType,
		&i.RebillFactor,
		&i.RebilledInvoiceID,
		&i.StockItemID,
		&i.StockItemDescription,
		&i.StockQuantity,
		&i.CapitalAssetID,
		&i.PropertyID,
		&i.Status,
		&i.SubmittedAt,
		&i.ApprovedAt,
		&i.ApprovedByUserID,
		&i.PaidAt,
		&i.RejectionNote,
		&i.OcrConfidence,
		&i.OcrProcessedAt,
		&i.SupplierName,
		&i.SupplierVatNumber,
		&i.InvoiceNumber,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createExpenseAttachment = `-- name: CreateExpenseAttachment :one

INSERT INTO expense_attachments (
    expense_id,
    organisation_id,
    file_name,
    content_type,
    file_size_bytes,
    storage_path,
    storage_bucket,
    description,
    is_primary,
    uploaded_by_user_id
) VALUES (
    $1,   -- expense_id           UUID
    $2,   -- organisation_id      UUID
    $3,   -- file_name            VARCHAR e.g. 'receipt_jan.pdf'
    $4,   -- content_type         VARCHAR e.g. 'application/pdf'
    $5,   -- file_size_bytes      INTEGER
    $6,   -- storage_path         TEXT e.g. 'orgs/abc123/expenses/xyz/receipt.pdf'
    $7,   -- storage_bucket       VARCHAR e.g. 'myapp-expense-documents-prod'
    $8,   -- description          TEXT (nullable — user label for this file)
    $9,   -- is_primary           BOOLEAN
    $10   -- uploaded_by_user_id  UUID
)
RETURNING id, expense_id, organisation_id, file_name, content_type, file_size_bytes, storage_path, storage_bucket, description, is_primary, ocr_status, ocr_raw_text, ocr_extracted_data, ocr_processed_at, uploaded_by_user_id, created_at, updated_at
`

type CreateExpenseAttachmentParams struct {
	ExpenseID        uuid.UUID   `json:"expense_id"`
	OrganisationID   uuid.UUID   `json:"organisation_id"`
	FileName         string      `json:"file_name"`
	ContentType      string      `json:"content_type"`
	FileSizeBytes    int32       `json:"file_size_bytes"`
	StoragePath      string      `json:"storage_path"`
	StorageBucket    string      `json:"storage_bucket"`
	Description      pgtype.Text `json:"description"`
	IsPrimary        bool        `json:"is_primary"`
	UploadedByUserID uuid.UUID   `json:"uploaded_by_user_id"`
}

// =============================================================================
// SECTION 3: EXPENSE ATTACHMENTS
// =============================================================================
// -----------------------------------------------------------------------------
// CreateExpenseAttachment
// Records metadata for an uploaded file. The actual file has already been
// written to GCS by the time this is called. storage_path is the GCS object
// path — never a signed URL (those are generated on-demand, not stored).
// -----------------------------------------------------------------------------
func (q *Queries) CreateExpenseAttachment(ctx context.Context, arg CreateExpenseAttachmentParams) (ExpenseAttachment, error) {
	row := q.db.QueryRow(ctx, createExpenseAttachment,
		arg.ExpenseID,
		arg.OrganisationID,
		arg.FileName,
		arg.ContentType,
		arg.FileSizeBytes,
		arg.StoragePath,
		arg.StorageBucket,
		arg.Description,
		arg.IsPrimary,
		arg.UploadedByUserID,
	)
	var i ExpenseAttachment
	err := row.Scan(
		&i.ID,
		&i.ExpenseID,
		&i.OrganisationID,
		&i.FileName,
		&i.ContentType,
		&i.FileSizeBytes,
		&i.StoragePath,
		&i.StorageBucket,
		&i.Description,
		&i.IsPrimary,
		&i.OcrStatus,
		&i.OcrRawText,
		&i.OcrExtractedData,
		&i.OcrProcessedAt,
		&i.UploadedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createExpenseMileage = `-- name: CreateExpenseMileage :one



INSERT INTO expense_mileage (
    expense_id,
    miles,
    journey_description,
    journey_from,
    journey_to,
    vehicle_type,
    engine_type,
    engine_size,
    reclaim_mileage,
    initial_rate_ppm,
    reduced_rate_ppm,
    rebill_rate_ppm,
    reimbursement_minor,
    have_vat_receipt
) VALUES (
    $1,   -- expense_id           UUID (from CreateExpense)
    $2,   -- miles                NUMERIC e.g. 42.5
    $3,   -- journey_description  TEXT (nullable)
    $4,   -- journey_from         VARCHAR (nullable)
    $5,   -- journey_to           VARCHAR (nullable)
    $6,   -- vehicle_type         'CAR'|'MOTORCYCLE'|'BICYCLE'
    $7,   -- engine_type          VARCHAR (nullable for bicycles)
    $8,   -- engine_size          VARCHAR (nullable)
    $9,   -- reclaim_mileage      BOOLEAN (true = claim AMAP from HMRC)
    $10,  -- initial_rate_ppm     INTEGER (pence-per-mile, e.g. 45 = 45p/mile)
    $11,  -- reduced_rate_ppm     INTEGER (pence-per-mile above 10k threshold, e.g. 25)
    $12,  -- rebill_rate_ppm      INTEGER (nullable — ppm to charge client)
    $13,  -- reimbursement_minor  INTEGER (total reimbursement in pence, computed by service)
    $14   -- have_vat_receipt     BOOLEAN
)
RETURNING id, expense_id, miles, journey_description, journey_from, journey_to, vehicle_type, engine_type, engine_size, reclaim_mileage, initial_rate_ppm, reduced_rate_ppm, rebill_rate_ppm, reimbursement_minor, have_vat_receipt, created_at, updated_at
`

type CreateExpenseMileageParams struct {
	ExpenseID          uuid.UUID   `json:"expense_id"`
	Miles              string      `json:"miles"`
	JourneyDescription pgtype.Text `json:"journey_description"`
	JourneyFrom        pgtype.Text `json:"journey_from"`
	JourneyTo          pgtype.Text `json:"journey_to"`
	VehicleType        string      `json:"vehicle_type"`
	EngineType         pgtype.Text `json:"engine_type"`
	EngineSize         pgtype.Text `json:"engine_size"`
	ReclaimMileage     bool        `json:"reclaim_mileage"`
	InitialRatePpm     pgtype.Int4 `json:"initial_rate_ppm"`
	ReducedRatePpm     pgtype.Int4 `json:"reduced_rate_ppm"`
	RebillRatePpm      pgtype.Int4 `json:"rebill_rate_ppm"`
	ReimbursementMinor pgtype.Int4 `json:"reimbursement_minor"`
	HaveVatReceipt     bool        `json:"have_vat_receipt"`
}

// idempotent: deleting an already-deleted record is a no-op
// =============================================================================
// SECTION 2: EXPENSE MILEAGE
// =============================================================================
// -----------------------------------------------------------------------------
// CreateExpenseMileage
// Inserts the mileage sub-record for a mileage claim.
// Always called immediately after CreateExpense when category is_mileage = true.
// The expense_id here is the UUID returned by CreateExpense.
// -----------------------------------------------------------------------------
func (q *Queries) CreateExpenseMileage(ctx context.Context, arg CreateExpenseMileageParams) (ExpenseMileage, error) {
	row := q.db.QueryRow(ctx, createExpenseMileage,
		arg.ExpenseID,
		arg.Miles,
		arg.JourneyDescription,
		arg.JourneyFrom,
		arg.JourneyTo,
		arg.VehicleType,
		arg.EngineType,
		arg.EngineSize,
		arg.ReclaimMileage,
		arg.InitialRatePpm,
		arg.ReducedRatePpm,
		arg.RebillRatePpm,
		arg.ReimbursementMinor,
		arg.HaveVatReceipt,
	)
	var i ExpenseMileage
	err := row.Scan(
		&i.ID,
		&i.ExpenseID,
		&i.Miles,
		&i.JourneyDescription,
		&i.JourneyFrom,
		&i.JourneyTo,
		&i.VehicleType,
		&i.EngineType,
		&i.EngineSize,
		&i.ReclaimMileage,
		&i.InitialRatePpm,
		&i.ReducedRatePpm,
		&i.RebillRatePpm,
		&i.ReimbursementMinor,
		&i.HaveVatReceipt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createExpenseRecurrence = `-- name: CreateExpenseRecurrence :one

INSERT INTO expense_recurrence (
    expense_id,
    organisation_id,
    frequency,
    next_recurs_on,
    end_date
) VALUES (
    $1,   -- expense_id      UUID (the template expense)
    $2,   -- organisation_id UUID
    $3,   -- frequency       e.g. 'MONTHLY', 'QUARTERLY'
    $4,   -- next_recurs_on  DATE (when the next copy should be created)
    $5    -- end_date        DATE (nullable — NULL means recur forever)
)
RETURNING id, expense_id, organisation_id, frequency, next_recurs_on, end_date, is_active, created_at, updated_at
`

type CreateExpenseRecurrenceParams struct {
	ExpenseID      uuid.UUID   `json:"expense_id"`
	OrganisationID uuid.UUID   `json:"organisation_id"`
	Frequency      string      `json:"frequency"`
	NextRecursOn   pgtype.Date `json:"next_recurs_on"`
	EndDate        pgtype.Date `json:"end_date"`
}

// =============================================================================
// SECTION 4: EXPENSE RECURRENCE
// =============================================================================
// -----------------------------------------------------------------------------
// CreateExpenseRecurrence
// Attaches a recurrence schedule to an expense template.
// The parent expense row holds the financial values; this table holds the
// schedule. The service layer reads next_recurs_on daily and creates new
// expense rows as copies of the template.
// -----------------------------------------------------------------------------
func (q *Queries) CreateExpenseRecurrence(ctx context.Context, arg CreateExpenseRecurrenceParams) (ExpenseRecurrence, error) {
	row := q.db.QueryRow(ctx, createExpenseRecurrence,
		arg.ExpenseID,
		arg.OrganisationID,
		arg.Frequency,
		arg.NextRecursOn,
		arg.EndDate,
	)
	var i ExpenseRecurrence
	err := row.Scan(
		&i.ID,
		&i.ExpenseID,
		&i.OrganisationID,
		&i.Frequency,
		&i.NextRecursOn,
		&i.EndDate,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateExpenseRecurrence = `-- name: DeactivateExpenseRecurrence :exec
UPDATE expense_recurrence SET
    is_active  = FALSE,
    updated_at = now()
WHERE expense_id      = $1
  AND organisation_id = $2
`

type DeactivateExpenseRecurrenceParams struct {
	ExpenseID      uuid.UUID `json:"expense_id"`
	OrganisationID uuid.UUID `json:"organisation_id"`
}

// -----------------------------------------------------------------------------
// DeactivateExpenseRecurrence
// Stops a recurrence. Sets is_active = false rather than deleting the row
// so we retain the history of when it was active.
// -----------------------------------------------------------------------------
func (q *Queries) DeactivateExpenseRecurrence(ctx context.Context, arg DeactivateExpenseRecurrenceParams) error {
	_, err := q.db.Exec(ctx, deactivateExpenseRecurrence, arg.ExpenseID, arg.OrganisationID)
	return err
}

const deleteExpenseAttachment = `-- name: DeleteExpenseAttachment :exec
DELETE FROM expense_attachments
WHERE id              = $1
  AND organisation_id = $2
`

type DeleteExpenseAttachmentParams struct {
	ID             uuid.UUID `json:"id"`
	OrganisationID uuid.UUID `json:"organisation_id"`
}

// -----------------------------------------------------------------------------
// DeleteExpenseAttachment
// Hard delete — attachments can be genuinely removed (they're not financial
// records themselves, just supporting documents). The file in GCS must be
// deleted separately by the application layer after this succeeds.
// :exec returns only an error.
// -----------------------------------------------------------------------------
func (q *Queries) DeleteExpenseAttachment(ctx context.Context, arg DeleteExpenseAttachmentParams) error {
	_, err := q.db.Exec(ctx, deleteExpenseAttachment, arg.ID, arg.OrganisationID)
	return err
}

const getExpense = `-- name: GetExpense :one


SELECT id, organisation_id, user_id, created_by_user_id, category_id, dated_on, description, receipt_reference, currency, native_currency, exchange_rate, gross_value_minor, native_gross_value_minor, vat_rate_id, vat_rate_bps, vat_value_minor, native_vat_value_minor, manual_vat_amount_minor, vat_status, ec_status, project_id, rebill_type, rebill_factor, rebilled_invoice_id, stock_item_id, stock_item_description, stock_quantity, capital_asset_id, property_id, status, submitted_at, approved_at, approved_by_user_id, paid_at, rejection_note, ocr_confidence, ocr_processed_at, supplier_name, supplier_vat_number, invoice_number, deleted_at, created_at, updated_at FROM expenses
WHERE id              = $1   -- expense UUID
  AND organisation_id = $2   -- tenant scope — never skip this
  AND deleted_at IS NULL
`

type GetExpenseParams struct {
	ID             uuid.UUID `json:"id"`
	OrganisationID uuid.UUID `json:"organisation_id"`
}

// ^ RETURNING * tells sqlc to map the full expenses row as the return type.
//
//	sqlc will generate an Expense struct with all columns as fields.
//
// -----------------------------------------------------------------------------
// GetExpense
// Fetch a single expense by its UUID, scoped to the organisation.
// We ALWAYS scope by organisation_id — never fetch by id alone.
// This prevents one tenant accidentally reading another's data if an id leaks.
// deleted_at IS NULL ensures soft-deleted records are invisible.
// -----------------------------------------------------------------------------
func (q *Queries) GetExpense(ctx context.Context, arg GetExpenseParams) (Expense, error) {
	row := q.db.QueryRow(ctx, getExpense, arg.ID, arg.OrganisationID)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.UserID,
		&i.CreatedByUserID,
		&i.CategoryID,
		&i.DatedOn,
		&i.Description,
		&i.ReceiptReference,
		&i.Currency,
		&i.NativeCurrency,
		&i.ExchangeRate,
		&i.GrossValueMinor,
		&i.NativeGrossValueMinor,
		&i.VatRateID,
		&i.VatRateBps,
		&i.VatValueMinor,
		&i.NativeVatValueMinor,
		&i.ManualVatAmountMinor,
		&i.VatStatus,
		&i.EcStatus,
		&i.ProjectID,
		&i.RebillType,
		&i.RebillFactor,
		&i.RebilledInvoiceID,
		&i.StockItemID,
		&i.StockItemDescription,
		&i.StockQuantity,
		&i.CapitalAssetID,
		&i.PropertyID,
		&i.Status,
		&i.SubmittedAt,
		&i.ApprovedAt,
		&i.ApprovedByUserID,
		&i.PaidAt,
		&i.RejectionNote,
		&i.OcrConfidence,
		&i.OcrProcessedAt,
		&i.SupplierName,
		&i.SupplierVatNumber,
		&i.InvoiceNumber,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExpenseAttachment = `-- name: GetExpenseAttachment :one


SELECT id, expense_id, organisation_id, file_name, content_type, file_size_bytes, storage_path, storage_bucket, description, is_primary, ocr_status, ocr_raw_text, ocr_extracted_data, ocr_processed_at, uploaded_by_user_id, created_at, updated_at FROM expense_attachments
WHERE id              = $1
  AND organisation_id = $2
`

type GetExpenseAttachmentParams struct {
	ID             uuid.UUID `json:"id"`
	OrganisationID uuid.UUID `json:"organisation_id"`
}

// is_primary DESC: TRUE sorts before FALSE, so primary comes first
// -----------------------------------------------------------------------------
// GetExpenseAttachment
// Single attachment by id — used when generating a signed download URL.
// We scope by organisation_id to prevent cross-tenant access.
// -----------------------------------------------------------------------------
func (q *Queries) GetExpenseAttachment(ctx context.Context, arg GetExpenseAttachmentParams) (ExpenseAttachment, error) {
	row := q.db.QueryRow(ctx, getExpenseAttachment, arg.ID, arg.OrganisationID)
	var i ExpenseAttachment
	err := row.Scan(
		&i.ID,
		&i.ExpenseID,
		&i.OrganisationID,
		&i.FileName,
		&i.ContentType,
		&i.FileSizeBytes,
		&i.StoragePath,
		&i.StorageBucket,
		&i.Description,
		&i.IsPrimary,
		&i.OcrStatus,
		&i.OcrRawText,
		&i.OcrExtractedData,
		&i.OcrProcessedAt,
		&i.UploadedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExpenseMileage = `-- name: GetExpenseMileage :one
SELECT id, expense_id, miles, journey_description, journey_from, journey_to, vehicle_type, engine_type, engine_size, reclaim_mileage, initial_rate_ppm, reduced_rate_ppm, rebill_rate_ppm, reimbursement_minor, have_vat_receipt, created_at, updated_at FROM expense_mileage
WHERE expense_id = $1
`

// -----------------------------------------------------------------------------
// GetExpenseMileage
// Fetch the mileage sub-record for a given expense.
// Called when rendering the mileage claim detail view.
// -----------------------------------------------------------------------------
func (q *Queries) GetExpenseMileage(ctx context.Context, expenseID uuid.UUID) (ExpenseMileage, error) {
	row := q.db.QueryRow(ctx, getExpenseMileage, expenseID)
	var i ExpenseMileage
	err := row.Scan(
		&i.ID,
		&i.ExpenseID,
		&i.Miles,
		&i.JourneyDescription,
		&i.JourneyFrom,
		&i.JourneyTo,
		&i.VehicleType,
		&i.EngineType,
		&i.EngineSize,
		&i.ReclaimMileage,
		&i.InitialRatePpm,
		&i.ReducedRatePpm,
		&i.RebillRatePpm,
		&i.ReimbursementMinor,
		&i.HaveVatReceipt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExpenseRecurrence = `-- name: GetExpenseRecurrence :one
SELECT id, expense_id, organisation_id, frequency, next_recurs_on, end_date, is_active, created_at, updated_at FROM expense_recurrence
WHERE expense_id = $1
`

// -----------------------------------------------------------------------------
// GetExpenseRecurrence
// Fetch recurrence settings for a given expense.
// -----------------------------------------------------------------------------
func (q *Queries) GetExpenseRecurrence(ctx context.Context, expenseID uuid.UUID) (ExpenseRecurrence, error) {
	row := q.db.QueryRow(ctx, getExpenseRecurrence, expenseID)
	var i ExpenseRecurrence
	err := row.Scan(
		&i.ID,
		&i.ExpenseID,
		&i.OrganisationID,
		&i.Frequency,
		&i.NextRecursOn,
		&i.EndDate,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExpenseWithDetails = `-- name: GetExpenseWithDetails :one


SELECT id, organisation_id, user_id, created_by_user_id, dated_on, description, receipt_reference, invoice_number, supplier_name, supplier_vat_number, currency, native_currency, exchange_rate, gross_value_minor, native_gross_value_minor, vat_rate_bps, vat_value_minor, native_vat_value_minor, manual_vat_amount_minor, vat_status, ec_status, project_id, rebill_type, rebill_factor, rebilled_invoice_id, stock_item_id, stock_quantity, capital_asset_id, status, submitted_at, approved_at, approved_by_user_id, paid_at, category_nominal_code, category_name, category_is_mileage, category_is_capital_asset, miles, vehicle_type, engine_type, engine_size, reclaim_mileage, initial_rate_ppm, reduced_rate_ppm, rebill_rate_ppm, reimbursement_minor, created_at, updated_at FROM v_expenses_full
WHERE id              = $1
  AND organisation_id = $2
`

type GetExpenseWithDetailsParams struct {
	ID             uuid.UUID `json:"id"`
	OrganisationID uuid.UUID `json:"organisation_id"`
}

// soft delete filter
// -----------------------------------------------------------------------------
// GetExpenseWithDetails
// Fetches an expense joined with its category name and nominal code.
// Uses the v_expenses_full view we defined in the schema.
// This is the query you'd use for the "view expense" detail page.
// -----------------------------------------------------------------------------
func (q *Queries) GetExpenseWithDetails(ctx context.Context, arg GetExpenseWithDetailsParams) (VExpensesFull, error) {
	row := q.db.QueryRow(ctx, getExpenseWithDetails, arg.ID, arg.OrganisationID)
	var i VExpensesFull
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.UserID,
		&i.CreatedByUserID,
		&i.DatedOn,
		&i.Description,
		&i.ReceiptReference,
		&i.InvoiceNumber,
		&i.SupplierName,
		&i.SupplierVatNumber,
		&i.Currency,
		&i.NativeCurrency,
		&i.ExchangeRate,
		&i.GrossValueMinor,
		&i.NativeGrossValueMinor,
		&i.VatRateBps,
		&i.VatValueMinor,
		&i.NativeVatValueMinor,
		&i.ManualVatAmountMinor,
		&i.VatStatus,
		&i.EcStatus,
		&i.ProjectID,
		&i.RebillType,
		&i.RebillFactor,
		&i.RebilledInvoiceID,
		&i.StockItemID,
		&i.StockQuantity,
		&i.CapitalAssetID,
		&i.Status,
		&i.SubmittedAt,
		&i.ApprovedAt,
		&i.ApprovedByUserID,
		&i.PaidAt,
		&i.CategoryNominalCode,
		&i.CategoryName,
		&i.CategoryIsMileage,
		&i.CategoryIsCapitalAsset,
		&i.Miles,
		&i.VehicleType,
		&i.EngineType,
		&i.EngineSize,
		&i.ReclaimMileage,
		&i.InitialRatePpm,
		&i.ReducedRatePpm,
		&i.RebillRatePpm,
		&i.ReimbursementMinor,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDueRecurrences = `-- name: ListDueRecurrences :many
SELECT id, expense_id, organisation_id, frequency, next_recurs_on, end_date, is_active, created_at, updated_at FROM expense_recurrence
WHERE next_recurs_on <= CURRENT_DATE   -- due today or overdue
  AND is_active      = TRUE
  AND (end_date IS NULL OR end_date >= CURRENT_DATE)
ORDER BY next_recurs_on ASC
`

// -----------------------------------------------------------------------------
// ListDueRecurrences
// Returns all active recurrences that are due today or overdue.
// This is the query your cron job / scheduler runs daily to generate new
// expense copies. It returns the recurrence rows; the service then fetches
// the template expense and creates a new copy for each one.
// -----------------------------------------------------------------------------
func (q *Queries) ListDueRecurrences(ctx context.Context) ([]ExpenseRecurrence, error) {
	rows, err := q.db.Query(ctx, listDueRecurrences)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExpenseRecurrence
	for rows.Next() {
		var i ExpenseRecurrence
		if err := rows.Scan(
			&i.ID,
			&i.ExpenseID,
			&i.OrganisationID,
			&i.Frequency,
			&i.NextRecursOn,
			&i.EndDate,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpenseAttachments = `-- name: ListExpenseAttachments :many
SELECT id, expense_id, organisation_id, file_name, content_type, file_size_bytes, storage_path, storage_bucket, description, is_primary, ocr_status, ocr_raw_text, ocr_extracted_data, ocr_processed_at, uploaded_by_user_id, created_at, updated_at FROM expense_attachments
WHERE expense_id = $1
ORDER BY is_primary DESC, created_at ASC
`

// -----------------------------------------------------------------------------
// ListExpenseAttachments
// All attachments for one expense, primary file first.
// The UI shows attachments in this order.
// -----------------------------------------------------------------------------
func (q *Queries) ListExpenseAttachments(ctx context.Context, expenseID uuid.UUID) ([]ExpenseAttachment, error) {
	rows, err := q.db.Query(ctx, listExpenseAttachments, expenseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExpenseAttachment
	for rows.Next() {
		var i ExpenseAttachment
		if err := rows.Scan(
			&i.ID,
			&i.ExpenseID,
			&i.OrganisationID,
			&i.FileName,
			&i.ContentType,
			&i.FileSizeBytes,
			&i.StoragePath,
			&i.StorageBucket,
			&i.Description,
			&i.IsPrimary,
			&i.OcrStatus,
			&i.OcrRawText,
			&i.OcrExtractedData,
			&i.OcrProcessedAt,
			&i.UploadedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpenseCategories = `-- name: ListExpenseCategories :many

SELECT id, organisation_id, nominal_code, name, description, category_group, is_mileage, is_capital_asset, is_stock_purchase, is_active, created_at, updated_at FROM expense_categories
WHERE organisation_id = $1
  AND is_active = TRUE
ORDER BY category_group, nominal_code
`

// =============================================================================
// SECTION 6: EXPENSE CATEGORIES (reference data)
// =============================================================================
// -----------------------------------------------------------------------------
// ListExpenseCategories
// All ACTIVE categories for an organisation, for the expense category picker.
// Scoped by organisation_id — categories are per-tenant reference data.
// Ordered by category_group then nominal_code so the UI can render stable
// sections (Admin expenses / Assets and stock / Cost of Sales).
// -----------------------------------------------------------------------------
func (q *Queries) ListExpenseCategories(ctx context.Context, organisationID uuid.UUID) ([]ExpenseCategory, error) {
	rows, err := q.db.Query(ctx, listExpenseCategories, organisationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExpenseCategory
	for rows.Next() {
		var i ExpenseCategory
		if err := rows.Scan(
			&i.ID,
			&i.OrganisationID,
			&i.NominalCode,
			&i.Name,
			&i.Description,
			&i.CategoryGroup,
			&i.IsMileage,
			&i.IsCapitalAsset,
			&i.IsStockPurchase,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpenses = `-- name: ListExpenses :many
SELECT id, organisation_id, user_id, created_by_user_id, category_id, dated_on, description, receipt_reference, currency, native_currency, exchange_rate, gross_value_minor, native_gross_value_minor, vat_rate_id, vat_rate_bps, vat_value_minor, native_vat_value_minor, manual_vat_amount_minor, vat_status, ec_status, project_id, rebill_type, rebill_factor, rebilled_invoice_id, stock_item_id, stock_item_description, stock_quantity, capital_asset_id, property_id, status, submitted_at, approved_at, approved_by_user_id, paid_at, rejection_note, ocr_confidence, ocr_processed_at, supplier_name, supplier_vat_number, invoice_number, deleted_at, created_at, updated_at FROM expenses
WHERE organisation_id = $1
  AND deleted_at IS NULL
ORDER BY dated_on DESC, created_at DESC
`

// -----------------------------------------------------------------------------
// ListExpenses
// Returns all active expenses for an organisation, newest first.
// This is the base query for the expenses list page with no filters.
// -----------------------------------------------------------------------------
func (q *Queries) ListExpenses(ctx context.Context, organisationID uuid.UUID) ([]Expense, error) {
	rows, err := q.db.Query(ctx, listExpenses, organisationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Expense
	for rows.Next() {
		var i Expense
		if err := rows.Scan(
			&i.ID,
			&i.OrganisationID,
			&i.UserID,
			&i.CreatedByUserID,
			&i.CategoryID,
			&i.DatedOn,
			&i.Description,
			&i.ReceiptReference,
			&i.Currency,
			&i.NativeCurrency,
			&i.ExchangeRate,
			&i.GrossValueMinor,
			&i.NativeGrossValueMinor,
			&i.VatRateID,
			&i.VatRateBps,
			&i.VatValueMinor,
			&i.NativeVatValueMinor,
			&i.ManualVatAmountMinor,
			&i.VatStatus,
			&i.EcStatus,
			&i.ProjectID,
			&i.RebillType,
			&i.RebillFactor,
			&i.RebilledInvoiceID,
			&i.StockItemID,
			&i.StockItemDescription,
			&i.StockQuantity,
			&i.CapitalAssetID,
			&i.PropertyID,
			&i.Status,
			&i.SubmittedAt,
			&i.ApprovedAt,
			&i.ApprovedByUserID,
			&i.PaidAt,
			&i.RejectionNote,
			&i.OcrConfidence,
			&i.OcrProcessedAt,
			&i.SupplierName,
			&i.SupplierVatNumber,
			&i.InvoiceNumber,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpensesByDateRange = `-- name: ListExpensesByDateRange :many
SELECT id, organisation_id, user_id, created_by_user_id, category_id, dated_on, description, receipt_reference, currency, native_currency, exchange_rate, gross_value_minor, native_gross_value_minor, vat_rate_id, vat_rate_bps, vat_value_minor, native_vat_value_minor, manual_vat_amount_minor, vat_status, ec_status, project_id, rebill_type, rebill_factor, rebilled_invoice_id, stock_item_id, stock_item_description, stock_quantity, capital_asset_id, property_id, status, submitted_at, approved_at, approved_by_user_id, paid_at, rejection_note, ocr_confidence, ocr_processed_at, supplier_name, supplier_vat_number, invoice_number, deleted_at, created_at, updated_at FROM expenses
WHERE organisation_id = $1
  AND dated_on BETWEEN $2 AND $3   -- $2 = from_date, $3 = to_date
  AND deleted_at IS NULL
ORDER BY dated_on DESC
`

type ListExpensesByDateRangeParams struct {
	OrganisationID uuid.UUID   `json:"organisation_id"`
	DatedOn        pgtype.Date `json:"dated_on"`
	DatedOn_2      pgtype.Date `json:"dated_on_2"`
}

// -----------------------------------------------------------------------------
// ListExpensesByDateRange
// Filter by date range — used on the expenses list page date picker.
// Both from_date and to_date are inclusive (BETWEEN is inclusive in PostgreSQL).
// -----------------------------------------------------------------------------
func (q *Queries) ListExpensesByDateRange(ctx context.Context, arg ListExpensesByDateRangeParams) ([]Expense, error) {
	rows, err := q.db.Query(ctx, listExpensesByDateRange, arg.OrganisationID, arg.DatedOn, arg.DatedOn_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Expense
	for rows.Next() {
		var i Expense
		if err := rows.Scan(
			&i.ID,
			&i.OrganisationID,
			&i.UserID,
			&i.CreatedByUserID,
			&i.CategoryID,
			&i.DatedOn,
			&i.Description,
			&i.ReceiptReference,
			&i.Currency,
			&i.NativeCurrency,
			&i.ExchangeRate,
			&i.GrossValueMinor,
			&i.NativeGrossValueMinor,
			&i.VatRateID,
			&i.VatRateBps,
			&i.VatValueMinor,
			&i.NativeVatValueMinor,
			&i.ManualVatAmountMinor,
			&i.VatStatus,
			&i.EcStatus,
			&i.ProjectID,
			&i.RebillType,
			&i.RebillFactor,
			&i.RebilledInvoiceID,
			&i.StockItemID,
			&i.StockItemDescription,
			&i.StockQuantity,
			&i.CapitalAssetID,
			&i.PropertyID,
			&i.Status,
			&i.SubmittedAt,
			&i.ApprovedAt,
			&i.ApprovedByUserID,
			&i.PaidAt,
			&i.RejectionNote,
			&i.OcrConfidence,
			&i.OcrProcessedAt,
			&i.SupplierName,
			&i.SupplierVatNumber,
			&i.InvoiceNumber,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpensesByProject = `-- name: ListExpensesByProject :many


SELECT id, organisation_id, user_id, created_by_user_id, category_id, dated_on, description, receipt_reference, currency, native_currency, exchange_rate, gross_value_minor, native_gross_value_minor, vat_rate_id, vat_rate_bps, vat_value_minor, native_vat_value_minor, manual_vat_amount_minor, vat_status, ec_status, project_id, rebill_type, rebill_factor, rebilled_invoice_id, stock_item_id, stock_item_description, stock_quantity, capital_asset_id, property_id, status, submitted_at, approved_at, approved_by_user_id, paid_at, rejection_note, ocr_confidence, ocr_processed_at, supplier_name, supplier_vat_number, invoice_number, deleted_at, created_at, updated_at FROM expenses
WHERE organisation_id = $1
  AND project_id      = $2
  AND deleted_at IS NULL
ORDER BY dated_on DESC
`

type ListExpensesByProjectParams struct {
	OrganisationID uuid.UUID   `json:"organisation_id"`
	ProjectID      pgtype.UUID `json:"project_id"`
}

// oldest first so managers action the earliest claims first
// -----------------------------------------------------------------------------
// ListExpensesByProject
// All expenses linked to a specific project (for rebilling to a client).
// -----------------------------------------------------------------------------
func (q *Queries) ListExpensesByProject(ctx context.Context, arg ListExpensesByProjectParams) ([]Expense, error) {
	rows, err := q.db.Query(ctx, listExpensesByProject, arg.OrganisationID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Expense
	for rows.Next() {
		var i Expense
		if err := rows.Scan(
			&i.ID,
			&i.OrganisationID,
			&i.UserID,
			&i.CreatedByUserID,
			&i.CategoryID,
			&i.DatedOn,
			&i.Description,
			&i.ReceiptReference,
			&i.Currency,
			&i.NativeCurrency,
			&i.ExchangeRate,
			&i.GrossValueMinor,
			&i.NativeGrossValueMinor,
			&i.VatRateID,
			&i.VatRateBps,
			&i.VatValueMinor,
			&i.NativeVatValueMinor,
			&i.ManualVatAmountMinor,
			&i.VatStatus,
			&i.EcStatus,
			&i.ProjectID,
			&i.RebillType,
			&i.RebillFactor,
			&i.RebilledInvoiceID,
			&i.StockItemID,
			&i.StockItemDescription,
			&i.StockQuantity,
			&i.CapitalAssetID,
			&i.PropertyID,
			&i.Status,
			&i.SubmittedAt,
			&i.ApprovedAt,
			&i.ApprovedByUserID,
			&i.PaidAt,
			&i.RejectionNote,
			&i.OcrConfidence,
			&i.OcrProcessedAt,
			&i.SupplierName,
			&i.SupplierVatNumber,
			&i.InvoiceNumber,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpensesByStatus = `-- name: ListExpensesByStatus :many
SELECT id, organisation_id, user_id, created_by_user_id, category_id, dated_on, description, receipt_reference, currency, native_currency, exchange_rate, gross_value_minor, native_gross_value_minor, vat_rate_id, vat_rate_bps, vat_value_minor, native_vat_value_minor, manual_vat_amount_minor, vat_status, ec_status, project_id, rebill_type, rebill_factor, rebilled_invoice_id, stock_item_id, stock_item_description, stock_quantity, capital_asset_id, property_id, status, submitted_at, approved_at, approved_by_user_id, paid_at, rejection_note, ocr_confidence, ocr_processed_at, supplier_name, supplier_vat_number, invoice_number, deleted_at, created_at, updated_at FROM expenses
WHERE organisation_id = $1
  AND status          = $2   -- 'DRAFT'|'SUBMITTED'|'APPROVED'|'REJECTED'|'PAID'
  AND deleted_at IS NULL
ORDER BY submitted_at ASC
`

type ListExpensesByStatusParams struct {
	OrganisationID uuid.UUID `json:"organisation_id"`
	Status         string    `json:"status"`
}

// -----------------------------------------------------------------------------
// ListExpensesByStatus
// Filter by workflow status — e.g. fetch all 'SUBMITTED' expenses for the
// manager approval queue.
// -----------------------------------------------------------------------------
func (q *Queries) ListExpensesByStatus(ctx context.Context, arg ListExpensesByStatusParams) ([]Expense, error) {
	rows, err := q.db.Query(ctx, listExpensesByStatus, arg.OrganisationID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Expense
	for rows.Next() {
		var i Expense
		if err := rows.Scan(
			&i.ID,
			&i.OrganisationID,
			&i.UserID,
			&i.CreatedByUserID,
			&i.CategoryID,
			&i.DatedOn,
			&i.Description,
			&i.ReceiptReference,
			&i.Currency,
			&i.NativeCurrency,
			&i.ExchangeRate,
			&i.GrossValueMinor,
			&i.NativeGrossValueMinor,
			&i.VatRateID,
			&i.VatRateBps,
			&i.VatValueMinor,
			&i.NativeVatValueMinor,
			&i.ManualVatAmountMinor,
			&i.VatStatus,
			&i.EcStatus,
			&i.ProjectID,
			&i.RebillType,
			&i.RebillFactor,
			&i.RebilledInvoiceID,
			&i.StockItemID,
			&i.StockItemDescription,
			&i.StockQuantity,
			&i.CapitalAssetID,
			&i.PropertyID,
			&i.Status,
			&i.SubmittedAt,
			&i.ApprovedAt,
			&i.ApprovedByUserID,
			&i.PaidAt,
			&i.RejectionNote,
			&i.OcrConfidence,
			&i.OcrProcessedAt,
			&i.SupplierName,
			&i.SupplierVatNumber,
			&i.InvoiceNumber,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpensesByUser = `-- name: ListExpensesByUser :many
SELECT id, organisation_id, user_id, created_by_user_id, category_id, dated_on, description, receipt_reference, currency, native_currency, exchange_rate, gross_value_minor, native_gross_value_minor, vat_rate_id, vat_rate_bps, vat_value_minor, native_vat_value_minor, manual_vat_amount_minor, vat_status, ec_status, project_id, rebill_type, rebill_factor, rebilled_invoice_id, stock_item_id, stock_item_description, stock_quantity, capital_asset_id, property_id, status, submitted_at, approved_at, approved_by_user_id, paid_at, rejection_note, ocr_confidence, ocr_processed_at, supplier_name, supplier_vat_number, invoice_number, deleted_at, created_at, updated_at FROM expenses
WHERE organisation_id = $1
  AND user_id         = $2
  AND deleted_at IS NULL
ORDER BY dated_on DESC, created_at DESC
`

type ListExpensesByUserParams struct {
	OrganisationID uuid.UUID `json:"organisation_id"`
	UserID         uuid.UUID `json:"user_id"`
}

// -----------------------------------------------------------------------------
// ListExpensesByUser
// Expenses for a specific claimant (the "my expenses" view).
// Useful for employee self-service: they only see their own claims.
// -----------------------------------------------------------------------------
func (q *Queries) ListExpensesByUser(ctx context.Context, arg ListExpensesByUserParams) ([]Expense, error) {
	rows, err := q.db.Query(ctx, listExpensesByUser, arg.OrganisationID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Expense
	for rows.Next() {
		var i Expense
		if err := rows.Scan(
			&i.ID,
			&i.OrganisationID,
			&i.UserID,
			&i.CreatedByUserID,
			&i.CategoryID,
			&i.DatedOn,
			&i.Description,
			&i.ReceiptReference,
			&i.Currency,
			&i.NativeCurrency,
			&i.ExchangeRate,
			&i.GrossValueMinor,
			&i.NativeGrossValueMinor,
			&i.VatRateID,
			&i.VatRateBps,
			&i.VatValueMinor,
			&i.NativeVatValueMinor,
			&i.ManualVatAmountMinor,
			&i.VatStatus,
			&i.EcStatus,
			&i.ProjectID,
			&i.RebillType,
			&i.RebillFactor,
			&i.RebilledInvoiceID,
			&i.StockItemID,
			&i.StockItemDescription,
			&i.StockQuantity,
			&i.CapitalAssetID,
			&i.PropertyID,
			&i.Status,
			&i.SubmittedAt,
			&i.ApprovedAt,
			&i.ApprovedByUserID,
			&i.PaidAt,
			&i.RejectionNote,
			&i.OcrConfidence,
			&i.OcrProcessedAt,
			&i.SupplierName,
			&i.SupplierVatNumber,
			&i.InvoiceNumber,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpensesUpdatedSince = `-- name: ListExpensesUpdatedSince :many
SELECT id, organisation_id, user_id, created_by_user_id, category_id, dated_on, description, receipt_reference, currency, native_currency, exchange_rate, gross_value_minor, native_gross_value_minor, vat_rate_id, vat_rate_bps, vat_value_minor, native_vat_value_minor, manual_vat_amount_minor, vat_status, ec_status, project_id, rebill_type, rebill_factor, rebilled_invoice_id, stock_item_id, stock_item_description, stock_quantity, capital_asset_id, property_id, status, submitted_at, approved_at, approved_by_user_id, paid_at, rejection_note, ocr_confidence, ocr_processed_at, supplier_name, supplier_vat_number, invoice_number, deleted_at, created_at, updated_at FROM expenses
WHERE organisation_id = $1
  AND updated_at      > $2   -- strict greater-than (caller passes their last-sync timestamp)
ORDER BY updated_at ASC
`

type ListExpensesUpdatedSinceParams struct {
	OrganisationID uuid.UUID          `json:"organisation_id"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

// -----------------------------------------------------------------------------
// ListExpensesUpdatedSince
// Returns all expenses modified after a given timestamp.
// Used for sync / webhook scenarios: "give me everything changed since X".
// Note: we do NOT filter deleted_at here — we want to surface soft-deleted
// records so the consumer can remove them from their local cache too.
// -----------------------------------------------------------------------------
func (q *Queries) ListExpensesUpdatedSince(ctx context.Context, arg ListExpensesUpdatedSinceParams) ([]Expense, error) {
	rows, err := q.db.Query(ctx, listExpensesUpdatedSince, arg.OrganisationID, arg.UpdatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Expense
	for rows.Next() {
		var i Expense
		if err := rows.Scan(
			&i.ID,
			&i.OrganisationID,
			&i.UserID,
			&i.CreatedByUserID,
			&i.CategoryID,
			&i.DatedOn,
			&i.Description,
			&i.ReceiptReference,
			&i.Currency,
			&i.NativeCurrency,
			&i.ExchangeRate,
			&i.GrossValueMinor,
			&i.NativeGrossValueMinor,
			&i.VatRateID,
			&i.VatRateBps,
			&i.VatValueMinor,
			&i.NativeVatValueMinor,
			&i.ManualVatAmountMinor,
			&i.VatStatus,
			&i.EcStatus,
			&i.ProjectID,
			&i.RebillType,
			&i.RebillFactor,
			&i.RebilledInvoiceID,
			&i.StockItemID,
			&i.StockItemDescription,
			&i.StockQuantity,
			&i.CapitalAssetID,
			&i.PropertyID,
			&i.Status,
			&i.SubmittedAt,
			&i.ApprovedAt,
			&i.ApprovedByUserID,
			&i.PaidAt,
			&i.RejectionNote,
			&i.OcrConfidence,
			&i.OcrProcessedAt,
			&i.SupplierName,
			&i.SupplierVatNumber,
			&i.InvoiceNumber,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentExpenses = `-- name: ListRecentExpenses :many
SELECT id, organisation_id, user_id, created_by_user_id, category_id, dated_on, description, receipt_reference, currency, native_currency, exchange_rate, gross_value_minor, native_gross_value_minor, vat_rate_id, vat_rate_bps, vat_value_minor, native_vat_value_minor, manual_vat_amount_minor, vat_status, ec_status, project_id, rebill_type, rebill_factor, rebilled_invoice_id, stock_item_id, stock_item_description, stock_quantity, capital_asset_id, property_id, status, submitted_at, approved_at, approved_by_user_id, paid_at, rejection_note, ocr_confidence, ocr_processed_at, supplier_name, supplier_vat_number, invoice_number, deleted_at, created_at, updated_at FROM expenses
WHERE organisation_id = $1
  AND dated_on        >= CURRENT_DATE - INTERVAL '30 days'
  AND deleted_at IS NULL
ORDER BY dated_on DESC, created_at DESC
`

// -----------------------------------------------------------------------------
// ListRecentExpenses
// Last 30 days of expenses — useful for the dashboard "recent activity" widget.
// -----------------------------------------------------------------------------
func (q *Queries) ListRecentExpenses(ctx context.Context, organisationID uuid.UUID) ([]Expense, error) {
	rows, err := q.db.Query(ctx, listRecentExpenses, organisationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Expense
	for rows.Next() {
		var i Expense
		if err := rows.Scan(
			&i.ID,
			&i.OrganisationID,
			&i.UserID,
			&i.CreatedByUserID,
			&i.CategoryID,
			&i.DatedOn,
			&i.Description,
			&i.ReceiptReference,
			&i.Currency,
			&i.NativeCurrency,
			&i.ExchangeRate,
			&i.GrossValueMinor,
			&i.NativeGrossValueMinor,
			&i.VatRateID,
			&i.VatRateBps,
			&i.VatValueMinor,
			&i.NativeVatValueMinor,
			&i.ManualVatAmountMinor,
			&i.VatStatus,
			&i.EcStatus,
			&i.ProjectID,
			&i.RebillType,
			&i.RebillFactor,
			&i.RebilledInvoiceID,
			&i.StockItemID,
			&i.StockItemDescription,
			&i.StockQuantity,
			&i.CapitalAssetID,
			&i.PropertyID,
			&i.Status,
			&i.SubmittedAt,
			&i.ApprovedAt,
			&i.ApprovedByUserID,
			&i.PaidAt,
			&i.RejectionNote,
			&i.OcrConfidence,
			&i.OcrProcessedAt,
			&i.SupplierName,
			&i.SupplierVatNumber,
			&i.InvoiceNumber,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVatRatesByCountry = `-- name: ListVatRatesByCountry :many

SELECT id, name, rate_bps, country_code, is_fixed_ratio, effective_from, effective_to, created_at
FROM vat_rates
WHERE country_code = $1
  AND effective_from <= CURRENT_DATE                        -- not yet in effect → excluded
  AND (effective_to IS NULL OR effective_to >= CURRENT_DATE) -- expired → excluded; NULL = still active
ORDER BY name
`

type ListVatRatesByCountryRow struct {
	ID            uuid.UUID          `json:"id"`
	Name          string             `json:"name"`
	RateBps       int32              `json:"rate_bps"`
	CountryCode   string             `json:"country_code"`
	IsFixedRatio  bool               `json:"is_fixed_ratio"`
	EffectiveFrom pgtype.Date        `json:"effective_from"`
	EffectiveTo   pgtype.Date        `json:"effective_to"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

// =============================================================================
// SECTION 7: VAT RATES (reference data)
// =============================================================================
// -----------------------------------------------------------------------------
// ListVatRatesByCountry
// All VAT rates that are valid TODAY for a given country, for the VAT rate
// picker. VAT rates are global reference data keyed by country_code (not per
// organisation) — the caller passes the organisation's country.
//
// "Valid today" means the rate is in its effective window:
//   - effective_from is on or before today (not a future rate), AND
//   - effective_to is NULL (still active) or on/after today (not yet expired).
//
// This is why the COVID 5% hospitality rate, for example, stops appearing once
// its effective_to date has passed.
//
// Explicit column list (not SELECT *) per project convention. Uses
// idx_vat_rates_country for the country_code lookup.
// -----------------------------------------------------------------------------
func (q *Queries) ListVatRatesByCountry(ctx context.Context, countryCode string) ([]ListVatRatesByCountryRow, error) {
	rows, err := q.db.Query(ctx, listVatRatesByCountry, countryCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVatRatesByCountryRow
	for rows.Next() {
		var i ListVatRatesByCountryRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.RateBps,
			&i.CountryCode,
			&i.IsFixedRatio,
			&i.EffectiveFrom,
			&i.EffectiveTo,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteExpense = `-- name: SoftDeleteExpense :exec
UPDATE expenses SET
    deleted_at = now(),
    updated_at = now()
WHERE id              = $1
  AND organisation_id = $2
  AND deleted_at IS NULL
`

type SoftDeleteExpenseParams struct {
	ID             uuid.UUID `json:"id"`
	OrganisationID uuid.UUID `json:"organisation_id"`
}

// -----------------------------------------------------------------------------
// SoftDeleteExpense
// Sets deleted_at to mark the record as deleted. The row remains in the DB
// for audit purposes but is invisible to all other queries.
// Accounting records should never be hard-deleted once submitted.
// :exec means the generated Go function returns only an error (no row back).
// -----------------------------------------------------------------------------
func (q *Queries) SoftDeleteExpense(ctx context.Context, arg SoftDeleteExpenseParams) error {
	_, err := q.db.Exec(ctx, softDeleteExpense, arg.ID, arg.OrganisationID)
	return err
}

const sumExpensesByCategory = `-- name: SumExpensesByCategory :many

SELECT
    ec.id               AS category_id,
    ec.nominal_code,
    ec.name             AS category_name,
    COUNT(e.id)         AS expense_count,
    -- SUM returns BIGINT when summing INTEGER columns — good, avoids overflow
    -- for organisations with many expenses. COALESCE handles the case where
    -- there are no matching rows (SUM of empty set = NULL, not 0).
    COALESCE(SUM(e.native_gross_value_minor), 0)  AS total_gross_minor,
    COALESCE(SUM(e.native_vat_value_minor), 0)    AS total_vat_minor
FROM expenses e
JOIN expense_categories ec ON ec.id = e.category_id
WHERE e.organisation_id = $1
  AND e.dated_on BETWEEN $2 AND $3
  AND e.deleted_at IS NULL
  AND e.status IN ('APPROVED', 'PAID')   -- only count approved/paid expenses in reports
GROUP BY ec.id, ec.nominal_code, ec.name
ORDER BY ec.nominal_code
`

type SumExpensesByCategoryParams struct {
	OrganisationID uuid.UUID   `json:"organisation_id"`
	DatedOn        pgtype.Date `json:"dated_on"`
	DatedOn_2      pgtype.Date `json:"dated_on_2"`
}

type SumExpensesByCategoryRow struct {
	CategoryID      uuid.UUID   `json:"category_id"`
	NominalCode     string      `json:"nominal_code"`
	CategoryName    string      `json:"category_name"`
	ExpenseCount    int64       `json:"expense_count"`
	TotalGrossMinor interface{} `json:"total_gross_minor"`
	TotalVatMinor   interface{} `json:"total_vat_minor"`
}

// =============================================================================
// SECTION 5: REPORTING / AGGREGATION QUERIES
// =============================================================================
// -----------------------------------------------------------------------------
// SumExpensesByCategory
// Totals per category for a date range — used on the P&L and expense reports.
// Returns category name, nominal code, and total gross + VAT in home currency.
// These are INTEGER sums (pence); the service layer formats them for display.
// -----------------------------------------------------------------------------
func (q *Queries) SumExpensesByCategory(ctx context.Context, arg SumExpensesByCategoryParams) ([]SumExpensesByCategoryRow, error) {
	rows, err := q.db.Query(ctx, sumExpensesByCategory, arg.OrganisationID, arg.DatedOn, arg.DatedOn_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SumExpensesByCategoryRow
	for rows.Next() {
		var i SumExpensesByCategoryRow
		if err := rows.Scan(
			&i.CategoryID,
			&i.NominalCode,
			&i.CategoryName,
			&i.ExpenseCount,
			&i.TotalGrossMinor,
			&i.TotalVatMinor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumExpensesByMonth = `-- name: SumExpensesByMonth :many
SELECT
    DATE_TRUNC('month', dated_on)::DATE              AS month,
    COALESCE(SUM(native_gross_value_minor), 0)       AS total_gross_minor,
    COALESCE(SUM(native_vat_value_minor), 0)         AS total_vat_minor,
    COUNT(id)                                        AS expense_count
FROM expenses
WHERE organisation_id = $1
  AND dated_on        >= DATE_TRUNC('year', $2::DATE)    -- start of year
  AND dated_on        <  DATE_TRUNC('year', $2::DATE) + INTERVAL '1 year'
  AND deleted_at IS NULL
  AND status IN ('APPROVED', 'PAID')
GROUP BY DATE_TRUNC('month', dated_on)
ORDER BY month ASC
`

type SumExpensesByMonthParams struct {
	OrganisationID uuid.UUID   `json:"organisation_id"`
	Column2        pgtype.Date `json:"column_2"`
}

type SumExpensesByMonthRow struct {
	Month           pgtype.Date `json:"month"`
	TotalGrossMinor interface{} `json:"total_gross_minor"`
	TotalVatMinor   interface{} `json:"total_vat_minor"`
	ExpenseCount    int64       `json:"expense_count"`
}

// -----------------------------------------------------------------------------
// SumExpensesByMonth
// Month-by-month totals for a calendar year — used for trend charts.
// DATE_TRUNC rounds each dated_on down to the first of its month, letting
// GROUP BY aggregate by month cleanly.
// -----------------------------------------------------------------------------
func (q *Queries) SumExpensesByMonth(ctx context.Context, arg SumExpensesByMonthParams) ([]SumExpensesByMonthRow, error) {
	rows, err := q.db.Query(ctx, sumExpensesByMonth, arg.OrganisationID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SumExpensesByMonthRow
	for rows.Next() {
		var i SumExpensesByMonthRow
		if err := rows.Scan(
			&i.Month,
			&i.TotalGrossMinor,
			&i.TotalVatMinor,
			&i.ExpenseCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAttachmentOCRStatus = `-- name: UpdateAttachmentOCRStatus :one
UPDATE expense_attachments SET
    ocr_status         = $2,   -- 'PROCESSING'|'COMPLETE'|'FAILED'
    ocr_raw_text       = $3,   -- full text from OCR engine (nullable)
    ocr_extracted_data = $4,   -- JSONB structured fields (nullable)
    ocr_processed_at   = now(),
    updated_at         = now()
WHERE id = $1
RETURNING id, expense_id, organisation_id, file_name, content_type, file_size_bytes, storage_path, storage_bucket, description, is_primary, ocr_status, ocr_raw_text, ocr_extracted_data, ocr_processed_at, uploaded_by_user_id, created_at, updated_at
`

type UpdateAttachmentOCRStatusParams struct {
	ID               uuid.UUID   `json:"id"`
	OcrStatus        string      `json:"ocr_status"`
	OcrRawText       pgtype.Text `json:"ocr_raw_text"`
	OcrExtractedData []byte      `json:"ocr_extracted_data"`
}

// -----------------------------------------------------------------------------
// UpdateAttachmentOCRStatus
// Called by the background OCR processing pipeline to record results.
// ocr_extracted_data is JSONB — in Go this will be a []byte that your service
// deserialises into a struct (e.g. ExtractedExpenseData).
// -----------------------------------------------------------------------------
func (q *Queries) UpdateAttachmentOCRStatus(ctx context.Context, arg UpdateAttachmentOCRStatusParams) (ExpenseAttachment, error) {
	row := q.db.QueryRow(ctx, updateAttachmentOCRStatus,
		arg.ID,
		arg.OcrStatus,
		arg.OcrRawText,
		arg.OcrExtractedData,
	)
	var i ExpenseAttachment
	err := row.Scan(
		&i.ID,
		&i.ExpenseID,
		&i.OrganisationID,
		&i.FileName,
		&i.ContentType,
		&i.FileSizeBytes,
		&i.StoragePath,
		&i.StorageBucket,
		&i.Description,
		&i.IsPrimary,
		&i.OcrStatus,
		&i.OcrRawText,
		&i.OcrExtractedData,
		&i.OcrProcessedAt,
		&i.UploadedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateExpense = `-- name: UpdateExpense :one
UPDATE expenses SET
    category_id              = $3,
    dated_on                 = $4,
    description              = $5,
    receipt_reference        = $6,
    invoice_number           = $7,
    supplier_name            = $8,
    supplier_vat_number      = $9,
    currency                 = $10,
    native_currency          = $11,
    exchange_rate            = $12,
    gross_value_minor        = $13,
    native_gross_value_minor = $14,
    vat_rate_id              = $15,
    vat_rate_bps             = $16,
    vat_value_minor          = $17,
    native_vat_value_minor   = $18,
    manual_vat_amount_minor  = $19,
    vat_status               = $20,
    ec_status                = $21,
    project_id               = $22,
    rebill_type              = $23,
    rebill_factor            = $24,
    stock_item_id            = $25,
    stock_item_description   = $26,
    stock_quantity           = $27,
    property_id              = $28,
    updated_at               = now()
WHERE id              = $1   -- expense UUID
  AND organisation_id = $2   -- tenant scope
  AND deleted_at IS NULL     -- can't update a deleted record
RETURNING id, organisation_id, user_id, created_by_user_id, category_id, dated_on, description, receipt_reference, currency, native_currency, exchange_rate, gross_value_minor, native_gross_value_minor, vat_rate_id, vat_rate_bps, vat_value_minor, native_vat_value_minor, manual_vat_amount_minor, vat_status, ec_status, project_id, rebill_type, rebill_factor, rebilled_invoice_id, stock_item_id, stock_item_description, stock_quantity, capital_asset_id, property_id, status, submitted_at, approved_at, approved_by_user_id, paid_at, rejection_note, ocr_confidence, ocr_processed_at, supplier_name, supplier_vat_number, invoice_number, deleted_at, created_at, updated_at
`

type UpdateExpenseParams struct {
	ID                    uuid.UUID      `json:"id"`
	OrganisationID        uuid.UUID      `json:"organisation_id"`
	CategoryID            uuid.UUID      `json:"category_id"`
	DatedOn               pgtype.Date    `json:"dated_on"`
	Description           string         `json:"description"`
	ReceiptReference      pgtype.Text    `json:"receipt_reference"`
	InvoiceNumber         pgtype.Text    `json:"invoice_number"`
	SupplierName          pgtype.Text    `json:"supplier_name"`
	SupplierVatNumber     pgtype.Text    `json:"supplier_vat_number"`
	Currency              string         `json:"currency"`
	NativeCurrency        string         `json:"native_currency"`
	ExchangeRate          pgtype.Numeric `json:"exchange_rate"`
	GrossValueMinor       int32          `json:"gross_value_minor"`
	NativeGrossValueMinor int32          `json:"native_gross_value_minor"`
	VatRateID             pgtype.UUID    `json:"vat_rate_id"`
	VatRateBps            pgtype.Int4    `json:"vat_rate_bps"`
	VatValueMinor         int32          `json:"vat_value_minor"`
	NativeVatValueMinor   int32          `json:"native_vat_value_minor"`
	ManualVatAmountMinor  pgtype.Int4    `json:"manual_vat_amount_minor"`
	VatStatus             string         `json:"vat_status"`
	EcStatus              string         `json:"ec_status"`
	ProjectID             pgtype.UUID    `json:"project_id"`
	RebillType            pgtype.Text    `json:"rebill_type"`
	RebillFactor          pgtype.Numeric `json:"rebill_factor"`
	StockItemID           pgtype.UUID    `json:"stock_item_id"`
	StockItemDescription  pgtype.Text    `json:"stock_item_description"`
	StockQuantity         pgtype.Numeric `json:"stock_quantity"`
	PropertyID            pgtype.UUID    `json:"property_id"`
}

// -----------------------------------------------------------------------------
// UpdateExpense
// Updates the editable fields on an expense. Only allowed when status is
// DRAFT or REJECTED (the application layer enforces this, not the DB).
// We update updated_at explicitly here even though the trigger also does it —
// belt-and-suspenders approach.
// RETURNING * gives us the updated row back so the API can return it.
// -----------------------------------------------------------------------------
func (q *Queries) UpdateExpense(ctx context.Context, arg UpdateExpenseParams) (Expense, error) {
	row := q.db.QueryRow(ctx, updateExpense,
		arg.ID,
		arg.OrganisationID,
		arg.CategoryID,
		arg.DatedOn,
		arg.Description,
		arg.ReceiptReference,
		arg.InvoiceNumber,
		arg.SupplierName,
		arg.SupplierVatNumber,
		arg.Currency,
		arg.NativeCurrency,
		arg.ExchangeRate,
		arg.GrossValueMinor,
		arg.NativeGrossValueMinor,
		arg.VatRateID,
		arg.VatRateBps,
		arg.VatValueMinor,
		arg.NativeVatValueMinor,
		arg.ManualVatAmountMinor,
		arg.VatStatus,
		arg.EcStatus,
		arg.ProjectID,
		arg.RebillType,
		arg.RebillFactor,
		arg.StockItemID,
		arg.StockItemDescription,
		arg.StockQuantity,
		arg.PropertyID,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.UserID,
		&i.CreatedByUserID,
		&i.CategoryID,
		&i.DatedOn,
		&i.Description,
		&i.ReceiptReference,
		&i.Currency,
		&i.NativeCurrency,
		&i.ExchangeRate,
		&i.GrossValueMinor,
		&i.NativeGrossValueMinor,
		&i.VatRateID,
		&i.VatRateBps,
		&i.VatValueMinor,
		&i.NativeVatValueMinor,
		&i.ManualVatAmountMinor,
		&i.VatStatus,
		&i.EcStatus,
		&i.ProjectID,
		&i.RebillType,
		&i.RebillFactor,
		&i.RebilledInvoiceID,
		&i.StockItemID,
		&i.StockItemDescription,
		&i.StockQuantity,
		&i.CapitalAssetID,
		&i.PropertyID,
		&i.Status,
		&i.SubmittedAt,
		&i.ApprovedAt,
		&i.ApprovedByUserID,
		&i.PaidAt,
		&i.RejectionNote,
		&i.OcrConfidence,
		&i.OcrProcessedAt,
		&i.SupplierName,
		&i.SupplierVatNumber,
		&i.InvoiceNumber,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateExpenseMileage = `-- name: UpdateExpenseMileage :one
UPDATE expense_mileage SET
    miles                = $2,
    journey_description  = $3,
    journey_from         = $4,
    journey_to           = $5,
    vehicle_type         = $6,
    engine_type          = $7,
    engine_size          = $8,
    reclaim_mileage      = $9,
    initial_rate_ppm     = $10,
    reduced_rate_ppm     = $11,
    rebill_rate_ppm      = $12,
    reimbursement_minor  = $13,
    have_vat_receipt     = $14,
    updated_at           = now()
WHERE expense_id = $1
RETURNING id, expense_id, miles, journey_description, journey_from, journey_to, vehicle_type, engine_type, engine_size, reclaim_mileage, initial_rate_ppm, reduced_rate_ppm, rebill_rate_ppm, reimbursement_minor, have_vat_receipt, created_at, updated_at
`

type UpdateExpenseMileageParams struct {
	ExpenseID          uuid.UUID   `json:"expense_id"`
	Miles              string      `json:"miles"`
	JourneyDescription pgtype.Text `json:"journey_description"`
	JourneyFrom        pgtype.Text `json:"journey_from"`
	JourneyTo          pgtype.Text `json:"journey_to"`
	VehicleType        string      `json:"vehicle_type"`
	EngineType         pgtype.Text `json:"engine_type"`
	EngineSize         pgtype.Text `json:"engine_size"`
	ReclaimMileage     bool        `json:"reclaim_mileage"`
	InitialRatePpm     pgtype.Int4 `json:"initial_rate_ppm"`
	ReducedRatePpm     pgtype.Int4 `json:"reduced_rate_ppm"`
	RebillRatePpm      pgtype.Int4 `json:"rebill_rate_ppm"`
	ReimbursementMinor pgtype.Int4 `json:"reimbursement_minor"`
	HaveVatReceipt     bool        `json:"have_vat_receipt"`
}

// -----------------------------------------------------------------------------
// UpdateExpenseMileage
// Update mileage fields — only valid while parent expense is DRAFT/REJECTED.
// -----------------------------------------------------------------------------
func (q *Queries) UpdateExpenseMileage(ctx context.Context, arg UpdateExpenseMileageParams) (ExpenseMileage, error) {
	row := q.db.QueryRow(ctx, updateExpenseMileage,
		arg.ExpenseID,
		arg.Miles,
		arg.JourneyDescription,
		arg.JourneyFrom,
		arg.JourneyTo,
		arg.VehicleType,
		arg.EngineType,
		arg.EngineSize,
		arg.ReclaimMileage,
		arg.InitialRatePpm,
		arg.ReducedRatePpm,
		arg.RebillRatePpm,
		arg.ReimbursementMinor,
		arg.HaveVatReceipt,
	)
	var i ExpenseMileage
	err := row.Scan(
		&i.ID,
		&i.ExpenseID,
		&i.Miles,
		&i.JourneyDescription,
		&i.JourneyFrom,
		&i.JourneyTo,
		&i.VehicleType,
		&i.EngineType,
		&i.EngineSize,
		&i.ReclaimMileage,
		&i.InitialRatePpm,
		&i.ReducedRatePpm,
		&i.RebillRatePpm,
		&i.ReimbursementMinor,
		&i.HaveVatReceipt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateExpenseStatus = `-- name: UpdateExpenseStatus :one
UPDATE expenses SET
    status               = $3,
    -- Set the relevant timestamp based on the new status
    -- We set all three here; the application passes NULL for the ones not relevant
    submitted_at         = $4,   -- set when status becomes SUBMITTED
    approved_at          = $5,   -- set when status becomes APPROVED
    approved_by_user_id  = $6,   -- set when status becomes APPROVED
    paid_at              = $7,   -- set when status becomes PAID
    rejection_note       = $8,   -- set when status becomes REJECTED
    updated_at           = now()
WHERE id              = $1
  AND organisation_id = $2
  AND deleted_at IS NULL
RETURNING id, organisation_id, user_id, created_by_user_id, category_id, dated_on, description, receipt_reference, currency, native_currency, exchange_rate, gross_value_minor, native_gross_value_minor, vat_rate_id, vat_rate_bps, vat_value_minor, native_vat_value_minor, manual_vat_amount_minor, vat_status, ec_status, project_id, rebill_type, rebill_factor, rebilled_invoice_id, stock_item_id, stock_item_description, stock_quantity, capital_asset_id, property_id, status, submitted_at, approved_at, approved_by_user_id, paid_at, rejection_note, ocr_confidence, ocr_processed_at, supplier_name, supplier_vat_number, invoice_number, deleted_at, created_at, updated_at
`

type UpdateExpenseStatusParams struct {
	ID               uuid.UUID          `json:"id"`
	OrganisationID   uuid.UUID          `json:"organisation_id"`
	Status           string             `json:"status"`
	SubmittedAt      pgtype.Timestamptz `json:"submitted_at"`
	ApprovedAt       pgtype.Timestamptz `json:"approved_at"`
	ApprovedByUserID pgtype.UUID        `json:"approved_by_user_id"`
	PaidAt           pgtype.Timestamptz `json:"paid_at"`
	RejectionNote    pgtype.Text        `json:"rejection_note"`
}

// -----------------------------------------------------------------------------
// UpdateExpenseStatus
// Dedicated query for status transitions only.
// Separating this from UpdateExpense prevents accidental overwrite of all
// fields during a status change (e.g. manager approving shouldn't change amounts).
// The application layer validates the transition is legal before calling this.
// -----------------------------------------------------------------------------
func (q *Queries) UpdateExpenseStatus(ctx context.Context, arg UpdateExpenseStatusParams) (Expense, error) {
	row := q.db.QueryRow(ctx, updateExpenseStatus,
		arg.ID,
		arg.OrganisationID,
		arg.Status,
		arg.SubmittedAt,
		arg.ApprovedAt,
		arg.ApprovedByUserID,
		arg.PaidAt,
		arg.RejectionNote,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.UserID,
		&i.CreatedByUserID,
		&i.CategoryID,
		&i.DatedOn,
		&i.Description,
		&i.ReceiptReference,
		&i.Currency,
		&i.NativeCurrency,
		&i.ExchangeRate,
		&i.GrossValueMinor,
		&i.NativeGrossValueMinor,
		&i.VatRateID,
		&i.VatRateBps,
		&i.VatValueMinor,
		&i.NativeVatValueMinor,
		&i.ManualVatAmountMinor,
		&i.VatStatus,
		&i.EcStatus,
		&i.ProjectID,
		&i.RebillType,
		&i.RebillFactor,
		&i.RebilledInvoiceID,
		&i.StockItemID,
		&i.StockItemDescription,
		&i.StockQuantity,
		&i.CapitalAssetID,
		&i.PropertyID,
		&i.Status,
		&i.SubmittedAt,
		&i.ApprovedAt,
		&i.ApprovedByUserID,
		&i.PaidAt,
		&i.RejectionNote,
		&i.OcrConfidence,
		&i.OcrProcessedAt,
		&i.SupplierName,
		&i.SupplierVatNumber,
		&i.InvoiceNumber,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRecurrenceNextDate = `-- name: UpdateRecurrenceNextDate :one
UPDATE expense_recurrence SET
    next_recurs_on = $2,
    updated_at     = now()
WHERE expense_id = $1
RETURNING id, expense_id, organisation_id, frequency, next_recurs_on, end_date, is_active, created_at, updated_at
`

type UpdateRecurrenceNextDateParams struct {
	ExpenseID    uuid.UUID   `json:"expense_id"`
	NextRecursOn pgtype.Date `json:"next_recurs_on"`
}

// -----------------------------------------------------------------------------
// UpdateRecurrenceNextDate
// After a recurrence fires and a new expense is created, advance the
// next_recurs_on date. The service layer calculates the next date based on
// frequency (e.g. add 1 month) and passes it here.
// -----------------------------------------------------------------------------
func (q *Queries) UpdateRecurrenceNextDate(ctx context.Context, arg UpdateRecurrenceNextDateParams) (ExpenseRecurrence, error) {
	row := q.db.QueryRow(ctx, updateRecurrenceNextDate, arg.ExpenseID, arg.NextRecursOn)
	var i ExpenseRecurrence
	err := row.Scan(
		&i.ID,
		&i.ExpenseID,
		&i.OrganisationID,
		&i.Frequency,
		&i.NextRecursOn,
		&i.EndDate,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
