// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package auth

import (
	"database/sql/driver"
	"fmt"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type OrganisationRole string

const (
	OrganisationRoleOwner      OrganisationRole = "owner"
	OrganisationRoleAdmin      OrganisationRole = "admin"
	OrganisationRoleMember     OrganisationRole = "member"
	OrganisationRoleAccountant OrganisationRole = "accountant"
	OrganisationRoleReadOnly   OrganisationRole = "read_only"
)

func (e *OrganisationRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrganisationRole(s)
	case string:
		*e = OrganisationRole(s)
	default:
		return fmt.Errorf("unsupported scan type for OrganisationRole: %T", src)
	}
	return nil
}

type NullOrganisationRole struct {
	OrganisationRole OrganisationRole `json:"organisation_role"`
	Valid            bool             `json:"valid"` // Valid is true if OrganisationRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrganisationRole) Scan(value interface{}) error {
	if value == nil {
		ns.OrganisationRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrganisationRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrganisationRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrganisationRole), nil
}

// Per-(organisation,user) payroll employee information (FreeAgent-style). Owner/admin only; one row per membership; optional (absent = defaults). Money in pence.
type EmployeePayroll struct {
	OrganisationID      uuid.UUID   `json:"organisation_id"`
	UserID              uuid.UUID   `json:"user_id"`
	IsExistingEmployee  bool        `json:"is_existing_employee"`
	StartDate           pgtype.Date `json:"start_date"`
	StartingDeclaration pgtype.Text `json:"starting_declaration"`
	NicCalculation      string      `json:"nic_calculation"`
	NormalWorkingHours  pgtype.Text `json:"normal_working_hours"`
	PaidHourly          bool        `json:"paid_hourly"`
	PaidIrregularly     bool        `json:"paid_irregularly"`
	PayrollID           pgtype.Text `json:"payroll_id"`
	TaxCode             pgtype.Text `json:"tax_code"`
	Week1Month1Basis    bool        `json:"week1_month1_basis"`
	// HMRC National Insurance category letter (NIC table letter).
	NiCategoryLetter         string `json:"ni_category_letter"`
	StudentLoanUndergraduate bool   `json:"student_loan_undergraduate"`
	StudentLoanPostgraduate  bool   `json:"student_loan_postgraduate"`
	// Monthly basic pay in pence (minor units). Never float.
	BasicPayMinor             int64 `json:"basic_pay_minor"`
	AllowanceMinor            int64 `json:"allowance_minor"`
	OtherPaymentsMinor        int64 `json:"other_payments_minor"`
	PayNotSubjectToTaxNiMinor int64 `json:"pay_not_subject_to_tax_ni_minor"`
	// Top-level flag; statutory amount detail is deferred (UI disables the Yes path).
	ReceivingStatutoryPay          bool  `json:"receiving_statutory_pay"`
	PayrollGivingMinor             int64 `json:"payroll_giving_minor"`
	OtherDeductionsNetPayMinor     int64 `json:"other_deductions_net_pay_minor"`
	ItemsClass1NicNotPayeMinor     int64 `json:"items_class1_nic_not_paye_minor"`
	SalarySacrificeDeductionsMinor int64 `json:"salary_sacrifice_deductions_minor"`
	// Auto-enrolment status; the making-contributions amount detail is deferred (UI disables that option).
	PensionStatus     string             `json:"pension_status"`
	LeavingNextPayRun bool               `json:"leaving_next_pay_run"`
	LeavingDate       pgtype.Date        `json:"leaving_date"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

// Tenant entity. One row per registered business. All other tables point to this via organisation_id.
type Organisation struct {
	ID                   uuid.UUID   `json:"id"`
	Name                 string      `json:"name"`
	Slug                 pgtype.Text `json:"slug"`
	CompaniesHouseNumber pgtype.Text `json:"companies_house_number"`
	LegalName            pgtype.Text `json:"legal_name"`
	RegisteredAddress    pgtype.Text `json:"registered_address"`
	CompanyType          pgtype.Text `json:"company_type"`
	AddressLine1         pgtype.Text `json:"address_line_1"`
	AddressLine2         pgtype.Text `json:"address_line_2"`
	AddressLine3         pgtype.Text `json:"address_line_3"`
	Town                 pgtype.Text `json:"town"`
	Region               pgtype.Text `json:"region"`
	Postcode             pgtype.Text `json:"postcode"`
	// HMRC Unique Taxpayer Reference. Required for Self Assessment / Corp Tax.
	Utr pgtype.Text `json:"utr"`
	// VAT Registration Number, stored as the bare 9 digits (no GB prefix) — the form input and the HMRC MTD {vrn} path segment. NULL if not VAT-registered.
	Vrn                       pgtype.Text        `json:"vrn"`
	PayeReference             pgtype.Text        `json:"paye_reference"`
	AccountsOfficeReference   pgtype.Text        `json:"accounts_office_reference"`
	ClaimsEmploymentAllowance bool               `json:"claims_employment_allowance"`
	VatRegistered             bool               `json:"vat_registered"`
	VatUsesNonStandardRates   bool               `json:"vat_uses_non_standard_rates"`
	VatEffectiveDate          pgtype.Date        `json:"vat_effective_date"`
	VatFirstReturnPeriodEnd   pgtype.Date        `json:"vat_first_return_period_end"`
	VatReturnFrequency        pgtype.Text        `json:"vat_return_frequency"`
	VatAccountingBasis        pgtype.Text        `json:"vat_accounting_basis"`
	VatFlatRateScheme         bool               `json:"vat_flat_rate_scheme"`
	VatFlatRateBps            pgtype.Int4        `json:"vat_flat_rate_bps"`
	VatPreRegExpenseMonths    pgtype.Int4        `json:"vat_pre_reg_expense_months"`
	BusinessPhone             pgtype.Text        `json:"business_phone"`
	ContactEmail              pgtype.Text        `json:"contact_email"`
	ContactPhone              pgtype.Text        `json:"contact_phone"`
	Website                   pgtype.Text        `json:"website"`
	BusinessCategory          pgtype.Text        `json:"business_category"`
	BusinessDescription       pgtype.Text        `json:"business_description"`
	Plan                      string             `json:"plan"`
	TrialEndsAt               pgtype.Timestamptz `json:"trial_ends_at"`
	StripeCustomerID          pgtype.Text        `json:"stripe_customer_id"`
	StripeSubscriptionID      pgtype.Text        `json:"stripe_subscription_id"`
	NativeCurrency            string             `json:"native_currency"`
	// ISO 3166-1 alpha-2 country the org belongs to (e.g. GB). Selects the applicable vat_rates, which are keyed by the same country_code. NOT NULL, defaults to GB.
	CountryCode       string             `json:"country_code"`
	Timezone          string             `json:"timezone"`
	NextInvoiceNumber int32              `json:"next_invoice_number"`
	IsActive          bool               `json:"is_active"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

type OrganisationMembership struct {
	ID                        uuid.UUID          `json:"id"`
	OrganisationID            uuid.UUID          `json:"organisation_id"`
	UserID                    uuid.UUID          `json:"user_id"`
	Role                      OrganisationRole   `json:"role"`
	Status                    string             `json:"status"`
	InviteToken               pgtype.Text        `json:"invite_token"`
	InviteSentAt              pgtype.Timestamptz `json:"invite_sent_at"`
	InviteAcceptedAt          pgtype.Timestamptz `json:"invite_accepted_at"`
	InvitedByUserID           pgtype.UUID        `json:"invited_by_user_id"`
	InboxLocalPart            pgtype.Text        `json:"inbox_local_part"`
	InboxLocalPartGeneratedAt pgtype.Timestamptz `json:"inbox_local_part_generated_at"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
}

// Platform-level identity. One row per person. A user belongs to one or more organisations via organisation_memberships.
type User struct {
	ID uuid.UUID `json:"id"`
	// Login identifier. Stored lowercase. Globally unique across all tenants.
	Email string `json:"email"`
	// bcrypt hash at cost 12. NULL for OAuth-only accounts. Never store plaintext.
	PasswordHash pgtype.Text `json:"password_hash"`
	FirstName    string      `json:"first_name"`
	LastName     string      `json:"last_name"`
	Phone        pgtype.Text `json:"phone"`
	AvatarUrl    pgtype.Text `json:"avatar_url"`
	// UK NINO (payroll). Nullable; format validated in the service layer, not by a CHECK.
	NationalInsuranceNumber pgtype.Text `json:"national_insurance_number"`
	// User's PERSONAL 10-digit HMRC Unique Tax Reference (payroll/Self Assessment). Distinct from organisations.utr (the company UTR).
	Utr pgtype.Text `json:"utr"`
	// Date of birth (payroll: NI category by age, pension auto-enrolment). DATE — no time component.
	DateOfBirth pgtype.Date `json:"date_of_birth"`
	// Personal/home address (payroll). Free text, nullable. Distinct from the organisation address.
	AddressLine1 pgtype.Text `json:"address_line_1"`
	AddressLine2 pgtype.Text `json:"address_line_2"`
	AddressLine3 pgtype.Text `json:"address_line_3"`
	AddressLine4 pgtype.Text `json:"address_line_4"`
	// Personal/home postcode (payroll). Free text, nullable.
	Postcode                pgtype.Text        `json:"postcode"`
	EmailVerifiedAt         pgtype.Timestamptz `json:"email_verified_at"`
	EmailVerificationToken  pgtype.Text        `json:"email_verification_token"`
	EmailVerificationSentAt pgtype.Timestamptz `json:"email_verification_sent_at"`
	PasswordResetToken      pgtype.Text        `json:"password_reset_token"`
	PasswordResetSentAt     pgtype.Timestamptz `json:"password_reset_sent_at"`
	FailedLoginCount        int32              `json:"failed_login_count"`
	LockedUntil             pgtype.Timestamptz `json:"locked_until"`
	LastLoginAt             pgtype.Timestamptz `json:"last_login_at"`
	// Uses PostgreSQL native INET type — stores IPv4 and IPv6 without needing a string.
	LastLoginIp *netip.Addr        `json:"last_login_ip"`
	IsSuperuser bool               `json:"is_superuser"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}
