// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: categories.sql

package categories

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const categoryOfferedForType = `-- name: CategoryOfferedForType :one
SELECT EXISTS (
    SELECT 1
    FROM transaction_type_categories m
    JOIN categories c
      ON  c.organisation_id = $1
      AND c.is_active
      AND ( (m.nominal_code <> '' AND c.nominal_code = m.nominal_code)
         OR (m.api_group   <> '' AND c.api_group     = m.api_group) )
    WHERE m.transaction_type_code = $2
      AND (m.company_type = 'ALL' OR m.company_type = $3)
      AND c.id = $4
) AS offered
`

type CategoryOfferedForTypeParams struct {
	OrganisationID      uuid.UUID `json:"organisation_id"`
	TransactionTypeCode string    `json:"transaction_type_code"`
	CompanyType         string    `json:"company_type"`
	CategoryID          uuid.UUID `json:"category_id"`
}

// -----------------------------------------------------------------------------
// CategoryOfferedForType — does this type offer this nominal (for the org's
// company_type)? Backs the explain service's "is this category valid for the
// chosen type" guard. Returns the matching nominal_code(s) (empty = not offered).
// -----------------------------------------------------------------------------
func (q *Queries) CategoryOfferedForType(ctx context.Context, arg CategoryOfferedForTypeParams) (bool, error) {
	row := q.db.QueryRow(ctx, categoryOfferedForType,
		arg.OrganisationID,
		arg.TransactionTypeCode,
		arg.CompanyType,
		arg.CategoryID,
	)
	var offered bool
	err := row.Scan(&offered)
	return offered, err
}

const getCategory = `-- name: GetCategory :one
SELECT id, organisation_id, nominal_code, name, description, account_type, api_group, tax_reporting_name, allowable_for_tax, default_vat, is_capital_asset, is_system_managed, is_active, created_at, updated_at FROM categories
WHERE id              = $1
  AND organisation_id = $2
`

type GetCategoryParams struct {
	ID             uuid.UUID `json:"id"`
	OrganisationID uuid.UUID `json:"organisation_id"`
}

// -----------------------------------------------------------------------------
// GetCategory — one category by id, org-scoped. :one.
// -----------------------------------------------------------------------------
func (q *Queries) GetCategory(ctx context.Context, arg GetCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, getCategory, arg.ID, arg.OrganisationID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.NominalCode,
		&i.Name,
		&i.Description,
		&i.AccountType,
		&i.ApiGroup,
		&i.TaxReportingName,
		&i.AllowableForTax,
		&i.DefaultVat,
		&i.IsCapitalAsset,
		&i.IsSystemManaged,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTransactionType = `-- name: GetTransactionType :one
SELECT code, name, direction, entity_link, display_order, is_active, created_at FROM transaction_types WHERE code = $1
`

// -----------------------------------------------------------------------------
// GetTransactionType — one type by code (global reference). :one.
// Used by the explain service to read a type's direction + entity_link.
// -----------------------------------------------------------------------------
func (q *Queries) GetTransactionType(ctx context.Context, code string) (TransactionType, error) {
	row := q.db.QueryRow(ctx, getTransactionType, code)
	var i TransactionType
	err := row.Scan(
		&i.Code,
		&i.Name,
		&i.Direction,
		&i.EntityLink,
		&i.DisplayOrder,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getVatRate = `-- name: GetVatRate :one
SELECT id, country_code, name, rate_bps, is_fixed_ratio, effective_from, effective_to, created_at FROM vat_rates WHERE id = $1
`

// -----------------------------------------------------------------------------
// GetVatRate — one VAT rate by id (for the VAT extraction on an explanation).
// The frontend picks the id from GET /api/v1/vat-rates; the service reads rate_bps
// and feeds money.ComputeFixedVAT. :one.
// -----------------------------------------------------------------------------
func (q *Queries) GetVatRate(ctx context.Context, id uuid.UUID) (VatRate, error) {
	row := q.db.QueryRow(ctx, getVatRate, id)
	var i VatRate
	err := row.Scan(
		&i.ID,
		&i.CountryCode,
		&i.Name,
		&i.RateBps,
		&i.IsFixedRatio,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.CreatedAt,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many


SELECT id, organisation_id, nominal_code, name, description, account_type, api_group, tax_reporting_name, allowable_for_tax, default_vat, is_capital_asset, is_system_managed, is_active, created_at, updated_at FROM categories
WHERE organisation_id = $1
  AND is_active
ORDER BY nominal_code
`

// =============================================================================
// CATEGORIES MODULE — SQLC QUERIES
// File: db/queries/categories.sql
//
// Type-safe Go for the Chart of Accounts + reconcile reference tables (categories,
// transaction_types, transaction_type_categories — defined in categories_schema.sql).
// Generated by a DEDICATED sqlc block (see sqlc.yaml) into package `categories` at
// db/categories.
//
// categories is PER-ORG; transaction_types + the mapping are GLOBAL reference. The
// mapping SOFT-links categories by nominal_code (no FK across the global/per-org
// boundary), resolved against the caller's org at query time.
//
// Annotation syntax:
//
//	-- name: FuncName :one|:many|:exec
//	$1 ... positional params; sqlc.arg(name) for named; sqlc.embed(t) to nest a struct.
//
// =============================================================================
// -----------------------------------------------------------------------------
// ListCategories — the org's whole active Chart of Accounts, by nominal code.
// Populates the full category list / settings screen. Org-scoped. :many.
// -----------------------------------------------------------------------------
func (q *Queries) ListCategories(ctx context.Context, organisationID uuid.UUID) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories, organisationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.OrganisationID,
			&i.NominalCode,
			&i.Name,
			&i.Description,
			&i.AccountType,
			&i.ApiGroup,
			&i.TaxReportingName,
			&i.AllowableForTax,
			&i.DefaultVat,
			&i.IsCapitalAsset,
			&i.IsSystemManaged,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoriesForType = `-- name: ListCategoriesForType :many
SELECT c.id, c.organisation_id, c.nominal_code, c.name, c.description, c.account_type, c.api_group, c.tax_reporting_name, c.allowable_for_tax, c.default_vat, c.is_capital_asset, c.is_system_managed, c.is_active, c.created_at, c.updated_at, m.display_label
FROM transaction_type_categories m
JOIN categories c
  ON  c.organisation_id = $1
  AND c.is_active
  -- a mapping row targets EITHER a specific nominal OR a whole api_group
  AND ( (m.nominal_code <> '' AND c.nominal_code = m.nominal_code)
     OR (m.api_group   <> '' AND c.api_group     = m.api_group) )
WHERE m.transaction_type_code = $2
  AND (m.company_type = 'ALL' OR m.company_type = $3)
ORDER BY m.display_order, c.nominal_code
`

type ListCategoriesForTypeParams struct {
	OrganisationID      uuid.UUID `json:"organisation_id"`
	TransactionTypeCode string    `json:"transaction_type_code"`
	CompanyType         string    `json:"company_type"`
}

type ListCategoriesForTypeRow struct {
	Category     Category    `json:"category"`
	DisplayLabel pgtype.Text `json:"display_label"`
}

// -----------------------------------------------------------------------------
// ListCategoriesForType — EVERY category a transaction type offers, resolved
// against the caller's org's CoA. The "which accounts can I pick for this type"
// query — and each returned row IS the account that type-category pair posts to.
//
// Joins the GLOBAL mapping (transaction_type_categories) to the PER-ORG categories
// by nominal_code. company_type filters to the org: the 'ALL' rows always apply,
// the rest only for a matching company_type (e.g. Money Paid to User differs Ltd
// vs sole trader). display_label overrides the category name where the tab used a
// friendlier label. :many.
// -----------------------------------------------------------------------------
func (q *Queries) ListCategoriesForType(ctx context.Context, arg ListCategoriesForTypeParams) ([]ListCategoriesForTypeRow, error) {
	rows, err := q.db.Query(ctx, listCategoriesForType, arg.OrganisationID, arg.TransactionTypeCode, arg.CompanyType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCategoriesForTypeRow
	for rows.Next() {
		var i ListCategoriesForTypeRow
		if err := rows.Scan(
			&i.Category.ID,
			&i.Category.OrganisationID,
			&i.Category.NominalCode,
			&i.Category.Name,
			&i.Category.Description,
			&i.Category.AccountType,
			&i.Category.ApiGroup,
			&i.Category.TaxReportingName,
			&i.Category.AllowableForTax,
			&i.Category.DefaultVat,
			&i.Category.IsCapitalAsset,
			&i.Category.IsSystemManaged,
			&i.Category.IsActive,
			&i.Category.CreatedAt,
			&i.Category.UpdatedAt,
			&i.DisplayLabel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionTypes = `-- name: ListTransactionTypes :many
SELECT code, name, direction, entity_link, display_order, is_active, created_at FROM transaction_types
WHERE is_active
ORDER BY direction, display_order, name
`

// -----------------------------------------------------------------------------
// ListTransactionTypes — the 18 explanation types (GLOBAL reference). :many.
// Drives the "Type" dropdown, grouped by direction then display order.
// -----------------------------------------------------------------------------
func (q *Queries) ListTransactionTypes(ctx context.Context) ([]TransactionType, error) {
	rows, err := q.db.Query(ctx, listTransactionTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TransactionType
	for rows.Next() {
		var i TransactionType
		if err := rows.Scan(
			&i.Code,
			&i.Name,
			&i.Direction,
			&i.EntityLink,
			&i.DisplayOrder,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
