// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payroll.sql

package payroll

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const completePayRun = `-- name: CompletePayRun :one
UPDATE pay_runs SET
    status                            = 'completed',
    employment_allowance_amount_minor = $3,
    updated_at                        = now()
WHERE id = $1
  AND organisation_id = $2
RETURNING id, organisation_id, created_by_user_id, tax_year_start, frequency, period, period_start, period_end, payment_date, status, employment_allowance_claimed, employment_allowance_amount_minor, deleted_at, created_at, updated_at
`

type CompletePayRunParams struct {
	ID                             uuid.UUID `json:"id"`
	OrganisationID                 uuid.UUID `json:"organisation_id"`
	EmploymentAllowanceAmountMinor int64     `json:"employment_allowance_amount_minor"`
}

// "Run & Report": finalise the run and record the Employment Allowance offset.
func (q *Queries) CompletePayRun(ctx context.Context, arg CompletePayRunParams) (PayRun, error) {
	row := q.db.QueryRow(ctx, completePayRun, arg.ID, arg.OrganisationID, arg.EmploymentAllowanceAmountMinor)
	var i PayRun
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.CreatedByUserID,
		&i.TaxYearStart,
		&i.Frequency,
		&i.Period,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.PaymentDate,
		&i.Status,
		&i.EmploymentAllowanceClaimed,
		&i.EmploymentAllowanceAmountMinor,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPayRun = `-- name: CreatePayRun :one

INSERT INTO pay_runs (
    organisation_id,
    created_by_user_id,
    tax_year_start,
    period,
    period_start,
    period_end,
    payment_date,
    employment_allowance_claimed
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, organisation_id, created_by_user_id, tax_year_start, frequency, period, period_start, period_end, payment_date, status, employment_allowance_claimed, employment_allowance_amount_minor, deleted_at, created_at, updated_at
`

type CreatePayRunParams struct {
	OrganisationID             uuid.UUID   `json:"organisation_id"`
	CreatedByUserID            uuid.UUID   `json:"created_by_user_id"`
	TaxYearStart               int32       `json:"tax_year_start"`
	Period                     int32       `json:"period"`
	PeriodStart                pgtype.Date `json:"period_start"`
	PeriodEnd                  pgtype.Date `json:"period_end"`
	PaymentDate                pgtype.Date `json:"payment_date"`
	EmploymentAllowanceClaimed bool        `json:"employment_allowance_claimed"`
}

// =============================================================================
// PAY RUNS (the "Month N" header)
// =============================================================================
func (q *Queries) CreatePayRun(ctx context.Context, arg CreatePayRunParams) (PayRun, error) {
	row := q.db.QueryRow(ctx, createPayRun,
		arg.OrganisationID,
		arg.CreatedByUserID,
		arg.TaxYearStart,
		arg.Period,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.PaymentDate,
		arg.EmploymentAllowanceClaimed,
	)
	var i PayRun
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.CreatedByUserID,
		&i.TaxYearStart,
		&i.Frequency,
		&i.Period,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.PaymentDate,
		&i.Status,
		&i.EmploymentAllowanceClaimed,
		&i.EmploymentAllowanceAmountMinor,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPayslip = `-- name: CreatePayslip :one

INSERT INTO payslips (
    organisation_id,
    pay_run_id,
    user_id,
    tax_code,
    ni_category_letter,
    nic_calculation,
    week1_month1_basis,
    student_loan_undergraduate,
    student_loan_postgraduate,
    basic_pay_minor,
    allowance_minor,
    other_payments_minor,
    pay_not_subject_to_tax_ni_minor,
    payroll_giving_minor,
    other_deductions_net_pay_minor,
    items_class1_nic_not_paye_minor,
    salary_sacrifice_deductions_minor,
    leaving_payslip
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18
)
RETURNING id, organisation_id, pay_run_id, user_id, tax_code, ni_category_letter, nic_calculation, week1_month1_basis, student_loan_undergraduate, student_loan_postgraduate, basic_pay_minor, overtime_minor, bonus_minor, commission_minor, allowance_minor, absence_payments_minor, holiday_pay_minor, other_payments_minor, pay_not_subject_to_tax_ni_minor, statutory_sick_pay_minor, statutory_maternity_pay_minor, statutory_paternity_pay_minor, statutory_adoption_pay_minor, shared_parental_pay_minor, statutory_neonatal_care_pay_minor, statutory_parental_bereavement_pay_minor, payroll_giving_minor, other_deductions_net_pay_minor, items_class1_nic_not_paye_minor, salary_sacrifice_deductions_minor, gross_pay_minor, taxable_pay_minor, niable_pay_minor, tax_deducted_minor, employee_ni_minor, employer_ni_minor, employee_pension_minor, employer_pension_minor, student_loan_minor, net_pay_minor, hours_worked, comment, leaving_payslip, created_at, updated_at
`

type CreatePayslipParams struct {
	OrganisationID                 uuid.UUID   `json:"organisation_id"`
	PayRunID                       uuid.UUID   `json:"pay_run_id"`
	UserID                         uuid.UUID   `json:"user_id"`
	TaxCode                        pgtype.Text `json:"tax_code"`
	NiCategoryLetter               string      `json:"ni_category_letter"`
	NicCalculation                 string      `json:"nic_calculation"`
	Week1Month1Basis               bool        `json:"week1_month1_basis"`
	StudentLoanUndergraduate       bool        `json:"student_loan_undergraduate"`
	StudentLoanPostgraduate        bool        `json:"student_loan_postgraduate"`
	BasicPayMinor                  int64       `json:"basic_pay_minor"`
	AllowanceMinor                 int64       `json:"allowance_minor"`
	OtherPaymentsMinor             int64       `json:"other_payments_minor"`
	PayNotSubjectToTaxNiMinor      int64       `json:"pay_not_subject_to_tax_ni_minor"`
	PayrollGivingMinor             int64       `json:"payroll_giving_minor"`
	OtherDeductionsNetPayMinor     int64       `json:"other_deductions_net_pay_minor"`
	ItemsClass1NicNotPayeMinor     int64       `json:"items_class1_nic_not_paye_minor"`
	SalarySacrificeDeductionsMinor int64       `json:"salary_sacrifice_deductions_minor"`
	LeavingPayslip                 bool        `json:"leaving_payslip"`
}

// =============================================================================
// PAYSLIPS
// =============================================================================
func (q *Queries) CreatePayslip(ctx context.Context, arg CreatePayslipParams) (Payslip, error) {
	row := q.db.QueryRow(ctx, createPayslip,
		arg.OrganisationID,
		arg.PayRunID,
		arg.UserID,
		arg.TaxCode,
		arg.NiCategoryLetter,
		arg.NicCalculation,
		arg.Week1Month1Basis,
		arg.StudentLoanUndergraduate,
		arg.StudentLoanPostgraduate,
		arg.BasicPayMinor,
		arg.AllowanceMinor,
		arg.OtherPaymentsMinor,
		arg.PayNotSubjectToTaxNiMinor,
		arg.PayrollGivingMinor,
		arg.OtherDeductionsNetPayMinor,
		arg.ItemsClass1NicNotPayeMinor,
		arg.SalarySacrificeDeductionsMinor,
		arg.LeavingPayslip,
	)
	var i Payslip
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.PayRunID,
		&i.UserID,
		&i.TaxCode,
		&i.NiCategoryLetter,
		&i.NicCalculation,
		&i.Week1Month1Basis,
		&i.StudentLoanUndergraduate,
		&i.StudentLoanPostgraduate,
		&i.BasicPayMinor,
		&i.OvertimeMinor,
		&i.BonusMinor,
		&i.CommissionMinor,
		&i.AllowanceMinor,
		&i.AbsencePaymentsMinor,
		&i.HolidayPayMinor,
		&i.OtherPaymentsMinor,
		&i.PayNotSubjectToTaxNiMinor,
		&i.StatutorySickPayMinor,
		&i.StatutoryMaternityPayMinor,
		&i.StatutoryPaternityPayMinor,
		&i.StatutoryAdoptionPayMinor,
		&i.SharedParentalPayMinor,
		&i.StatutoryNeonatalCarePayMinor,
		&i.StatutoryParentalBereavementPayMinor,
		&i.PayrollGivingMinor,
		&i.OtherDeductionsNetPayMinor,
		&i.ItemsClass1NicNotPayeMinor,
		&i.SalarySacrificeDeductionsMinor,
		&i.GrossPayMinor,
		&i.TaxablePayMinor,
		&i.NiablePayMinor,
		&i.TaxDeductedMinor,
		&i.EmployeeNiMinor,
		&i.EmployerNiMinor,
		&i.EmployeePensionMinor,
		&i.EmployerPensionMinor,
		&i.StudentLoanMinor,
		&i.NetPayMinor,
		&i.HoursWorked,
		&i.Comment,
		&i.LeavingPayslip,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePayslipsForRun = `-- name: DeletePayslipsForRun :exec
DELETE FROM payslips
WHERE pay_run_id = $1
  AND organisation_id = $2
`

type DeletePayslipsForRunParams struct {
	PayRunID       uuid.UUID `json:"pay_run_id"`
	OrganisationID uuid.UUID `json:"organisation_id"`
}

// Remove all payslips of a draft run (used by "Refresh from profiles", which then
// re-snapshots them from the current employee profiles).
func (q *Queries) DeletePayslipsForRun(ctx context.Context, arg DeletePayslipsForRunParams) error {
	_, err := q.db.Exec(ctx, deletePayslipsForRun, arg.PayRunID, arg.OrganisationID)
	return err
}

const getLatestPayRun = `-- name: GetLatestPayRun :one
SELECT id, organisation_id, created_by_user_id, tax_year_start, frequency, period, period_start, period_end, payment_date, status, employment_allowance_claimed, employment_allowance_amount_minor, deleted_at, created_at, updated_at FROM pay_runs
WHERE organisation_id = $1
  AND tax_year_start = $2
  AND deleted_at IS NULL
ORDER BY period DESC
LIMIT 1
`

type GetLatestPayRunParams struct {
	OrganisationID uuid.UUID `json:"organisation_id"`
	TaxYearStart   int32     `json:"tax_year_start"`
}

// The most recent live run for a year — used for the sequencing check (next period
// = latest + 1) AND the edit-lock (only the latest run may be edited/deleted).
func (q *Queries) GetLatestPayRun(ctx context.Context, arg GetLatestPayRunParams) (PayRun, error) {
	row := q.db.QueryRow(ctx, getLatestPayRun, arg.OrganisationID, arg.TaxYearStart)
	var i PayRun
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.CreatedByUserID,
		&i.TaxYearStart,
		&i.Frequency,
		&i.Period,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.PaymentDate,
		&i.Status,
		&i.EmploymentAllowanceClaimed,
		&i.EmploymentAllowanceAmountMinor,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNiThresholds = `-- name: GetNiThresholds :one
SELECT tax_year_start, lel_annual_minor, lel_monthly_minor, pt_annual_minor, pt_monthly_minor, st_annual_minor, st_monthly_minor, uel_annual_minor, uel_monthly_minor FROM payroll_ni_thresholds
WHERE tax_year_start = $1
`

func (q *Queries) GetNiThresholds(ctx context.Context, taxYearStart int32) (PayrollNiThreshold, error) {
	row := q.db.QueryRow(ctx, getNiThresholds, taxYearStart)
	var i PayrollNiThreshold
	err := row.Scan(
		&i.TaxYearStart,
		&i.LelAnnualMinor,
		&i.LelMonthlyMinor,
		&i.PtAnnualMinor,
		&i.PtMonthlyMinor,
		&i.StAnnualMinor,
		&i.StMonthlyMinor,
		&i.UelAnnualMinor,
		&i.UelMonthlyMinor,
	)
	return i, err
}

const getOrganisationPayrollSettings = `-- name: GetOrganisationPayrollSettings :one
SELECT
    name,
    paye_reference,
    accounts_office_reference,
    claims_employment_allowance,
    address_line_1,
    address_line_2,
    address_line_3,
    town,
    region,
    postcode
FROM organisations
WHERE id = $1
  AND deleted_at IS NULL
`

type GetOrganisationPayrollSettingsRow struct {
	Name                      string      `json:"name"`
	PayeReference             pgtype.Text `json:"paye_reference"`
	AccountsOfficeReference   pgtype.Text `json:"accounts_office_reference"`
	ClaimsEmploymentAllowance bool        `json:"claims_employment_allowance"`
	AddressLine1              pgtype.Text `json:"address_line_1"`
	AddressLine2              pgtype.Text `json:"address_line_2"`
	AddressLine3              pgtype.Text `json:"address_line_3"`
	Town                      pgtype.Text `json:"town"`
	Region                    pgtype.Text `json:"region"`
	Postcode                  pgtype.Text `json:"postcode"`
}

// The org's payroll references for the overview/payslip header (PAYE ref, etc.).
func (q *Queries) GetOrganisationPayrollSettings(ctx context.Context, id uuid.UUID) (GetOrganisationPayrollSettingsRow, error) {
	row := q.db.QueryRow(ctx, getOrganisationPayrollSettings, id)
	var i GetOrganisationPayrollSettingsRow
	err := row.Scan(
		&i.Name,
		&i.PayeReference,
		&i.AccountsOfficeReference,
		&i.ClaimsEmploymentAllowance,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.AddressLine3,
		&i.Town,
		&i.Region,
		&i.Postcode,
	)
	return i, err
}

const getPayRun = `-- name: GetPayRun :one
SELECT id, organisation_id, created_by_user_id, tax_year_start, frequency, period, period_start, period_end, payment_date, status, employment_allowance_claimed, employment_allowance_amount_minor, deleted_at, created_at, updated_at FROM pay_runs
WHERE id = $1
  AND organisation_id = $2
  AND deleted_at IS NULL
`

type GetPayRunParams struct {
	ID             uuid.UUID `json:"id"`
	OrganisationID uuid.UUID `json:"organisation_id"`
}

func (q *Queries) GetPayRun(ctx context.Context, arg GetPayRunParams) (PayRun, error) {
	row := q.db.QueryRow(ctx, getPayRun, arg.ID, arg.OrganisationID)
	var i PayRun
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.CreatedByUserID,
		&i.TaxYearStart,
		&i.Frequency,
		&i.Period,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.PaymentDate,
		&i.Status,
		&i.EmploymentAllowanceClaimed,
		&i.EmploymentAllowanceAmountMinor,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPayslip = `-- name: GetPayslip :one
SELECT id, organisation_id, pay_run_id, user_id, tax_code, ni_category_letter, nic_calculation, week1_month1_basis, student_loan_undergraduate, student_loan_postgraduate, basic_pay_minor, overtime_minor, bonus_minor, commission_minor, allowance_minor, absence_payments_minor, holiday_pay_minor, other_payments_minor, pay_not_subject_to_tax_ni_minor, statutory_sick_pay_minor, statutory_maternity_pay_minor, statutory_paternity_pay_minor, statutory_adoption_pay_minor, shared_parental_pay_minor, statutory_neonatal_care_pay_minor, statutory_parental_bereavement_pay_minor, payroll_giving_minor, other_deductions_net_pay_minor, items_class1_nic_not_paye_minor, salary_sacrifice_deductions_minor, gross_pay_minor, taxable_pay_minor, niable_pay_minor, tax_deducted_minor, employee_ni_minor, employer_ni_minor, employee_pension_minor, employer_pension_minor, student_loan_minor, net_pay_minor, hours_worked, comment, leaving_payslip, created_at, updated_at FROM payslips
WHERE id = $1
  AND organisation_id = $2
`

type GetPayslipParams struct {
	ID             uuid.UUID `json:"id"`
	OrganisationID uuid.UUID `json:"organisation_id"`
}

func (q *Queries) GetPayslip(ctx context.Context, arg GetPayslipParams) (Payslip, error) {
	row := q.db.QueryRow(ctx, getPayslip, arg.ID, arg.OrganisationID)
	var i Payslip
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.PayRunID,
		&i.UserID,
		&i.TaxCode,
		&i.NiCategoryLetter,
		&i.NicCalculation,
		&i.Week1Month1Basis,
		&i.StudentLoanUndergraduate,
		&i.StudentLoanPostgraduate,
		&i.BasicPayMinor,
		&i.OvertimeMinor,
		&i.BonusMinor,
		&i.CommissionMinor,
		&i.AllowanceMinor,
		&i.AbsencePaymentsMinor,
		&i.HolidayPayMinor,
		&i.OtherPaymentsMinor,
		&i.PayNotSubjectToTaxNiMinor,
		&i.StatutorySickPayMinor,
		&i.StatutoryMaternityPayMinor,
		&i.StatutoryPaternityPayMinor,
		&i.StatutoryAdoptionPayMinor,
		&i.SharedParentalPayMinor,
		&i.StatutoryNeonatalCarePayMinor,
		&i.StatutoryParentalBereavementPayMinor,
		&i.PayrollGivingMinor,
		&i.OtherDeductionsNetPayMinor,
		&i.ItemsClass1NicNotPayeMinor,
		&i.SalarySacrificeDeductionsMinor,
		&i.GrossPayMinor,
		&i.TaxablePayMinor,
		&i.NiablePayMinor,
		&i.TaxDeductedMinor,
		&i.EmployeeNiMinor,
		&i.EmployerNiMinor,
		&i.EmployeePensionMinor,
		&i.EmployerPensionMinor,
		&i.StudentLoanMinor,
		&i.NetPayMinor,
		&i.HoursWorked,
		&i.Comment,
		&i.LeavingPayslip,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaxYear = `-- name: GetTaxYear :one



SELECT tax_year_start, label, employment_allowance_cap_minor, default_tax_code, period_count, created_at, updated_at FROM payroll_tax_years
WHERE tax_year_start = $1
`

// =============================================================================
// PAYROLL MODULE — SQLC QUERIES
// File: db/queries/payroll.sql
//
// Type-safe Go for the pay_runs + payslips tables and the four GLOBAL rate tables
// defined in db/schema/payroll_schema.sql, plus read-only snapshot joins over the
// existing employee_payroll / organisation_memberships / users tables (loaded from
// auth_schema.sql in this block's schema list). Generated into package `payroll`
// at db/payroll.
//
// The pay_runs / payslips queries are ORGANISATION-SCOPED (multi-tenancy) and the
// header is SOFT-DELETE-AWARE (deleted_at IS NULL). The rate-table reads are GLOBAL
// (statutory data shared by every org), keyed only by tax_year_start.
// =============================================================================
// =============================================================================
// RATE TABLES (global reference data, read-only at runtime)
// =============================================================================
func (q *Queries) GetTaxYear(ctx context.Context, taxYearStart int32) (PayrollTaxYear, error) {
	row := q.db.QueryRow(ctx, getTaxYear, taxYearStart)
	var i PayrollTaxYear
	err := row.Scan(
		&i.TaxYearStart,
		&i.Label,
		&i.EmploymentAllowanceCapMinor,
		&i.DefaultTaxCode,
		&i.PeriodCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActivePayrollEmployees = `-- name: ListActivePayrollEmployees :many

SELECT
    u.id                                                        AS user_id,
    u.first_name,
    u.last_name,
    ep.tax_code                                                 AS tax_code,
    COALESCE(ep.ni_category_letter, 'A')                        AS ni_category_letter,
    COALESCE(ep.nic_calculation, 'employee')                    AS nic_calculation,
    COALESCE(ep.week1_month1_basis, FALSE)                      AS week1_month1_basis,
    COALESCE(ep.student_loan_undergraduate, FALSE)              AS student_loan_undergraduate,
    COALESCE(ep.student_loan_postgraduate, FALSE)               AS student_loan_postgraduate,
    COALESCE(ep.basic_pay_minor, 0)::BIGINT                     AS basic_pay_minor,
    COALESCE(ep.allowance_minor, 0)::BIGINT                     AS allowance_minor,
    COALESCE(ep.other_payments_minor, 0)::BIGINT               AS other_payments_minor,
    COALESCE(ep.pay_not_subject_to_tax_ni_minor, 0)::BIGINT     AS pay_not_subject_to_tax_ni_minor,
    COALESCE(ep.payroll_giving_minor, 0)::BIGINT                AS payroll_giving_minor,
    COALESCE(ep.other_deductions_net_pay_minor, 0)::BIGINT      AS other_deductions_net_pay_minor,
    COALESCE(ep.items_class1_nic_not_paye_minor, 0)::BIGINT     AS items_class1_nic_not_paye_minor,
    COALESCE(ep.salary_sacrifice_deductions_minor, 0)::BIGINT   AS salary_sacrifice_deductions_minor,
    COALESCE(ep.leaving_next_pay_run, FALSE)                    AS leaving_next_pay_run,
    COALESCE(ep.pension_status, 'opted_out_or_ineligible')      AS pension_status,
    ep.start_date                                               AS start_date,
    ep.leaving_date                                             AS leaving_date
FROM organisation_memberships m
JOIN users u ON u.id = m.user_id AND u.deleted_at IS NULL
LEFT JOIN employee_payroll ep
    ON ep.organisation_id = m.organisation_id AND ep.user_id = m.user_id
WHERE m.organisation_id = $1
  AND m.status = 'active'
ORDER BY u.last_name, u.first_name
`

type ListActivePayrollEmployeesRow struct {
	UserID                         uuid.UUID   `json:"user_id"`
	FirstName                      string      `json:"first_name"`
	LastName                       string      `json:"last_name"`
	TaxCode                        pgtype.Text `json:"tax_code"`
	NiCategoryLetter               string      `json:"ni_category_letter"`
	NicCalculation                 string      `json:"nic_calculation"`
	Week1Month1Basis               bool        `json:"week1_month1_basis"`
	StudentLoanUndergraduate       bool        `json:"student_loan_undergraduate"`
	StudentLoanPostgraduate        bool        `json:"student_loan_postgraduate"`
	BasicPayMinor                  int64       `json:"basic_pay_minor"`
	AllowanceMinor                 int64       `json:"allowance_minor"`
	OtherPaymentsMinor             int64       `json:"other_payments_minor"`
	PayNotSubjectToTaxNiMinor      int64       `json:"pay_not_subject_to_tax_ni_minor"`
	PayrollGivingMinor             int64       `json:"payroll_giving_minor"`
	OtherDeductionsNetPayMinor     int64       `json:"other_deductions_net_pay_minor"`
	ItemsClass1NicNotPayeMinor     int64       `json:"items_class1_nic_not_paye_minor"`
	SalarySacrificeDeductionsMinor int64       `json:"salary_sacrifice_deductions_minor"`
	LeavingNextPayRun              bool        `json:"leaving_next_pay_run"`
	PensionStatus                  string      `json:"pension_status"`
	StartDate                      pgtype.Date `json:"start_date"`
	LeavingDate                    pgtype.Date `json:"leaving_date"`
}

// =============================================================================
// SNAPSHOT SOURCE (active employees + their payroll profile)
// =============================================================================
// Every ACTIVE member of the org with their employee_payroll profile (LEFT JOIN, so
// a member with no saved profile still appears, read as column defaults via COALESCE).
// This is what PreparePayRun snapshots into draft payslips.
func (q *Queries) ListActivePayrollEmployees(ctx context.Context, organisationID uuid.UUID) ([]ListActivePayrollEmployeesRow, error) {
	rows, err := q.db.Query(ctx, listActivePayrollEmployees, organisationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActivePayrollEmployeesRow
	for rows.Next() {
		var i ListActivePayrollEmployeesRow
		if err := rows.Scan(
			&i.UserID,
			&i.FirstName,
			&i.LastName,
			&i.TaxCode,
			&i.NiCategoryLetter,
			&i.NicCalculation,
			&i.Week1Month1Basis,
			&i.StudentLoanUndergraduate,
			&i.StudentLoanPostgraduate,
			&i.BasicPayMinor,
			&i.AllowanceMinor,
			&i.OtherPaymentsMinor,
			&i.PayNotSubjectToTaxNiMinor,
			&i.PayrollGivingMinor,
			&i.OtherDeductionsNetPayMinor,
			&i.ItemsClass1NicNotPayeMinor,
			&i.SalarySacrificeDeductionsMinor,
			&i.LeavingNextPayRun,
			&i.PensionStatus,
			&i.StartDate,
			&i.LeavingDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNiCategoryRates = `-- name: ListNiCategoryRates :many
SELECT category_letter, employee_main_bps, employee_upper_bps, employer_bps
FROM payroll_ni_category_rates
WHERE tax_year_start = $1
ORDER BY category_letter
`

type ListNiCategoryRatesRow struct {
	CategoryLetter   string `json:"category_letter"`
	EmployeeMainBps  int32  `json:"employee_main_bps"`
	EmployeeUpperBps int32  `json:"employee_upper_bps"`
	EmployerBps      int32  `json:"employer_bps"`
}

func (q *Queries) ListNiCategoryRates(ctx context.Context, taxYearStart int32) ([]ListNiCategoryRatesRow, error) {
	rows, err := q.db.Query(ctx, listNiCategoryRates, taxYearStart)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNiCategoryRatesRow
	for rows.Next() {
		var i ListNiCategoryRatesRow
		if err := rows.Scan(
			&i.CategoryLetter,
			&i.EmployeeMainBps,
			&i.EmployeeUpperBps,
			&i.EmployerBps,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPayRuns = `-- name: ListPayRuns :many
SELECT id, organisation_id, created_by_user_id, tax_year_start, frequency, period, period_start, period_end, payment_date, status, employment_allowance_claimed, employment_allowance_amount_minor, deleted_at, created_at, updated_at FROM pay_runs
WHERE organisation_id = $1
  AND tax_year_start = $2
  AND deleted_at IS NULL
ORDER BY period DESC
`

type ListPayRunsParams struct {
	OrganisationID uuid.UUID `json:"organisation_id"`
	TaxYearStart   int32     `json:"tax_year_start"`
}

// The org's runs for a tax year, newest period first (the overview History list).
func (q *Queries) ListPayRuns(ctx context.Context, arg ListPayRunsParams) ([]PayRun, error) {
	rows, err := q.db.Query(ctx, listPayRuns, arg.OrganisationID, arg.TaxYearStart)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PayRun
	for rows.Next() {
		var i PayRun
		if err := rows.Scan(
			&i.ID,
			&i.OrganisationID,
			&i.CreatedByUserID,
			&i.TaxYearStart,
			&i.Frequency,
			&i.Period,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.PaymentDate,
			&i.Status,
			&i.EmploymentAllowanceClaimed,
			&i.EmploymentAllowanceAmountMinor,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPayeBands = `-- name: ListPayeBands :many
SELECT region, band_order, upper_threshold_minor, rate_bps
FROM payroll_paye_bands
WHERE tax_year_start = $1
ORDER BY region, band_order
`

type ListPayeBandsRow struct {
	Region              string      `json:"region"`
	BandOrder           int32       `json:"band_order"`
	UpperThresholdMinor pgtype.Int8 `json:"upper_threshold_minor"`
	RateBps             int32       `json:"rate_bps"`
}

func (q *Queries) ListPayeBands(ctx context.Context, taxYearStart int32) ([]ListPayeBandsRow, error) {
	rows, err := q.db.Query(ctx, listPayeBands, taxYearStart)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPayeBandsRow
	for rows.Next() {
		var i ListPayeBandsRow
		if err := rows.Scan(
			&i.Region,
			&i.BandOrder,
			&i.UpperThresholdMinor,
			&i.RateBps,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPayslipsForRun = `-- name: ListPayslipsForRun :many
SELECT id, organisation_id, pay_run_id, user_id, tax_code, ni_category_letter, nic_calculation, week1_month1_basis, student_loan_undergraduate, student_loan_postgraduate, basic_pay_minor, overtime_minor, bonus_minor, commission_minor, allowance_minor, absence_payments_minor, holiday_pay_minor, other_payments_minor, pay_not_subject_to_tax_ni_minor, statutory_sick_pay_minor, statutory_maternity_pay_minor, statutory_paternity_pay_minor, statutory_adoption_pay_minor, shared_parental_pay_minor, statutory_neonatal_care_pay_minor, statutory_parental_bereavement_pay_minor, payroll_giving_minor, other_deductions_net_pay_minor, items_class1_nic_not_paye_minor, salary_sacrifice_deductions_minor, gross_pay_minor, taxable_pay_minor, niable_pay_minor, tax_deducted_minor, employee_ni_minor, employer_ni_minor, employee_pension_minor, employer_pension_minor, student_loan_minor, net_pay_minor, hours_worked, comment, leaving_payslip, created_at, updated_at FROM payslips
WHERE pay_run_id = $1
  AND organisation_id = $2
ORDER BY created_at
`

type ListPayslipsForRunParams struct {
	PayRunID       uuid.UUID `json:"pay_run_id"`
	OrganisationID uuid.UUID `json:"organisation_id"`
}

func (q *Queries) ListPayslipsForRun(ctx context.Context, arg ListPayslipsForRunParams) ([]Payslip, error) {
	rows, err := q.db.Query(ctx, listPayslipsForRun, arg.PayRunID, arg.OrganisationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payslip
	for rows.Next() {
		var i Payslip
		if err := rows.Scan(
			&i.ID,
			&i.OrganisationID,
			&i.PayRunID,
			&i.UserID,
			&i.TaxCode,
			&i.NiCategoryLetter,
			&i.NicCalculation,
			&i.Week1Month1Basis,
			&i.StudentLoanUndergraduate,
			&i.StudentLoanPostgraduate,
			&i.BasicPayMinor,
			&i.OvertimeMinor,
			&i.BonusMinor,
			&i.CommissionMinor,
			&i.AllowanceMinor,
			&i.AbsencePaymentsMinor,
			&i.HolidayPayMinor,
			&i.OtherPaymentsMinor,
			&i.PayNotSubjectToTaxNiMinor,
			&i.StatutorySickPayMinor,
			&i.StatutoryMaternityPayMinor,
			&i.StatutoryPaternityPayMinor,
			&i.StatutoryAdoptionPayMinor,
			&i.SharedParentalPayMinor,
			&i.StatutoryNeonatalCarePayMinor,
			&i.StatutoryParentalBereavementPayMinor,
			&i.PayrollGivingMinor,
			&i.OtherDeductionsNetPayMinor,
			&i.ItemsClass1NicNotPayeMinor,
			&i.SalarySacrificeDeductionsMinor,
			&i.GrossPayMinor,
			&i.TaxablePayMinor,
			&i.NiablePayMinor,
			&i.TaxDeductedMinor,
			&i.EmployeeNiMinor,
			&i.EmployerNiMinor,
			&i.EmployeePensionMinor,
			&i.EmployerPensionMinor,
			&i.StudentLoanMinor,
			&i.NetPayMinor,
			&i.HoursWorked,
			&i.Comment,
			&i.LeavingPayslip,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunPayslipNames = `-- name: ListRunPayslipNames :many
SELECT p.user_id, u.first_name, u.last_name
FROM payslips p
JOIN users u ON u.id = p.user_id
WHERE p.pay_run_id = $1
  AND p.organisation_id = $2
`

type ListRunPayslipNamesParams struct {
	PayRunID       uuid.UUID `json:"pay_run_id"`
	OrganisationID uuid.UUID `json:"organisation_id"`
}

type ListRunPayslipNamesRow struct {
	UserID    uuid.UUID `json:"user_id"`
	FirstName string    `json:"first_name"`
	LastName  string    `json:"last_name"`
}

// The employee display names for a run's payslips, in ONE query (so the detail
// builder doesn't fetch each user individually).
func (q *Queries) ListRunPayslipNames(ctx context.Context, arg ListRunPayslipNamesParams) ([]ListRunPayslipNamesRow, error) {
	rows, err := q.db.Query(ctx, listRunPayslipNames, arg.PayRunID, arg.OrganisationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRunPayslipNamesRow
	for rows.Next() {
		var i ListRunPayslipNamesRow
		if err := rows.Scan(&i.UserID, &i.FirstName, &i.LastName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listYearToDateByUserUpToPeriod = `-- name: ListYearToDateByUserUpToPeriod :many
SELECT
    p.user_id,
    COALESCE(SUM(p.gross_pay_minor), 0)::BIGINT    AS gross_pay_minor,
    COALESCE(SUM(p.taxable_pay_minor), 0)::BIGINT  AS taxable_pay_minor,
    COALESCE(SUM(p.niable_pay_minor), 0)::BIGINT   AS niable_pay_minor,
    COALESCE(SUM(p.tax_deducted_minor), 0)::BIGINT AS tax_deducted_minor,
    COALESCE(SUM(p.employee_ni_minor), 0)::BIGINT  AS employee_ni_minor,
    COALESCE(SUM(p.employer_ni_minor), 0)::BIGINT  AS employer_ni_minor,
    COALESCE(SUM(p.net_pay_minor), 0)::BIGINT      AS net_pay_minor
FROM payslips p
JOIN pay_runs r ON r.id = p.pay_run_id AND r.deleted_at IS NULL
WHERE p.organisation_id = $1
  AND r.tax_year_start = $2
  AND r.period <= $3
GROUP BY p.user_id
`

type ListYearToDateByUserUpToPeriodParams struct {
	OrganisationID uuid.UUID `json:"organisation_id"`
	TaxYearStart   int32     `json:"tax_year_start"`
	Period         int32     `json:"period"`
}

type ListYearToDateByUserUpToPeriodRow struct {
	UserID           uuid.UUID `json:"user_id"`
	GrossPayMinor    int64     `json:"gross_pay_minor"`
	TaxablePayMinor  int64     `json:"taxable_pay_minor"`
	NiablePayMinor   int64     `json:"niable_pay_minor"`
	TaxDeductedMinor int64     `json:"tax_deducted_minor"`
	EmployeeNiMinor  int64     `json:"employee_ni_minor"`
	EmployerNiMinor  int64     `json:"employer_ni_minor"`
	NetPayMinor      int64     `json:"net_pay_minor"`
}

// Per-employee year-to-date totals for the org in ONE query, summed over periods UP
// TO AND INCLUDING $3. Avoids an N+1 over the employee list. Used three ways:
//   - prepare: pass (period - 1) for the cumulative "prior" YTD the engine needs;
//   - run detail / payslip YTD block: pass the run's period;
//   - overview: pass 12 (the whole year).
func (q *Queries) ListYearToDateByUserUpToPeriod(ctx context.Context, arg ListYearToDateByUserUpToPeriodParams) ([]ListYearToDateByUserUpToPeriodRow, error) {
	rows, err := q.db.Query(ctx, listYearToDateByUserUpToPeriod, arg.OrganisationID, arg.TaxYearStart, arg.Period)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListYearToDateByUserUpToPeriodRow
	for rows.Next() {
		var i ListYearToDateByUserUpToPeriodRow
		if err := rows.Scan(
			&i.UserID,
			&i.GrossPayMinor,
			&i.TaxablePayMinor,
			&i.NiablePayMinor,
			&i.TaxDeductedMinor,
			&i.EmployeeNiMinor,
			&i.EmployerNiMinor,
			&i.NetPayMinor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeletePayRun = `-- name: SoftDeletePayRun :exec
UPDATE pay_runs SET
    deleted_at = now(),
    updated_at = now()
WHERE id = $1
  AND organisation_id = $2
`

type SoftDeletePayRunParams struct {
	ID             uuid.UUID `json:"id"`
	OrganisationID uuid.UUID `json:"organisation_id"`
}

func (q *Queries) SoftDeletePayRun(ctx context.Context, arg SoftDeletePayRunParams) error {
	_, err := q.db.Exec(ctx, softDeletePayRun, arg.ID, arg.OrganisationID)
	return err
}

const sumOrgYearToDate = `-- name: SumOrgYearToDate :one
SELECT
    COALESCE(SUM(p.gross_pay_minor), 0)::BIGINT    AS gross_pay_minor,
    COALESCE(SUM(p.tax_deducted_minor), 0)::BIGINT AS tax_deducted_minor,
    COALESCE(SUM(p.employee_ni_minor + p.employer_ni_minor), 0)::BIGINT AS total_ni_minor,
    COALESCE(SUM(r.employment_allowance_amount_minor), 0)::BIGINT AS employment_allowance_minor
FROM payslips p
JOIN pay_runs r ON r.id = p.pay_run_id AND r.deleted_at IS NULL
WHERE p.organisation_id = $1
  AND r.tax_year_start = $2
`

type SumOrgYearToDateParams struct {
	OrganisationID uuid.UUID `json:"organisation_id"`
	TaxYearStart   int32     `json:"tax_year_start"`
}

type SumOrgYearToDateRow struct {
	GrossPayMinor            int64 `json:"gross_pay_minor"`
	TaxDeductedMinor         int64 `json:"tax_deducted_minor"`
	TotalNiMinor             int64 `json:"total_ni_minor"`
	EmploymentAllowanceMinor int64 `json:"employment_allowance_minor"`
}

// Whole-organisation year-to-date totals for the overview's Year-to-date card.
func (q *Queries) SumOrgYearToDate(ctx context.Context, arg SumOrgYearToDateParams) (SumOrgYearToDateRow, error) {
	row := q.db.QueryRow(ctx, sumOrgYearToDate, arg.OrganisationID, arg.TaxYearStart)
	var i SumOrgYearToDateRow
	err := row.Scan(
		&i.GrossPayMinor,
		&i.TaxDeductedMinor,
		&i.TotalNiMinor,
		&i.EmploymentAllowanceMinor,
	)
	return i, err
}

const sumPayRunTotals = `-- name: SumPayRunTotals :one
SELECT
    COALESCE(SUM(gross_pay_minor), 0)::BIGINT    AS gross_pay_minor,
    COALESCE(SUM(tax_deducted_minor), 0)::BIGINT AS tax_deducted_minor,
    COALESCE(SUM(employee_ni_minor), 0)::BIGINT  AS employee_ni_minor,
    COALESCE(SUM(employer_ni_minor), 0)::BIGINT  AS employer_ni_minor,
    COALESCE(SUM(net_pay_minor), 0)::BIGINT      AS net_pay_minor
FROM payslips
WHERE pay_run_id = $1
  AND organisation_id = $2
`

type SumPayRunTotalsParams struct {
	PayRunID       uuid.UUID `json:"pay_run_id"`
	OrganisationID uuid.UUID `json:"organisation_id"`
}

type SumPayRunTotalsRow struct {
	GrossPayMinor    int64 `json:"gross_pay_minor"`
	TaxDeductedMinor int64 `json:"tax_deducted_minor"`
	EmployeeNiMinor  int64 `json:"employee_ni_minor"`
	EmployerNiMinor  int64 `json:"employer_ni_minor"`
	NetPayMinor      int64 `json:"net_pay_minor"`
}

// Per-run totals for the History row (pay/tax/NI/net for one run).
func (q *Queries) SumPayRunTotals(ctx context.Context, arg SumPayRunTotalsParams) (SumPayRunTotalsRow, error) {
	row := q.db.QueryRow(ctx, sumPayRunTotals, arg.PayRunID, arg.OrganisationID)
	var i SumPayRunTotalsRow
	err := row.Scan(
		&i.GrossPayMinor,
		&i.TaxDeductedMinor,
		&i.EmployeeNiMinor,
		&i.EmployerNiMinor,
		&i.NetPayMinor,
	)
	return i, err
}

const sumYearToDateForUser = `-- name: SumYearToDateForUser :one

SELECT
    COALESCE(SUM(p.gross_pay_minor), 0)::BIGINT    AS gross_pay_minor,
    COALESCE(SUM(p.taxable_pay_minor), 0)::BIGINT  AS taxable_pay_minor,
    COALESCE(SUM(p.niable_pay_minor), 0)::BIGINT   AS niable_pay_minor,
    COALESCE(SUM(p.tax_deducted_minor), 0)::BIGINT AS tax_deducted_minor,
    COALESCE(SUM(p.employee_ni_minor), 0)::BIGINT  AS employee_ni_minor,
    COALESCE(SUM(p.employer_ni_minor), 0)::BIGINT  AS employer_ni_minor,
    COALESCE(SUM(p.net_pay_minor), 0)::BIGINT      AS net_pay_minor
FROM payslips p
JOIN pay_runs r ON r.id = p.pay_run_id AND r.deleted_at IS NULL
WHERE p.organisation_id = $1
  AND p.user_id = $2
  AND r.tax_year_start = $3
  AND r.period <= $4
`

type SumYearToDateForUserParams struct {
	OrganisationID uuid.UUID `json:"organisation_id"`
	UserID         uuid.UUID `json:"user_id"`
	TaxYearStart   int32     `json:"tax_year_start"`
	Period         int32     `json:"period"`
}

type SumYearToDateForUserRow struct {
	GrossPayMinor    int64 `json:"gross_pay_minor"`
	TaxablePayMinor  int64 `json:"taxable_pay_minor"`
	NiablePayMinor   int64 `json:"niable_pay_minor"`
	TaxDeductedMinor int64 `json:"tax_deducted_minor"`
	EmployeeNiMinor  int64 `json:"employee_ni_minor"`
	EmployerNiMinor  int64 `json:"employer_ni_minor"`
	NetPayMinor      int64 `json:"net_pay_minor"`
}

// =============================================================================
// AGGREGATES (year-to-date — derived, never stored as a running total)
// =============================================================================
// Cumulative figures for one employee across a tax year, up to AND INCLUDING the
// given period. Pass (period - 1) for the "prior" YTD the cumulative engine needs;
// pass the current period for the payslip's YTD display. Joins payslips → pay_runs
// for the tax year + period filter.
func (q *Queries) SumYearToDateForUser(ctx context.Context, arg SumYearToDateForUserParams) (SumYearToDateForUserRow, error) {
	row := q.db.QueryRow(ctx, sumYearToDateForUser,
		arg.OrganisationID,
		arg.UserID,
		arg.TaxYearStart,
		arg.Period,
	)
	var i SumYearToDateForUserRow
	err := row.Scan(
		&i.GrossPayMinor,
		&i.TaxablePayMinor,
		&i.NiablePayMinor,
		&i.TaxDeductedMinor,
		&i.EmployeeNiMinor,
		&i.EmployerNiMinor,
		&i.NetPayMinor,
	)
	return i, err
}

const updatePayRunEmploymentAllowance = `-- name: UpdatePayRunEmploymentAllowance :exec
UPDATE pay_runs SET
    employment_allowance_amount_minor = $3,
    updated_at                        = now()
WHERE id = $1
  AND organisation_id = $2
`

type UpdatePayRunEmploymentAllowanceParams struct {
	ID                             uuid.UUID `json:"id"`
	OrganisationID                 uuid.UUID `json:"organisation_id"`
	EmploymentAllowanceAmountMinor int64     `json:"employment_allowance_amount_minor"`
}

// Set the EA offset on a run without changing its status (recomputed whenever the
// run's payslips change, so the draft's "Due to HMRC" reflects the allowance).
func (q *Queries) UpdatePayRunEmploymentAllowance(ctx context.Context, arg UpdatePayRunEmploymentAllowanceParams) error {
	_, err := q.db.Exec(ctx, updatePayRunEmploymentAllowance, arg.ID, arg.OrganisationID, arg.EmploymentAllowanceAmountMinor)
	return err
}

const updatePayslipComputed = `-- name: UpdatePayslipComputed :one
UPDATE payslips SET
    gross_pay_minor        = $3,
    taxable_pay_minor      = $4,
    niable_pay_minor       = $5,
    tax_deducted_minor     = $6,
    employee_ni_minor      = $7,
    employer_ni_minor      = $8,
    employee_pension_minor = $9,
    employer_pension_minor = $10,
    student_loan_minor     = $11,
    net_pay_minor          = $12,
    updated_at             = now()
WHERE id = $1
  AND organisation_id = $2
RETURNING id, organisation_id, pay_run_id, user_id, tax_code, ni_category_letter, nic_calculation, week1_month1_basis, student_loan_undergraduate, student_loan_postgraduate, basic_pay_minor, overtime_minor, bonus_minor, commission_minor, allowance_minor, absence_payments_minor, holiday_pay_minor, other_payments_minor, pay_not_subject_to_tax_ni_minor, statutory_sick_pay_minor, statutory_maternity_pay_minor, statutory_paternity_pay_minor, statutory_adoption_pay_minor, shared_parental_pay_minor, statutory_neonatal_care_pay_minor, statutory_parental_bereavement_pay_minor, payroll_giving_minor, other_deductions_net_pay_minor, items_class1_nic_not_paye_minor, salary_sacrifice_deductions_minor, gross_pay_minor, taxable_pay_minor, niable_pay_minor, tax_deducted_minor, employee_ni_minor, employer_ni_minor, employee_pension_minor, employer_pension_minor, student_loan_minor, net_pay_minor, hours_worked, comment, leaving_payslip, created_at, updated_at
`

type UpdatePayslipComputedParams struct {
	ID                   uuid.UUID `json:"id"`
	OrganisationID       uuid.UUID `json:"organisation_id"`
	GrossPayMinor        int64     `json:"gross_pay_minor"`
	TaxablePayMinor      int64     `json:"taxable_pay_minor"`
	NiablePayMinor       int64     `json:"niable_pay_minor"`
	TaxDeductedMinor     int64     `json:"tax_deducted_minor"`
	EmployeeNiMinor      int64     `json:"employee_ni_minor"`
	EmployerNiMinor      int64     `json:"employer_ni_minor"`
	EmployeePensionMinor int64     `json:"employee_pension_minor"`
	EmployerPensionMinor int64     `json:"employer_pension_minor"`
	StudentLoanMinor     int64     `json:"student_loan_minor"`
	NetPayMinor          int64     `json:"net_pay_minor"`
}

// Write the engine's computed figures back onto the payslip.
func (q *Queries) UpdatePayslipComputed(ctx context.Context, arg UpdatePayslipComputedParams) (Payslip, error) {
	row := q.db.QueryRow(ctx, updatePayslipComputed,
		arg.ID,
		arg.OrganisationID,
		arg.GrossPayMinor,
		arg.TaxablePayMinor,
		arg.NiablePayMinor,
		arg.TaxDeductedMinor,
		arg.EmployeeNiMinor,
		arg.EmployerNiMinor,
		arg.EmployeePensionMinor,
		arg.EmployerPensionMinor,
		arg.StudentLoanMinor,
		arg.NetPayMinor,
	)
	var i Payslip
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.PayRunID,
		&i.UserID,
		&i.TaxCode,
		&i.NiCategoryLetter,
		&i.NicCalculation,
		&i.Week1Month1Basis,
		&i.StudentLoanUndergraduate,
		&i.StudentLoanPostgraduate,
		&i.BasicPayMinor,
		&i.OvertimeMinor,
		&i.BonusMinor,
		&i.CommissionMinor,
		&i.AllowanceMinor,
		&i.AbsencePaymentsMinor,
		&i.HolidayPayMinor,
		&i.OtherPaymentsMinor,
		&i.PayNotSubjectToTaxNiMinor,
		&i.StatutorySickPayMinor,
		&i.StatutoryMaternityPayMinor,
		&i.StatutoryPaternityPayMinor,
		&i.StatutoryAdoptionPayMinor,
		&i.SharedParentalPayMinor,
		&i.StatutoryNeonatalCarePayMinor,
		&i.StatutoryParentalBereavementPayMinor,
		&i.PayrollGivingMinor,
		&i.OtherDeductionsNetPayMinor,
		&i.ItemsClass1NicNotPayeMinor,
		&i.SalarySacrificeDeductionsMinor,
		&i.GrossPayMinor,
		&i.TaxablePayMinor,
		&i.NiablePayMinor,
		&i.TaxDeductedMinor,
		&i.EmployeeNiMinor,
		&i.EmployerNiMinor,
		&i.EmployeePensionMinor,
		&i.EmployerPensionMinor,
		&i.StudentLoanMinor,
		&i.NetPayMinor,
		&i.HoursWorked,
		&i.Comment,
		&i.LeavingPayslip,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePayslipInputs = `-- name: UpdatePayslipInputs :one
UPDATE payslips SET
    basic_pay_minor                          = $3,
    overtime_minor                           = $4,
    bonus_minor                              = $5,
    commission_minor                         = $6,
    allowance_minor                          = $7,
    absence_payments_minor                   = $8,
    holiday_pay_minor                        = $9,
    other_payments_minor                     = $10,
    pay_not_subject_to_tax_ni_minor          = $11,
    statutory_sick_pay_minor                 = $12,
    statutory_maternity_pay_minor            = $13,
    statutory_paternity_pay_minor            = $14,
    statutory_adoption_pay_minor             = $15,
    shared_parental_pay_minor                = $16,
    statutory_neonatal_care_pay_minor        = $17,
    statutory_parental_bereavement_pay_minor = $18,
    payroll_giving_minor                     = $19,
    other_deductions_net_pay_minor           = $20,
    items_class1_nic_not_paye_minor          = $21,
    salary_sacrifice_deductions_minor        = $22,
    tax_code                                 = $23,
    ni_category_letter                       = $24,
    nic_calculation                          = $25,
    week1_month1_basis                       = $26,
    student_loan_undergraduate               = $27,
    student_loan_postgraduate                = $28,
    hours_worked                             = $29,
    comment                                  = $30,
    updated_at                               = now()
WHERE id = $1
  AND organisation_id = $2
RETURNING id, organisation_id, pay_run_id, user_id, tax_code, ni_category_letter, nic_calculation, week1_month1_basis, student_loan_undergraduate, student_loan_postgraduate, basic_pay_minor, overtime_minor, bonus_minor, commission_minor, allowance_minor, absence_payments_minor, holiday_pay_minor, other_payments_minor, pay_not_subject_to_tax_ni_minor, statutory_sick_pay_minor, statutory_maternity_pay_minor, statutory_paternity_pay_minor, statutory_adoption_pay_minor, shared_parental_pay_minor, statutory_neonatal_care_pay_minor, statutory_parental_bereavement_pay_minor, payroll_giving_minor, other_deductions_net_pay_minor, items_class1_nic_not_paye_minor, salary_sacrifice_deductions_minor, gross_pay_minor, taxable_pay_minor, niable_pay_minor, tax_deducted_minor, employee_ni_minor, employer_ni_minor, employee_pension_minor, employer_pension_minor, student_loan_minor, net_pay_minor, hours_worked, comment, leaving_payslip, created_at, updated_at
`

type UpdatePayslipInputsParams struct {
	ID                                   uuid.UUID      `json:"id"`
	OrganisationID                       uuid.UUID      `json:"organisation_id"`
	BasicPayMinor                        int64          `json:"basic_pay_minor"`
	OvertimeMinor                        int64          `json:"overtime_minor"`
	BonusMinor                           int64          `json:"bonus_minor"`
	CommissionMinor                      int64          `json:"commission_minor"`
	AllowanceMinor                       int64          `json:"allowance_minor"`
	AbsencePaymentsMinor                 int64          `json:"absence_payments_minor"`
	HolidayPayMinor                      int64          `json:"holiday_pay_minor"`
	OtherPaymentsMinor                   int64          `json:"other_payments_minor"`
	PayNotSubjectToTaxNiMinor            int64          `json:"pay_not_subject_to_tax_ni_minor"`
	StatutorySickPayMinor                int64          `json:"statutory_sick_pay_minor"`
	StatutoryMaternityPayMinor           int64          `json:"statutory_maternity_pay_minor"`
	StatutoryPaternityPayMinor           int64          `json:"statutory_paternity_pay_minor"`
	StatutoryAdoptionPayMinor            int64          `json:"statutory_adoption_pay_minor"`
	SharedParentalPayMinor               int64          `json:"shared_parental_pay_minor"`
	StatutoryNeonatalCarePayMinor        int64          `json:"statutory_neonatal_care_pay_minor"`
	StatutoryParentalBereavementPayMinor int64          `json:"statutory_parental_bereavement_pay_minor"`
	PayrollGivingMinor                   int64          `json:"payroll_giving_minor"`
	OtherDeductionsNetPayMinor           int64          `json:"other_deductions_net_pay_minor"`
	ItemsClass1NicNotPayeMinor           int64          `json:"items_class1_nic_not_paye_minor"`
	SalarySacrificeDeductionsMinor       int64          `json:"salary_sacrifice_deductions_minor"`
	TaxCode                              pgtype.Text    `json:"tax_code"`
	NiCategoryLetter                     string         `json:"ni_category_letter"`
	NicCalculation                       string         `json:"nic_calculation"`
	Week1Month1Basis                     bool           `json:"week1_month1_basis"`
	StudentLoanUndergraduate             bool           `json:"student_loan_undergraduate"`
	StudentLoanPostgraduate              bool           `json:"student_loan_postgraduate"`
	HoursWorked                          pgtype.Numeric `json:"hours_worked"`
	Comment                              pgtype.Text    `json:"comment"`
}

// Apply the editable inputs from the Edit Payslip screen (the snapshot config and
// the computed columns are written separately).
func (q *Queries) UpdatePayslipInputs(ctx context.Context, arg UpdatePayslipInputsParams) (Payslip, error) {
	row := q.db.QueryRow(ctx, updatePayslipInputs,
		arg.ID,
		arg.OrganisationID,
		arg.BasicPayMinor,
		arg.OvertimeMinor,
		arg.BonusMinor,
		arg.CommissionMinor,
		arg.AllowanceMinor,
		arg.AbsencePaymentsMinor,
		arg.HolidayPayMinor,
		arg.OtherPaymentsMinor,
		arg.PayNotSubjectToTaxNiMinor,
		arg.StatutorySickPayMinor,
		arg.StatutoryMaternityPayMinor,
		arg.StatutoryPaternityPayMinor,
		arg.StatutoryAdoptionPayMinor,
		arg.SharedParentalPayMinor,
		arg.StatutoryNeonatalCarePayMinor,
		arg.StatutoryParentalBereavementPayMinor,
		arg.PayrollGivingMinor,
		arg.OtherDeductionsNetPayMinor,
		arg.ItemsClass1NicNotPayeMinor,
		arg.SalarySacrificeDeductionsMinor,
		arg.TaxCode,
		arg.NiCategoryLetter,
		arg.NicCalculation,
		arg.Week1Month1Basis,
		arg.StudentLoanUndergraduate,
		arg.StudentLoanPostgraduate,
		arg.HoursWorked,
		arg.Comment,
	)
	var i Payslip
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.PayRunID,
		&i.UserID,
		&i.TaxCode,
		&i.NiCategoryLetter,
		&i.NicCalculation,
		&i.Week1Month1Basis,
		&i.StudentLoanUndergraduate,
		&i.StudentLoanPostgraduate,
		&i.BasicPayMinor,
		&i.OvertimeMinor,
		&i.BonusMinor,
		&i.CommissionMinor,
		&i.AllowanceMinor,
		&i.AbsencePaymentsMinor,
		&i.HolidayPayMinor,
		&i.OtherPaymentsMinor,
		&i.PayNotSubjectToTaxNiMinor,
		&i.StatutorySickPayMinor,
		&i.StatutoryMaternityPayMinor,
		&i.StatutoryPaternityPayMinor,
		&i.StatutoryAdoptionPayMinor,
		&i.SharedParentalPayMinor,
		&i.StatutoryNeonatalCarePayMinor,
		&i.StatutoryParentalBereavementPayMinor,
		&i.PayrollGivingMinor,
		&i.OtherDeductionsNetPayMinor,
		&i.ItemsClass1NicNotPayeMinor,
		&i.SalarySacrificeDeductionsMinor,
		&i.GrossPayMinor,
		&i.TaxablePayMinor,
		&i.NiablePayMinor,
		&i.TaxDeductedMinor,
		&i.EmployeeNiMinor,
		&i.EmployerNiMinor,
		&i.EmployeePensionMinor,
		&i.EmployerPensionMinor,
		&i.StudentLoanMinor,
		&i.NetPayMinor,
		&i.HoursWorked,
		&i.Comment,
		&i.LeavingPayslip,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
