// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bills.sql

package bills

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const contactHasBills = `-- name: ContactHasBills :one
SELECT EXISTS (
    SELECT 1 FROM bills
    WHERE contact_id      = $1   -- contact UUID
      AND organisation_id = $2   -- tenant scope — never skip this
      AND deleted_at IS NULL
) AS has_bills
`

type ContactHasBillsParams struct {
	ContactID      uuid.UUID `json:"contact_id"`
	OrganisationID uuid.UUID `json:"organisation_id"`
}

// -----------------------------------------------------------------------------
// ContactHasBills
// "Is this contact referenced by any live bill?" — the cross-domain check the
// contacts module's delete guard needs (a soft-deleted contact must not strand
// bills). Mirrors projects.ContactHasProjects / invoices.ContactHasInvoices; the
// contacts service will inject the bills querier and OR this into its in-use
// check (wiring deferred to the service increment — this is the datalayer half).
// -----------------------------------------------------------------------------
func (q *Queries) ContactHasBills(ctx context.Context, arg ContactHasBillsParams) (bool, error) {
	row := q.db.QueryRow(ctx, contactHasBills, arg.ContactID, arg.OrganisationID)
	var has_bills bool
	err := row.Scan(&has_bills)
	return has_bills, err
}

const countBillAttachments = `-- name: CountBillAttachments :one
SELECT count(*) FROM bill_attachments
WHERE bill_id = $1
`

// -----------------------------------------------------------------------------
// CountBillAttachments
// How many files a bill already has. The service calls this when a new file is
// uploaded: if the count is 0, this upload is the FIRST and becomes the primary
// (default) attachment. Scoped by bill_id only — the caller has already been
// authorised against the parent bill's organisation.
// -----------------------------------------------------------------------------
func (q *Queries) CountBillAttachments(ctx context.Context, billID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countBillAttachments, billID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBill = `-- name: CreateBill :one



INSERT INTO bills (
    organisation_id,
    created_by_user_id,
    contact_id,
    reference,
    dated_on,
    due_on,
    currency,
    comments,
    is_hire_purchase,
    category_id,
    vat_rate_id,
    vat_rate_bps,
    net_value_minor,
    sales_tax_value_minor,
    total_value_minor,
    project_id
) VALUES (
    $1,   -- organisation_id       UUID (tenant that owns the bill)
    $2,   -- created_by_user_id    UUID (audit)
    $3,   -- contact_id            UUID (the supplier)
    $4,   -- reference             VARCHAR (supplier's invoice number)
    $5,   -- dated_on              DATE ("Bill Date")
    $6,   -- due_on                DATE ("Due On", nullable)
    $7,   -- currency              CHAR(3) e.g. 'GBP'
    $8,   -- comments              TEXT (nullable)
    $9,   -- is_hire_purchase      BOOLEAN
    $10,  -- category_id           UUID (CoA spending account)
    $11,  -- vat_rate_id           UUID (nullable — the picked vat_rates row)
    $12,  -- vat_rate_bps          INTEGER (nullable — rate snapshot in bps)
    $13,  -- net_value_minor       BIGINT (ex-VAT, pence)
    $14,  -- sales_tax_value_minor BIGINT (VAT, pence)
    $15,  -- total_value_minor     BIGINT (gross, pence)
    $16   -- project_id            UUID (nullable "Link to Project")
)
RETURNING id, organisation_id, created_by_user_id, contact_id, reference, dated_on, due_on, currency, comments, is_hire_purchase, category_id, vat_rate_id, vat_rate_bps, net_value_minor, sales_tax_value_minor, total_value_minor, paid_value_minor, due_value_minor, project_id, deleted_at, created_at, updated_at
`

type CreateBillParams struct {
	OrganisationID     uuid.UUID   `json:"organisation_id"`
	CreatedByUserID    uuid.UUID   `json:"created_by_user_id"`
	ContactID          uuid.UUID   `json:"contact_id"`
	Reference          pgtype.Text `json:"reference"`
	DatedOn            pgtype.Date `json:"dated_on"`
	DueOn              pgtype.Date `json:"due_on"`
	Currency           string      `json:"currency"`
	Comments           pgtype.Text `json:"comments"`
	IsHirePurchase     bool        `json:"is_hire_purchase"`
	CategoryID         uuid.UUID   `json:"category_id"`
	VatRateID          pgtype.UUID `json:"vat_rate_id"`
	VatRateBps         pgtype.Int4 `json:"vat_rate_bps"`
	NetValueMinor      int64       `json:"net_value_minor"`
	SalesTaxValueMinor int64       `json:"sales_tax_value_minor"`
	TotalValueMinor    int64       `json:"total_value_minor"`
	ProjectID          pgtype.UUID `json:"project_id"`
}

// =============================================================================
// BILLS MODULE — SQLC QUERIES
// File: db/queries/bills.sql
//
// Type-safe Go for the bills + bill_attachments tables defined in
// db/schema/bills_schema.sql. Generated by a DEDICATED sqlc block (see sqlc.yaml)
// into package `bills` at db/bills — separate from the other domain packages so
// types don't bleed across modules.
//
// Annotation / parameter syntax is identical to the other query files:
//
//	-- name: FuncName :one|:many|:exec
//	$1, $2 ...  positional params, typed from the schema columns.
//
// Every query is ORGANISATION-SCOPED (multi-tenancy) and, on the header,
// SOFT-DELETE-AWARE (deleted_at IS NULL). organisation_id / created_by_user_id
// come from the authenticated token in the (future) service layer, never from the
// request body.
//
// There is no status lifecycle: a bill is editable/deletable while UNPAID. The PAID
// value is mutated only by its own dedicated query (UpdateBillPaidValue — the banking
// reconciliation seam), NOT by UpdateBill, so a field edit can't clobber the payment.
// =============================================================================
// =============================================================================
// BILL  (the record — header + single spending line)
// =============================================================================
// -----------------------------------------------------------------------------
// CreateBill  (the "setter")
// Inserts a bill and returns the full row via RETURNING * (so the caller gets the
// generated id, defaults and the computed due_value_minor without a second
// round-trip). The single spending line is flat on the row: category_id +
// vat_rate_id/vat_rate_bps + the net/sales_tax/total the service computed.
// paid_value_minor defaults to 0 (written later by banking), so it isn't supplied here.
// -----------------------------------------------------------------------------
func (q *Queries) CreateBill(ctx context.Context, arg CreateBillParams) (Bill, error) {
	row := q.db.QueryRow(ctx, createBill,
		arg.OrganisationID,
		arg.CreatedByUserID,
		arg.ContactID,
		arg.Reference,
		arg.DatedOn,
		arg.DueOn,
		arg.Currency,
		arg.Comments,
		arg.IsHirePurchase,
		arg.CategoryID,
		arg.VatRateID,
		arg.VatRateBps,
		arg.NetValueMinor,
		arg.SalesTaxValueMinor,
		arg.TotalValueMinor,
		arg.ProjectID,
	)
	var i Bill
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.CreatedByUserID,
		&i.ContactID,
		&i.Reference,
		&i.DatedOn,
		&i.DueOn,
		&i.Currency,
		&i.Comments,
		&i.IsHirePurchase,
		&i.CategoryID,
		&i.VatRateID,
		&i.VatRateBps,
		&i.NetValueMinor,
		&i.SalesTaxValueMinor,
		&i.TotalValueMinor,
		&i.PaidValueMinor,
		&i.DueValueMinor,
		&i.ProjectID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createBillAttachment = `-- name: CreateBillAttachment :one

INSERT INTO bill_attachments (
    bill_id,
    organisation_id,
    file_name,
    content_type,
    file_size_bytes,
    storage_path,
    storage_bucket,
    description,
    is_primary,
    uploaded_by_user_id,
    content_hash
) VALUES (
    $1,   -- bill_id              UUID
    $2,   -- organisation_id      UUID
    $3,   -- file_name            VARCHAR e.g. 'supplier_invoice.pdf'
    $4,   -- content_type         VARCHAR e.g. 'application/pdf'
    $5,   -- file_size_bytes      INTEGER
    $6,   -- storage_path         TEXT e.g. 'orgs/abc123/bills/xyz/invoice.pdf'
    $7,   -- storage_bucket       VARCHAR e.g. 'myapp-bill-documents-prod'
    $8,   -- description          TEXT (nullable — user label for this file)
    $9,   -- is_primary           BOOLEAN
    $10,  -- uploaded_by_user_id  UUID
    $11   -- content_hash         VARCHAR (nullable — hex SHA-256 of the file bytes)
)
RETURNING id, bill_id, organisation_id, file_name, content_type, file_size_bytes, content_hash, storage_path, storage_bucket, description, is_primary, ocr_status, ocr_raw_text, ocr_extracted_data, ocr_processed_at, uploaded_by_user_id, created_at, updated_at
`

type CreateBillAttachmentParams struct {
	BillID           uuid.UUID   `json:"bill_id"`
	OrganisationID   uuid.UUID   `json:"organisation_id"`
	FileName         string      `json:"file_name"`
	ContentType      string      `json:"content_type"`
	FileSizeBytes    int32       `json:"file_size_bytes"`
	StoragePath      string      `json:"storage_path"`
	StorageBucket    string      `json:"storage_bucket"`
	Description      pgtype.Text `json:"description"`
	IsPrimary        bool        `json:"is_primary"`
	UploadedByUserID uuid.UUID   `json:"uploaded_by_user_id"`
	ContentHash      pgtype.Text `json:"content_hash"`
}

// =============================================================================
// BILL ATTACHMENTS
// Clone of the expense_attachments query set, scoped to bills. The bytes live in
// GCS; these rows are the metadata. The GCS upload / OCR WIRING is deferred — but
// the queries exist so the future bill attachment + Smart-Capture service can use
// them unchanged.
// =============================================================================
// -----------------------------------------------------------------------------
// CreateBillAttachment
// Records metadata for an uploaded file. The actual file has already been written
// to GCS by the time this is called. storage_path is the GCS object key — never a
// signed URL (those are generated on demand, not stored).
// -----------------------------------------------------------------------------
func (q *Queries) CreateBillAttachment(ctx context.Context, arg CreateBillAttachmentParams) (BillAttachment, error) {
	row := q.db.QueryRow(ctx, createBillAttachment,
		arg.BillID,
		arg.OrganisationID,
		arg.FileName,
		arg.ContentType,
		arg.FileSizeBytes,
		arg.StoragePath,
		arg.StorageBucket,
		arg.Description,
		arg.IsPrimary,
		arg.UploadedByUserID,
		arg.ContentHash,
	)
	var i BillAttachment
	err := row.Scan(
		&i.ID,
		&i.BillID,
		&i.OrganisationID,
		&i.FileName,
		&i.ContentType,
		&i.FileSizeBytes,
		&i.ContentHash,
		&i.StoragePath,
		&i.StorageBucket,
		&i.Description,
		&i.IsPrimary,
		&i.OcrStatus,
		&i.OcrRawText,
		&i.OcrExtractedData,
		&i.OcrProcessedAt,
		&i.UploadedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBillAttachment = `-- name: DeleteBillAttachment :exec
DELETE FROM bill_attachments
WHERE id              = $1
  AND organisation_id = $2
`

type DeleteBillAttachmentParams struct {
	ID             uuid.UUID `json:"id"`
	OrganisationID uuid.UUID `json:"organisation_id"`
}

// -----------------------------------------------------------------------------
// DeleteBillAttachment
// Hard delete — attachments can be genuinely removed (they're supporting
// documents, not financial records themselves). The file in GCS must be deleted
// separately by the application layer after this succeeds. :exec returns only an
// error.
// -----------------------------------------------------------------------------
func (q *Queries) DeleteBillAttachment(ctx context.Context, arg DeleteBillAttachmentParams) error {
	_, err := q.db.Exec(ctx, deleteBillAttachment, arg.ID, arg.OrganisationID)
	return err
}

const findDuplicateBillReceipt = `-- name: FindDuplicateBillReceipt :one
SELECT a.bill_id
FROM bill_attachments a
JOIN bills b ON b.id = a.bill_id
WHERE a.organisation_id = $1
  AND a.content_hash    = $2
  AND b.deleted_at IS NULL
LIMIT 1
`

type FindDuplicateBillReceiptParams struct {
	OrganisationID uuid.UUID   `json:"organisation_id"`
	ContentHash    pgtype.Text `json:"content_hash"`
}

// -----------------------------------------------------------------------------
// FindDuplicateBillReceipt
// Content-level dedupe: is there already a NON-DELETED bill in this org whose
// attachment has the identical content hash? Returns that bill's id if so (the
// caller then skips re-capturing the same file). A bill has no claimant, so —
// unlike the expense version — this is scoped by organisation only. Hits
// idx_bill_attachments_content_hash.
// -----------------------------------------------------------------------------
func (q *Queries) FindDuplicateBillReceipt(ctx context.Context, arg FindDuplicateBillReceiptParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, findDuplicateBillReceipt, arg.OrganisationID, arg.ContentHash)
	var bill_id uuid.UUID
	err := row.Scan(&bill_id)
	return bill_id, err
}

const getBill = `-- name: GetBill :one
SELECT id, organisation_id, created_by_user_id, contact_id, reference, dated_on, due_on, currency, comments, is_hire_purchase, category_id, vat_rate_id, vat_rate_bps, net_value_minor, sales_tax_value_minor, total_value_minor, paid_value_minor, due_value_minor, project_id, deleted_at, created_at, updated_at FROM bills
WHERE id              = $1   -- bill UUID
  AND organisation_id = $2   -- tenant scope — never skip this
  AND deleted_at IS NULL
`

type GetBillParams struct {
	ID             uuid.UUID `json:"id"`
	OrganisationID uuid.UUID `json:"organisation_id"`
}

// -----------------------------------------------------------------------------
// GetBill  (the "getter")
// Fetch a single bill by id, scoped to the organisation. We ALWAYS scope by
// organisation_id — never fetch by id alone — so one tenant can't read another's
// bill if an id leaks. deleted_at IS NULL hides soft-deleted rows.
// -----------------------------------------------------------------------------
func (q *Queries) GetBill(ctx context.Context, arg GetBillParams) (Bill, error) {
	row := q.db.QueryRow(ctx, getBill, arg.ID, arg.OrganisationID)
	var i Bill
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.CreatedByUserID,
		&i.ContactID,
		&i.Reference,
		&i.DatedOn,
		&i.DueOn,
		&i.Currency,
		&i.Comments,
		&i.IsHirePurchase,
		&i.CategoryID,
		&i.VatRateID,
		&i.VatRateBps,
		&i.NetValueMinor,
		&i.SalesTaxValueMinor,
		&i.TotalValueMinor,
		&i.PaidValueMinor,
		&i.DueValueMinor,
		&i.ProjectID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBillAttachment = `-- name: GetBillAttachment :one
SELECT id, bill_id, organisation_id, file_name, content_type, file_size_bytes, content_hash, storage_path, storage_bucket, description, is_primary, ocr_status, ocr_raw_text, ocr_extracted_data, ocr_processed_at, uploaded_by_user_id, created_at, updated_at FROM bill_attachments
WHERE id              = $1
  AND organisation_id = $2
`

type GetBillAttachmentParams struct {
	ID             uuid.UUID `json:"id"`
	OrganisationID uuid.UUID `json:"organisation_id"`
}

// -----------------------------------------------------------------------------
// GetBillAttachment
// Single attachment by id — used when generating a signed download URL. Scoped by
// organisation_id to prevent cross-tenant access.
// -----------------------------------------------------------------------------
func (q *Queries) GetBillAttachment(ctx context.Context, arg GetBillAttachmentParams) (BillAttachment, error) {
	row := q.db.QueryRow(ctx, getBillAttachment, arg.ID, arg.OrganisationID)
	var i BillAttachment
	err := row.Scan(
		&i.ID,
		&i.BillID,
		&i.OrganisationID,
		&i.FileName,
		&i.ContentType,
		&i.FileSizeBytes,
		&i.ContentHash,
		&i.StoragePath,
		&i.StorageBucket,
		&i.Description,
		&i.IsPrimary,
		&i.OcrStatus,
		&i.OcrRawText,
		&i.OcrExtractedData,
		&i.OcrProcessedAt,
		&i.UploadedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBillAttachments = `-- name: ListBillAttachments :many
SELECT id, bill_id, organisation_id, file_name, content_type, file_size_bytes, content_hash, storage_path, storage_bucket, description, is_primary, ocr_status, ocr_raw_text, ocr_extracted_data, ocr_processed_at, uploaded_by_user_id, created_at, updated_at FROM bill_attachments
WHERE bill_id = $1
ORDER BY is_primary DESC, created_at ASC
`

// -----------------------------------------------------------------------------
// ListBillAttachments
// All attachments for one bill, primary file first. The UI shows them in this
// order (is_primary DESC: TRUE sorts before FALSE, so primary comes first).
// -----------------------------------------------------------------------------
func (q *Queries) ListBillAttachments(ctx context.Context, billID uuid.UUID) ([]BillAttachment, error) {
	rows, err := q.db.Query(ctx, listBillAttachments, billID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BillAttachment
	for rows.Next() {
		var i BillAttachment
		if err := rows.Scan(
			&i.ID,
			&i.BillID,
			&i.OrganisationID,
			&i.FileName,
			&i.ContentType,
			&i.FileSizeBytes,
			&i.ContentHash,
			&i.StoragePath,
			&i.StorageBucket,
			&i.Description,
			&i.IsPrimary,
			&i.OcrStatus,
			&i.OcrRawText,
			&i.OcrExtractedData,
			&i.OcrProcessedAt,
			&i.UploadedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBillCategories = `-- name: ListBillCategories :many
SELECT id, nominal_code, name, account_type, api_group, default_vat
FROM categories
WHERE organisation_id = $1
  AND is_active
  AND is_system_managed = FALSE
  AND account_type IN ('COST_OF_SALES','ADMIN_EXPENSE','CAPITAL_ASSET')
ORDER BY account_type, nominal_code
`

type ListBillCategoriesRow struct {
	ID          uuid.UUID   `json:"id"`
	NominalCode string      `json:"nominal_code"`
	Name        string      `json:"name"`
	AccountType string      `json:"account_type"`
	ApiGroup    pgtype.Text `json:"api_group"`
	DefaultVat  pgtype.Text `json:"default_vat"`
}

// -----------------------------------------------------------------------------
// ListBillCategories
// The "Spending Category" picker. The bill's category_id is a CoA (categories)
// account, but a bill may only post to a SPENDING account — so we return just the
// subset the expense form offers: cost of sales, admin expenses and capital
// assets. Income / balance-sheet / system-managed accounts are excluded. Selects
// default_vat so the service can resolve the form's "Auto" VAT rate from the
// chosen category. Org-scoped, active rows only.
// (The exact account_type set is intended to match what the expense form lists;
//
//	revisit if/when expense_categories and categories are unified — see BACKLOG.)
//
// -----------------------------------------------------------------------------
func (q *Queries) ListBillCategories(ctx context.Context, organisationID uuid.UUID) ([]ListBillCategoriesRow, error) {
	rows, err := q.db.Query(ctx, listBillCategories, organisationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBillCategoriesRow
	for rows.Next() {
		var i ListBillCategoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.NominalCode,
			&i.Name,
			&i.AccountType,
			&i.ApiGroup,
			&i.DefaultVat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBills = `-- name: ListBills :many


SELECT id, organisation_id, created_by_user_id, contact_id, reference, dated_on, due_on, currency, comments, is_hire_purchase, category_id, vat_rate_id, vat_rate_bps, net_value_minor, sales_tax_value_minor, total_value_minor, paid_value_minor, due_value_minor, project_id, deleted_at, created_at, updated_at FROM bills
WHERE organisation_id = $1
  AND deleted_at IS NULL
ORDER BY dated_on DESC, created_at DESC
`

// soft delete filter
// -----------------------------------------------------------------------------
// ListBills  (the "list")
// All live bills for an organisation, newest first, for the bills list page.
// -----------------------------------------------------------------------------
func (q *Queries) ListBills(ctx context.Context, organisationID uuid.UUID) ([]Bill, error) {
	rows, err := q.db.Query(ctx, listBills, organisationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bill
	for rows.Next() {
		var i Bill
		if err := rows.Scan(
			&i.ID,
			&i.OrganisationID,
			&i.CreatedByUserID,
			&i.ContactID,
			&i.Reference,
			&i.DatedOn,
			&i.DueOn,
			&i.Currency,
			&i.Comments,
			&i.IsHirePurchase,
			&i.CategoryID,
			&i.VatRateID,
			&i.VatRateBps,
			&i.NetValueMinor,
			&i.SalesTaxValueMinor,
			&i.TotalValueMinor,
			&i.PaidValueMinor,
			&i.DueValueMinor,
			&i.ProjectID,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBillsByContact = `-- name: ListBillsByContact :many
SELECT id, organisation_id, created_by_user_id, contact_id, reference, dated_on, due_on, currency, comments, is_hire_purchase, category_id, vat_rate_id, vat_rate_bps, net_value_minor, sales_tax_value_minor, total_value_minor, paid_value_minor, due_value_minor, project_id, deleted_at, created_at, updated_at FROM bills
WHERE organisation_id = $1
  AND contact_id      = $2
  AND deleted_at IS NULL
ORDER BY dated_on DESC, created_at DESC
`

type ListBillsByContactParams struct {
	OrganisationID uuid.UUID `json:"organisation_id"`
	ContactID      uuid.UUID `json:"contact_id"`
}

// -----------------------------------------------------------------------------
// ListBillsByContact
// The live bills owed to one supplier (e.g. the contact detail page). Backed by
// idx_bills_org_contact.
// -----------------------------------------------------------------------------
func (q *Queries) ListBillsByContact(ctx context.Context, arg ListBillsByContactParams) ([]Bill, error) {
	rows, err := q.db.Query(ctx, listBillsByContact, arg.OrganisationID, arg.ContactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bill
	for rows.Next() {
		var i Bill
		if err := rows.Scan(
			&i.ID,
			&i.OrganisationID,
			&i.CreatedByUserID,
			&i.ContactID,
			&i.Reference,
			&i.DatedOn,
			&i.DueOn,
			&i.Currency,
			&i.Comments,
			&i.IsHirePurchase,
			&i.CategoryID,
			&i.VatRateID,
			&i.VatRateBps,
			&i.NetValueMinor,
			&i.SalesTaxValueMinor,
			&i.TotalValueMinor,
			&i.PaidValueMinor,
			&i.DueValueMinor,
			&i.ProjectID,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOutstandingBills = `-- name: ListOutstandingBills :many
SELECT id, organisation_id, created_by_user_id, contact_id, reference, dated_on, due_on, currency, comments, is_hire_purchase, category_id, vat_rate_id, vat_rate_bps, net_value_minor, sales_tax_value_minor, total_value_minor, paid_value_minor, due_value_minor, project_id, deleted_at, created_at, updated_at FROM bills
WHERE organisation_id = $1
  AND due_value_minor > 0
  AND deleted_at IS NULL
ORDER BY dated_on ASC, created_at ASC
`

// -----------------------------------------------------------------------------
// ListOutstandingBills
// The org's bills that still owe money (due_value_minor > 0 = total − paid). Backs
// the banking "Bill Payment" explanation picker. Unlike invoices there is NO status
// filter — bills have no lifecycle; any unpaid/part-paid bill is payable. Oldest
// first (the natural "pay these next" order). :many.
// -----------------------------------------------------------------------------
func (q *Queries) ListOutstandingBills(ctx context.Context, organisationID uuid.UUID) ([]Bill, error) {
	rows, err := q.db.Query(ctx, listOutstandingBills, organisationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bill
	for rows.Next() {
		var i Bill
		if err := rows.Scan(
			&i.ID,
			&i.OrganisationID,
			&i.CreatedByUserID,
			&i.ContactID,
			&i.Reference,
			&i.DatedOn,
			&i.DueOn,
			&i.Currency,
			&i.Comments,
			&i.IsHirePurchase,
			&i.CategoryID,
			&i.VatRateID,
			&i.VatRateBps,
			&i.NetValueMinor,
			&i.SalesTaxValueMinor,
			&i.TotalValueMinor,
			&i.PaidValueMinor,
			&i.DueValueMinor,
			&i.ProjectID,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markBillAttachmentOCRProcessing = `-- name: MarkBillAttachmentOCRProcessing :exec
UPDATE bill_attachments SET
    ocr_status = 'PROCESSING',
    updated_at = now()
WHERE id              = $1
  AND organisation_id = $2
`

type MarkBillAttachmentOCRProcessingParams struct {
	ID             uuid.UUID `json:"id"`
	OrganisationID uuid.UUID `json:"organisation_id"`
}

// -----------------------------------------------------------------------------
// MarkBillAttachmentOCRProcessing
// Flips an attachment from PENDING to PROCESSING when the OCR worker picks it up.
// Deliberately separate from UpdateBillAttachmentOCRStatus: a non-terminal
// transition, so it does NOT set ocr_processed_at. Org-scoped like every write.
// -----------------------------------------------------------------------------
func (q *Queries) MarkBillAttachmentOCRProcessing(ctx context.Context, arg MarkBillAttachmentOCRProcessingParams) error {
	_, err := q.db.Exec(ctx, markBillAttachmentOCRProcessing, arg.ID, arg.OrganisationID)
	return err
}

const setBillAttachmentPrimary = `-- name: SetBillAttachmentPrimary :exec
UPDATE bill_attachments SET
    is_primary = TRUE,
    updated_at = now()
WHERE id              = $1
  AND organisation_id = $2
`

type SetBillAttachmentPrimaryParams struct {
	ID             uuid.UUID `json:"id"`
	OrganisationID uuid.UUID `json:"organisation_id"`
}

// -----------------------------------------------------------------------------
// SetBillAttachmentPrimary
// Marks a single attachment as the primary one for its bill. Pair it with
// UnsetBillPrimary inside one transaction so the "exactly one primary" invariant
// holds. organisation_id prevents cross-tenant writes.
// -----------------------------------------------------------------------------
func (q *Queries) SetBillAttachmentPrimary(ctx context.Context, arg SetBillAttachmentPrimaryParams) error {
	_, err := q.db.Exec(ctx, setBillAttachmentPrimary, arg.ID, arg.OrganisationID)
	return err
}

const softDeleteBill = `-- name: SoftDeleteBill :exec
UPDATE bills SET
    deleted_at = now(),
    updated_at = now()
WHERE id              = $1
  AND organisation_id = $2
  AND deleted_at IS NULL
`

type SoftDeleteBillParams struct {
	ID             uuid.UUID `json:"id"`
	OrganisationID uuid.UUID `json:"organisation_id"`
}

// -----------------------------------------------------------------------------
// SoftDeleteBill  (the "delete")
// Sets deleted_at to mark the bill deleted (it stays in the DB for audit and so
// payments/history that reference it don't dangle). Mirrors SoftDeleteInvoice.
// :exec returns only an error. Idempotent — deleting an already-deleted bill
// matches no live row and is a no-op. Whether the bill's status ALLOWS deletion
// (e.g. DRAFT only) is a service-layer guard.
// -----------------------------------------------------------------------------
func (q *Queries) SoftDeleteBill(ctx context.Context, arg SoftDeleteBillParams) error {
	_, err := q.db.Exec(ctx, softDeleteBill, arg.ID, arg.OrganisationID)
	return err
}

const unsetBillPrimary = `-- name: UnsetBillPrimary :exec
UPDATE bill_attachments SET
    is_primary = FALSE,
    updated_at = now()
WHERE bill_id         = $1
  AND organisation_id = $2
  AND is_primary      = TRUE
`

type UnsetBillPrimaryParams struct {
	BillID         uuid.UUID `json:"bill_id"`
	OrganisationID uuid.UUID `json:"organisation_id"`
}

// -----------------------------------------------------------------------------
// UnsetBillPrimary
// Clears the primary flag on every attachment of a bill. Run inside a transaction
// immediately BEFORE SetBillAttachmentPrimary so exactly one row ends up flagged
// primary. organisation_id keeps the update tenant-scoped.
// -----------------------------------------------------------------------------
func (q *Queries) UnsetBillPrimary(ctx context.Context, arg UnsetBillPrimaryParams) error {
	_, err := q.db.Exec(ctx, unsetBillPrimary, arg.BillID, arg.OrganisationID)
	return err
}

const updateBill = `-- name: UpdateBill :one
UPDATE bills SET
    contact_id            = $3,
    reference             = $4,
    dated_on              = $5,
    due_on                = $6,
    currency              = $7,
    comments              = $8,
    is_hire_purchase      = $9,
    category_id           = $10,
    vat_rate_id           = $11,
    vat_rate_bps          = $12,
    net_value_minor       = $13,
    sales_tax_value_minor = $14,
    total_value_minor     = $15,
    project_id            = $16,
    updated_at            = now()
WHERE id              = $1   -- bill UUID
  AND organisation_id = $2   -- tenant scope
  AND deleted_at IS NULL     -- can't update a deleted bill
RETURNING id, organisation_id, created_by_user_id, contact_id, reference, dated_on, due_on, currency, comments, is_hire_purchase, category_id, vat_rate_id, vat_rate_bps, net_value_minor, sales_tax_value_minor, total_value_minor, paid_value_minor, due_value_minor, project_id, deleted_at, created_at, updated_at
`

type UpdateBillParams struct {
	ID                 uuid.UUID   `json:"id"`
	OrganisationID     uuid.UUID   `json:"organisation_id"`
	ContactID          uuid.UUID   `json:"contact_id"`
	Reference          pgtype.Text `json:"reference"`
	DatedOn            pgtype.Date `json:"dated_on"`
	DueOn              pgtype.Date `json:"due_on"`
	Currency           string      `json:"currency"`
	Comments           pgtype.Text `json:"comments"`
	IsHirePurchase     bool        `json:"is_hire_purchase"`
	CategoryID         uuid.UUID   `json:"category_id"`
	VatRateID          pgtype.UUID `json:"vat_rate_id"`
	VatRateBps         pgtype.Int4 `json:"vat_rate_bps"`
	NetValueMinor      int64       `json:"net_value_minor"`
	SalesTaxValueMinor int64       `json:"sales_tax_value_minor"`
	TotalValueMinor    int64       `json:"total_value_minor"`
	ProjectID          pgtype.UUID `json:"project_id"`
}

// -----------------------------------------------------------------------------
// UpdateBill  (the "update" — editable header + single-line body)
// Full update of the caller-editable fields (PUT semantics). Deliberately does
// NOT touch paid_value_minor (banking owns it) nor organisation_id /
// created_by_user_id. net/sales_tax/total ARE updated here because they are
// recomputed by the service from the (edited) single line on every save.
// updated_at is set explicitly in addition to the trigger (belt-and-suspenders).
// Whether a bill is editable (unpaid) is a service-layer guard.
// -----------------------------------------------------------------------------
func (q *Queries) UpdateBill(ctx context.Context, arg UpdateBillParams) (Bill, error) {
	row := q.db.QueryRow(ctx, updateBill,
		arg.ID,
		arg.OrganisationID,
		arg.ContactID,
		arg.Reference,
		arg.DatedOn,
		arg.DueOn,
		arg.Currency,
		arg.Comments,
		arg.IsHirePurchase,
		arg.CategoryID,
		arg.VatRateID,
		arg.VatRateBps,
		arg.NetValueMinor,
		arg.SalesTaxValueMinor,
		arg.TotalValueMinor,
		arg.ProjectID,
	)
	var i Bill
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.CreatedByUserID,
		&i.ContactID,
		&i.Reference,
		&i.DatedOn,
		&i.DueOn,
		&i.Currency,
		&i.Comments,
		&i.IsHirePurchase,
		&i.CategoryID,
		&i.VatRateID,
		&i.VatRateBps,
		&i.NetValueMinor,
		&i.SalesTaxValueMinor,
		&i.TotalValueMinor,
		&i.PaidValueMinor,
		&i.DueValueMinor,
		&i.ProjectID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBillAttachmentOCRStatus = `-- name: UpdateBillAttachmentOCRStatus :one
UPDATE bill_attachments SET
    ocr_status         = $3,   -- 'COMPLETE'|'FAILED'|'SKIPPED'
    ocr_raw_text       = $4,   -- full text from OCR engine (nullable)
    ocr_extracted_data = $5,   -- JSONB structured fields (nullable)
    ocr_processed_at   = now(),
    updated_at         = now()
WHERE id              = $1
  AND organisation_id = $2     -- tenant scope — never skip this
RETURNING id, bill_id, organisation_id, file_name, content_type, file_size_bytes, content_hash, storage_path, storage_bucket, description, is_primary, ocr_status, ocr_raw_text, ocr_extracted_data, ocr_processed_at, uploaded_by_user_id, created_at, updated_at
`

type UpdateBillAttachmentOCRStatusParams struct {
	ID               uuid.UUID   `json:"id"`
	OrganisationID   uuid.UUID   `json:"organisation_id"`
	OcrStatus        string      `json:"ocr_status"`
	OcrRawText       pgtype.Text `json:"ocr_raw_text"`
	OcrExtractedData []byte      `json:"ocr_extracted_data"`
}

// -----------------------------------------------------------------------------
// UpdateBillAttachmentOCRStatus
// Records a TERMINAL OCR result (COMPLETE / FAILED / SKIPPED) on an attachment.
// ocr_extracted_data is JSONB — in Go a []byte the service marshals from its
// extraction result. ocr_processed_at is stamped now() because the attachment has
// reached a terminal OCR state. Org-scoped as defence in depth. For the
// PENDING→PROCESSING transition use MarkBillAttachmentOCRProcessing instead, which
// deliberately does NOT stamp ocr_processed_at.
// -----------------------------------------------------------------------------
func (q *Queries) UpdateBillAttachmentOCRStatus(ctx context.Context, arg UpdateBillAttachmentOCRStatusParams) (BillAttachment, error) {
	row := q.db.QueryRow(ctx, updateBillAttachmentOCRStatus,
		arg.ID,
		arg.OrganisationID,
		arg.OcrStatus,
		arg.OcrRawText,
		arg.OcrExtractedData,
	)
	var i BillAttachment
	err := row.Scan(
		&i.ID,
		&i.BillID,
		&i.OrganisationID,
		&i.FileName,
		&i.ContentType,
		&i.FileSizeBytes,
		&i.ContentHash,
		&i.StoragePath,
		&i.StorageBucket,
		&i.Description,
		&i.IsPrimary,
		&i.OcrStatus,
		&i.OcrRawText,
		&i.OcrExtractedData,
		&i.OcrProcessedAt,
		&i.UploadedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBillPaidValue = `-- name: UpdateBillPaidValue :one
UPDATE bills SET
    paid_value_minor = $3,
    updated_at       = now()
WHERE id              = $1
  AND organisation_id = $2
  AND deleted_at IS NULL
RETURNING id, organisation_id, created_by_user_id, contact_id, reference, dated_on, due_on, currency, comments, is_hire_purchase, category_id, vat_rate_id, vat_rate_bps, net_value_minor, sales_tax_value_minor, total_value_minor, paid_value_minor, due_value_minor, project_id, deleted_at, created_at, updated_at
`

type UpdateBillPaidValueParams struct {
	ID             uuid.UUID `json:"id"`
	OrganisationID uuid.UUID `json:"organisation_id"`
	PaidValueMinor int64     `json:"paid_value_minor"`
}

// -----------------------------------------------------------------------------
// UpdateBillPaidValue
// Sets the amount settled against the bill. This is the BANKING module's seam —
// reconciliation writes paid_value_minor here (the bills service never does).
// It drives the derived Unpaid/Part paid/Paid display + whether the bill is
// still editable/deletable, and due_value_minor recomputes from it automatically.
// -----------------------------------------------------------------------------
func (q *Queries) UpdateBillPaidValue(ctx context.Context, arg UpdateBillPaidValueParams) (Bill, error) {
	row := q.db.QueryRow(ctx, updateBillPaidValue, arg.ID, arg.OrganisationID, arg.PaidValueMinor)
	var i Bill
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.CreatedByUserID,
		&i.ContactID,
		&i.Reference,
		&i.DatedOn,
		&i.DueOn,
		&i.Currency,
		&i.Comments,
		&i.IsHirePurchase,
		&i.CategoryID,
		&i.VatRateID,
		&i.VatRateBps,
		&i.NetValueMinor,
		&i.SalesTaxValueMinor,
		&i.TotalValueMinor,
		&i.PaidValueMinor,
		&i.DueValueMinor,
		&i.ProjectID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
