// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package bills

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// -----------------------------------------------------------------------------
	// ContactHasBills
	// "Is this contact referenced by any live bill?" — the cross-domain check the
	// contacts module's delete guard needs (a soft-deleted contact must not strand
	// bills). Mirrors projects.ContactHasProjects / invoices.ContactHasInvoices; the
	// contacts service will inject the bills querier and OR this into its in-use
	// check (wiring deferred to the service increment — this is the datalayer half).
	// -----------------------------------------------------------------------------
	ContactHasBills(ctx context.Context, arg ContactHasBillsParams) (bool, error)
	// -----------------------------------------------------------------------------
	// CountBillAttachments
	// How many files a bill already has. The service calls this when a new file is
	// uploaded: if the count is 0, this upload is the FIRST and becomes the primary
	// (default) attachment. Scoped by bill_id only — the caller has already been
	// authorised against the parent bill's organisation.
	// -----------------------------------------------------------------------------
	CountBillAttachments(ctx context.Context, billID uuid.UUID) (int64, error)
	// =============================================================================
	// BILLS MODULE — SQLC QUERIES
	// File: db/queries/bills.sql
	//
	// Type-safe Go for the bills + bill_attachments tables defined in
	// db/schema/bills_schema.sql. Generated by a DEDICATED sqlc block (see sqlc.yaml)
	// into package `bills` at db/bills — separate from the other domain packages so
	// types don't bleed across modules.
	//
	// Annotation / parameter syntax is identical to the other query files:
	//   -- name: FuncName :one|:many|:exec
	//   $1, $2 ...  positional params, typed from the schema columns.
	//
	// Every query is ORGANISATION-SCOPED (multi-tenancy) and, on the header,
	// SOFT-DELETE-AWARE (deleted_at IS NULL). organisation_id / created_by_user_id
	// come from the authenticated token in the (future) service layer, never from the
	// request body.
	//
	// There is no status lifecycle: a bill is editable/deletable while UNPAID. The PAID
	// value is mutated only by its own dedicated query (UpdateBillPaidValue — the banking
	// reconciliation seam), NOT by UpdateBill, so a field edit can't clobber the payment.
	// =============================================================================
	// =============================================================================
	// BILL  (the record — header + single spending line)
	// =============================================================================
	// -----------------------------------------------------------------------------
	// CreateBill  (the "setter")
	// Inserts a bill and returns the full row via RETURNING * (so the caller gets the
	// generated id, defaults and the computed due_value_minor without a second
	// round-trip). The single spending line is flat on the row: category_id +
	// vat_rate_id/vat_rate_bps + the net/sales_tax/total the service computed.
	// paid_value_minor defaults to 0 (written later by banking), so it isn't supplied here.
	// -----------------------------------------------------------------------------
	CreateBill(ctx context.Context, arg CreateBillParams) (Bill, error)
	// =============================================================================
	// BILL ATTACHMENTS
	// Clone of the expense_attachments query set, scoped to bills. The bytes live in
	// GCS; these rows are the metadata. The GCS upload / OCR WIRING is deferred — but
	// the queries exist so the future bill attachment + Smart-Capture service can use
	// them unchanged.
	// =============================================================================
	// -----------------------------------------------------------------------------
	// CreateBillAttachment
	// Records metadata for an uploaded file. The actual file has already been written
	// to GCS by the time this is called. storage_path is the GCS object key — never a
	// signed URL (those are generated on demand, not stored).
	// -----------------------------------------------------------------------------
	CreateBillAttachment(ctx context.Context, arg CreateBillAttachmentParams) (BillAttachment, error)
	// -----------------------------------------------------------------------------
	// DeleteBillAttachment
	// Hard delete — attachments can be genuinely removed (they're supporting
	// documents, not financial records themselves). The file in GCS must be deleted
	// separately by the application layer after this succeeds. :exec returns only an
	// error.
	// -----------------------------------------------------------------------------
	DeleteBillAttachment(ctx context.Context, arg DeleteBillAttachmentParams) error
	// -----------------------------------------------------------------------------
	// FindDuplicateBillReceipt
	// Content-level dedupe: is there already a NON-DELETED bill in this org whose
	// attachment has the identical content hash? Returns that bill's id if so (the
	// caller then skips re-capturing the same file). A bill has no claimant, so —
	// unlike the expense version — this is scoped by organisation only. Hits
	// idx_bill_attachments_content_hash.
	// -----------------------------------------------------------------------------
	FindDuplicateBillReceipt(ctx context.Context, arg FindDuplicateBillReceiptParams) (uuid.UUID, error)
	// -----------------------------------------------------------------------------
	// GetBill  (the "getter")
	// Fetch a single bill by id, scoped to the organisation. We ALWAYS scope by
	// organisation_id — never fetch by id alone — so one tenant can't read another's
	// bill if an id leaks. deleted_at IS NULL hides soft-deleted rows.
	// -----------------------------------------------------------------------------
	GetBill(ctx context.Context, arg GetBillParams) (Bill, error)
	// -----------------------------------------------------------------------------
	// GetBillAttachment
	// Single attachment by id — used when generating a signed download URL. Scoped by
	// organisation_id to prevent cross-tenant access.
	// -----------------------------------------------------------------------------
	GetBillAttachment(ctx context.Context, arg GetBillAttachmentParams) (BillAttachment, error)
	// -----------------------------------------------------------------------------
	// ListBillAttachments
	// All attachments for one bill, primary file first. The UI shows them in this
	// order (is_primary DESC: TRUE sorts before FALSE, so primary comes first).
	// -----------------------------------------------------------------------------
	ListBillAttachments(ctx context.Context, billID uuid.UUID) ([]BillAttachment, error)
	// -----------------------------------------------------------------------------
	// ListBillCategories
	// The "Spending Category" picker. The bill's category_id is a CoA (categories)
	// account, but a bill may only post to a SPENDING account — so we return just the
	// subset the expense form offers: cost of sales, admin expenses and capital
	// assets. Income / balance-sheet / system-managed accounts are excluded. Selects
	// default_vat so the service can resolve the form's "Auto" VAT rate from the
	// chosen category. Org-scoped, active rows only.
	// (The exact account_type set is intended to match what the expense form lists;
	//  revisit if/when expense_categories and categories are unified — see BACKLOG.)
	// -----------------------------------------------------------------------------
	ListBillCategories(ctx context.Context, organisationID uuid.UUID) ([]ListBillCategoriesRow, error)
	// soft delete filter
	// -----------------------------------------------------------------------------
	// ListBills  (the "list")
	// All live bills for an organisation, newest first, for the bills list page.
	// -----------------------------------------------------------------------------
	ListBills(ctx context.Context, organisationID uuid.UUID) ([]Bill, error)
	// -----------------------------------------------------------------------------
	// ListBillsByContact
	// The live bills owed to one supplier (e.g. the contact detail page). Backed by
	// idx_bills_org_contact.
	// -----------------------------------------------------------------------------
	ListBillsByContact(ctx context.Context, arg ListBillsByContactParams) ([]Bill, error)
	// -----------------------------------------------------------------------------
	// ListOutstandingBills
	// The org's bills that still owe money (due_value_minor > 0 = total − paid). Backs
	// the banking "Bill Payment" explanation picker. Unlike invoices there is NO status
	// filter — bills have no lifecycle; any unpaid/part-paid bill is payable. Oldest
	// first (the natural "pay these next" order). :many.
	// -----------------------------------------------------------------------------
	ListOutstandingBills(ctx context.Context, organisationID uuid.UUID) ([]Bill, error)
	// -----------------------------------------------------------------------------
	// MarkBillAttachmentOCRProcessing
	// Flips an attachment from PENDING to PROCESSING when the OCR worker picks it up.
	// Deliberately separate from UpdateBillAttachmentOCRStatus: a non-terminal
	// transition, so it does NOT set ocr_processed_at. Org-scoped like every write.
	// -----------------------------------------------------------------------------
	MarkBillAttachmentOCRProcessing(ctx context.Context, arg MarkBillAttachmentOCRProcessingParams) error
	// -----------------------------------------------------------------------------
	// SetBillAttachmentPrimary
	// Marks a single attachment as the primary one for its bill. Pair it with
	// UnsetBillPrimary inside one transaction so the "exactly one primary" invariant
	// holds. organisation_id prevents cross-tenant writes.
	// -----------------------------------------------------------------------------
	SetBillAttachmentPrimary(ctx context.Context, arg SetBillAttachmentPrimaryParams) error
	// -----------------------------------------------------------------------------
	// SoftDeleteBill  (the "delete")
	// Sets deleted_at to mark the bill deleted (it stays in the DB for audit and so
	// payments/history that reference it don't dangle). Mirrors SoftDeleteInvoice.
	// :exec returns only an error. Idempotent — deleting an already-deleted bill
	// matches no live row and is a no-op. Whether the bill's status ALLOWS deletion
	// (e.g. DRAFT only) is a service-layer guard.
	// -----------------------------------------------------------------------------
	SoftDeleteBill(ctx context.Context, arg SoftDeleteBillParams) error
	// -----------------------------------------------------------------------------
	// UnsetBillPrimary
	// Clears the primary flag on every attachment of a bill. Run inside a transaction
	// immediately BEFORE SetBillAttachmentPrimary so exactly one row ends up flagged
	// primary. organisation_id keeps the update tenant-scoped.
	// -----------------------------------------------------------------------------
	UnsetBillPrimary(ctx context.Context, arg UnsetBillPrimaryParams) error
	// -----------------------------------------------------------------------------
	// UpdateBill  (the "update" — editable header + single-line body)
	// Full update of the caller-editable fields (PUT semantics). Deliberately does
	// NOT touch paid_value_minor (banking owns it) nor organisation_id /
	// created_by_user_id. net/sales_tax/total ARE updated here because they are
	// recomputed by the service from the (edited) single line on every save.
	// updated_at is set explicitly in addition to the trigger (belt-and-suspenders).
	// Whether a bill is editable (unpaid) is a service-layer guard.
	// -----------------------------------------------------------------------------
	UpdateBill(ctx context.Context, arg UpdateBillParams) (Bill, error)
	// -----------------------------------------------------------------------------
	// UpdateBillAttachmentOCRStatus
	// Records a TERMINAL OCR result (COMPLETE / FAILED / SKIPPED) on an attachment.
	// ocr_extracted_data is JSONB — in Go a []byte the service marshals from its
	// extraction result. ocr_processed_at is stamped now() because the attachment has
	// reached a terminal OCR state. Org-scoped as defence in depth. For the
	// PENDING→PROCESSING transition use MarkBillAttachmentOCRProcessing instead, which
	// deliberately does NOT stamp ocr_processed_at.
	// -----------------------------------------------------------------------------
	UpdateBillAttachmentOCRStatus(ctx context.Context, arg UpdateBillAttachmentOCRStatusParams) (BillAttachment, error)
	// -----------------------------------------------------------------------------
	// UpdateBillPaidValue
	// Sets the amount settled against the bill. This is the BANKING module's seam —
	// reconciliation writes paid_value_minor here (the bills service never does).
	// It drives the derived Unpaid/Part paid/Paid display + whether the bill is
	// still editable/deletable, and due_value_minor recomputes from it automatically.
	// -----------------------------------------------------------------------------
	UpdateBillPaidValue(ctx context.Context, arg UpdateBillPaidValueParams) (Bill, error)
}

var _ Querier = (*Queries)(nil)
