-- =============================================================================
-- AUTH MODULE — SQLC QUERIES
-- File: db/queries/auth.sql
--
-- Type-safe Go for the three auth tables defined in db/schema/auth_schema.sql:
--   - users                     — platform-level login identity
--   - organisations             — the tenant/company entity
--   - organisation_memberships  — links users to organisations with a role
--
-- These queries are generated by a DEDICATED sqlc block (see sqlc.yaml) into
-- package `auth` at db/auth — separate from the expenses package so the auth
-- domain types (User, Organisation, ...) don't leak into db/expenses.
--
-- Annotation / parameter syntax is identical to db/queries/query.sql:
--   -- name: FuncName :one|:many|:exec
--   $1, $2 ...  positional params, typed from the schema columns.
-- =============================================================================


-- =============================================================================
-- SECTION 1: USERS
-- =============================================================================

-- -----------------------------------------------------------------------------
-- CreateUser
-- Registers a new platform identity. id, created_at and updated_at are filled
-- by schema defaults, so we only supply the caller-provided fields and return
-- the full row via RETURNING so the caller gets the generated id immediately.
--
-- password_hash and phone are nullable:
--   - password_hash is NULL for OAuth-only accounts (Google/Microsoft sign-in)
--   - phone is optional (used later for 2FA / recovery)
-- The caller is responsible for hashing the password (bcrypt cost 12) and for
-- passing a lower-cased email — the schema stores email normalised to lowercase
-- and enforces it as the globally-unique login identifier.
-- -----------------------------------------------------------------------------
-- name: CreateUser :one
INSERT INTO users (
    email,
    password_hash,
    first_name,
    last_name,
    phone
) VALUES (
    $1,   -- email          VARCHAR  (must be lowercase; globally unique)
    $2,   -- password_hash  VARCHAR  (bcrypt hash; NULL for OAuth-only users)
    $3,   -- first_name     VARCHAR
    $4,   -- last_name      VARCHAR
    $5    -- phone          VARCHAR  (nullable)
)
RETURNING *;


-- -----------------------------------------------------------------------------
-- GetUser
-- Fetch a single user by id. Soft-deleted users are invisible.
-- -----------------------------------------------------------------------------
-- name: GetUser :one
SELECT * FROM users
WHERE id = $1
  AND deleted_at IS NULL;


-- -----------------------------------------------------------------------------
-- GetUserByEmail
-- The login lookup — the most frequent query on this table (idx_users_email).
-- Returns the row even if the account is locked or inactive so the application
-- layer can return the correct, specific error (locked / unverified / disabled)
-- rather than a generic "not found". The caller passes a lower-cased email.
-- -----------------------------------------------------------------------------
-- name: GetUserByEmail :one
SELECT * FROM users
WHERE email = $1
  AND deleted_at IS NULL;


-- -----------------------------------------------------------------------------
-- GetUserByVerificationToken
-- Looks up the user during the email-confirmation flow (idx_users_verification_token).
-- -----------------------------------------------------------------------------
-- name: GetUserByVerificationToken :one
SELECT * FROM users
WHERE email_verification_token = $1
  AND deleted_at IS NULL;


-- -----------------------------------------------------------------------------
-- GetUserByPasswordResetToken
-- Looks up the user when they click a password-reset link (idx_users_reset_token).
-- Token expiry (1 hour) is enforced in the application layer using
-- password_reset_sent_at, not in this query.
-- -----------------------------------------------------------------------------
-- name: GetUserByPasswordResetToken :one
SELECT * FROM users
WHERE password_reset_token = $1
  AND deleted_at IS NULL;


-- -----------------------------------------------------------------------------
-- UpdateUser
-- Updates editable profile fields only. Credentials, verification state and
-- security counters have their own dedicated queries below. Returns the updated
-- row so an API handler can echo it straight back.
-- -----------------------------------------------------------------------------
-- name: UpdateUser :one
UPDATE users SET
    first_name = $2,
    last_name  = $3,
    phone      = $4,
    avatar_url = $5,
    updated_at = now()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING *;


-- -----------------------------------------------------------------------------
-- UpdateUserPassword
-- Sets a new password hash and clears any outstanding reset token. Used by both
-- "change password" (while logged in) and "reset password" (via emailed token).
-- -----------------------------------------------------------------------------
-- name: UpdateUserPassword :exec
UPDATE users SET
    password_hash          = $2,
    password_reset_token   = NULL,
    password_reset_sent_at = NULL,
    updated_at             = now()
WHERE id = $1
  AND deleted_at IS NULL;


-- -----------------------------------------------------------------------------
-- SetEmailVerificationToken
-- Stores a freshly-generated verification token and stamps the send time.
-- Called on registration and on "resend verification email".
-- -----------------------------------------------------------------------------
-- name: SetEmailVerificationToken :exec
UPDATE users SET
    email_verification_token   = $2,
    email_verification_sent_at = now(),
    updated_at                 = now()
WHERE id = $1
  AND deleted_at IS NULL;


-- -----------------------------------------------------------------------------
-- VerifyUserEmail
-- Marks the email confirmed and burns the token in a single round-trip, keyed
-- by the token from the verification link. Returns the verified user (or no row
-- if the token is unknown/already used).
-- -----------------------------------------------------------------------------
-- name: VerifyUserEmail :one
UPDATE users SET
    email_verified_at        = now(),
    email_verification_token = NULL,
    updated_at               = now()
WHERE email_verification_token = $1
  AND deleted_at IS NULL
RETURNING *;


-- -----------------------------------------------------------------------------
-- SetPasswordResetToken
-- Begins the forgot-password flow: stores the reset token and send time, keyed
-- by email. Returns the user so the caller can send the reset email. A missing
-- email simply returns no row — the handler should respond identically either
-- way to avoid leaking which emails are registered.
-- -----------------------------------------------------------------------------
-- name: SetPasswordResetToken :one
UPDATE users SET
    password_reset_token   = $2,
    password_reset_sent_at = now(),
    updated_at             = now()
WHERE email = $1
  AND deleted_at IS NULL
RETURNING *;


-- -----------------------------------------------------------------------------
-- RecordSuccessfulLogin
-- Called after a password check passes: stamps the login, records the source
-- IP, and resets the failure counter / lockout. last_login_ip uses PostgreSQL's
-- native INET type.
-- -----------------------------------------------------------------------------
-- name: RecordSuccessfulLogin :exec
UPDATE users SET
    last_login_at      = now(),
    last_login_ip      = $2,
    failed_login_count = 0,
    locked_until       = NULL,
    updated_at         = now()
WHERE id = $1;


-- -----------------------------------------------------------------------------
-- IncrementFailedLogin
-- Bumps the failed-attempt counter on a bad password and returns the new total
-- so the application can decide whether to lock the account (then call LockUser).
-- -----------------------------------------------------------------------------
-- name: IncrementFailedLogin :one
UPDATE users SET
    failed_login_count = failed_login_count + 1,
    updated_at         = now()
WHERE id = $1
RETURNING failed_login_count;


-- -----------------------------------------------------------------------------
-- LockUser
-- Locks the account until the given timestamp after too many failed attempts.
-- The application computes locked_until (e.g. now() + 15 minutes).
-- -----------------------------------------------------------------------------
-- name: LockUser :exec
UPDATE users SET
    locked_until = $2,
    updated_at   = now()
WHERE id = $1;


-- -----------------------------------------------------------------------------
-- SoftDeleteUser
-- Soft-deletes the account: sets deleted_at and flips is_active off. Idempotent
-- — deleting an already-deleted user is a no-op.
-- -----------------------------------------------------------------------------
-- name: SoftDeleteUser :exec
UPDATE users SET
    deleted_at = now(),
    is_active  = FALSE,
    updated_at = now()
WHERE id = $1
  AND deleted_at IS NULL;


-- =============================================================================
-- SECTION 2: ORGANISATIONS
-- =============================================================================

-- -----------------------------------------------------------------------------
-- CreateOrganisation
-- Creates a tenant. plan defaults to 'trial' and the UK currency/timezone
-- defaults apply, but we accept currency/timezone explicitly so non-default
-- setups work from day one. slug is nullable (set later for subdomain routing).
-- -----------------------------------------------------------------------------
-- name: CreateOrganisation :one
INSERT INTO organisations (
    name,
    slug,
    native_currency,
    timezone,
    country_code
) VALUES (
    $1,   -- name             VARCHAR  (trading name)
    $2,   -- slug             VARCHAR  (nullable, URL-safe identifier)
    $3,   -- native_currency  CHAR(3)  e.g. 'GBP'
    $4,   -- timezone         VARCHAR  e.g. 'Europe/London'
    $5    -- country_code     CHAR(2)  ISO 3166-1 alpha-2, e.g. 'GB'
)
RETURNING *;


-- -----------------------------------------------------------------------------
-- GetOrganisation
-- Fetch a tenant by id. Soft-deleted organisations are invisible.
-- -----------------------------------------------------------------------------
-- name: GetOrganisation :one
SELECT * FROM organisations
WHERE id = $1
  AND deleted_at IS NULL;


-- -----------------------------------------------------------------------------
-- GetNextInvoiceNumber
-- The next sequential number for the org's "global" invoice sequence. The
-- invoices module formats it zero-padded (1 → '001') to pre-fill a new invoice's
-- reference field.
-- -----------------------------------------------------------------------------
-- name: GetNextInvoiceNumber :one
SELECT next_invoice_number FROM organisations
WHERE id = $1
  AND deleted_at IS NULL;


-- -----------------------------------------------------------------------------
-- RaiseInvoiceNumber
-- Raises the org's invoice counter so it is AT LEAST `at_least` — the floor below
-- which the next-reference suggestion never drops. Called on create with
-- (used number + 1), so the counter advances MONOTONICALLY (a number is never
-- re-suggested once used, even after the invoice is deleted). GREATEST makes it
-- idempotent, concurrency-safe, and immune to out-of-order references — it can only
-- ever move the counter UP. :exec.
-- -----------------------------------------------------------------------------
-- name: RaiseInvoiceNumber :exec
UPDATE organisations SET
    next_invoice_number = GREATEST(next_invoice_number, sqlc.arg(at_least))
WHERE id = sqlc.arg(id)
  AND deleted_at IS NULL;


-- -----------------------------------------------------------------------------
-- GetOrganisationBySlug
-- Resolves a tenant from its slug — used for subdomain / vanity-URL routing
-- (idx_organisations_slug).
-- -----------------------------------------------------------------------------
-- name: GetOrganisationBySlug :one
SELECT * FROM organisations
WHERE slug = $1
  AND deleted_at IS NULL;


-- -----------------------------------------------------------------------------
-- UpdateOrganisation
-- Updates the company-settings fields shown on the Company Details screen:
-- identity, the structured address, UK company/tax references, the invoice
-- contact details, the business profile, and locale. Billing columns and the
-- HMRC MTD OAuth tokens are intentionally left to their own dedicated flows and
-- not touched here. The legacy registered_address column is no longer written
-- (superseded by the structured address_line_*/town/region/postcode columns).
-- -----------------------------------------------------------------------------
-- name: UpdateOrganisation :one
UPDATE organisations SET
    name                      = $2,
    slug                      = $3,
    companies_house_number    = $4,
    legal_name                = $5,
    company_type              = $6,
    address_line_1            = $7,
    address_line_2            = $8,
    address_line_3            = $9,
    town                      = $10,
    region                    = $11,
    postcode                  = $12,
    utr                       = $13,
    vrn                       = $14,
    paye_reference            = $15,
    accounts_office_reference = $16,
    business_phone            = $17,
    contact_email             = $18,
    contact_phone             = $19,
    website                   = $20,
    business_category         = $21,
    business_description      = $22,
    native_currency           = $23,
    timezone                  = $24,
    country_code              = $25,
    updated_at                = now()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING *;


-- -----------------------------------------------------------------------------
-- SoftDeleteOrganisation
-- Soft-deletes a tenant: sets deleted_at and flips is_active off.
-- -----------------------------------------------------------------------------
-- name: SoftDeleteOrganisation :exec
UPDATE organisations SET
    deleted_at = now(),
    is_active  = FALSE,
    updated_at = now()
WHERE id = $1
  AND deleted_at IS NULL;


-- =============================================================================
-- SECTION 3: ORGANISATION MEMBERSHIPS
-- The join between users and organisations. The role lives here, not on users,
-- because the same person can hold different roles at different organisations.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- CreateMembership
-- Directly adds a user to an organisation as an active member — e.g. the
-- founding owner at sign-up. For email invitations use CreateInvitedMembership.
-- The (organisation_id, user_id) pair is UNIQUE, so a duplicate add errors.
-- -----------------------------------------------------------------------------
-- name: CreateMembership :one
INSERT INTO organisation_memberships (
    organisation_id,
    user_id,
    role,
    status
) VALUES (
    $1,   -- organisation_id  UUID
    $2,   -- user_id          UUID
    $3,   -- role             organisation_role  ('owner'|'admin'|'member'|'accountant'|'read_only')
    $4    -- status           VARCHAR            ('active'|'invited'|'suspended'|'deactivated')
)
RETURNING *;


-- -----------------------------------------------------------------------------
-- CreateInvitedMembership
-- Creates a pending ('invited') membership and records the invite token, send
-- time and inviting admin. The invitee accepts via AcceptInvite.
-- -----------------------------------------------------------------------------
-- name: CreateInvitedMembership :one
INSERT INTO organisation_memberships (
    organisation_id,
    user_id,
    role,
    status,
    invite_token,
    invite_sent_at,
    invited_by_user_id
) VALUES (
    $1,        -- organisation_id     UUID
    $2,        -- user_id             UUID
    $3,        -- role                organisation_role
    'invited', -- status fixed to 'invited'
    $4,        -- invite_token        VARCHAR  (random token emailed to the invitee)
    now(),     -- invite_sent_at
    $5         -- invited_by_user_id  UUID     (the admin who sent the invite)
)
RETURNING *;


-- -----------------------------------------------------------------------------
-- GetMembership
-- Fetches the membership for a specific user at a specific organisation — the
-- core authorisation check (does this user belong here, and in what role?).
-- Uses the uq_membership unique pair (organisation_id, user_id).
-- -----------------------------------------------------------------------------
-- name: GetMembership :one
SELECT * FROM organisation_memberships
WHERE organisation_id = $1
  AND user_id         = $2;


-- -----------------------------------------------------------------------------
-- GetMembershipByInviteToken
-- Resolves a pending membership from its invite token (idx_memberships_invite_token).
-- -----------------------------------------------------------------------------
-- name: GetMembershipByInviteToken :one
SELECT * FROM organisation_memberships
WHERE invite_token = $1;


-- -----------------------------------------------------------------------------
-- ListOrganisationsForUser
-- All organisations a user actively belongs to, with their role at each — this
-- powers the organisation switcher after login. Returns the full organisation
-- row plus the membership role.
-- -----------------------------------------------------------------------------
-- name: ListOrganisationsForUser :many
SELECT
    o.*,
    m.role
FROM organisations o
JOIN organisation_memberships m ON m.organisation_id = o.id
WHERE m.user_id    = $1
  AND m.status     = 'active'
  AND o.deleted_at IS NULL
ORDER BY o.name;


-- -----------------------------------------------------------------------------
-- ListMembersByOrganisation
-- The members admin page: every member of an organisation joined to their user
-- profile. Projects only the fields the UI needs (no password_hash).
-- -----------------------------------------------------------------------------
-- name: ListMembersByOrganisation :many
SELECT
    m.id         AS membership_id,
    m.role,
    m.status,
    m.created_at AS member_since,
    u.id         AS user_id,
    u.email,
    u.first_name,
    u.last_name,
    u.avatar_url,
    u.last_login_at
FROM organisation_memberships m
JOIN users u ON u.id = m.user_id
WHERE m.organisation_id = $1
  AND u.deleted_at IS NULL
ORDER BY u.last_name, u.first_name;


-- -----------------------------------------------------------------------------
-- UpdateMembershipRole
-- Changes a member's role (e.g. promote 'member' → 'admin').
-- -----------------------------------------------------------------------------
-- name: UpdateMembershipRole :exec
UPDATE organisation_memberships SET
    role       = $3,
    updated_at = now()
WHERE organisation_id = $1
  AND user_id         = $2;


-- -----------------------------------------------------------------------------
-- UpdateMembershipStatus
-- Changes a membership's status — used to suspend or deactivate a member.
-- (We deactivate memberships rather than deleting them, to keep the audit trail
-- and avoid orphaning historical expenses that reference the user_id.)
-- -----------------------------------------------------------------------------
-- name: UpdateMembershipStatus :exec
UPDATE organisation_memberships SET
    status     = $3,
    updated_at = now()
WHERE organisation_id = $1
  AND user_id         = $2;


-- -----------------------------------------------------------------------------
-- AcceptInvite
-- Completes the invitation flow: activates the membership, stamps the accept
-- time and burns the token, keyed by the token from the invite link.
-- -----------------------------------------------------------------------------
-- name: AcceptInvite :one
UPDATE organisation_memberships SET
    status             = 'active',
    invite_accepted_at = now(),
    invite_token       = NULL,
    updated_at         = now()
WHERE invite_token = $1
RETURNING *;


-- -----------------------------------------------------------------------------
-- GetMembershipByInboxLocalPart
-- Resolves a receipt-inbox address (its local part) to the (claimant) user and
-- organisation it belongs to — the routing step for an inbound email. Returns a
-- row ONLY when the whole chain is live: the membership is active, the user is
-- active and not soft-deleted, and the organisation is not soft-deleted. So a
-- deactivated member's (or a deleted user's/org's) address simply stops
-- resolving. The lookup is a single-column hit on the UNIQUE inbox_local_part index.
-- -----------------------------------------------------------------------------
-- name: GetMembershipByInboxLocalPart :one
SELECT m.user_id, m.organisation_id
FROM organisation_memberships m
JOIN users u         ON u.id = m.user_id
JOIN organisations o ON o.id = m.organisation_id
WHERE m.inbox_local_part = $1
  AND m.status     = 'active'
  AND u.is_active  = TRUE
  AND u.deleted_at IS NULL
  AND o.deleted_at IS NULL;


-- -----------------------------------------------------------------------------
-- SetMembershipInboxLocalPart
-- Provisions the receipt-inbox address for a membership. The `inbox_local_part
-- IS NULL` guard makes generation idempotent and race-safe: it only ever fills an
-- unset address, never overwrites one. Returns the value on success; matches no
-- row (pgx.ErrNoRows) when the address was already set (e.g. by a concurrent
-- request) — the caller then re-reads it. A clash with another membership's
-- address raises a unique_violation, which the caller catches to retry with a
-- different candidate.
-- -----------------------------------------------------------------------------
-- name: SetMembershipInboxLocalPart :one
UPDATE organisation_memberships SET
    inbox_local_part              = $3,
    inbox_local_part_generated_at = now(),
    updated_at                    = now()
WHERE organisation_id = $1
  AND user_id         = $2
  AND inbox_local_part IS NULL
RETURNING inbox_local_part;
