-- =============================================================================
-- BANKING MODULE — SQLC QUERIES
-- File: db/queries/banking.sql
--
-- Type-safe Go for the bank_accounts + bank_transactions tables defined in
-- db/schema/banking_schema.sql. Generated by a DEDICATED sqlc block (see
-- sqlc.yaml) into package `banking` at db/banking — separate from the other
-- domains so types don't bleed across modules.
--
-- Annotation / parameter syntax is identical to db/queries/contacts.sql:
--   -- name: FuncName :one|:many|:exec
--   $1, $2 ...  positional params, typed from the schema columns.
--
-- Every query is ORGANISATION-SCOPED (multi-tenancy) and SOFT-DELETE-AWARE
-- (deleted_at IS NULL).
--
-- Money note: amounts are BIGINT minor units (pence) → Go int64. The List/Get
-- account queries DERIVE current_balance_minor (opening + SUM of the account's
-- live transactions); it is never stored. amount_minor is SIGNED (+ in / - out),
-- so the SUM is the net movement.
-- =============================================================================


-- #############################################################################
-- BANK ACCOUNTS
-- #############################################################################

-- -----------------------------------------------------------------------------
-- CreateBankAccount  (the "setter")
-- Inserts a new bank account and returns the full row via RETURNING *. id,
-- status/flag defaults, created_at, updated_at and deleted_at are filled by
-- schema defaults, so we only supply the caller-provided columns.
--
-- organisation_id and created_by_user_id come from the authenticated token in
-- the service layer, never from the request body. RETURNING * gives the base row
-- (no derived balance — a fresh account's balance is just its opening balance).
-- -----------------------------------------------------------------------------
-- name: CreateBankAccount :one
INSERT INTO bank_accounts (
    organisation_id,
    created_by_user_id,
    name,
    currency,
    status,
    is_personal,
    is_primary,
    bank_name,
    account_number,
    sort_code,
    routing_number,
    bank_account_type,
    iban,
    bic,
    show_on_invoices,
    opening_balance_minor,
    opening_balance_date,
    guess_explanations
) VALUES (
    $1,   -- organisation_id        UUID (tenant that owns the account)
    $2,   -- created_by_user_id     UUID (audit)
    $3,   -- name                   VARCHAR (required)
    $4,   -- currency               CHAR(3) e.g. 'GBP'
    $5,   -- status                 VARCHAR 'active'|'closed'
    $6,   -- is_personal            BOOLEAN
    $7,   -- is_primary             BOOLEAN (≤1 live primary per org — enforced by index)
    $8,   -- bank_name              VARCHAR (nullable)
    $9,   -- account_number         VARCHAR (nullable)
    $10,  -- sort_code              VARCHAR (nullable; UK)
    $11,  -- routing_number         VARCHAR (nullable; US)
    $12,  -- bank_account_type      VARCHAR (nullable; 'checking'|'savings', US)
    $13,  -- iban                   VARCHAR (nullable; international)
    $14,  -- bic                    VARCHAR (nullable; SWIFT/BIC)
    $15,  -- show_on_invoices       BOOLEAN
    $16,  -- opening_balance_minor  BIGINT (pence)
    $17,  -- opening_balance_date   DATE (nullable)
    $18   -- guess_explanations     BOOLEAN
)
RETURNING *;


-- -----------------------------------------------------------------------------
-- GetBankAccount  (the "getter", with derived balance)
-- Fetch a single account by id, scoped to the organisation, with its DERIVED
-- current_balance_minor = opening + SUM(live transactions). We ALWAYS scope by
-- organisation_id — never fetch by id alone. The LEFT JOIN keeps the row even
-- when the account has no transactions (its deleted_at filter lives in the ON
-- clause, not WHERE, so it doesn't turn the LEFT JOIN into an INNER one). The
-- whole sum is cast to BIGINT so it maps to Go int64 (SUM of bigint is numeric).
-- -----------------------------------------------------------------------------
-- name: GetBankAccount :one
SELECT
    a.*,
    (a.opening_balance_minor + COALESCE(SUM(t.amount_minor), 0))::bigint AS current_balance_minor
FROM bank_accounts a
LEFT JOIN bank_transactions t
       ON t.bank_account_id = a.id
      AND t.deleted_at IS NULL
WHERE a.id              = $1   -- account UUID
  AND a.organisation_id = $2   -- tenant scope — never skip this
  AND a.deleted_at IS NULL     -- soft delete filter
GROUP BY a.id;


-- -----------------------------------------------------------------------------
-- ListBankAccounts  (the "list", with derived balance)
-- All live accounts for an organisation, each with its derived current balance,
-- for the bank-accounts list page. Primary account first (the form note: "appear
-- at the top of Banking lists and dropdowns"), then by name.
-- -----------------------------------------------------------------------------
-- name: ListBankAccounts :many
SELECT
    a.*,
    (a.opening_balance_minor + COALESCE(SUM(t.amount_minor), 0))::bigint AS current_balance_minor
FROM bank_accounts a
LEFT JOIN bank_transactions t
       ON t.bank_account_id = a.id
      AND t.deleted_at IS NULL
WHERE a.organisation_id = $1
  AND a.deleted_at IS NULL
GROUP BY a.id
ORDER BY a.is_primary DESC, a.name;


-- -----------------------------------------------------------------------------
-- UpdateBankAccount  (the "update")
-- Full update of an account's editable fields (PUT semantics). organisation_id
-- and created_by_user_id are NOT editable. updated_at is set explicitly in
-- addition to the trigger (belt-and-suspenders). RETURNING * echoes the row.
--
-- Note: setting is_primary = TRUE while another live primary exists violates
-- idx_bank_accounts_one_primary; the service unsets the old primary first
-- (UnsetPrimaryBankAccounts), inside one transaction.
-- -----------------------------------------------------------------------------
-- name: UpdateBankAccount :one
UPDATE bank_accounts SET
    name                  = $3,
    currency              = $4,
    status                = $5,
    is_personal           = $6,
    is_primary            = $7,
    bank_name             = $8,
    account_number        = $9,
    sort_code             = $10,
    routing_number        = $11,
    bank_account_type     = $12,
    iban                  = $13,
    bic                   = $14,
    show_on_invoices      = $15,
    opening_balance_minor = $16,
    opening_balance_date  = $17,
    guess_explanations    = $18,
    updated_at            = now()
WHERE id              = $1   -- account UUID
  AND organisation_id = $2   -- tenant scope
  AND deleted_at IS NULL     -- can't update a deleted account
RETURNING *;


-- -----------------------------------------------------------------------------
-- UnsetPrimaryBankAccounts  (clear the org's current primary)
-- Sets is_primary = FALSE on whichever live account is currently primary for the
-- org. Called inside a transaction BEFORE marking a new primary, so the partial
-- unique index (≤1 live primary per org) is never transiently violated. :exec.
-- Idempotent — if there is no current primary it simply matches no rows.
-- -----------------------------------------------------------------------------
-- name: UnsetPrimaryBankAccounts :exec
UPDATE bank_accounts SET
    is_primary = FALSE,
    updated_at = now()
WHERE organisation_id = $1
  AND is_primary
  AND deleted_at IS NULL;


-- -----------------------------------------------------------------------------
-- SoftDeleteBankAccount  (the "delete")
-- Marks the account deleted (financial records are never hard-removed; its
-- transactions stay for audit). :exec. Idempotent — deleting an already-deleted
-- account matches no live row and is a no-op.
-- -----------------------------------------------------------------------------
-- name: SoftDeleteBankAccount :exec
UPDATE bank_accounts SET
    deleted_at = now(),
    updated_at = now()
WHERE id              = $1
  AND organisation_id = $2
  AND deleted_at IS NULL;


-- #############################################################################
-- BANK TRANSACTIONS
-- #############################################################################

-- -----------------------------------------------------------------------------
-- CreateBankTransaction  (the "setter")
-- Inserts one statement line and returns the full row. organisation_id is passed
-- explicitly (denormalised onto the line) so every later query is org-scoped
-- without a join. created_by_user_id is NULL for a feed line, set for a manual
-- one. amount_minor is SIGNED (+ in / - out).
-- -----------------------------------------------------------------------------
-- name: CreateBankTransaction :one
INSERT INTO bank_transactions (
    organisation_id,
    bank_account_id,
    created_by_user_id,
    dated_on,
    amount_minor,
    description,
    bank_memo,
    balance_minor,
    status,
    source,
    external_id
) VALUES (
    $1,   -- organisation_id     UUID (tenant; denormalised from the account)
    $2,   -- bank_account_id     UUID (the account this line belongs to)
    $3,   -- created_by_user_id  UUID (nullable; NULL = from feed)
    $4,   -- dated_on            DATE
    $5,   -- amount_minor        BIGINT signed (+ in / - out)
    $6,   -- description         VARCHAR (nullable)
    $7,   -- bank_memo           TEXT (nullable; raw bank narrative)
    $8,   -- balance_minor       BIGINT (nullable; running statement balance)
    $9,   -- status              VARCHAR 'unexplained'|'explained'|'for_approval'
    $10,  -- source              VARCHAR 'feed'|'manual'|'statement'
    $11   -- external_id         VARCHAR (nullable; provider txn id for dedupe)
)
RETURNING *;


-- -----------------------------------------------------------------------------
-- GetBankTransaction  (the "getter")
-- Fetch a single transaction by id, scoped to the organisation. deleted_at
-- IS NULL hides soft-deleted lines.
-- -----------------------------------------------------------------------------
-- name: GetBankTransaction :one
SELECT * FROM bank_transactions
WHERE id              = $1   -- transaction UUID
  AND organisation_id = $2   -- tenant scope — never skip this
  AND deleted_at IS NULL;


-- -----------------------------------------------------------------------------
-- ListBankTransactions  (the "list", paginated)
-- The statement lines for ONE account, newest first, for the transactions page.
-- Scoped by org AND account. Paginated with LIMIT/OFFSET (the list shows a page
-- size selector). created_at is the tiebreaker so same-dated lines are stable.
-- -----------------------------------------------------------------------------
-- name: ListBankTransactions :many
SELECT * FROM bank_transactions
WHERE organisation_id = $1   -- tenant scope
  AND bank_account_id = $2   -- which account's statement
  AND deleted_at IS NULL
ORDER BY dated_on DESC, created_at DESC
LIMIT $3 OFFSET $4;


-- -----------------------------------------------------------------------------
-- GetBankTransactionByExternalID  (feed dedupe lookup)
-- Used by the future bank-feed ingestion to skip a transaction it already has.
-- Keyed on (bank_account_id, external_id) — exactly the columns of the partial
-- unique index idx_bank_transactions_external — so it is an index lookup. The
-- account already implies the org (it was loaded org-scoped). :one.
-- -----------------------------------------------------------------------------
-- name: GetBankTransactionByExternalID :one
SELECT * FROM bank_transactions
WHERE bank_account_id = $1   -- the account
  AND external_id     = $2   -- the provider's transaction id
  AND deleted_at IS NULL;


-- -----------------------------------------------------------------------------
-- SoftDeleteBankTransaction  (the "delete")
-- Marks a line deleted (e.g. removing a manually-added transaction). Org-scoped.
-- :exec. Idempotent — an already-deleted line matches nothing and is a no-op.
-- -----------------------------------------------------------------------------
-- name: SoftDeleteBankTransaction :exec
UPDATE bank_transactions SET
    deleted_at = now(),
    updated_at = now()
WHERE id              = $1
  AND organisation_id = $2
  AND deleted_at IS NULL;
