-- =============================================================================
-- CONTACTS MODULE — SQLC QUERIES
-- File: db/queries/contacts.sql
--
-- Type-safe Go for the contacts table defined in db/schema/contacts_schema.sql.
-- Generated by a DEDICATED sqlc block (see sqlc.yaml) into package `contacts` at
-- db/contacts — separate from the expenses/auth packages so domain types don't
-- bleed across modules.
--
-- Annotation / parameter syntax is identical to db/queries/query.sql:
--   -- name: FuncName :one|:many|:exec
--   $1, $2 ...  positional params, typed from the schema columns.
--
-- Every query is ORGANISATION-SCOPED (multi-tenancy) and SOFT-DELETE-AWARE
-- (deleted_at IS NULL), mirroring the expenses queries.
-- =============================================================================


-- -----------------------------------------------------------------------------
-- CreateContact  (the "setter")
-- Inserts a new contact and returns the full row via RETURNING * so the caller
-- gets the generated id and timestamps without a second round-trip. id,
-- is_active, created_at, updated_at and deleted_at are filled by schema
-- defaults, so we only supply the caller-provided columns.
--
-- organisation_id and created_by_user_id come from the authenticated token in
-- the service layer, never from the request body.
-- -----------------------------------------------------------------------------
-- name: CreateContact :one
INSERT INTO contacts (
    organisation_id,
    created_by_user_id,
    first_name,
    last_name,
    organisation_name,
    email,
    billing_email,
    telephone,
    mobile,
    address_line_1,
    address_line_2,
    address_line_3,
    town,
    region,
    postcode,
    country_code,
    default_payment_terms_days,
    uses_contact_level_email_settings,
    uses_contact_level_invoice_sequence,
    display_contact_name,
    charge_vat,
    vat_registration_number,
    invoice_language,
    bank_sort_code,
    bank_account_number,
    bank_recipient_name
) VALUES (
    $1,   -- organisation_id                     UUID (tenant that owns the contact)
    $2,   -- created_by_user_id                  UUID (audit)
    $3,   -- first_name                          VARCHAR (nullable)
    $4,   -- last_name                           VARCHAR (nullable)
    $5,   -- organisation_name                   VARCHAR (nullable — the contact's company)
    $6,   -- email                               VARCHAR (nullable)
    $7,   -- billing_email                       VARCHAR (nullable)
    $8,   -- telephone                           VARCHAR (nullable)
    $9,   -- mobile                              VARCHAR (nullable)
    $10,  -- address_line_1                      VARCHAR (nullable)
    $11,  -- address_line_2                      VARCHAR (nullable)
    $12,  -- address_line_3                      VARCHAR (nullable)
    $13,  -- town                                VARCHAR (nullable)
    $14,  -- region                              VARCHAR (nullable)
    $15,  -- postcode                            VARCHAR (nullable)
    $16,  -- country_code                        CHAR(2) e.g. 'GB'
    $17,  -- default_payment_terms_days          INTEGER (nullable; 0 = Due on Receipt)
    $18,  -- uses_contact_level_email_settings   BOOLEAN
    $19,  -- uses_contact_level_invoice_sequence BOOLEAN
    $20,  -- display_contact_name                BOOLEAN
    $21,  -- charge_vat                          VARCHAR 'ALWAYS'|'NEVER'|'SAME_COUNTRY'
    $22,  -- vat_registration_number             VARCHAR (nullable)
    $23,  -- invoice_language                    VARCHAR e.g. 'en'
    $24,  -- bank_sort_code                      VARCHAR (nullable)
    $25,  -- bank_account_number                 VARCHAR (nullable)
    $26   -- bank_recipient_name                 VARCHAR (nullable)
)
RETURNING *;


-- -----------------------------------------------------------------------------
-- GetContact  (the "getter")
-- Fetch a single contact by id, scoped to the organisation. We ALWAYS scope by
-- organisation_id — never fetch by id alone — so one tenant can't read another's
-- contact if an id leaks. deleted_at IS NULL hides soft-deleted rows.
-- -----------------------------------------------------------------------------
-- name: GetContact :one
SELECT * FROM contacts
WHERE id              = $1   -- contact UUID
  AND organisation_id = $2   -- tenant scope — never skip this
  AND deleted_at IS NULL;    -- soft delete filter


-- -----------------------------------------------------------------------------
-- ListContacts  (the "list")
-- All active (non-deleted) contacts for an organisation, for the contacts list
-- page. Ordered by company then person name; NULLs sort last in ASC, so unnamed
-- companies / nameless rows fall to the bottom.
-- -----------------------------------------------------------------------------
-- name: ListContacts :many
SELECT * FROM contacts
WHERE organisation_id = $1
  AND deleted_at IS NULL
ORDER BY organisation_name, last_name, first_name;


-- -----------------------------------------------------------------------------
-- UpdateContact  (the "update")
-- Full update of a contact's editable fields (PUT semantics). organisation_id
-- and created_by_user_id are NOT editable. updated_at is set explicitly here in
-- addition to the trigger (belt-and-suspenders). RETURNING * gives the updated
-- row back so the API can echo it.
-- -----------------------------------------------------------------------------
-- name: UpdateContact :one
UPDATE contacts SET
    first_name                          = $3,
    last_name                           = $4,
    organisation_name                   = $5,
    email                               = $6,
    billing_email                       = $7,
    telephone                           = $8,
    mobile                              = $9,
    address_line_1                      = $10,
    address_line_2                      = $11,
    address_line_3                      = $12,
    town                                = $13,
    region                              = $14,
    postcode                            = $15,
    country_code                        = $16,
    default_payment_terms_days          = $17,
    uses_contact_level_email_settings   = $18,
    uses_contact_level_invoice_sequence = $19,
    display_contact_name                = $20,
    charge_vat                          = $21,
    vat_registration_number             = $22,
    invoice_language                    = $23,
    bank_sort_code                      = $24,
    bank_account_number                 = $25,
    bank_recipient_name                 = $26,
    updated_at                          = now()
WHERE id              = $1   -- contact UUID
  AND organisation_id = $2   -- tenant scope
  AND deleted_at IS NULL     -- can't update a deleted contact
RETURNING *;


-- -----------------------------------------------------------------------------
-- SoftDeleteContact  (the "delete")
-- Sets deleted_at to mark the contact deleted (it stays in the DB for audit and
-- so historical invoices that reference it don't dangle). Mirrors
-- SoftDeleteExpense. :exec returns only an error. Idempotent — deleting an
-- already-deleted contact matches no live row and is a no-op.
-- -----------------------------------------------------------------------------
-- name: SoftDeleteContact :exec
UPDATE contacts SET
    deleted_at = now(),
    is_active  = false,   -- keep the lifecycle columns coherent: a deleted contact is not active
    updated_at = now()
WHERE id              = $1
  AND organisation_id = $2
  AND deleted_at IS NULL;
