-- =============================================================================
-- INTEGRATIONS MODULE — SQLC QUERIES
-- File: db/queries/integrations.sql
--
-- Type-safe Go for the integrations tables defined in
-- db/schema/integrations_schema.sql. Generated by a DEDICATED sqlc block (see
-- sqlc.yaml) into package `integrations` at db/integrations.
--
-- Named parameters (@name) are used throughout for clarity, matching the style
-- already used in db/queries/query.sql.
--
-- Every query is ORGANISATION-SCOPED (multi-tenancy): the credential/token
-- queries key on (organisation_id, provider); the push-result queries reach the
-- tenant through integration_id; GetExpenseForPush re-checks organisation_id.
-- =============================================================================


-- -----------------------------------------------------------------------------
-- GetProviderCredentials
-- The GLOBAL OAuth app credentials for a provider (client_id/client_secret).
-- These identify OUR application and are shared by every organisation, so there
-- is no organisation_id — the lookup is by provider key alone (the primary key).
-- The app only ever READS these; rows are managed directly in the DB. :one —
-- callers treat pgx.ErrNoRows as "not configured".
-- -----------------------------------------------------------------------------
-- name: GetProviderCredentials :one
SELECT * FROM provider_credentials
WHERE provider = @provider;


-- -----------------------------------------------------------------------------
-- GetIntegration
-- The org's connection for a provider. Backed by the unique (organisation_id,
-- provider) index. Used everywhere we need the client creds, the tokens, or just
-- the integration_id (the internal endpoints all resolve org -> integration_id
-- through here). :one — callers treat pgx.ErrNoRows as "not configured".
-- -----------------------------------------------------------------------------
-- name: GetIntegration :one
SELECT * FROM organisation_integrations
WHERE organisation_id = @organisation_id
  AND provider        = @provider;


-- -----------------------------------------------------------------------------
-- SetIntegrationTokens
-- Store the tokens obtained from the OAuth token endpoint — on the initial
-- connect AND on every server-side refresh. Stamps connected_at = now() so the
-- status flips to "connected" (and a refresh keeps it connected).
--
-- This is an UPSERT: the per-org row no longer pre-exists (credentials are now
-- global, in provider_credentials), so the FIRST successful connect INSERTs the
-- row; later connects/refreshes UPDATE it via the (organisation_id, provider)
-- unique key. An org therefore has a row here iff it has connected at least once.
-- -----------------------------------------------------------------------------
-- name: SetIntegrationTokens :exec
INSERT INTO organisation_integrations (organisation_id, provider, access_token, refresh_token, token_expires_at, connected_at)
VALUES (@organisation_id, @provider, @access_token, @refresh_token, @token_expires_at, now())
ON CONFLICT (organisation_id, provider) DO UPDATE
    SET access_token     = EXCLUDED.access_token,
        refresh_token    = EXCLUDED.refresh_token,
        token_expires_at = EXCLUDED.token_expires_at,
        connected_at     = now(),
        updated_at       = now();


-- -----------------------------------------------------------------------------
-- ClearIntegrationTokens
-- Disconnect: drop the tokens but KEEP the client credentials (so reconnecting
-- doesn't require re-entering them). Also used when a refresh fails — clearing
-- connected_at surfaces "needs reconnect" on the settings screen.
-- -----------------------------------------------------------------------------
-- name: ClearIntegrationTokens :exec
UPDATE organisation_integrations
SET access_token     = NULL,
    refresh_token    = NULL,
    token_expires_at = NULL,
    connected_at     = NULL,
    updated_at       = now()
WHERE organisation_id = @organisation_id
  AND provider        = @provider;


-- -----------------------------------------------------------------------------
-- DeleteIntegration
-- Remove the connection entirely (credentials included). ON DELETE CASCADE
-- cleans up the integration_expense_pushes rows. Disconnect (above) is the
-- softer option; this is a full removal.
-- -----------------------------------------------------------------------------
-- name: DeleteIntegration :exec
DELETE FROM organisation_integrations
WHERE organisation_id = @organisation_id
  AND provider        = @provider;


-- -----------------------------------------------------------------------------
-- UpsertExpensePushResult
-- Record the outcome of a push, one row per (integration, expense). On success
-- external_expense_ref is the external URL and push_error is NULL; on failure
-- it's the reverse. The unique (integration_id, expense_id) key makes this an
-- UPSERT, so an Eventarc retry or a manual re-push updates the same row instead
-- of duplicating — this is the idempotency anchor for the whole flow.
-- -----------------------------------------------------------------------------
-- name: UpsertExpensePushResult :exec
INSERT INTO integration_expense_pushes (integration_id, expense_id, external_expense_ref, push_error)
VALUES (@integration_id, @expense_id, @external_expense_ref, @push_error)
ON CONFLICT (integration_id, expense_id) DO UPDATE
    SET external_expense_ref = EXCLUDED.external_expense_ref,
        push_error           = EXCLUDED.push_error,
        pushed_at            = now();


-- -----------------------------------------------------------------------------
-- GetExpensePushResult
-- Read the outcome row for an (integration, expense). The internal expense-read
-- endpoint uses this to compute `already_pushed` (a row whose external_expense_ref
-- is non-NULL means a prior push succeeded → the workflow exits early). :one —
-- pgx.ErrNoRows means "never attempted".
-- -----------------------------------------------------------------------------
-- name: GetExpensePushResult :one
SELECT * FROM integration_expense_pushes
WHERE integration_id = @integration_id
  AND expense_id     = @expense_id;


-- -----------------------------------------------------------------------------
-- GetExpenseForPush
-- Assemble the provider-neutral data the workflow needs to build a push payload,
-- in one round-trip: the expense's money (as pence integers — the Go handler
-- formats them to decimal strings), its category's nominal_code, and the
-- claimant's email (the key the workflow matches against the external system's
-- users). Org-scoped + soft-delete-aware. ec_status is returned RAW; the
-- provider-specific vocabulary mapping happens in the workflow.
-- -----------------------------------------------------------------------------
-- name: GetExpenseForPush :one
SELECT
    e.id                AS expense_id,
    e.organisation_id   AS organisation_id,
    u.email             AS claimant_email,
    c.nominal_code      AS nominal_code,
    e.dated_on          AS dated_on,
    e.description       AS description,
    e.currency          AS currency,
    e.gross_value_minor AS gross_value_minor,
    e.vat_value_minor   AS vat_value_minor,
    e.vat_rate_bps      AS vat_rate_bps,
    e.ec_status         AS ec_status,
    e.status            AS status
FROM expenses e
JOIN users u              ON u.id = e.user_id
JOIN expense_categories c ON c.id = e.category_id
WHERE e.id              = @expense_id
  AND e.organisation_id = @organisation_id
  AND e.deleted_at IS NULL;
