-- =============================================================================
-- INVOICES MODULE — SQLC QUERIES
-- File: db/queries/invoices.sql
--
-- Type-safe Go for the invoices + invoice_items tables defined in
-- db/schema/invoices_schema.sql. Generated by a DEDICATED sqlc block (see
-- sqlc.yaml) into package `invoices` at db/invoices — separate from the other
-- domain packages so types don't bleed across modules.
--
-- Annotation / parameter syntax is identical to the other query files:
--   -- name: FuncName :one|:many|:exec
--   $1, $2 ...  positional params, typed from the schema columns.
--
-- Every query is ORGANISATION-SCOPED (multi-tenancy) and, on the header,
-- SOFT-DELETE-AWARE (deleted_at IS NULL). organisation_id / created_by_user_id
-- come from the authenticated token in the (future) service layer, never from the
-- request body.
--
-- The header's STATUS and the TOTALS are mutated by their own dedicated queries
-- (UpdateInvoiceStatus / UpdateInvoiceTotals / UpdateInvoicePaidValue), NOT by
-- UpdateInvoice — so a field edit can't accidentally clobber the lifecycle or the
-- computed money, mirroring how the expenses module keeps status transitions
-- separate from field edits.
-- =============================================================================


-- =============================================================================
-- INVOICE HEADER
-- =============================================================================

-- -----------------------------------------------------------------------------
-- CreateInvoice  (the "setter")
-- Inserts a new invoice header and returns the full row via RETURNING * (so the
-- caller gets the generated id, defaults and the computed due_value_minor without
-- a second round-trip). status defaults to 'DRAFT', all *_value_minor default to
-- 0, and due_value_minor is GENERATED — so none of those are supplied here; the
-- service inserts the header, then the lines, then sets the totals.
-- -----------------------------------------------------------------------------
-- name: CreateInvoice :one
INSERT INTO invoices (
    organisation_id,
    created_by_user_id,
    contact_id,
    dated_on,
    due_on,
    reference,
    currency
) VALUES (
    $1,   -- organisation_id     UUID (tenant that owns the invoice)
    $2,   -- created_by_user_id  UUID (audit)
    $3,   -- contact_id          UUID (who it's billed to)
    $4,   -- dated_on            DATE
    $5,   -- due_on              DATE (nullable)
    $6,   -- reference           VARCHAR (nullable until issued)
    $7    -- currency            CHAR(3) e.g. 'GBP'
)
RETURNING *;


-- -----------------------------------------------------------------------------
-- GetInvoice  (the "getter")
-- Fetch a single invoice header by id, scoped to the organisation. We ALWAYS scope
-- by organisation_id — never fetch by id alone — so one tenant can't read another's
-- invoice if an id leaks. deleted_at IS NULL hides soft-deleted rows.
-- -----------------------------------------------------------------------------
-- name: GetInvoice :one
SELECT * FROM invoices
WHERE id              = $1   -- invoice UUID
  AND organisation_id = $2   -- tenant scope — never skip this
  AND deleted_at IS NULL;    -- soft delete filter


-- -----------------------------------------------------------------------------
-- ListInvoices  (the "list")
-- All live invoices for an organisation, newest first, for the invoices list page.
-- -----------------------------------------------------------------------------
-- name: ListInvoices :many
SELECT * FROM invoices
WHERE organisation_id = $1
  AND deleted_at IS NULL
ORDER BY dated_on DESC, created_at DESC;


-- -----------------------------------------------------------------------------
-- ListInvoicesByContact
-- The live invoices raised for one contact (e.g. the contact detail page). Backed
-- by idx_invoices_org_contact.
-- -----------------------------------------------------------------------------
-- name: ListInvoicesByContact :many
SELECT * FROM invoices
WHERE organisation_id = $1
  AND contact_id      = $2
  AND deleted_at IS NULL
ORDER BY dated_on DESC, created_at DESC;


-- -----------------------------------------------------------------------------
-- UpdateInvoice  (the "update" — editable header fields only)
-- Full update of the caller-editable header fields (PUT semantics). Deliberately
-- does NOT touch status or any *_value_minor — those have their own queries.
-- organisation_id / created_by_user_id are not editable. updated_at is set
-- explicitly here in addition to the trigger (belt-and-suspenders). Whether an
-- invoice is editable in its current status is a service-layer guard.
-- -----------------------------------------------------------------------------
-- name: UpdateInvoice :one
UPDATE invoices SET
    contact_id = $3,
    dated_on   = $4,
    due_on     = $5,
    reference  = $6,
    currency   = $7,
    updated_at = now()
WHERE id              = $1   -- invoice UUID
  AND organisation_id = $2   -- tenant scope
  AND deleted_at IS NULL     -- can't update a deleted invoice
RETURNING *;


-- -----------------------------------------------------------------------------
-- UpdateInvoiceTotals
-- Writes the service-computed money roll-up (net / sales tax / gross) after the
-- lines have been (re)built. due_value_minor recomputes automatically (it's
-- GENERATED from total_value_minor - paid_value_minor). paid_value_minor is NOT
-- touched here — it has its own query.
-- -----------------------------------------------------------------------------
-- name: UpdateInvoiceTotals :one
UPDATE invoices SET
    net_value_minor       = $3,
    sales_tax_value_minor = $4,
    total_value_minor     = $5,
    updated_at            = now()
WHERE id              = $1
  AND organisation_id = $2
  AND deleted_at IS NULL
RETURNING *;


-- -----------------------------------------------------------------------------
-- UpdateInvoiceStatus
-- Moves the stored lifecycle (DRAFT|SCHEDULED|SENT|WRITTEN_OFF|REFUNDED). A single
-- query suffices because the minimal header has no per-transition timestamp columns
-- to set (unlike the expenses approval machine); split this out if paid_on /
-- written_off_date are added later. Legal-transition checking is a service guard;
-- the DB CHECK only constrains the value set.
-- -----------------------------------------------------------------------------
-- name: UpdateInvoiceStatus :one
UPDATE invoices SET
    status     = $3,
    updated_at = now()
WHERE id              = $1
  AND organisation_id = $2
  AND deleted_at IS NULL
RETURNING *;


-- -----------------------------------------------------------------------------
-- UpdateInvoicePaidValue
-- Sets the amount settled against the invoice. Anticipates the payments /
-- reconciliation path (deferred — see BACKLOG); paid_value_minor drives the
-- DERIVED Paid/Overpaid/Overdue display status, and due_value_minor recomputes
-- from it automatically.
-- -----------------------------------------------------------------------------
-- name: UpdateInvoicePaidValue :one
UPDATE invoices SET
    paid_value_minor = $3,
    updated_at       = now()
WHERE id              = $1
  AND organisation_id = $2
  AND deleted_at IS NULL
RETURNING *;


-- -----------------------------------------------------------------------------
-- SoftDeleteInvoice  (the "delete")
-- Sets deleted_at to mark the invoice deleted (it stays in the DB for audit and so
-- payments/history that reference it don't dangle). Mirrors SoftDeleteContact.
-- :exec returns only an error. Idempotent — deleting an already-deleted invoice
-- matches no live row and is a no-op. Whether the invoice's status ALLOWS deletion
-- (e.g. DRAFT only) is a service-layer guard.
-- -----------------------------------------------------------------------------
-- name: SoftDeleteInvoice :exec
UPDATE invoices SET
    deleted_at = now(),
    updated_at = now()
WHERE id              = $1
  AND organisation_id = $2
  AND deleted_at IS NULL;


-- -----------------------------------------------------------------------------
-- ContactHasInvoices
-- "Is this contact referenced by any live invoice?" — the cross-domain check the
-- contacts module's delete guard needs (a soft-deleted contact must not strand
-- invoices). Mirrors projects.ContactHasProjects; the contacts service will inject
-- the invoices querier and OR this into its existing in-use check (wiring deferred
-- to the service increment — this is the datalayer half).
-- -----------------------------------------------------------------------------
-- name: ContactHasInvoices :one
SELECT EXISTS (
    SELECT 1 FROM invoices
    WHERE contact_id      = $1
      AND organisation_id = $2
      AND deleted_at IS NULL
) AS has_invoices;


-- =============================================================================
-- INVOICE LINE ITEMS
-- =============================================================================

-- -----------------------------------------------------------------------------
-- CreateInvoiceItem
-- Inserts one line. organisation_id is denormalised from the parent invoice (set
-- by the service). The service typically inserts all lines for an invoice inside
-- one transaction, then calls UpdateInvoiceTotals.
-- -----------------------------------------------------------------------------
-- name: CreateInvoiceItem :one
INSERT INTO invoice_items (
    invoice_id,
    organisation_id,
    position,
    description,
    quantity,
    price_minor,
    sales_tax_rate_bps
) VALUES (
    $1,   -- invoice_id          UUID (parent)
    $2,   -- organisation_id     UUID (denormalised tenant scope)
    $3,   -- position            INTEGER (1-based)
    $4,   -- description         TEXT
    $5,   -- quantity            NUMERIC (as string)
    $6,   -- price_minor         BIGINT (per-unit, ex-VAT, pence)
    $7    -- sales_tax_rate_bps  INTEGER (basis points)
)
RETURNING *;


-- -----------------------------------------------------------------------------
-- ListInvoiceItems
-- The lines of an invoice, in display order. Scoped by organisation_id too (the
-- denormalised column) so a leaked invoice id alone can't read another tenant's lines.
-- -----------------------------------------------------------------------------
-- name: ListInvoiceItems :many
SELECT * FROM invoice_items
WHERE invoice_id      = $1
  AND organisation_id = $2
ORDER BY position;


-- -----------------------------------------------------------------------------
-- DeleteInvoiceItemsForInvoice
-- Removes ALL lines of an invoice. Supports the "replace the lines" edit pattern:
-- the service deletes the existing lines and re-inserts the submitted set inside one
-- transaction, then recomputes the totals. Org-scoped defensively.
-- -----------------------------------------------------------------------------
-- name: DeleteInvoiceItemsForInvoice :exec
DELETE FROM invoice_items
WHERE invoice_id      = $1
  AND organisation_id = $2;


-- -----------------------------------------------------------------------------
-- DeleteInvoiceItem
-- Removes a single line by id (scoped to its parent invoice + org).
-- -----------------------------------------------------------------------------
-- name: DeleteInvoiceItem :exec
DELETE FROM invoice_items
WHERE id              = $1
  AND invoice_id      = $2
  AND organisation_id = $3;
