-- =============================================================================
-- OVERVIEW MODULE — SQLC QUERIES
-- File: db/queries/overview.sql
--
-- Read-only aggregations that back the "Overview" dashboard (the FreeAgent-style
-- landing page). Like the VAT module, the Overview is inherently CROSS-DOMAIN —
-- it summarises banking, invoices, expenses and bills — so its reads are
-- centralised here and generated by a DEDICATED sqlc block (see sqlc.yaml) into
-- package `overview` at db/overview, rather than scattered across each domain's
-- query file. Nothing here writes.
--
-- Every query is ORGANISATION-SCOPED (multi-tenancy) and SOFT-DELETE-AWARE.
-- Money is BIGINT minor units (pence) → Go int64, converted to decimal pound
-- strings (money.MinorToPounds) in the service. Never float.
-- =============================================================================


-- -----------------------------------------------------------------------------
-- CashflowByMonth  (Cashflow card)
-- Money IN vs money OUT per month over the last 12 months (the current month plus
-- the prior 11), for the org's bank transactions. bank_transactions.amount_minor
-- is SIGNED pence: POSITIVE = money in, NEGATIVE = money out.
--
-- generate_series produces ALL 12 month buckets (first-of-month), so a month with
-- no transactions still appears as a zero row — the Go service can map straight
-- onto a fixed 12-point axis without doing any calendar maths. The LEFT JOIN keeps
-- those empty months; FILTER splits the signed amount into the two series, and
-- outgoing is flipped to a POSITIVE magnitude so the API/chart show it as a
-- positive bar.
--
-- @reference_date is "today" (the service passes time.Now(); a test can pin it).
-- =============================================================================
-- name: CashflowByMonth :many
SELECT
    gs.month::date                                                          AS month,
    COALESCE(SUM(t.amount_minor)  FILTER (WHERE t.amount_minor > 0), 0)::bigint AS incoming_minor,
    COALESCE(SUM(-t.amount_minor) FILTER (WHERE t.amount_minor < 0), 0)::bigint AS outgoing_minor
FROM generate_series(
        date_trunc('month', @reference_date::date) - INTERVAL '11 months',
        date_trunc('month', @reference_date::date),
        INTERVAL '1 month'
     ) AS gs(month)
LEFT JOIN bank_transactions t
       ON t.organisation_id = @organisation_id::uuid
      AND t.deleted_at IS NULL
      AND date_trunc('month', t.dated_on) = gs.month
GROUP BY gs.month
ORDER BY gs.month ASC;


-- -----------------------------------------------------------------------------
-- InvoiceTimelineByMonth  (Invoice Timeline card)
-- SENT invoices' total bucketed by month into three status series — Overdue / Due
-- / Paid — matching the invoice list's deriveDisplayStatus (internal/invoices):
--   Paid    : paid_value_minor >= total_value_minor   (covers Paid + Overpaid;
--             a zero-value invoice lands here contributing 0)
--   Overdue : unpaid AND due_on IS NOT NULL AND due_on < today
--   Due     : unpaid AND (due_on IS NULL OR due_on >= today)   ("Open")
-- Each invoice's WHOLE total_value_minor goes into exactly one bucket (whole-
-- invoice classification, matching the solid bars in the mock).
--
-- Window = current month −8 .. +3 (12 buckets) so recent overdue history AND
-- near-future due invoices both show. generate_series zero-fills empty months;
-- a row is placed in the month of COALESCE(due_on, dated_on). Only live SENT
-- invoices count (DRAFT/SCHEDULED/WRITTEN_OFF/REFUNDED excluded).
--
-- @reference_date is "today" (the service passes time.Now(); a test can pin it).
-- =============================================================================
-- name: InvoiceTimelineByMonth :many
SELECT
    gs.month::date AS month,
    COALESCE(SUM(i.total_value_minor) FILTER (
        WHERE i.paid_value_minor < i.total_value_minor
          AND i.due_on IS NOT NULL AND i.due_on < @reference_date::date), 0)::bigint AS overdue_minor,
    COALESCE(SUM(i.total_value_minor) FILTER (
        WHERE i.paid_value_minor < i.total_value_minor
          AND (i.due_on IS NULL OR i.due_on >= @reference_date::date)), 0)::bigint AS due_minor,
    COALESCE(SUM(i.total_value_minor) FILTER (
        WHERE i.paid_value_minor >= i.total_value_minor), 0)::bigint AS paid_minor
FROM generate_series(
        date_trunc('month', @reference_date::date) - INTERVAL '8 months',
        date_trunc('month', @reference_date::date) + INTERVAL '3 months',
        INTERVAL '1 month'
     ) AS gs(month)
LEFT JOIN invoices i
       ON i.organisation_id = @organisation_id::uuid
      AND i.deleted_at IS NULL
      AND i.status = 'SENT'
      AND date_trunc('month', COALESCE(i.due_on, i.dated_on)) = gs.month
GROUP BY gs.month
ORDER BY gs.month ASC;


-- -----------------------------------------------------------------------------
-- OutstandingInvoiceTotal  (Invoice Timeline headline figure)
-- The org's total unpaid receivables: SUM of the generated due_value_minor over
-- live SENT invoices that still owe (due_value_minor > 0). NOT window-bound — it
-- is the full outstanding figure shown beneath the chart.
-- =============================================================================
-- name: OutstandingInvoiceTotal :one
SELECT COALESCE(SUM(due_value_minor), 0)::bigint AS outstanding_minor
FROM invoices
WHERE organisation_id = @organisation_id::uuid
  AND deleted_at IS NULL
  AND status = 'SENT'
  AND due_value_minor > 0;


-- -----------------------------------------------------------------------------
-- BankBalanceByMonth  (Banking card — balance-over-time area chart)
-- Month-end TOTAL bank balance over the last 12 months: Σ opening balances (live
-- accounts) + Σ all transactions dated on/before each month end. CUMULATIVE, so it
-- includes history BEFORE the window — each point is the true running balance at
-- that month end (the same derivation the Bank Accounts page uses, summed across
-- accounts). bank_transactions.amount_minor is SIGNED (+ in / − out).
--
-- The final cast to ::bigint maps the result to Go int64 — SUM of bigint is numeric
-- (→ string under our sqlc override), so GetBankAccount casts the same way.
-- @reference_date is "today" (the service passes time.Now(); a test can pin it).
-- =============================================================================
-- name: BankBalanceByMonth :many
SELECT
    gs.month::date AS month,
    (
      (SELECT COALESCE(SUM(a.opening_balance_minor), 0)
         FROM bank_accounts a
        WHERE a.organisation_id = @organisation_id::uuid AND a.deleted_at IS NULL)
      + COALESCE((
          SELECT SUM(t.amount_minor)
            FROM bank_transactions t
           WHERE t.organisation_id = @organisation_id::uuid
             AND t.deleted_at IS NULL
             AND t.dated_on < gs.month + INTERVAL '1 month'
        ), 0)
    )::bigint AS balance_minor
FROM generate_series(
        date_trunc('month', @reference_date::date) - INTERVAL '11 months',
        date_trunc('month', @reference_date::date),
        INTERVAL '1 month'
     ) AS gs(month)
ORDER BY gs.month ASC;


-- -----------------------------------------------------------------------------
-- BankBalanceSummary  (Banking card — headline)
-- The org's CURRENT total balance (opening + ALL live transactions, exactly the
-- Bank Accounts page's derived balance summed across accounts) plus the live-
-- account count (drives the "All accounts" label). Cast ::bigint → int64.
-- =============================================================================
-- name: BankBalanceSummary :one
SELECT
    (
      (SELECT COALESCE(SUM(opening_balance_minor), 0) FROM bank_accounts
        WHERE organisation_id = @organisation_id::uuid AND deleted_at IS NULL)
      + (SELECT COALESCE(SUM(amount_minor), 0) FROM bank_transactions
        WHERE organisation_id = @organisation_id::uuid AND deleted_at IS NULL)
    )::bigint AS total_balance_minor,
    (SELECT count(*) FROM bank_accounts
      WHERE organisation_id = @organisation_id::uuid AND deleted_at IS NULL) AS account_count;
