-- =============================================================================
-- PROJECTS MODULE — SQLC QUERIES
-- File: db/queries/projects.sql
--
-- Type-safe Go for the projects table defined in db/schema/projects_schema.sql.
-- Generated by a dedicated sqlc block (see sqlc.yaml) into package `projects`
-- at db/projects — separate from expenses/auth/contacts packages.
--
-- Annotation / parameter syntax is identical to db/queries/query.sql:
--   -- name: FuncName :one|:many|:exec
--   $1, $2 ... positional params, typed from the schema columns.
--
-- Every query is ORGANISATION-SCOPED (multi-tenancy). Projects use hard delete
-- (no deleted_at) so there is no soft-delete filter to maintain.
-- =============================================================================


-- -----------------------------------------------------------------------------
-- CreateProject
-- Inserts a new project row and returns it via RETURNING * so the caller gets
-- the generated id and timestamps without a second round-trip.
-- organisation_id and contact_id are supplied by the service layer (validated
-- from the auth token and the request body respectively).
-- -----------------------------------------------------------------------------
-- name: CreateProject :one
INSERT INTO projects (
    organisation_id,
    contact_id,
    name,
    status,
    contract_po_number,
    project_invoice_sequence,
    currency,
    budget_type,
    budget_hours_minutes,
    budget_days,
    budget_money_pence,
    hours_per_day_minutes,
    billing_rate_pence,
    billing_rate_unit,
    billing_rate_plus_vat,
    is_ir35,
    start_date,
    end_date,
    include_unbillable_time
) VALUES (
    $1,   -- organisation_id        UUID
    $2,   -- contact_id             UUID
    $3,   -- name                   TEXT
    $4,   -- status                 TEXT  e.g. 'active'
    $5,   -- contract_po_number     TEXT  (nullable)
    $6,   -- project_invoice_sequence BOOLEAN
    $7,   -- currency               TEXT  e.g. 'GBP'
    $8,   -- budget_type            TEXT  'hours'|'days'|'money' (nullable)
    $9,   -- budget_hours_minutes   INTEGER (nullable)
    $10,  -- budget_days            INTEGER (nullable)
    $11,  -- budget_money_pence     BIGINT  (nullable)
    $12,  -- hours_per_day_minutes  INTEGER (nullable)
    $13,  -- billing_rate_pence     BIGINT  (nullable)
    $14,  -- billing_rate_unit      TEXT   'per_hour'|'per_day' (nullable)
    $15,  -- billing_rate_plus_vat  BOOLEAN
    $16,  -- is_ir35                BOOLEAN
    $17,  -- start_date             DATE (nullable)
    $18,  -- end_date               DATE (nullable)
    $19   -- include_unbillable_time BOOLEAN
)
RETURNING *;


-- -----------------------------------------------------------------------------
-- GetProject
-- Fetch a single project by id, always scoped to the organisation.
-- Never fetch by id alone — a leaked id must not reveal another tenant's data.
-- -----------------------------------------------------------------------------
-- name: GetProject :one
SELECT * FROM projects
WHERE id              = $1   -- project UUID
  AND organisation_id = $2;  -- tenant scope — never skip this


-- -----------------------------------------------------------------------------
-- ListProjects
-- All projects for an organisation, newest first. Used for the project list
-- page and to populate dropdowns (e.g. on time entries, invoices).
-- -----------------------------------------------------------------------------
-- name: ListProjects :many
SELECT * FROM projects
WHERE organisation_id = $1
ORDER BY created_at DESC;


-- -----------------------------------------------------------------------------
-- UpdateProject
-- Full update of all editable fields (PUT semantics). organisation_id is the
-- tenant guard — a row in a different org is invisible. RETURNING * echoes the
-- updated row so the API can return the result without a second SELECT.
-- -----------------------------------------------------------------------------
-- name: UpdateProject :one
UPDATE projects SET
    contact_id               = $3,
    name                     = $4,
    status                   = $5,
    contract_po_number       = $6,
    project_invoice_sequence = $7,
    currency                 = $8,
    budget_type              = $9,
    budget_hours_minutes     = $10,
    budget_days              = $11,
    budget_money_pence       = $12,
    hours_per_day_minutes    = $13,
    billing_rate_pence       = $14,
    billing_rate_unit        = $15,
    billing_rate_plus_vat    = $16,
    is_ir35                  = $17,
    start_date               = $18,
    end_date                 = $19,
    include_unbillable_time  = $20,
    updated_at               = now()
WHERE id              = $1   -- project UUID
  AND organisation_id = $2   -- tenant scope
RETURNING *;


-- -----------------------------------------------------------------------------
-- DeleteProject
-- Hard delete: the project row is permanently removed. Safe for now because
-- projects are not yet referenced by invoice lines. When invoice line FKs are
-- added, replace this with a soft-delete (deleted_at) instead.
-- -----------------------------------------------------------------------------
-- name: DeleteProject :exec
DELETE FROM projects
WHERE id              = $1   -- project UUID
  AND organisation_id = $2;  -- tenant scope — guards against cross-tenant deletes
