package userauth

// service.go
// =============================================================================
// Service (now userauth.Service) — the business logic layer for the signed-in
// user's own
// "My Details" (the personal profile screen modelled on FreeAgent's My Details:
// a read-only login email plus an editable first/last name).
//
// All of this data lives on the users table (db/schema/auth_schema.sql), so this
// service is a thin layer over the existing auth queries — exactly like
// OrganisationService / MemberService:
//
//   HTTP handler (server.go)
//     ↓
//   Service (this file)
//     ↓
//   auth.Querier (db/auth — generated by sqlc)
//     ↓
//   PostgreSQL
//
// The user is taken from the bearer token (authUserID), never a path/body param,
// so a caller can only ever read or edit their OWN profile. That is the one
// SIMPLIFICATION from OrganisationService: there is no membership/role check,
// because there is no "may I edit this user?" question — you are always allowed
// to edit yourself. (GetUser already hides soft-deleted users, so a deleted
// account 404s.)
//
// It reuses the package's own UserResponse DTO + its projector NewUserResponse
// (auth.go) — the very same safe shape the login response returns — and the
// kernel.Err* constructors. There is no money here, so no pence/decimal conversion.
// =============================================================================

import (
	"context"
	"errors"
	"strings"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"

	auth "github.com/operationfb/accounting-saas/db/auth"
	"github.com/operationfb/accounting-saas/internal/kernel"
	"github.com/operationfb/accounting-saas/token"
)

// UpdateProfileRequest is the JSON body accepted by PUT /api/v1/profile (the
// "My Details" screen). It carries only the editable profile fields. The login
// email is deliberately absent (changing it is a separate, security-sensitive
// flow), as are phone/avatar_url — the service preserves those. Both names are
// required (they are NOT NULL on the users table and starred on the form); `max`
// matches the VARCHAR(100) columns. The user is taken from the token, so there
// is no id here. The GET/PUT responses reuse the login UserResponse shape.
type UpdateProfileRequest struct {
	FirstName string `json:"first_name" binding:"required,max=100"`
	LastName  string `json:"last_name" binding:"required,max=100"`
	// Optional payroll-identity fields (future payroll module). Pointers so the
	// form can distinguish "not sent" from "cleared"; both end up NULL here, which
	// is fine — this is a full-form save, not a partial PATCH. Format is validated
	// in the service via the shared kernel.Parse* helpers (the same ones the admin
	// path uses), so the rules can't drift between the two screens.
	NationalInsuranceNumber *string `json:"national_insurance_number"`
	UTR                     *string `json:"utr"`
	DateOfBirth             *string `json:"date_of_birth"` // ISO YYYY-MM-DD
	// Optional personal/home address (future payroll module). Free text — no
	// validation, blank/omitted -> NULL via kernel.NullText.
	AddressLine1 *string `json:"address_line_1"`
	AddressLine2 *string `json:"address_line_2"`
	AddressLine3 *string `json:"address_line_3"`
	AddressLine4 *string `json:"address_line_4"`
	Postcode     *string `json:"postcode"`
}

// Service holds the auth query set plus the token maker: reading/updating the
// user are single-table operations, so there is no pool/transaction to keep
// (same shape as OrganisationService / MemberService). The token maker +
// accessTokenDuration are needed by SwitchOrganisation, which re-mints the
// PASETO token scoped to a different organisation (the same mechanism login uses
// in auth.go).
type Service struct {
	authQueries auth.Querier

	// Token minting for the organisation switch. Mirrors AuthHandler: switching
	// org just means issuing a fresh token carrying a different OrganisationID.
	tokenMaker          token.Maker
	accessTokenDuration time.Duration
}

// NewService is the constructor, called once in main.go. authQueries is the
// same auth.Querier already shared with the other auth-backed services;
// tokenMaker + accessTokenDuration are the same values AuthHandler receives, so
// a switched token is indistinguishable from a login token.
func NewService(authQueries auth.Querier, tokenMaker token.Maker, accessTokenDuration time.Duration) *Service {
	return &Service{
		authQueries:         authQueries,
		tokenMaker:          tokenMaker,
		accessTokenDuration: accessTokenDuration,
	}
}

// =============================================================================
// GET
// =============================================================================

// GetProfile returns the caller's own profile. The user is taken from the
// authenticated token, so a caller can only ever read themselves.
func (s *Service) GetProfile(ctx context.Context, authUserID uuid.UUID) (*UserResponse, error) {
	u, err := s.authQueries.GetUser(ctx, authUserID)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			// Soft-deleted (or never existed) — GetUser filters deleted_at IS NULL.
			return nil, kernel.ErrNotFound("user", authUserID.String())
		}
		return nil, kernel.ErrInternal(err)
	}
	resp := NewUserResponse(u)
	return &resp, nil
}

// =============================================================================
// UPDATE
// =============================================================================

// UpdateProfile updates the editable profile fields (first/last name). The user
// is taken from the token, so it always targets the caller's own row.
//
// This is a read-modify-write: the sqlc UpdateUser query also owns the phone and
// avatar_url columns, which the My Details form does not edit, so we fetch the
// existing row first and pass those through unchanged — otherwise a save from
// this form would NULL them. (Same pattern as OrganisationService preserving
// slug/vrn/native_currency/timezone.) Email is not editable here at all.
func (s *Service) UpdateProfile(
	ctx context.Context,
	authUserID uuid.UUID,
	req UpdateProfileRequest,
) (*UserResponse, error) {
	// Validate / normalise. first/last name are NOT NULL on the users table and
	// required on the form. The binding `required` tag catches a missing value at
	// the HTTP edge; this re-check (after trimming) covers direct/test callers and
	// rejects whitespace-only input.
	firstName := strings.TrimSpace(req.FirstName)
	lastName := strings.TrimSpace(req.LastName)
	if firstName == "" {
		return nil, kernel.ErrValidation("first_name is required", nil)
	}
	if lastName == "" {
		return nil, kernel.ErrValidation("last_name is required", nil)
	}

	// Parse + validate the optional payroll fields (422 on a bad value). The same
	// kernel helpers back the admin path, so the rules stay in one place. A
	// nil/blank value normalises to a NULL column.
	nino, err := kernel.ParseNINO(req.NationalInsuranceNumber)
	if err != nil {
		return nil, err
	}
	utr, err := kernel.ParseUTR(req.UTR)
	if err != nil {
		return nil, err
	}
	dob, err := kernel.ParseDateOfBirth(req.DateOfBirth)
	if err != nil {
		return nil, err
	}

	// Read first so we can preserve the columns this form does not edit (phone,
	// avatar_url), and to 404 if the account was soft-deleted.
	existing, err := s.authQueries.GetUser(ctx, authUserID)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, kernel.ErrNotFound("user", authUserID.String())
		}
		return nil, kernel.ErrInternal(err)
	}

	updated, err := s.authQueries.UpdateUser(ctx, auth.UpdateUserParams{
		ID:        authUserID,
		FirstName: firstName,
		LastName:  lastName,
		// Preserved — not on the My Details form.
		Phone:     existing.Phone,
		AvatarUrl: existing.AvatarUrl,
		// Payroll identity (edited on the User Details screen).
		NationalInsuranceNumber: nino,
		Utr:                     utr,
		DateOfBirth:             dob,
		// Personal/home address (free text; blank -> NULL).
		AddressLine1: kernel.NullText(req.AddressLine1),
		AddressLine2: kernel.NullText(req.AddressLine2),
		AddressLine3: kernel.NullText(req.AddressLine3),
		AddressLine4: kernel.NullText(req.AddressLine4),
		Postcode:     kernel.NullText(req.Postcode),
	})
	if err != nil {
		// The row was live a moment ago; ErrNoRows means it was soft-deleted in between.
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, kernel.ErrNotFound("user", authUserID.String())
		}
		return nil, kernel.ErrInternal(err)
	}
	resp := NewUserResponse(updated)
	return &resp, nil
}

// =============================================================================
// ORGANISATION SWITCHING
// A user may belong to several organisations. Login (auth.go) scopes the session
// to their first active membership; these two methods let the client (a) list
// every org the user can switch to and (b) re-scope the session to another one.
// =============================================================================

// ListMyOrganisations returns every organisation the caller is an ACTIVE member
// of, with their role at each — the data behind the top-bar org switcher. It
// wraps the existing ListOrganisationsForUser query (also used at login) and
// projects each row onto the same safe OrganisationResponse shape the login
// response uses. An org-less user gets an empty list (not an error).
func (s *Service) ListMyOrganisations(ctx context.Context, authUserID uuid.UUID) ([]OrganisationResponse, error) {
	rows, err := s.authQueries.ListOrganisationsForUser(ctx, authUserID)
	if err != nil {
		return nil, kernel.ErrInternal(err)
	}
	orgs := make([]OrganisationResponse, 0, len(rows))
	for _, r := range rows {
		orgs = append(orgs, OrganisationResponse{
			ID:             r.ID.String(),
			Name:           r.Name,
			CountryCode:    r.CountryCode,
			NativeCurrency: r.NativeCurrency,
			Role:           string(r.Role),
		})
	}
	return orgs, nil
}

// SwitchOrganisation re-mints the caller's session token, scoping it to a
// DIFFERENT organisation they belong to. This is the whole mechanism for
// switching org: the PASETO token carries a single OrganisationID, so switching
// means issuing a fresh token with the target id.
//
// The caller must be an ACTIVE member of the target org — AuthorizeMember does
// the GetMembership + status check and returns their role there (or a 403 for a
// non-member / deactivated membership; a cross-tenant org id is simply one the
// user has no membership at, so it 403s the same way). We then re-mint the token
// and return the SAME shape login returns (token + user + organisation), so the
// client can reuse its session-setting path.
func (s *Service) SwitchOrganisation(ctx context.Context, authUserID, orgID uuid.UUID) (*LoginUserResponse, error) {
	// Authorise: must be an active member of the target org. Returns the caller's
	// role there, which we surface on the organisation response (role is per-org).
	role, err := kernel.AuthorizeMember(ctx, s.authQueries, authUserID, orgID)
	if err != nil {
		return nil, err // already an AppError (403 for non-member/inactive, 500 otherwise)
	}

	// Load the org for its name + country_code — neither is inside the token, and
	// the client needs both (name for the top bar, country_code for VAT scoping).
	org, err := s.authQueries.GetOrganisation(ctx, orgID)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			// A soft-deleted org: AuthorizeMember passed, but the org row is gone.
			return nil, kernel.ErrNotFound("organisation", orgID.String())
		}
		return nil, kernel.ErrInternal(err)
	}

	// country_code is NOT NULL in the schema; guard defensively (mirrors login) so
	// a blank value fails loudly rather than issuing a session with no country.
	if strings.TrimSpace(org.CountryCode) == "" {
		return nil, kernel.ErrInternal(errors.New("switch: organisation has an empty country_code"))
	}

	// Load the user so the response carries the same safe user view login returns.
	user, err := s.authQueries.GetUser(ctx, authUserID)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, kernel.ErrNotFound("user", authUserID.String())
		}
		return nil, kernel.ErrInternal(err)
	}

	// Re-mint the token, now scoped to the target org.
	accessToken, err := s.tokenMaker.CreateToken(authUserID, orgID, s.accessTokenDuration)
	if err != nil {
		return nil, kernel.ErrInternal(err)
	}

	return &LoginUserResponse{
		AccessToken: accessToken,
		User:        NewUserResponse(user),
		Organisation: &OrganisationResponse{
			ID:             org.ID.String(),
			Name:           org.Name,
			CountryCode:    org.CountryCode,
			NativeCurrency: org.NativeCurrency,
			Role:           string(role),
		},
	}, nil
}
