package userauth

// service.go
// =============================================================================
// Service (now userauth.Service) — the business logic layer for the signed-in
// user's own
// "My Details" (the personal profile screen modelled on FreeAgent's My Details:
// a read-only login email plus an editable first/last name).
//
// All of this data lives on the users table (db/schema/auth_schema.sql), so this
// service is a thin layer over the existing auth queries — exactly like
// OrganisationService / MemberService:
//
//   HTTP handler (server.go)
//     ↓
//   Service (this file)
//     ↓
//   auth.Querier (db/auth — generated by sqlc)
//     ↓
//   PostgreSQL
//
// The user is taken from the bearer token (authUserID), never a path/body param,
// so a caller can only ever read or edit their OWN profile. That is the one
// SIMPLIFICATION from OrganisationService: there is no membership/role check,
// because there is no "may I edit this user?" question — you are always allowed
// to edit yourself. (GetUser already hides soft-deleted users, so a deleted
// account 404s.)
//
// It reuses the package's own UserResponse DTO + its projector NewUserResponse
// (auth.go) — the very same safe shape the login response returns — and the
// kernel.Err* constructors. There is no money here, so no pence/decimal conversion.
// =============================================================================

import (
	"context"
	"errors"
	"strings"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"

	auth "github.com/operationfb/accounting-saas/db/auth"
	"github.com/operationfb/accounting-saas/internal/kernel"
)

// UpdateProfileRequest is the JSON body accepted by PUT /api/v1/profile (the
// "My Details" screen). It carries only the editable profile fields. The login
// email is deliberately absent (changing it is a separate, security-sensitive
// flow), as are phone/avatar_url — the service preserves those. Both names are
// required (they are NOT NULL on the users table and starred on the form); `max`
// matches the VARCHAR(100) columns. The user is taken from the token, so there
// is no id here. The GET/PUT responses reuse the login UserResponse shape.
type UpdateProfileRequest struct {
	FirstName string `json:"first_name" binding:"required,max=100"`
	LastName  string `json:"last_name" binding:"required,max=100"`
}

// Service holds only the auth query set: reading and updating the user are
// single-table operations, so there is no pool/transaction to keep (same shape
// as OrganisationService / MemberService).
type Service struct {
	authQueries auth.Querier
}

// NewService is the constructor, called once in main.go. authQueries is the
// same auth.Querier already shared with the other auth-backed services.
func NewService(authQueries auth.Querier) *Service {
	return &Service{authQueries: authQueries}
}

// =============================================================================
// GET
// =============================================================================

// GetProfile returns the caller's own profile. The user is taken from the
// authenticated token, so a caller can only ever read themselves.
func (s *Service) GetProfile(ctx context.Context, authUserID uuid.UUID) (*UserResponse, error) {
	u, err := s.authQueries.GetUser(ctx, authUserID)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			// Soft-deleted (or never existed) — GetUser filters deleted_at IS NULL.
			return nil, kernel.ErrNotFound("user", authUserID.String())
		}
		return nil, kernel.ErrInternal(err)
	}
	resp := NewUserResponse(u)
	return &resp, nil
}

// =============================================================================
// UPDATE
// =============================================================================

// UpdateProfile updates the editable profile fields (first/last name). The user
// is taken from the token, so it always targets the caller's own row.
//
// This is a read-modify-write: the sqlc UpdateUser query also owns the phone and
// avatar_url columns, which the My Details form does not edit, so we fetch the
// existing row first and pass those through unchanged — otherwise a save from
// this form would NULL them. (Same pattern as OrganisationService preserving
// slug/vrn/native_currency/timezone.) Email is not editable here at all.
func (s *Service) UpdateProfile(
	ctx context.Context,
	authUserID uuid.UUID,
	req UpdateProfileRequest,
) (*UserResponse, error) {
	// Validate / normalise. first/last name are NOT NULL on the users table and
	// required on the form. The binding `required` tag catches a missing value at
	// the HTTP edge; this re-check (after trimming) covers direct/test callers and
	// rejects whitespace-only input.
	firstName := strings.TrimSpace(req.FirstName)
	lastName := strings.TrimSpace(req.LastName)
	if firstName == "" {
		return nil, kernel.ErrValidation("first_name is required", nil)
	}
	if lastName == "" {
		return nil, kernel.ErrValidation("last_name is required", nil)
	}

	// Read first so we can preserve the columns this form does not edit (phone,
	// avatar_url), and to 404 if the account was soft-deleted.
	existing, err := s.authQueries.GetUser(ctx, authUserID)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, kernel.ErrNotFound("user", authUserID.String())
		}
		return nil, kernel.ErrInternal(err)
	}

	updated, err := s.authQueries.UpdateUser(ctx, auth.UpdateUserParams{
		ID:        authUserID,
		FirstName: firstName,
		LastName:  lastName,
		// Preserved — not on the My Details form.
		Phone:     existing.Phone,
		AvatarUrl: existing.AvatarUrl,
	})
	if err != nil {
		// The row was live a moment ago; ErrNoRows means it was soft-deleted in between.
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, kernel.ErrNotFound("user", authUserID.String())
		}
		return nil, kernel.ErrInternal(err)
	}
	resp := NewUserResponse(updated)
	return &resp, nil
}
